### ISSUE TITLE
Sign the uninstaller

### ISSUE THREAD

**Issue by mkver** [Nevcairiel/LAVFilters#100]
Hello Nevcairiel,

first, let me thank you for your work on LAVFilters (and on FFMPEG, MPC-HC etc.).
My issue is probably minor: Is it possible to sign the uninstaller that comes with your installer-releases? The installer is already signed so you can probably use this certificate if I am not mistaken.
Thanks.

Andi

**Comment by Nevcairiel** [comment]
There is no real reason not to sign it, except the problem that this requires integrating signing into the installer script, which means it wouldn't work without a careful signing setup anymore (ie. not anyone can run it anymore).

Maybe I'll add a second installer script that does signing for official builds, I'll think about it.
