### ISSUE TITLE
Support for Advanced Media Framework

### ISSUE THREAD

**Issue by nwgat** [Nevcairiel/LAVFilters#102]
You got Nvidia CUVID, Intel QuickSync, you are only missing AMD AMF (aka official open source version of Media SDK)

[GPUOpen](http://gpuopen.com/gaming-product/advanced-media-framework/)
[Github Project](https://github.com/GPUOpen-LibrariesAndSDKs/AMF)

[MF_Video_Decode_API.pdf](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_Decode_API.pdf)
[AMF_API_Reference.pdf](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_API_Reference.pdf)
[SimpleDecoder Example Code](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/tree/master/amf/public/samples/CPPSamples/SimpleDecoder)

**Comment by Nevcairiel** [comment]
Li have absolutely no plans to add more vendor specific stuff, I would rather remove the ones that exist.

Windows has a nice cross vendor API with DXVA2, there really should be no reason to have anything else, and if there is the vendors should be encouraged to work on their DXVA support instead.
