### ISSUE TITLE
MPC-HC freezes when going full-screen for movie being streamed to Miracast device the 

### ISSUE THREAD

**Issue by mareksuski** [Nevcairiel/LAVFilters#104]
Hi,

When using any of hardware acceleration (Intel QuickSync2, DVXA native) or no acceleration then when I try to switch to fullscreen then MPC-HC freezes.

I am streaming movie from My Surface Pro 4 to Microsoft WiDi dongle (https://www.microsoft.com/accessories/en-us/products/adapters/wireless-display-adapter-2/p3q-00001)

When I disable your video LAV Video filter and use "Microsoft DTV-DVD Video Decoder" instead then movie play full-screen very well.

BR,

Marek 
## MPC-HC (Nightly, 64-bit)

Build information:
    Version:            1.7.10.250 (63417e7)
    Compiler:           MSVC 2015 Update 3
    Build date:         Jul  7 2016
LAV Filters:
    LAV Splitter:       0.68.1.25
    LAV Video:          0.68.1.25
    LAV Audio:          0.68.1.25
    FFmpeg compiler:    MinGW-w64 GCC 5.4.0
Operating system:
    Name:               Windows NT 10.0 (build 14393)
    Version:            10.0 (64-bit)
Hardware:
    CPU:                Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    GPU:                Intel(R) HD Graphics 520 (driver version: 20.19.15.4463)

**Comment by Nevcairiel** [comment]
I have no way to test this, but I also have no idea why the video decoder would make a difference here - especially if you don't use hardware acceleration.

It would seem far more likely to be an issue in the video renderer, which somehow gets triggered by the decoder behaving differently?

**Comment by mareksuski** [comment]
Hi,

I can send you logs if they could be generated for you to debug.

**Comment by Nevcairiel** [comment]
After some investigation, it seems clear this would most likely be triggered by the video renderer - especially in software decoding mode LAV does not interact with the hardware at all, it only provides video images in a quite straight forward way.

So I would suggest to inquire with the video player or video renderer developers.
