### ISSUE TITLE
1920 × 1088 Video 4:2:2 slower picture and freeze 

### ISSUE THREAD

**Issue by pop-dahaka** [Nevcairiel/LAVFilters#105]
1920 × 1088 Video 4:2:2 slower picture and freeze , I attached a video for you 

http://www.mediafire.com/download/go3gyta8albaw56/UKI-1324_Path120160905-221450.rar

**Comment by pop-dahaka** [comment]
An other video **4:2:0** 1920 × 1088 with the same problem 
http://www.mediafire.com/download/8atdmth0l0y0jds/RTVS20160904-190327.rar

**Comment by filler56789** [comment]
It seems those files are very broken... I tested only the second one, and neither MPlayer nor TSmuxer like it.

```
=> mplayer -nosound -vf scale=1280:-2 RTVS20160904-190327.ts
MPlayer Redxii-SVN-r37870-4.9.3 (x86_64) (C) 2000-2016 MPlayer Team
FFmpeg version: N-80062-gdefb960
Build date: 2016-05-21 19:39:06 EDT
224 audio & 453 video codecs

Playing RTVS20160904-190327.ts.
Cache fill:  0.00% (0 bytes)

libavformat version 57.37.100 (internal)
TS file format detected.
VIDEO MPEG2(pid=512) NO AUDIO! (try increasing -tsprobe) NO SUBS (yet)!  PROGRAM N. 0
TS_PARSE: COULDN'T SYNC
MPEG: FATAL: EOF while searching for sequence header.
Video: Cannot read properties.
No stream found.


Exiting... (End of file)
```

**Comment by pop-dahaka** [comment]
I use Daum PotPlayer 1.6.63374 to open it . (i can record and send you an other file with different codec to test it)

> General
> ID                             : 1 (0x1)
> Complete name                  : C:\SmartDVB\045RC 4\Records\RTVS20160904-190327.ts
> Format                         : MPEG-TS
> File size                      : 66.7 MiB
> Duration                       : 1 min 3 s
> Start time                     : UTC 2016-09-04 17:05:01
> End time                       : UTC 2016-09-04 17:06:03
> Overall bit rate mode          : Variable
> Overall bit rate               : 8 290 kb/s
> Network name                   : SLQ005
> Original network name          : Astra Satellite Network 19,2'E
> Frequency                      : 4080000000
> OrbitalPosition                : 97.0W
> 
> Video
> ID                             : 512 (0x200)
> Menu ID                        : 1 (0x1)
> Format                         : AVC
> Format/Info                    : Advanced Video Codec
> Format profile                 : High@L4.1
> Format settings, CABAC         : Yes
> Format settings, ReFrames      : 4 frames
> Codec ID                       : 27
> Duration                       : 1 min 3 s
> Bit rate mode                  : Variable
> Bit rate                       : 7 104 kb/s
> Maximum bit rate               : 14.0 Mb/s
> Width                          : 1 920 pixels
> Height                         : 1 080 pixels
> Display aspect ratio           : 16:9
> Frame rate                     : 25.000 FPS
> Color space                    : YUV
> Chroma subsampling             : 4:2:0
> Bit depth                      : 8 bits
> Scan type                      : MBAFF
> Scan type, store method        : Separated fields
> Scan order                     : Bottom Field First
> Bits/(Pixel*Frame)             : 0.137
> Stream size                    : 54.1 MiB (81%)
> Color range                    : Limited
> Color primaries                : BT.709
> Transfer characteristics       : BT.709
> Matrix coefficients            : BT.709
> 
> Audio #1
> ID                             : 4112 (0x1010)
> Menu ID                        : 1 (0x1)
> Format                         : MPEG Audio
> Format version                 : Version 1
> Format profile                 : Layer 2
> Mode extension                 : Intensity Stereo + MS Stereo
> Codec ID                       : 3
> Duration                       : 1 min 4 s
> Bit rate mode                  : Constant
> Bit rate                       : 384 kb/s
> Channel(s)                     : 2 channels
> Sampling rate                  : 48.0 kHz
> Compression mode               : Lossy
> Delay relative to video        : -431 ms
> Stream size                    : 2.93 MiB (4%)
> Language                       : int
> 
> Audio #2
> ID                             : 4128 (0x1020)
> Menu ID                        : 1 (0x1)
> Format                         : MPEG Audio
> Format version                 : Version 1
> Format profile                 : Layer 2
> Mode extension                 : Intensity Stereo + MS Stereo
> Codec ID                       : 3
> Duration                       : 1 min 4 s
> Bit rate mode                  : Constant
> Bit rate                       : 384 kb/s
> Channel(s)                     : 2 channels
> Sampling rate                  : 48.0 kHz
> Compression mode               : Lossy
> Delay relative to video        : -430 ms
> Stream size                    : 2.93 MiB (4%)
> Language                       : svk
> 
> Text
> ID                             : 512 (0x200)-CC1
> Menu ID                        : 1 (0x1)
> Format                         : EIA-608
> Muxing mode                    : SCTE 128 / DTVCC Transport
> Muxing mode, more info         : Muxed in Video #1
> Duration                       : 1 min 3 s
> Bit rate mode                  : Constant
> Stream size                    : 0.00 Byte (0%)
> Language                       : int
> 
> Menu
> ID                             : 2048 (0x800)
> Menu ID                        : 1 (0x1)
> List                           : 512 (0x200) (AVC) / 4112 (0x1010) (MPEG Audio, int) / 4128 (0x1020) (MPEG Audio, svk)
> Language                       :  / int / svk
> Service name                   : RTVS
> Service provider               : SLQ005
> Service type                   : advanced codec HD digital television
> UTC 2016-09-04 00:00:00        : int:RTVS / int: /  /  / 24:00:00 / Running
> 
>

**Comment by Aleksoid1978** [comment]
Both files is broken.

**Comment by pop-dahaka** [comment]
I uploaded two new files with different codecs (Lav and Divx) from the same channel 1920 × 1088 Video 4:2:2 , please check them , i wish you find the problem and fix it .
Best Wishes .
https://www.mediafire.com/folder/3b02x2o1xphzb8c,itwttzecf9a9k3n/shared

**Comment by filler56789** [comment]
PotPlayer or/and VLC were designed to support broken media files.
As far as I know, Nevcairiel has no plans to make LAV Filters tolerate bad stuff...

**Comment by pop-dahaka** [comment]
Those files i upload were recorded from satellite feed using USB Tevii S662 (PC satellite card), 
HD satellite receiver can open and view those feed channels , 
But PC satellite card like Tevii S662 using Lav filter have problems as you can see from videos i upload , 
I wish you can find a solution .

**Comment by Aleksoid1978** [comment]
Last both files also broken - while playback skipping some data as invalid.

**Comment by pop-dahaka** [comment]
I contact Smart dvb coder and he told me to disable hardware acceleration , 
Now no broken no slow picture ,
Can you check those two files are broken at your system or not ?

https://www.mediafire.com/folder/fq5p0a4oamnfh15,3x4bgdhgbetgdl1/shared

**Comment by Aleksoid1978** [comment]
Last file is good :)

**Comment by pop-dahaka** [comment]
Thanks All ,
It was a problem of hardware acceleration , 
The solution is disable hardware acceleration .
