### ISSUE TITLE
Registry Values aren't recognized correctly

### ISSUE THREAD

**Issue by wedok** [Nevcairiel/LAVFilters#106]
i want to control lav settings via registry changes to change lav settings with my remote control.
i use dvbviewers command.vbs for this.

dvbviewers command.vbs sets the reg_dword "Mixing" to "1" and rebuilds the graph but lav still has mixing disabled.
regedit shows "Mixing" value "1".

i think lav is too fast or too slow in recognizing registry changes and due to this it always uses the previous value.

i use the same way to control reclock and with it everything works.

**Comment by Nevcairiel** [comment]
Settings are loaded when the LAV instance is created, and not at any other times. There are no plans to change this.

If this isn't enough to refresh settings on a graph rebuild, DVBViewer should maybe delete LAV and create a new one, instead of re-using it.
