### ISSUE TITLE
problem with audio tracks - MXF XDCAMHD422

### ISSUE THREAD

**Issue by marcobpasquali** [Nevcairiel/LAVFilters#107]
Hi,

I'm having a problem when trying to play a MXF file with multiple audio tracks.
The file has 8 audio tracks (XDCAM HD422) but LAV Splitter shows just one:

![image](https://cloud.githubusercontent.com/assets/20997756/18758792/e9e6a40c-80cf-11e6-8b98-8bff3fac5c83.png)

**MediaInfo from file:**

General
Complete name                            : SAT.MXF
Format                                   : MXF
Commercial name                          : XDCAM HD422
Format version                           : 1.3
Format profile                           : OP-1a
Format settings                          : Closed / Complete
File size                                : 535 MiB
Duration                                 : 1mn 14s
Overall bit rate                         : 60.4 Mbps
Encoded date                             : 2016-08-01 14:02:57.000
Writing application                      : SONY Opt 1.22

Video
ID                                       : 2
Format                                   : MPEG Video
Commercial name                          : XDCAM HD422
Format version                           : Version 2
Format profile                           : 4:2:2@High
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : M=3, N=15
Format settings, picture structure       : Frame
Format settings, wrapping mode           : Frame
Codec ID                                 : 0D01030102046001-0401020201040300
Duration                                 : 1mn 14s
Bit rate                                 : 50.0 Mbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 29.970 (30000/1001) fps
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:2
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.805
Stream size                              : 443 MiB (83%)
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio #1
ID                                       : 3
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, wrapping mode           : Frame (AES)
Codec ID                                 : 0D01030102060300
Duration                                 : 1mn 14s
Bit rate mode                            : Constant
Bit rate                                 : 1 152 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 KHz
Frame rate                               : 29.970 fps (1601.6 spf)
Bit depth                                : 24 bits
Stream size                              : 10.2 MiB (2%)

Audio #2
ID                                       : 4
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, wrapping mode           : Frame (AES)
Codec ID                                 : 0D01030102060300
Duration                                 : 1mn 14s
Bit rate mode                            : Constant
Bit rate                                 : 1 152 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 KHz
Frame rate                               : 29.970 fps (1601.6 spf)
Bit depth                                : 24 bits
Stream size                              : 10.2 MiB (2%)

Audio #3
ID                                       : 5
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, wrapping mode           : Frame (AES)
Codec ID                                 : 0D01030102060300
Duration                                 : 1mn 14s
Bit rate mode                            : Constant
Bit rate                                 : 1 152 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 KHz
Frame rate                               : 29.970 fps (1601.6 spf)
Bit depth                                : 24 bits
Stream size                              : 10.2 MiB (2%)

Audio #4
ID                                       : 6
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, wrapping mode           : Frame (AES)
Codec ID                                 : 0D01030102060300
Duration                                 : 1mn 14s
Bit rate mode                            : Constant
Bit rate                                 : 1 152 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 KHz
Frame rate                               : 29.970 fps (1601.6 spf)
Bit depth                                : 24 bits
Stream size                              : 10.2 MiB (2%)

Audio #5
ID                                       : 7
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, wrapping mode           : Frame (AES)
Codec ID                                 : 0D01030102060300
Duration                                 : 1mn 14s
Bit rate mode                            : Constant
Bit rate                                 : 1 152 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 KHz
Frame rate                               : 29.970 fps (1601.6 spf)
Bit depth                                : 24 bits
Stream size                              : 10.2 MiB (2%)

Audio #6
ID                                       : 8
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, wrapping mode           : Frame (AES)
Codec ID                                 : 0D01030102060300
Duration                                 : 1mn 14s
Bit rate mode                            : Constant
Bit rate                                 : 1 152 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 KHz
Frame rate                               : 29.970 fps (1601.6 spf)
Bit depth                                : 24 bits
Stream size                              : 10.2 MiB (2%)

Audio #7
ID                                       : 9
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, wrapping mode           : Frame (AES)
Codec ID                                 : 0D01030102060300
Duration                                 : 1mn 14s
Bit rate mode                            : Constant
Bit rate                                 : 1 152 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 KHz
Frame rate                               : 29.970 fps (1601.6 spf)
Bit depth                                : 24 bits
Stream size                              : 10.2 MiB (2%)

Audio #8
ID                                       : 10
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, wrapping mode           : Frame (AES)
Codec ID                                 : 0D01030102060300
Duration                                 : 1mn 14s
Bit rate mode                            : Constant
Bit rate                                 : 1 152 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 KHz
Frame rate                               : 29.970 fps (1601.6 spf)
Bit depth                                : 24 bits
Stream size                              : 10.2 MiB (2%)

Text #1
ID                                       : 11-CC1
Format                                   : EIA-608
Muxing mode                              : Ancillary data / CDP
Duration                                 : 1mn 14s
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)

Text #2
ID                                       : 11-1
Format                                   : EIA-708
Muxing mode                              : Ancillary data / CDP
Duration                                 : 1mn 14s
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)

Other #1
ID                                       : 1-Material
Type                                     : Time code
Format                                   : MXF TC
Time code of first frame                 : 00:00:00:00
Time code settings                       : Material Package
Time code, striped                       : Yes

Other #2
ID                                       : 1-Source
Type                                     : Time code
Format                                   : MXF TC
Time code of first frame                 : 00:00:00:00
Time code settings                       : Source Package
Time code, striped                       : Yes

Other #3
Type                                     : Time code
Format                                   : SMPTE TC
Muxing mode                              : SDTI
Time code of first frame                 : 00:00:00:00

**If I use another filter (payed filter) it shows all tracks:**
![image](https://cloud.githubusercontent.com/assets/20997756/18758878/435af466-80d0-11e6-875a-510f246c52cd.png)

**Does anyone knows how to solve it?**

**Comment by filler56789** [comment]
Not an answer to your question, but...

Well, the MXF container is really "unusual" regarding the audio part. Those eight "tracks" are not actual tracks at all, they are the eight channels of a multichannel stream, and should be played simultaneously. Apparently, then, LAV Splitter should be instructed to treat the MXF container differently, I guess **: -/**

**Comment by Aleksoid1978** [comment]
LAV Splitter always output only one pin for video/audio/subtitles. You need use IAMStreamSelect interface for get track's list and select/change it.

**Comment by marcobpasquali** [comment]
Hi @Aleksoid1978,
thanks for your reply!!

I understand that LAV Splitter just output only one pin for video/audio/subtitles but the problem is that Audio Output Pin is showing just 1 audio Stream but the file has 8..

If I open a MP4 with 2 audio streams it works correctly showing 2 streams, but with MXF no.

MXF:
![image](https://cloud.githubusercontent.com/assets/20997756/18834046/2c983372-83ca-11e6-9b8a-72a2bf904a23.png)

MP4:
![image](https://cloud.githubusercontent.com/assets/20997756/18834083/6e21c970-83ca-11e6-954c-b320791957a5.png)

Do you have any idea about what's wrong?

Thanks,
Marco

**Comment by marcobpasquali** [comment]
@Aleksoid1978 it was my fault, all the streams are there.
Sorry...
