### ISSUE TITLE
Memory Leak with h264/mov

### ISSUE THREAD

**Issue by MikOfClassX** [Nevcairiel/LAVFilters#109]
Hello,

I probably found a serious memory leak when the LAV filters deal with h264/mov files (other formats may also be affected).

I created a small tool that opens/closes the same test mediafile in a loop. Please see the attached pics.

Cheers,

Mik

![lav_h264](https://cloud.githubusercontent.com/assets/6151192/18987535/5f538268-8702-11e6-8cb9-4af2bb07d5b0.jpg)
![lav_wmv](https://cloud.githubusercontent.com/assets/6151192/18987536/5f5b4d54-8702-11e6-986e-5c34cb406b02.jpg)

**Comment by Nevcairiel** [comment]
Can you reproduce this using a typical player, say MPC-HC, playing your test file and just pressing Ctrl+E (Re-open file) a few times?

In past experiences, custom tools have more often been responsible for bad measurements than LAV actually leaking anything.

**Comment by MikOfClassX** [comment]
I understand your position, but MPC-HC is using internal decoders (it can be forced to use LAV, but it fails to loop a playlist of small test files). 
In any case, while I'm trying to find a suitable tool for the testing (i.e. something that does not spawn a new process for each media), my graph is something still without an apparent explication, apart the memory leak with some codecs.

Mik

**Comment by Nevcairiel** [comment]
I tried to reproduce any leaks with the tools at my disposale and could not find anything. If you can provide the necessary tools and ideally also the video(s) it happens with, please re-open the issue.
