### ISSUE TITLE
Unable to use DXVA with r9 290x

### ISSUE THREAD

**Issue by Velbrant** [Nevcairiel/LAVFilters#110]
![dxva](https://cloud.githubusercontent.com/assets/22802785/19330100/fa9352da-90e4-11e6-808e-7ee33b995617.jpg)

im not sure is there a driver problem or filter problem.. so i created a ticket in amd support too :)

**Comment by Aleksoid1978** [comment]
It's don't support HEVC 10bit DXVA.

**Comment by Nevcairiel** [comment]
Indeed, HEVC decoding isn't supported at all on 290x cards, not to mention 10-bit decoding. The hardware is too old.

**Comment by Velbrant** [comment]
thanks, h264 works ok.

**Comment by nwgat** [comment]
fiji (fury/x/nano) is the first one that supports hardware hevc decoding
