### ISSUE TITLE
cuvid hvec 10bit decodes in software mode

### ISSUE THREAD

**Issue by psionx** [Nevcairiel/LAVFilters#111]
Nvidia PureVideo:
Feature Set F
Introduced dedicated HEVC Main (8-bit) & Main 10 (10-bit) and VP9 hardware decoding video decoding up to 4096 × 2304 pixels resolution.
Feature Set G
Introduced dedicated hardware video decoding of HEVC Main 12 (12-bit) up to 4096 × 2304 pixels resolution.
Feature Set H
 are capable of hardware-accelerated decoding of 8192x8192 (8k resolution) H.265/HEVC video streams.[19] 
https://en.wikipedia.org/wiki/Nvidia_PureVideo

10bit HVEC has been supported since the release of the gtx 750 SE /950(set F). I'm using a gtx 1060 3gb(set H) with windows 10 anniversary update and lav decoder 0.68.1. dxva dose work at least gpu-z shows video engine load and h/w status is shown in mpc-hc. with cuvid I know I'm using the 1060 to decode and not the unreliabe decoder on my haswell cpu for h264 video. it'd be nice not to have to switch between them.

**Comment by Nevcairiel** [comment]
CUVID does not support proper 10-bit decode, its a limitation in the CUVID API.

I don't see whats wrong with using DXVA, it supports decoding for all codecs with perfect 10-bit output.

**Comment by psionx** [comment]
the cuvid api may be limited but the hardware that the api is using is not. so I see no reason the cuvid api can't be updated to take advantage of new features. the driver for my igpu is buggy and can't be updated due to being a custom intel driver by lenovo. meaning dxva+intel=broken, dxva+nvida=working with dxva copyback you can select the gpu to use. but in some cases copyback will desync audio among other problems over dxva native.

**Comment by Nevcairiel** [comment]
Feel free to tell NVIDIA that they should update their API then to allow 10-bit output. Its not something anyone else can do.

**Comment by psionx** [comment]
they did in NVIDIA VIDEO CODEC SDK 7.0
"NVDECODE API (formerly called NVCUVID API)"
https://developer.nvidia.com/nvidia-video-codec-sdk
it should fix your problems with vp9 at the very least.

**Comment by lvqcl** [comment]
That web page has a link to the "NVDECODE API Programming Guide" pdf. It contains the following info:

Hardware Video Decoder Capabilities:
H.265/HEVC: Main profile up to Level 5.1
VP9: Profile 0

And it looks like 10-bit **de**coding is **not** supported.

**Comment by Squall-Leonhart** [comment]
* HEVC/VP9 10/12 bit decoding SW support coming in Video Codec SDK 8.0

Definitely not supported in 7.0 or 7.1 going by that note.

maybe when nvidia decides to actually release 8.0 (as its quite overdue), Nev can add it.

**Comment by c4shflo** [comment]
Hey guys, I recently got an LG OLED65C7P and upgraded my HTPC to a 1050ti low profile so I can decode 10bit HEVC with it, my CPU isn't strong enough for that.

I was able to set MPC-HC up with madVR and the latest LAV filters (as of this writing). Everything decodes in hardware except 10bit HVEC. Since the API is available from Nvidia now, can we expect to see LAV filters support this?

**Comment by Nevcairiel** [comment]
LAV already supports this. Nevertheless, you should be using DXVA or the new upcoming D3D11 mode, not CUVID.

**Comment by c4shflo** [comment]
Thanks for checking in. I tried all of them, DXVA, copy back, etc... all do the same, I see H/W and smooth playback and low CPU usage unless the file is 10bit and then no "H/W" and choppy playback with high CPU usage. MAybe it's because i'm on Win 7 x64.

**Comment by Squall-Leonhart** [comment]
Windows 7 doesn't have the NV12 format required for this under the D3D11 feature level.

**Comment by Nevcairiel** [comment]
That is correct, but DXVA2 should still work on 7 regardless.

**Comment by Squall-Leonhart** [comment]
Ah, for some reason i misread that he was trying to use D3D11.
