### ISSUE TITLE
Video Decoder buffers

### ISSUE THREAD

**Issue by FrankMarcus** [Nevcairiel/LAVFilters#112]
It seems that the decoder is buffering up to two GOVs during H.264 decoding. Is it possible to reduce this to get a better latency?

**Comment by Nevcairiel** [comment]
Disable multi-threaded decoding, it should reduce the latency. Every thread increases the latency by one frame.

Other improvements are not really possible.

**Comment by FrankMarcus** [comment]
Thanks! I think you meant that i have to set the "Threads for Multi-Threading" to one. But still there's a latency (FullHD, 30 FPS, GOV 8) of about 250ms inside the decoder.
We decode up to 25 of these FullHD streams with the LAV decoder (DXVA native) in seperate threads with great results. There's only the latency issue compared to other H.264 decoders.
