### ISSUE TITLE
Improve realtime playback for camera feeds

### ISSUE THREAD

**Issue by lummoj** [Nevcairiel/LAVFilters#114]
I'm having an issue at the moment when playing back RTSP feeds from IP cameras using LAV where after several hours or days the feed becomes progressively more and more delayed (5-10 seconds or more).

I've tried adjusting parameters such as Maximum Queue Memory and Maximum Queue Packets. This seems to limit the maximum delay but leads to playback stuttering once those limits are reached.

FFplay has an option called AV_SYNC_EXTERNAL_CLOCK (-sync ext INPUT) which seems to fix the issue. I'm assuming it skips forward if required using the external clock rather than buffering. It seems the underlying problem may be related to a mismatch between the local clock and external source clock.

References:
https://github.com/FFmpeg/FFmpeg/blob/master/ffplay.c
http://stackoverflow.com/questions/16658873/how-to-minimize-the-delay-in-a-live-streaming-with-ffmpeg

Is it possible to implement this option or something similar in LAVFilters? I'm happy to do the legwork but if you could give me an idea of where to start that would be much appreciated.

**Comment by Nevcairiel** [comment]
At this time I do not plan to work on streaming support.

The key problem is that LAVs entire architecture is designed around playback of files, which allow reading ahead and buffering - while streams run in realtime and any buffering is problematic and best avoided. As such, the streaming concept does not really fit well into the architecture, which is where many of the problems come from.

On top of that, ffmpegs streaming support isn't all that perfect, so using a RTSP library like live555 would end up with a better result then an ffmpeg rtsp streaming filter.

**Comment by lummoj** [comment]
Thanks for the quick response Hendrik.

That makes perfect sense and I can understand it's a very different direction for the library compared to file based playback. 

I'll take a look at live555. We have used VLC in the past which I believe uses that for RTSP streaming.
