### ISSUE TITLE
Volume loss when jumping back during play.

### ISSUE THREAD

**Issue by retrue** [Nevcairiel/LAVFilters#115]
I use Windows 8.1 with the last versions of LAVFilters, madVR and MPC-HC but the problem has been happening for months now.
Sometimes, while playing a video, if I jump back using the left arrow key, the audio will lose volume in a clearly noticeable way. The only way to have normal volume again (short of closing and restarting MPC-HC) is going to Filters --> LAV Audio Decoder --> Audio Settings and changing a parameter there, it doesn't matter which. Just ticking an option, apply change, untick, apply change does the trick and the volume goes back to normal.
Dunno if it happens too when jumping forward.

**Comment by retrue** [comment]
I experienced this problem during months, but it has not happened again lately. I updated the audio drivers of the mainboard recently so maybe that is the explanation.
However I was using the old audio drivers for two years without this problem of volume loss, so I don't know the cause really. If it happens again, I will post it here.

**Comment by Nevcairiel** [comment]
There is various reasons how this could happen, but it doesn't seem like LAV would really cause this. If you can provide some more information if this behavior should come back, please re-open the issue.

**Comment by retrue** [comment]
Hi.
Yesterday I noticed again this problem. It happened while watching several episodes of an anime series. I don't know if it is a regression or it is caused by a particular codecs configuration.
The volume turned so low that I turned up the volume of the speakers to the maximum until I guessed that maybe was this bug. Going to the settings of LAV audio codec like I explained in the first post here returned the volume to normal.
I am using version version 0.70.2.44 of LAV filters and MPC-HC version 1.7.13.89.
The audio media info of that anime episode is:
```
Audio
ID                             : 2
Format                         : AAC
Format/Info                    : Advanced Audio Codec
Format profile                 : HE-AAC / LC
Codec ID                       : A_AAC
Duration                       : 23 min 8 s
Bit rate                       : 82.7 kb/s
Channel(s)                     : 2 channels
Channel positions              : Front: L R
Sampling rate                  : 48.0 kHz / 24.0 kHz
Frame rate                     : 23.438 FPS (1024 SPF)
Compression mode               : Lossy
Delay relative to video        : 40 ms
Stream size                    : 13.7 MiB (5%)
Language                       : Japanese
Default                        : Yes
Forced                         : No
```
