### ISSUE TITLE
please add an aspect ratio option (drop down for 4:3, 16:9 etc)

### ISSUE THREAD

**Issue by creftor** [Nevcairiel/LAVFilters#116]
any chance you guys can implement an aspect ratio option so you can change the ar when using wmp?

i know i can use mpc etc, but i prefer wmp, but there's no ar controls. i'm still using ffdshow because of this but it doesn't support hevec so i have lav installed for that, if an ar option can be added i can finally ditch ffdshow, also wondering why such an option hasn't been added yet?

**Comment by Nevcairiel** [comment]
I do not plan to offer such options. Overriding the aspect ratio is not the video decoders job, if your player can't do it, consider switching to one that can.
