### ISSUE TITLE
DXVA broken on RX480 with 0.69

### ISSUE THREAD

**Issue by Daisenki** [Nevcairiel/LAVFilters#118]
After I update to version 0.69 there was a problem with the playback of mp4 files, I spend hours today to try many things and find a solution for it... its your 0.69. After switching back to the 0.68.1 the issue is gone.

Let me explain that:

The playback of mp4 files stutter every few seconds, its like a jump, but the audio not, the audio is fine. It happens only at mp4 files (sorry for my basic knowledge about codecs etc). If I use copy-back = stutter; If I use native = playback stops after starting the video; If I use none = no stutter and the playback works fine. My first thought was maybe its the AMD driver (16.12.2 newest), reinstall it, its the same, back to old driver, its the same... then I switch back to the 0.68.1 everything works, copy-back works, native works, mp4 files work. No changes on any setting, only switching back ti 0.68.1 fix the issue.

I test it with the file: MPEG-4; AVC codec; 29.970

If you need any information to fix it or check it, ask me, you only need to say what you need. 

(Hope my english is ok, I'm not a native speaker)

**Comment by amayra** [comment]
did you try clean install ?

**Comment by Daisenki** [comment]
I made a clean install with DDU for the AMD driver, test MPC-HC in the last two nightly builds, test madvr 0.91.5 and 0.91.4, try many settings with madvr... the interesting question is, why does everything works correct with the 0.68.1 but not with the 0.69 on the same settings.

**Comment by mkver** [comment]
Does this happen for all mp4-files? And what happens if you remux these files to mkv-files? Do they play fine?

**Comment by Daisenki** [comment]
I have check a few mp4 files: 

Playback issue with 0.69: AVC, High@L4, CABAC : yes, ReFrames 16 frames, avc1, Advanced Video Coding 
Playback fine with 0.69: AVC, High@L3.1, CABAC : yes, ReFrames 11 frames, avc1, Advanced Video Coding 

Playback fine with 0.68.1: AVC, High@L4, CABAC : yes, ReFrames 16 frames, avc1, Advanced Video Coding 
Playback fine with 0.68.1: AVC, High@L3.1, CABAC : yes, ReFrames 11 frames, avc1, Advanced Video Coding 

Is the format profil the problem? But I don't unterstand that, because with the same settings both files work with 0.68.1

I can't remux, never did.

**Comment by mhanor** [comment]
I have a fresh RX 480, but installing 0.68.1 doesn't help. I assume that the drivers are buggy, because my old HD6850 never had any problems, except for some MPEG2 streams. I think it would be better to report the DXVA issue through www.amd.com/report

**Comment by Daisenki** [comment]
I already did report it to AMD, because it's not sure why it happens. Sadly the driver for the RX480 is pure shit, AMD did so much fixes and even more bugs came. I will never buy any more a AMD card in the future.

**Comment by nwgat** [comment]
Crimson 17.1.1/17.1.2 drivers are beta, so stick to older lavfilter or use [16.12.2 whql for stability](http://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-ReLive-Edition-16.12.2-Release-Notes.aspx)
there are always bugs, a friend of mine  had a bsod due to incompatibility with nvidia drivers

do mpc-be or mpc-hc built-in codecs also have this issue? does windows media player/Film and videos have it?

**Comment by mhanor** [comment]
I think AMD fixed the issue with the Crimson 17.2.1 drivers, released on February 10. At least, on my PC they seem to do DXVA without any issues.

**Comment by Daisenki** [comment]
I don't know and to be honest I have sold my RX480 because all these driver issues, not only this here. I made so many issue reports to AMD in the last months and with every new driver version new bugs and no fixes and no, I'm not the only one with problems, the AMD boards are full of issue reports. 

I'm using now a MSI 1060 and have no issues.

**Comment by mhanor** [comment]
You should close the issue. Just as a note, I spoke too soon about the new driver. It works better, but a small stream hiccup can lead to a decoder state where it won't recover.

**Comment by Arnaud-Loisy** [comment]
Still using previous beta drivers can't reproduce the issue on 0.69 with RX480 (with any driver i had with this version anyway)
Though i still have to find a video with ReFrames : 16 frames, tried with some from 1 to 6 frames.
Is it specific to this encoding setting ?

**Comment by Daisenki** [comment]
I close this issue now, because I can't test anything and with the change to Nvidia the problem is gone for me. If anyone had this issue too, he can open a new issue post.
