### ISSUE TITLE
Can it be done w/o admin rights?

### ISSUE THREAD

**Issue by andkirby** [Nevcairiel/LAVFilters#119]
It's a pain on a work laptop. So, can I install it w/o admin rights?

**Comment by kasper93** [comment]
No you cannot register filters without admin rights. You can use players like MPC-HC which doesn't require filters to be installed in order to use them.

**Comment by Nevcairiel** [comment]
Kasper93 is correct, installing requires admin, but not all players require them to be installed.

**Comment by andkirby** [comment]
Got it. Thanks for your answers, guys.
