### ISSUE TITLE
intermittent black screen

### ISSUE THREAD

**Issue by chi2king** [Nevcairiel/LAVFilters#121]
Hi!

I am using your codec for my windows forms project for playing mp4 files. Only problem is I sometimes get a black screen though with audio playing.

Is this a common issue? Attached is my video configuration and pc hardware

Thanks a lot.

![cpu](https://cloud.githubusercontent.com/assets/11574806/22395213/c165d154-e571-11e6-874d-b0fad0e5fcd2.png)
![display driver](https://cloud.githubusercontent.com/assets/11574806/22395198/7e3e4a3c-e571-11e6-8238-99d8644709c6.png)
![video codec](https://cloud.githubusercontent.com/assets/11574806/22395197/7e3d2882-e571-11e6-8549-50fb5633dec3.png)

**Comment by chi2king** [comment]
any suggestions here please? I already used DXVA2(copyback) with the selected Hardware Device to use but still the same

**Comment by chi2king** [comment]
no answer here?

**Comment by Hrxn** [comment]
Well, how to reproduce properly?

**Comment by Nevcairiel** [comment]
This sounds like a video renderer problem, not a decoder problem, as especially in software mode the decoder is known to function properly and independent of the system its running on.

I would suggest to seek support from the player you are using, or the video renderer.
