### ISSUE TITLE
Start reading WAVEFORMATEXTENSIBLE_CHANNEL_MASK tags in FLAC files.

### ISSUE THREAD

**Issue by ramicio** [Nevcairiel/LAVFilters#123]
This has been around forever, and yet hardly anyone supports it. I am sick of FLAC files being decoded wrong, and anything madshi does besides madVR is just dead at this point.

**Comment by Nevcairiel** [comment]
This should work just fine already when you use LAV Splitter +  LAV Audio, and a quick test on some samples I had around confirms that this is the case.

**Comment by ramicio** [comment]
The behavior is erratic. If I have a file with a 3f mask, LAV will change it to 60f, unless I check "Use Legacy 5.1 channel layout." If I have that option selected, LAV changes 60f files to 3f. Please reopen. This IS an issue. There seems to be no way to tell these filters to simply use that tag automatically ALL of the time.

**Comment by Nevcairiel** [comment]
This is absolutely intentional behavior, and there are no plans to change this.

**Comment by ramicio** [comment]
Why is it intentional to leave a person with no option to simply read what is specified in the file? If the channel mask is specified in the file, then obviously the person who made the file knows the behavior they want. Some 5.1 stuff is mastered for "side" speakers, and some for "rear" speakers. The whole point of a specified channel mask is to not have to go through menu hierarchies and manually check a tick box, but to let the player automatically read the specified layout from the file.
