### ISSUE TITLE
Selecting PCM Audio Channel in LAV Filter

### ISSUE THREAD

**Issue by l0phtgh0st** [Nevcairiel/LAVFilters#127]
MPC-HC just show 1 audio channel while it actually have 2 audio channel.

General
Complete name                  : C:\Users\Admin\Desktop\video.vob
Format                         : MPEG-PS
File size                      : 264 MiB
Duration                       : 4 min
Overall bit rate mode          : Variable
Overall bit rate               : 7 617 kb/s

Video
ID                             : 224 (0xE0)
Format                         : MPEG Video
Format version                 : Version 2
Format profile                 : Main@Main
Format settings, BVOP          : Yes
Format settings, Matrix        : Default
Format settings, GOP           : M=3, N=15
Format settings, picture struc : Frame
Duration                       : 4 min
Bit rate mode                  : Variable
Bit rate                       : 4 393 kb/s
Maximum bit rate               : 4 878 kb/s
Width                          : 720 pixels
Height                         : 480 pixels
Display aspect ratio           : 16:9
Frame rate                     : 29.970 (30000/1001) FPS
Standard                       : NTSC
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Interlaced
Scan order                     : Bottom Field First
Compression mode               : Lossy
Bits/(Pixel*Frame)             : 0.424
Time code of first frame       : 00:36:10:15
Time code source               : Group of pictures header
GOP, Open/Closed               : Closed
Stream size                    : 152 MiB (58%)

Audio #1
ID                             : 189 (0xBD)-160 (0xA0)
Format                         : PCM
Format settings, Endianness    : Big
Format settings, Sign          : Signed
Muxing mode                    : DVD-Video
Duration                       : 4 min
Bit rate mode                  : Constant
Bit rate                       : 1 536 kb/s
Channel(s)                     : 2 channels
Sampling rate                  : 48.0 kHz
Bit depth                      : 16 bits
Delay relative to video        : -87 ms
Stream size                    : 53.2 MiB (20%)

Audio #2
ID                             : 189 (0xBD)-161 (0xA1)
Format                         : PCM
Format settings, Endianness    : Big
Format settings, Sign          : Signed
Muxing mode                    : DVD-Video
Duration                       : 4 min
Bit rate mode                  : Constant
Bit rate                       : 1 536 kb/s
Channel(s)                     : 2 channels
Sampling rate                  : 48.0 kHz
Bit depth                      : 16 bits
Delay relative to video        : -87 ms
Stream size                    : 53.2 MiB (20%)

Menu
Duration                       : 4 min

Media Info Detail

``
Video: MPEG2 Video 720x480 (16:9) 29.97fps [V: mpeg2 main, yuv420p, 720x480]
Audio: LPCM 48000Hz stereo 1536kbps [A: pcm_dvd, 48000 Hz, 2 channels, s16, 1536 kb/s]
``

I thought I can just used [IAMStreamSelect.Enable](https://msdn.microsoft.com/en-us/library/windows/desktop/dd319795.aspx) to change stream (like usual).

The [IAMStreamSelect.Count](https://msdn.microsoft.com/en-us/library/windows/desktop/dd319794.aspx) method return 2 (one for video stream and one for audio stream.)

I have also try to use **ILAVAudioStatus.GetDecodeDetails** method and it return 2 in value of audio channel.

Since it is possible to change the channel in VLC player, I thought it could be done with LAV Filter.

Could you please tell me how to change PCM Audio Channel in LAV Filter?

I am a developer so I would appreciate it if you could point me to a method (or filter interface) in LAV Filter which I need to call to change PCM Audio Channel.

Thank you.

**Comment by Nevcairiel** [comment]
PCM is not special in any way. If LAV does not report multiple audio streams then for some reason it didn't detect the second stream. You would have to provide a sample file, otherwise there is nothing I can do.

**Comment by l0phtgh0st** [comment]
@Nevcairiel , I have send you an email containing the link to download the sample video.

Thank you

**Comment by Nevcairiel** [comment]
This should be fixed in the next version, thanks for providing a sample.
