### ISSUE TITLE
3D BluRay ISO files not playing 

### ISSUE THREAD

**Issue by HTPCSourcer** [Nevcairiel/LAVFilters#128]
Hi,

With the new release of MediaPortal 2.1 we also rolled out the recent LAV build 0.69. 

Since late December we had received some reports from a few people who couldn't play the 3D BluRay iso files anymore, something that we could not really test/confirm because nobody in the MP2 team has such files nor even a BluRay player.

Today we were able to confirm the existence of a problem in the LAV codec. We tested all LAV versions since 0.63 (the last version confirmed to work in connection with MediaPortal 2.1) and tried to play a particular 3D iso file on a MediaPortal 2.1 build:

0.63   plays OK
0.64   plays OK
0.65   plays OK
0.66   Broken
0.68.1 Broken
0.69 Broken

So something changed with 0.66 that affects the BR playback activity of MediaPortal 2.

The above can maybe give you a hint as to what might have caused this.

Thanks,
HTPCSourcer

**Comment by Nevcairiel** [comment]
LAV does not support any kind of ISO files. Additionally, 3D support was only added in 0.68, not any earlier versions.

**Comment by HTPCSourcer** [comment]
Hi Nevcairiel,

thanks for your quick reply.

I am just the messenger and can't supply any files to you directly. I'll see if I can get you access to something that people uploaded but would then need a private communication channel as the material is copyright-protected. Also, I would have supplied more specific details if only there was something logged at our side.

Regarding ISO: I didn't express myself well. The ISO's in question are of course mounted and accessible to the local file system as a directory by means of Dokan. The replay works using the MediaPortal player which builds the graph using the LAV codec(s). We could demonstrate that the combination of LAV 0.65 or earlier with MediaPortal works as expected (regardless of the DOkan version used), while LAV 0.66 and higher leads to the described symptoms.

**Comment by HTPCSourcer** [comment]
Hello again,

The problem is only occurring with large BlueRay ISO files that are mounted with Dokan. All DVD (and also some BR) play nicely, regardless of the LAV version used. Therefore I can't provide just a sample to reproduce the problem but we ned a full-blown BluRay structure to demonstrate it.

As I said we could provide you a download link for a full BR iso (lots of GB...). Nonetheless you would probably need to install MediaPortal 2.1, add a single share with just this particular BR file, and try to play it using different LAV versions. 

As previously mentioned the combination of MP 2.1 (pre/pre2) and LAV 0.65 works, but 0.66 to 0.69 don't.

Kindly let me know if (and in that case how) we coiuld proceed.

Thanks,
HTPCSourcer

**Comment by Nevcairiel** [comment]
As I said in my initial response, reports of "it doesn't work" are not very helpful, especially if it supposedly broke several years ago, and noone else found any problems until now. If any MediaPortal developers have analyzed the problems, they should make a proper bug report with the actual details of what doesn't work and what circumstances lead to it not working.

To me, it sounds like a problem very specific to MediaPortal, and as such without a MediaPortal developer analyzing the issue on their end and being able to report actual specifics, there is no place to start.

**Comment by HTPCSourcer** [comment]
No, it's not MP-specific. Let me cite morpheus_xx who just provided this information, where he tested the playback of the 3D BR without MediaPortal under Windows only.

*******
The issues were also reproducible without MP2.1:
 I mounted the ISO by Windows explorer, so they got a new drive letter. Then I have opened the index.bdmv using graphedit to test playback with DirectShow and LAV Splitter Source. This worked with lower LAV versions.

Important thing is, that another mounted BD ISO was working correctly also in recent versions, so I think it is a combination of some only kind of BD rips (maybe the 3D does make the difference???) and LAV versions. 
*********

**Comment by clsid2** [comment]
Copy the entire contents of the mounted iso to a folder on your harddrive. Test if that makes any difference when playing that.

Here are versions in between 0.65 and 0.66:
https://files.1f0.de/lavf/nightly/0.65/

GraphStudioNext:
https://github.com/cplussharp/graph-studio-next

**Comment by bobreese** [comment]
Tested down to and including 65.0-26, all good
65.0.-28 failed.
GraphEdit has 2 failures when trying to open the index. bdmv

![lav 65 0 28](https://cloud.githubusercontent.com/assets/461610/23616007/eb32f388-024d-11e7-96d7-f75319cec241.jpg)
![lav 65 0 28 second error](https://cloud.githubusercontent.com/assets/461610/23616006/eb2fb556-024d-11e7-98f6-0551c491d0d6.jpg)

**Comment by Nevcairiel** [comment]
Unless you can provide a sample which doesn't work there is nothing I can do. All discs I have tried, 3D or otherwise, work just fine, nor have I gotten such a report within the last 2 years in which this is supposedly broken.

**Comment by bobreese** [comment]
Is there someplace I can upload a 16G file?

**Comment by filler56789** [comment]
> bobreese wrote:
"Is there someplace I can upload a 16G file?"

Google Drive, probably.
As a last resort, you can always use BitTorrent's DHT and share a temporary magnet link.

**Comment by bobreese** [comment]
Working on a Google Drive upload
This is going to take Some Time to complete...

**Comment by Nevcairiel** [comment]
I found the reason for the problem, it was due to some over-zealous checks in libbluray. It should be corrected in the next build.

Thank you for providing a sample.
