### ISSUE TITLE
LAV Splitter Source problem with mpeg-dash

### ISSUE THREAD

**Issue by DavidBrenner3** [Nevcairiel/LAVFilters#129]
Hi,

Very good codecs, just a small problem:

I'm also a computer programmer and I made a small tool.
One of its features is to capture frames from video files using DSPack and samplegrabber.
But the onBuffer samplegrabber event doesn't seem to always fire when loading mpeg-dash files with LAV Splitter source.
Here is the screenshot of the graph:

![k-lite](https://cloud.githubusercontent.com/assets/9998134/24035125/e9976934-0afc-11e7-9201-d04b52ae1a5e.png)

But it does when using "File source (Async.)" + "LAV splitter".

![x-codec pack](https://cloud.githubusercontent.com/assets/9998134/24035138/ff7791c0-0afc-11e7-9dc8-da7bf8c15f72.png)

If you need more details and/or test files just let me know...

**Comment by Nevcairiel** [comment]
LAV doesn't actually support reading mpeg-dash streams.

**Comment by DavidBrenner3** [comment]
Thank you for fast reply.

Question: how to programatically disable the use of "LAV splitter Source" for mpeg-dash streams but keeping the "LAV Splitter"? Just when playing the mpeg-dash file and when capturing the frames.
My tool is using the default DirectX rendering and is modifying it later to exclude the video and audio output.
I tried to avoid its usage in OnSelectedFilter event but doesn't seem to be listed there.

And I have to find a way to detect it's a mpeg-dash too (couldn't find a way yet).

Could you help me with these too?

Thank you.

**Comment by Nevcairiel** [comment]
I'm not aware of an easy way to detect those. Being a streaming format, one would ordinarily assume its a URL, and you would point the player at the manifest file (the .mpd) - in which case LAV should not actually open anything since it doesn't understand the manifest.

But if you downloaded the individual  dash segments and try to open them, it'll try, since they are a format it basically understands (ie. mp4), but it still can't read them properly.

**Comment by DavidBrenner3** [comment]
This is such a file (the guy who made the Youtube downloader addon used for downloading it named it "mpeg-dash"):

https://drive.google.com/open?id=0ByKxAD_t9uvLWXFRcGZPb181cnc

**Comment by Nevcairiel** [comment]
The file plays just fine for me in either combination.

The basic DirectShow sample grabber filter is honestly not quite smart, it often fails on the most basic of tasks - if you rely on that, it might be better to write your own simple filter to grab frames out of a graph.

**Comment by DavidBrenner3** [comment]
You're right, the file plays fine.
But the problem is not playing, is capturing the frames.

I've done some tests and I noticed that it's the seeking (back and/or forth) that "confuses" the samplegrabber. If only one seek (to the start marker) is done, all is ok.
My solution is:
The user uses the play/pause/seeking commands to set the start and the finish marker; the code closes the video file, frees and recreates the window (where the DSPack components are; it has to be done, reloading video file is not enough) then reloads the video file, seeks to the start marker and plays until the finish marker, capturing the frames.
This way all the frames are captured and with the correct timestamps.

It's not that elegant solution but for the moment is acceptable.
