### ISSUE TITLE
LAV Splitter connection to File Source (Async.) fails with VFW_E_NO_ACCEPTABLE_TYPES

### ISSUE THREAD

**Issue by LuminescentMoon** [Nevcairiel/LAVFilters#132]
Using GraphStudioNext 0.7.1.24
Using LAVFilters 0.69

Steps to reproduce:
1. In a new graph, insert File Source (Async.) filter
2. Insert LAV Splitter filter
3. Using direct connection mode, connect Output pin of File Source (Async.) to Input pin of LAV Splitter

Result: The below error message

[Window Title]
Connecting Pins

[Main Instruction]
VFW_E_NO_ACCEPTABLE_TYPES (0x80040207)

[Content]
There is no common media type between these pins.
Connecting Pins (decimal -2147220985)

[Search for Error] [Show Graph Constrution Report] [OK] [Cancel]

**Comment by LuminescentMoon** [comment]
I'm guessing it's because LAV Splitter's Input pin doesn't offer any MediaTypes.

**Comment by filler56789** [comment]
Please post a MediaInfo report about the file(s) with which you're having this problem.
Even better if you share at least one sample file.
I have always used the combination File Source Async + LAV Splitter, and it has always worked fine thus far.
Equally possible: the build of GraphStudioNext you're using is buggy (???)

**Comment by Nevcairiel** [comment]
The only reason a connection would fail is if LAV doesn't support the file you are trying to open. It otherwise accepts any generic media types on the input pin.

**Comment by LuminescentMoon** [comment]
I see now. It only accepts media if its respective input format is enabled in the LAV Splitter configuration. Thanks for the help.
