### ISSUE TITLE
LAV 0.69 produces flickering showing HD TV

### ISSUE THREAD

**Issue by callibsoffm** [Nevcairiel/LAVFilters#133]
Hello,

LAV 0.69 produces flickering showing HD TV on Unitymedia when using DXVA2 copy back. All public HD telestations show this problem except ZDF. The problem is gone when turning off hardware accelaration. SD TV has no probleems.

OPS: Windows 10 64bit Build 15063, Graca: Radeon RX 460.

**Comment by callibsoffm** [comment]
Sorry, the the problem concerns DVBViewer using LAV in the above mentioned configuration.

**Comment by mhanor** [comment]
The video drivers are flawed. https://community.amd.com/thread/205135?start=300&tstart=0
Not even Microsoft's video codec works properly with AMD's DXVA implementation.

**Comment by callibsoffm** [comment]
With the new AMD drivers the problem is gone.

Thanks

Alexander

Von: mhanor [mailto:notifications@github.com]
Gesendet: Freitag, 28. April 2017 00:26
An: Nevcairiel/LAVFilters <LAVFilters@noreply.github.com>
Cc: Alexander Arnold <damienffm@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [Nevcairiel/LAVFilters] LAV 0.69 produces flickering showing HD TV (#133)


The video drivers are flawed. https://community.amd.com/thread/205135?start=300&tstart=0
Not even Microsoft's video codec works properly with AMD's DXVA implementation.
