### ISSUE TITLE
DVBSUB in Matroska lead to freezing during seeking

### ISSUE THREAD

**Issue by mkver** [Nevcairiel/LAVFilters#134]
Hello Nevcairiel,

seeking in matroska files (muxed by MKVToolNix) with DVB-subtitles occasionally leads to freezes. I used both MPC-HC 1.7.10 and 1.7.11 (always x64) to confirm this. The freezes are reproducible and the positions at which they happen depend on the queue settings in LAV Splitter (that's also why I post this here and not on MPC-HC's bugtracker). [Here](https://www.dropbox.com/s/dujznyz1cwrflft/EHwdA.mkv?dl=0) is a sample file.
If I open it, stop playback and use seek from keyframe to keyframe (Shift+Right), everything is right until 10.72s with the default values of 256 MB queue memory and 350 packets. Performing one more seek (to 11.36s) does not lead to 11.36s, but results in a freeze. With only 128 MB and 100 packets, I reach 30.56s and performing another seek to 31.2s results in a freeze. With 1280 MB and 1000 packets, I reach 7.4s and seeking to 8.04s fails. More tests showed that only the number of packets and not the queue memory affect this. (I have to add that I didn't use unreasonably low memory values: 128 MB was the lowest I tested.)
It also happens with other seeks, too: If I use 256 MB +350 packets and seek to 3:16, it freezes if I perform another +5s seek.
None of this happens if one deactivates the DVB subtitles in MPC-HC. Or if I remux the file and don't write the CueDuration and CueRelativePosition elements. Or if I don't seek, but just play the file (the subtitles are then shown correctly). That's all I know.
Other Matroska files with DVB subtitles show similar problems.

Greetings and thanks in advance
mkver

**Comment by amayra** [comment]
what do you use to renderer subtitles ?

**Comment by mkver** [comment]
MPC-HC's internal subtitle renderer. As has already been mentioned: I posted this here because the location of the freezes depend on LAV Splitter's queue packet length so that I am reasonably certain that it is an issue in LAV Splitter. It also does not depend on which video decoder I use.
What do you use to render the subtitles? Can you reproduce my findings? (I want to apologize if they turn out to be unreproducable.)

**Comment by Nevcairiel** [comment]
Its doubtful this is actually a LAV problem, the queue length controls how far ahead LAV reads, and as such how soon a subtitle decoder might receive the subtitles - as such, if one specific subtitle packet causes it to break, changing the queue size would change the point in time when it breaks, as you observed.

**Comment by mkver** [comment]
But then I wonder why ordinary playback doesn't freeze at all.

**Comment by mkver** [comment]
Ok, it seems that this issue only exists with EVR-CP+Internal Subtitle Renderer. It's not in LAV. I'll report it at MPC-HC's bug tracker. Sorry for wasting your time, Gentlemen.
