### ISSUE TITLE
There is a problem since 74 commit  - Update 7za.exe to 7-Zip 16.04 - antivirus delete it .

### ISSUE THREAD

**Issue by pop-dahaka** [Nevcairiel/LAVFilters#136]
Am using nightly build and there are problems related to antivirus from Update 7za.exe to 7-Zip 16.04 , kaspersky delete it as soon as i run it so i went to virustotal.com 
https://www.virustotal.com/en/file/3fcf72c2f3b8d827ce8798cf2721e8d2da799c7fba12e6685f774aed196f70e3/analysis/1495266510/

https://www.virustotal.com/en/file/96b5cb89201bc01f4ff0d1835aac2b9b0e491f10e72f9cfafdf233e421315d68/analysis/1495461408/

 , i wish you fix it when you have free time .

**Comment by filler56789** [comment]
What needs to be fixed is the antivirus software, not the installer of LAV Filters.

https://forum.doom9.org/showthread.php?p=1807503#post1807503

**Comment by pop-dahaka** [comment]
I sent to kaspersky and waiting for reply.

**Comment by Nevcairiel** [comment]
As mentioned above and in the forum thread, the file is entirely safe and quite interesting enough the 7za.exe itself does not get detected by anything by itself, but when put in the installer its suddenly evil.

Anyhow, Antivirus false-positives need to be reported to the antivirus makers, only they can fix it.

**Comment by pop-dahaka** [comment]
Problem Fixed only from the new LAVFilters-0.69.0-80.exe , thanks .

https://www.virustotal.com/en/file/feee3a2642cbfb7cb6618739807b9c6314d9c2247520292ee871ea7a0553d1c1/analysis/1495829579/
