### ISSUE TITLE
Blacklisting LAV in games

### ISSUE THREAD

**Issue by Keith94** [Nevcairiel/LAVFilters#137]
Some games have issues (crashing, freezing) when LAV Filters is installed on the system. How can I blacklist LAV Filters 0.69 from being loaded in certain games?

**Comment by Keith94** [comment]
I have tried creating a DWORD 32-bit value named `mgs2_sse.exe` in `HKCU\Software\LAV\Blacklist` with value set to 1, but it did not fix the freezing issue at the intro video. Is there something I'm missing? Only uninstalling LAV fixes it.

**Comment by Nevcairiel** [comment]
There is several independent blacklists, ie. to blacklist LAV Video you would need to add that key in HKCU\Software\LAV\Video\Blacklist,  or for the splitter in HKCU\Software\LAV\Splitter\Blacklist, and so on.

**Comment by Keith94** [comment]
What if adding the .exe value to blacklist doesn't fix it? Is there anything else I can try besides uninstalling?

**Comment by Voideka** [comment]
Blacklisting doesn't seem to work.
