### ISSUE TITLE
EVR in Windows 10 Creators Update does not support P016

### ISSUE THREAD

**Issue by tnti** [Nevcairiel/LAVFilters#138]
EVR in Windows 10 Creators Update does not support P016
Output P016 will cause the flower screen
May not support it P216 Y416 RGB48

**Comment by Nevcairiel** [comment]
So don't use it? :)

**Comment by Nevcairiel** [comment]
Just to expand on this, on my NVIDIA card EVR also doesn't accept P016 at all, so it has no chance to screw up either, which means the driver properly says that it doesn't support it.

If your driver is broken and claims it supports something that  it doesn't actually support, then thats not a problem in LAV.

**Comment by tnti** [comment]
understood
