### ISSUE TITLE
Heisenbugs on Changing stream on some VOB file? 

### ISSUE THREAD

**Issue by l0phtgh0st** [Nevcairiel/LAVFilters#139]
I am using **LAV Splitter 0.69.0.7-git**.

I have notice that when I try to change audio stream with `IAMStreamSelect.Enable` on VOB file type, the program something crash while something it work perfectly fine.

 Unfortunately I cannot reproduce the error, I just notice that the program crash due to `IAMStreamSelect.Enable ` by investigating the log file.

Could you please kindly advise me which steps I should take to prevent the bug? 

If it is possible, could you please tell me a way to reproduce a bug since I cannot reproduce it.

Thank you

**Comment by Nevcairiel** [comment]
Unfortunately, I cannot tell you how to reproduce bugs that I know nothing about - if I did, i could just fix them.

If you are able to make an actual bug report with actionable information (preferably a clear case to reproduce for me locally), please re-open this issue. As it stands, there is nothing here that I can act on.

PS:
You're using an outdated version of LAV Filters, there is always a chance something may have been fixed, so you should verify with the latest version.
