### ISSUE TITLE
AAC 5.1 audio

### ISSUE THREAD

**Issue by cfelicio** [Nevcairiel/LAVFilters#140]
Hi There,

Is there a way to output AAC audio in 5.1 format? I am using Kodi Dsplayer with the latest LAVFilters, and when I have a movie with AAC audio, the volume will come out very low, and 2 channels only instead of 5.1.

If I use the regular Kodi Player, it will transcode to AC3, and play correctly in 5.1. I saw a proposed solution is to add a bypass filter to use ffdshow audio instead in this case, but I'm wondering if there is any way to get it working with LAV.

Thanks!

**Comment by Nevcairiel** [comment]
AAC audio is decoded to ordinary uncompressed PCM audio. If you don't have the ability to output 5.1 PCM, then you'll need to downmix to Stereo. If the default downmix from Windows or your audio renderer is not working well, you can also instruct LAV to perform a downmix.

LAV does not support re-encoding audio to AC3, and is also rather unlikely to ever do that.
