### ISSUE TITLE
LAV Splitter Subtitles setting

### ISSUE THREAD

**Issue by kulaLin** [Nevcairiel/LAVFilters#141]
Test environment
Windows 10 1703 x64
Potplayer x64 1.7.2233
LAV 0.70.0 x64
Test file (uploaded to Onedrive)
https://1drv.ms/f/s!AjUqrmggBlQhgawppfosW2DtWTSEtQ

How to setting subtitles use the "TW CHT [chi]" or "ENG [eng]" default at LAV Splitter.
This file default subtitle is "CN CHS [chi]".
![sshot-2017-06-26- 20](https://user-images.githubusercontent.com/17091825/27520562-ce8e8c56-5a40-11e7-9a4c-226a66777df6.png)

Thanks.

**Comment by Nevcairiel** [comment]
You can only use the language tag to select subtitles (the part in square brackets). If its the same tag for all streams, there is no way to pre-select different ones.

LAV uses ISO 639-2/639-3  language codes, if those different languages have separate codes, the files should use them - that way you can pre-select them with the subtitle rules.

**Comment by sneaker2** [comment]
You can also use the subtitle track name to some extend. E.g. in advanved subtitle selection mode:
`eng:chi@CHT`
If English audio is selected it will then select the chinese tagged subtitle with the name that has "CHT" in it. The problem in this case is the tag doesn't allow spaces so you can't really differ "CN **CHT**", "**TW** CHS" and "**TW CHT**" as they all either have "TW" or "CHT" in them.

Also, the feature only works on subtitles, not audio. AFAIK.

**Comment by kulaLin** [comment]
Thanks your reply.

Potplayer has been fixed this bug, It will auto detect.
