### ISSUE TITLE
AAC 5.1 audio

### ISSUE THREAD

**Issue by cfelicio** [Nevcairiel/LAVFilters#142]
Following up on issue #140 

If LAV is supposed to output 5.1 PCM with 5.1 AAC input, then I need a bit further help :-)

1 - I have full capable receiver that can play up to 7.1 PCM no problem.
2 - I can output 5.1 PCM with AAC 5.1 input if I use reclock (I am not transcoding to AC3)
3 - I have set windows audio to output 5.1 sound, and all speakers work

When I use LAV with default settings, if there is AAC 5.1 input, LAV will only output 2.0 PCM, not 5.1.

I guess I could stay with reclock, but I'd prefer to simplify the setup if possible and only use LAV. 

Thanks!

**Comment by cfelicio** [comment]
could be windows is doing a downmix somewhere, and with reclock it works because I'm using WASAPI?

**Comment by Nevcairiel** [comment]
If you use any output that goes through the Windows mixer, then it'll mix to whatever format the audio device is configured to, independent of the input. You can change those formats in the "Manage audio devices" section of the control panel, using the "Configure" button on each device.

PS:
The issue tracker on GitHub is for reporting actual issues, not for setup help. Thats what the forum is for.

**Comment by cfelicio** [comment]
Thanks, the audio mixer is configured to output 5.1, and everything works as expected except for AAC, but I don't know at this point if this is an issue on windows, or LAV.

I will try the support forums, and I know you are busy, but if anytime during testing you get a chance to try out this scenario, and see if it works for you (with LAV default settings) it would be highly appreciated! :-)
