### ISSUE TITLE
LAVFilters for *unix ?

### ISSUE THREAD

**Issue by abdusamed91** [Nevcairiel/LAVFilters#143]
Is there any application/filter which does similar job for a Linux Machine?

**Comment by Nevcairiel** [comment]
LAVFilters is mostly just a wrapper around the FFmpeg libraries, so any application that uses FFmpeg (and is  of a certain quality) would do.

For playback, check out mpv.

**Comment by abdusamed91** [comment]
mpv doesn't have the ability to dowmix 5.1+ to stereo on the fly.

**Comment by richardpl** [comment]
Yes it does have.
