### ISSUE TITLE
LAV Splitter with 2nd Subtitle

### ISSUE THREAD

**Issue by kulaLin** [Nevcairiel/LAVFilters#146]
LAV Splitter not support 2nd subtitle ?
Potplayer built-in can load 2nd subtitle, but enable your LAV Splitter can't pick 2nd subtitle 

![sshot-2017-07-18- 02-16-26](https://user-images.githubusercontent.com/17091825/28323391-3b44c56e-6c0b-11e7-8156-ed75d2f0e4e4.png)

This is potplayer built-in mode, can pick 2nd subtitle
![sshot-2017-07-18- 02-13-50](https://user-images.githubusercontent.com/17091825/28323390-3b3fd5ea-6c0b-11e7-8379-94e72ee6cf0c.png)

**Comment by Nevcairiel** [comment]
LAV Splitter only supports serving one subtitle stream during playback. There are also no plans to change how this works.
