### ISSUE TITLE
Can't decoder H265 video

### ISSUE THREAD

**Issue by kulaLin** [Nevcairiel/LAVFilters#149]
PotPlayer v1.7.3398 build-in mode can working playback this video.

But using your LAV Video decoder can't working this, will be black screen

Could you fix this issue?

Sample file:
https://goo.gl/hE7GUs

**Comment by Nevcairiel** [comment]
The file appears to be broken.

**Comment by kulaLin** [comment]
Download again please, link updated.

![sshot-2017-08-07- 20-39-19](https://user-images.githubusercontent.com/17091825/29027013-4a35c04a-7bb1-11e7-8372-0d9507a5d8d8.png)
![sshot-2017-08-07- 20-41-18](https://user-images.githubusercontent.com/17091825/29027014-4ae400a6-7bb1-11e7-868f-70527fc66721.png)

**Comment by Hrxn** [comment]
Is that the normal stat info overlay of PotPlayer?

**Comment by Nevcairiel** [comment]
The stream is just broken

[hevc @ 079c30a0] Overread SPS by 8 bits
[hevc @ 079c30a0] SPS 0 does not exist.
[hevc @ 079c30a0] Overread SPS by 8 bits
[hevc @ 079c30a0] SPS 0 does not exist.
[hevc @ 079c30a0] PPS id out of range: 0

Streams that don't decode with FFmpeg will not decode with LAV Video.

**Comment by kulaLin** [comment]
But this issue have been fixed on PotPlayer and MPC-BE.

Do you want to fix this issue ?

**Comment by kulaLin** [comment]
@Hrxn Yes, this is PotPlayer's OSD Info (Press TAB)

**Comment by Nevcairiel** [comment]
No. If the file doesn't decode with ffmpeg, then report it to ffmpeg.
