### ISSUE TITLE
LAVFilters doesn't support wav files completely - incorrect time length reported.

### ISSUE THREAD

**Issue by JonasNo** [Nevcairiel/LAVFilters#151]
Since MPC-HC is using LAVFilters I'll report it directly here. It doesn't report the time length correctly on wav some files.

Example: https://mega.nz/#!YuomER6Y!YNkShluWwT47YI085AS170xTbV_seFFfpbtC_7tLMfU
Time length is 11:42 according to VLC.
MPC-HC reports itime length as 03:43 however when it reaches that time it continues to play.

The example was downloaded 2017-08-18 and is free this month.
More can be found here: http://www.mysurround.com/en/catalog-free-titles
(Creating an account is free).

```
MPC-HC (64-bit)
---------------

Build information:
    Version:            1.7.13 (e37826845)
    Compiler:           MSVC v19.00.24215.01
    Build date:         Jul 16 2017 18:47:17

LAV Filters:
    LAV Splitter:       0.70.2.1
    LAV Video:          0.70.2.1
    LAV Audio:          0.70.2.1
    FFmpeg compiler:    MinGW-w64 GCC 7.1.0

Operating system:
    Name:               Windows NT 6.1 (build 7601, Service Pack 1)
    Version:            6.1 (64-bit)

```

**Comment by mkver** [comment]
This is ac3 muxed in a wave container (if you look at the file in an hex editor, you will find many 0x00 in it (this is also the reason why this file is so compressibly); also, there seems to be an endianness swap on the ac3 data, but I actually don't know the specification of ac3 in wav). The 11:42 reported by VLC is also wrong: The real length is 3:24.768. This seems to be a bug in ffmpeg (or a limitation of ac3 in wav) and should be reported there. LAVFilters will inherit the fix for it (if it gets fixed).

**Comment by cehoyos** [comment]
I suspect the sample was created incorrectly and has an actual length of 3:42 when played with a CD player and a hardware decoder while the intended length (and the length when decoded with FFmpeg) is probably 3:24. If the intended duration is really 3:42, FFmpeg could be patched to support this but given that 44100 Hz are not supported by Dolby Digital, this would be surprising. How long do the other formats for this sample play (and which sample rate do they show for ffmpeg -i)?

When I play the sample with aplay on my hardware decoder, I can choose the duration by providing different sample rates: The file plays without distortion no matter the length, so the issue would not be easily noticed.

**Comment by cehoyos** [comment]
I suspect the sample was created incorrectly and has an actual length of 3:42 when played with a CD player and a hardware decoder while the intended length (and the length when decoded with FFmpeg) is probably 3:24. If the intended duration is really 3:42, why wouldn't the ac3 core signal this via a sample rate of 44100? How long do the other formats for this sample play (and which sample rate do they show for ffmpeg -i)?

When I play the sample with aplay on my hardware decoder, I can choose the duration by providing different sample rates: The file plays without distortion no matter the length, so the issue would not be easily noticed.

Or to say it differently: For Dolby Digital, FFmpeg does not trust the container sample rate but the signaled sample rate.

**Comment by Nevcairiel** [comment]
I suspect something is indeed disagreeing about the sample rate, which results in a wrong duration. It does stop playing at 3:24 (and doesn't keep playing after reaching the end like reported in the original issue)

If the container or the bitstream signal wrong information, there really isn't anything to be done about that.
