### ISSUE TITLE
Is Windows XP/2003 Server support closed?

### ISSUE THREAD

**Issue by eugeny71** [Nevcairiel/LAVFilters#152]
When I try to configure any ax-filter I see error message concerning InitOnceBeginInitialize entry point in kernel32.dll module under Windows 2003 Server x86 in all developer builds later then 0.70.2.16. Therefore LAVFilters became non-working. Support for pre-Vista systems was closed since build 0.70.2.29, wasn't it?

**Comment by Nevcairiel** [comment]
XP support has been removed in cd936764aa3915c858c824cf48301202bb69126e (0.70.2-18). This is intentional and a long time coming.
