### ISSUE TITLE
LAV Video D3D11 DXVA decoder's problem.

### ISSUE THREAD

**Issue by kyh96403** [Nevcairiel/LAVFilters#153]
1.
PotPlayer can change video renderer when playing.
When using madVR.
First playing is normal.
Second change madVR again, normal.
Third change madVR again, black screen.
That is LAV Video's problem.
I write fixing code.

HRESULT CLAVVideo::BreakConnect(PIN_DIRECTION dir)
{
  DbgLog((LOG_TRACE, 10, L"::BreakConnect"));
  if (dir == PINDIR_INPUT) {
    m_Decoder.Close();

    if (m_pFilterGraph)
      avfilter_graph_free(&m_pFilterGraph);
  }
  else
    m_Decoder.Flush(); // that is needed for release CD3D11MediaSample
  return __super::BreakConnect(dir);
}

2.
LAV Video D3D11 DXVA decoder create D3D11 device except D3D11_CREATE_DEVICE_BGRA_SUPPORT.
D3D11_CREATE_DEVICE_BGRA_SUPPORT is needed for Direct2D...
So please add D3D11_CREATE_DEVICE_BGRA_SUPPORT.

3.
Why don't using IMFDXGIDeviceManager for D3D11 DXVA?

**Comment by Nevcairiel** [comment]
1) Your fix is not correct. But I'll try to find out whats wrong there exactly.
2) Why would Direct2D be needed for video rendering?
3) It doesn't have any advantages.

**Comment by kyh96403** [comment]
1.
Yes...
Thanks^^

2.
That is needed for draw text(DirectWrite) on video...

3.
IMFDXGIDeviceManager is similar method and behavior with IDirect3DDeviceManager9.
So D3D11 and D3D9 DXVA decoder can write similar code.

**Comment by Nevcairiel** [comment]
The issue with reconnects should hopefully also be resolved.
