### ISSUE TITLE
LAV Splitter advanced mode, !f flag selecting "default+forced" subs

### ISSUE THREAD

**Issue by DendeX3** [Nevcairiel/LAVFilters#155]
The LAV Splitter advanced subtitles selection mode does not exclude forced subtitles if they are also set as "default", with !f tag. It's creating a "hole" in the logic to auto select subtitles, for some pretty common uses (select a foreign audio language in priority, with full subs).

Examples:
My goal is to auto select jpn audio with french full subtitles when possible, and french audio with french forced subtitles if there isn't any jpn audio.

-- Video 1 --
> Audio1 : french, default
> Audio2 : japanese
> Subs1 : french, forced, default (fre forced)
> Subs2 : french, not forced, not default (fre full)
> 
> LAV Splitter advanced settings : 
> Audio : jpn fre eng
> Subtitles : fre:fre|f fre:off *:fre|!f

--> LAV Splitter will correctly select Audio2 (jpn), but won't select Subs2 (french full), but Subs1. Cause ***:fre|!f** will select default ones even if they are forced (!f == dnh). 
Note : for Video1 ***:fre|!df** will select Subs2 but will also cause other issues (see Video 2).

-- Video 2 --
> Audio1 : japanese, default
> Audio2 : japanese (director's comments)
> Subs1 : french, not forced, default (fre full)
> Subs2 : french, not forced, not default (fre, director's comments)
> 
> LAV Splitter advanced settings : 
> Audio : jpn fre eng
> Subtitles : fre:fre|f fre:off *:fre|!df

--> LAV Splitter will correctly select Audio1 (jpn), but won't select Subs1 (french full), but Subs2...

The tag !f should really exclude default+forced subtitles to be used efficiently. I hope it will be fixed... LAV splitter would be nearly perfect with this ^^
Thanks in advance.
PS : if I misunderstood something so there is a way to already achieve this, please let me know.

**Comment by DendeX3** [comment]
In case I was not so clear (sry for my english) :
The current **!f** tag means "_default, or normal, or impaired_" when it should be "_default AND not forced, or normal, or impaired_" (as normal and impaired should never be forced).

*Maybe the **!h** flag has the same problem, idk.

**Comment by Nevcairiel** [comment]
Currently the ! modifier just inverts the flags, so as you seem to have figured out yourself, out of the possible "fdhn", using "!f" turns into "dhn", which basically just means any default, normal or hearing impaired track, instead of meaning "not forced" track, so if flags double up, this happens.

I'll think about changing it, as that would probably make more sense.

**Comment by DendeX3** [comment]
That would be perfect, thank you so much Nevcairiel !
Keep up the amazing work !

**Comment by rangerevo8** [comment]
Hi, I'm wondering the same about why !f flag selecting "default+forced" subs and found no way to workaround this. Is this already fixed?

**Comment by reallyuniquename** [comment]
@Nevcairiel has there been any movement on this? 

I'm trying to select `default` subtitles but only if they are not tagged as `forced`.

Is there a workaround like using multiple flags, e.g. `fre|ndh`?

**Comment by Nevcairiel** [comment]
This has been implemented in e037e24e9986d8ccb819dd6cda534cb32c5c8aa3
