### ISSUE TITLE
Sorry but impossible to use the MVC decoder even with installer.exe

### ISSUE THREAD

**Issue by benTSH** [Nevcairiel/LAVFilters#157]
Hi Hendrik,

Firstly thanks for your great job.

I can play mkv SBS or ISO 3d with SSIF in 3D but not with MKV with 3D frame packed I presume : "Stereo High@L4.1 / High@L4.1"

I don't understand where I'm wrong : libmfxsw32/64 are on their folders but in MPC external filters they won't appear in the add filter list even if you browse to load the DLL manualy 

here is where the installation is : C:\Program Files (x86)\LAV Filters  ( I'm on Vista x64 or W10 x64 - same problem on 2 HTPC )

What I've missed ? thanks by advance

**Comment by benTSH** [comment]
finally I found in the formats selection of LAV setting the option : h264mvc 3d so it seems installed but why the mkv does not use it ?

**Comment by Nevcairiel** [comment]
If SSIF Blu-ray files work but MKVs don't, then those MKVs are likely not in a compatible format. Only direct untouched rips from Blu-ray are supported.

And to clarify, 3D decoding has several other requirements, for example it's only supported with madVR.

**Comment by Nevcairiel** [comment]
Also, support is being provided on the Doom9 forums, please only report actual bugs here.
