### ISSUE TITLE
Load Matroska Segments video seek regression on v0.70

### ISSUE THREAD

**Issue by isral** [Nevcairiel/LAVFilters#158]
Seek mkv with ordered chapter break video that downloaded from hi10anime.com
![70](https://user-images.githubusercontent.com/3161234/30536217-2f31470c-9c8f-11e7-9f10-d5d73fda42d3.jpg)
It's not happen on old release (v0.68).
Disabling "Load Matroska Segments from external files" fix it.

How to reproduce (using anime Himouto! Umaru-chan):
1. Download (put in same folder):
* http://bc.vc/38388/http://hi10anime.uni.cx/hi10anime3/yusakatsuragi/[Hi10]_Himouto!_Umaru-chan_[BD_1080p]/(Hi10)_Himouto!_Umaru-chan_-_01_(BD_1080p)_(LNS)_(9860602B).mkv
* http://bc.vc/38388/http://hi10anime.uni.cx/hi10anime3/yusakatsuragi/[Hi10]_Himouto!_Umaru-chan_[BD_1080p]/(Hi10)_Himouto!_Umaru-chan_-_NCED_(BD_1080p)_(LNS)_(C2C50639).mkv
* http://bc.vc/38388/http://hi10anime.uni.cx/hi10anime3/yusakatsuragi/[Hi10]_Himouto!_Umaru-chan_[BD_1080p]/(Hi10)_Himouto!_Umaru-chan_-_NCOP_(BD_1080p)_(LNS)_(BC054BB2).mkv
2. Make sure "Load Matroska Segments from external files" enabled.
3. Open "(Hi10)_Himouto!_Umaru-chan_-_01_(BD_1080p)_(LNS)_(9860602B).mkv"
4. Seek several times inside several chapters.

**Comment by clsid2** [comment]
This is due to this change:
https://github.com/FFmpeg/FFmpeg/commit/840b41b2a643fc8f0617c0370125a19c02c6b586#diff-14fc5c260d4cfca4f7ad78f63be67560

**Comment by Nevcairiel** [comment]
Its related to that change, but can be fixed. Just need to get around to it.
