### ISSUE TITLE
Some vob (mpg/m2p) files not playing properly.

### ISSUE THREAD

**Issue by gaamaaresosa** [Nevcairiel/LAVFilters#159]
Pls. test these vob files with any LAV filters.
panchumittaye.vob file may play faster speed.
Annennamo 2.vob file may not start playing from first frame.

But same files playing properly in Elecard splitter and ffmpeg video decoders.

https://wetransfer.com/downloads/fcd2341750146102cf79680e8cf1d07a20170917034348/c96c376ebe75c5ed705b7ce166fb157d20170917034348/3326a7

Thanks in advance...
gaamaa

**Comment by Aleksoid1978** [comment]
Files don't exists.

**Comment by Nevcairiel** [comment]
Indeed, the file link is dead.

**Comment by gaamaaresosa** [comment]
Here is the new link again.
https://we.tl/lq8srVCwuD

**Comment by Nevcairiel** [comment]
Both of those files have broken timestamps to varying degrees.

**Comment by gaamaaresosa** [comment]
But both files playing fine with Elecard Splitter and ffdshow video decoders.

**Comment by Nevcairiel** [comment]
That doesn't change that the files are broken.

**Comment by gaamaaresosa** [comment]
Even VLC also playing these file smoother.

**Comment by Aleksoid1978** [comment]
Strange - perfect playback with MPC-BE internal filters.

**Comment by gaamaaresosa** [comment]
I just sent you only 2 sample files. 
But I have dozens of such files not playing with LAV filters.

**Comment by Nevcairiel** [comment]
Broken files are broken files however, there is no expectation of proper functioning if its corrupt in some form.

**Comment by gaamaaresosa** [comment]
![image](https://user-images.githubusercontent.com/21296884/31280825-47306c26-aacb-11e7-95ad-3a05e0742bbb.png)

As you said, this graph plays the same file perfect in MPC-BE

**Comment by Nevcairiel** [comment]
Comparisons with other filters are meaningless here. Every software works differently. If a particular software can deal better with your corrupt files, I would recommend to just use it.

**Comment by gaamaaresosa** [comment]
Thanks for your precious time spent on this issue.
