### ISSUE TITLE
Problem with playing AAC audio

### ISSUE THREAD

**Issue by qquiderr** [Nevcairiel/LAVFilters#162]
Hi, can you fix AAC audio? Basic AAC-LC works perfectly, HE-AAC v1 works too, but HE-AAC v2 dont work, i mean this wersion like in dab+ digital radio and etc. Here is link for some file with he-aac v2. Can you fix it?

https://ulozto.net/!KZ3Jr8C8OZP0/he-aac-v2-rar

This aac codec used by dab+ digital radio and some dvb-t2 and dvb-s2 platforms like digi slovakia @1W satellite.

**Comment by Nevcairiel** [comment]
AAC 960/120 should be supported in a future version.

**Comment by qquiderr** [comment]
Thanks! :)

**Comment by Nevcairiel** [comment]
AAC 960 is now supported in the latest nightly from https://files.1f0.de/lavf/nightly/, however SBR is not supported for 960 streams yet, so they'll play as 24kHz instead of 48kHz.

**Comment by qquiderr** [comment]
SBR and PS not working with some previous versions too. But he-aac v2 now working, It can be played Thanks. :)
