### ISSUE TITLE
UHD H.264 fallback to software decoding

### ISSUE THREAD

**Issue by Aleksoid1978** [Nevcairiel/LAVFilters#163]
Sample - https://yadi.sk/i/jHT5E3hd3NSuYo

MPC-BE use DXVA decoding.

**Comment by Nevcairiel** [comment]
The file uses the "baseline" profile, which is not supported in hardware. It may work, or it may not. There is no way to know from only the profile. Only "constrained baseline", "main" or "high" are fully supported in hardware, but not "baseline".
