### ISSUE TITLE
Retry reading HLS stream

### ISSUE THREAD

**Issue by Chocobo1** [Nevcairiel/LAVFilters#166]
I'm playing a radio stream with mpc-hc + LAVFilters.
My problem is the audio sometimes stop itself (paused in mpc-hc), I had to click play manually to continue playing.
At first I thought it's a buffer issue, but tweaking the buffer size didn't help.
Then I tried playing the stream in ffplay and it works (won't stop itself). I found something interesting in log:
```
...
[hls,applehttp @ 00000000004de7c0] Opening '<some url>-8577600.ts' for reading
[tls @ 0000000001cc6160] Creating security context failed (0x8009030f)
[hls,applehttp @ 00000000004de7c0] Failed to open segment of playlist 0
[hls,applehttp @ 00000000004de7c0] Opening '<some url>-8577601.ts' for reading
[hls,applehttp @ 00000000004de7c0] Opening '<some url>-8577602.ts' for reading
...
```
It seems to me ffplay will retry reading the stream on fail, maybe the logic in LAVFilters can be improved as so? 

ps. There is a parameter `max_reload` in ffmpeg: https://ffmpeg.org/ffmpeg-formats.html#hls-1 , not sure that is related to this issue.

**Comment by Nevcairiel** [comment]
Unless you can provide a way to reproduce this, its going to be hard to do anything about that.

**Comment by Nevcairiel** [comment]
Closing for lack of feedback.
