### ISSUE TITLE
E-AC3 doesn't bitstream and is incorrectly detected as AC3

### ISSUE THREAD

**Issue by kathampy** [Nevcairiel/LAVFilters#168]
I'm using MPC-HC with the internal LAV Filters 0.70.2.1-git.

When bitstreaming an E-AC3 Dolby Atmos track from an M2TS, the AVR is silent. The AVR says Dolby D instead of Dolby D+.
In tsMuxer the codec is detected as E-AC3 (DD+) 7.1 channels, but in LAV Filters it's only AC3 640 kb/s 5.1 channels.
Disabling E-AC3 bitstreaming does not fall back to software decoding - it's still bitstreamed as Dolby D.
Disabling AC3 bitstreaming makes it software decode the E-AC3 track (but as AC3 I presume).

The same M2TS file successfully bitstreams as Dolby D+ in PowerDVD.
I have not tested a non-Atmos E-AC3 track in LAV Filters.

**Comment by Nevcairiel** [comment]
E-AC3 on Blu-ray is not supported, and there are no plans on my side to work on it, so FFmpeg would need to get support for it.

The detection as AC3 isn't exactly incorrect, since it contains an AC3 core which is being played, the E-AC3 extension stream is not used.

**Comment by kathampy** [comment]
What's the difference between E-AC3 on Blu-ray and other sources?

**Comment by Nevcairiel** [comment]
E-AC3 on Blu-ray is not a full E-AC3 stream. It uses an ordinary 5.1 AC3 stream and a second E-AC3 extension stream that contains 4 channels which are supposed to replace the back channel from the AC3 5.1, and add two more channel for a 7.1 mix.

This entire setup with the two streams is specific to Blu-rays.

**Comment by kathampy** [comment]
Can AVRs from before Blu-ray's decode such a bitstream?

**Comment by Nevcairiel** [comment]
Probably not, but a Blu-ray player may know that and only send it the base AC3 block - which is the entire point of this setup, to be able to have backwards compat. Unfortunately it makes it a big headache.

**Comment by kathampy** [comment]
https://en.wikipedia.org/wiki/Talk%3ADolby_Digital_Plus#HDMI_EDID_Short_Audio_Descriptor_Byte_3
Maybe that unknown byte in the EDID tells the player if the AVR supports the Blu-ray version of E-AC3.

**Comment by kathampy** [comment]
Why doesn't the core AC3 bitstream successfully? The AVR says Dolby D but is silent.

**Comment by cehoyos** [comment]
Is there a sample for this unsupported audio stream?

**Comment by ValZapod** [comment]
@kathampy Is it now supported bu ffmpeg? This commit: https://github.com/FFmpeg/FFmpeg/commit/3e9d676192fc6ef719a904f8a2d114efec03d7c1
