### ISSUE TITLE
calling SetSyncSource with a value of null does't seem to make rendering go any faster with hardware acceleration

### ISSUE THREAD

**Issue by UffeHammer** [Nevcairiel/LAVFilters#172]
Hello

When calling SetSyncSource with a value of null does't seem to make rendering go any faster with hardware acceleration enabled, normally my program can scan a videoclip very fast when SyncSource in directshow is set to null, however with LAV filters and hardware acceleration enabled the rendering is almost at normal playback speed. Any idea what might be causing this problem?

Cheers
uffe

**Comment by Nevcairiel** [comment]
LAV does not control the rendering speed, it only feeds data to the renderers - which take over this task. LAV doesn't even interact with the SyncSource.

However, maybe hardware decoding just isn't much faster then realtime on your hardware?

**Comment by UffeHammer** [comment]
Well it is a Nvidia Geforce 1060 card with 6 gb ram so it is good enough for decoding UHD content with 10% cpu usage, with all the decoding happening on the card.
However this 2 hour 720p H.264 video clip takes 34 minutes to scan through, using the hardware decoder, where i'm not processing anything just decoding frames. But it only takes 25 minutes to scan using the software decoder, which should be much slower? It is a 6 year old AMD cpu with 3 cores (one of them failed and had to be disabled).

**Comment by Nevcairiel** [comment]
With old CPUs like that, it is likely that its slow because of the cost of copying the data back to system memory. In any case, LAV is not limited by anything but the actual performance of the system.
