### ISSUE TITLE
Multiple LAVFilters Instances in Taskbar

### ISSUE THREAD

**Issue by MikeLinder** [Nevcairiel/LAVFilters#174]
Using LAVFilters with Potplayer, I discover two LAVFilters Decoder icons remain active in Windows 10 Taskbar after Potplayer is closed. On reopening Potplayer, I see a third instance. 

I've uninstalled and reinstalled LAVFilters 0.70.2 yet the phenomenon remains the same, and two LAVFilters instances now start by themselves on Windows launch.

Each of theses instances has its own settings. Changing one does not change the others. Obviously, something is wrong. Which of these instance is active? How can I fix this issue?

**Comment by Nevcairiel** [comment]
Its certainly possible that some other application is using LAV in the background for something, I can't really tell you what that would be.

**Comment by MikeLinder** [comment]
I can’t imagine, either. No background AV programs are launched at Windows startup, and keeping an external USB mixer powered off at launch makes no difference. This began with an earlier LAVFilters installation, but stopped after upgrading to 0.70.2. Then a day or two later, the behavior returned. It’s a mystery.

**Comment by clsid2** [comment]
You can use Process Explorer to find the application that is using it.
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

I have seen several non-obvious programs use it. For example Steam and Explorer (when connecting phone).

**Comment by Nevcairiel** [comment]
clsid's suggestion should work. There isn't really anything LAV can do about that, if something is using it, then it shows up.
