### ISSUE TITLE
Add support for AVS2

### ISSUE THREAD

**Issue by 6hzzz** [Nevcairiel/LAVFilters#175]
[FFmpeg-devel] [PATCH] Add decoding support for the second generation IEEE 1857 video coding standard(AVS2) using uavs2d library(git clones https://github.com/nelvtpkusz/uavs2d.git uavs2d). Support AVS2 in mpegts, flv and mp4 format.
https://ffmpeg.org/pipermail/ffmpeg-devel/2016-November/202446.html

uavs2d is a free decode library for the 2nd generation IEEE 1857 video coding standard
https://github.com/Codersadis/uavs2d

**Comment by Nevcairiel** [comment]
This should make it into FFmpeg upstream first.

**Comment by 6hzzz** [comment]
> 
> 
> This should make it into FFmpeg upstream first.

November 6th, 2018, FFmpeg 4.1 "al-Khwarizmi"
* AVS2 video decoder via libdavs2

**Comment by 6hzzz** [comment]
CCTV4K.HLG.AVS2.AC3.CB.08-27.ts      757.7 MB
https://mega.nz/#!Lp8EASaI
