### ISSUE TITLE
LAV Video decoder forcibly defaulting to DXVA2-CBPB

### ISSUE THREAD

**Issue by ArcAngelRyse** [Nevcairiel/LAVFilters#178]
Hello, 

I'm reporting a bug as stated in the title for some odd reason whenever I open up mp4 files for some odd reason it defaults to DXVA2 (Copy-back) when it's suppose to be set to 'none'. I'm constantly finding myself return to the settings to change it back or videos freeze up and just stop playing requiring me to force quit the application.

![capture](https://user-images.githubusercontent.com/34932364/34430389-95c32d6c-ec32-11e7-9c4b-b7aa73576f52.PNG)

I haven't tested other formats, I would like to note. 

Hopefully a fix would show itself, 

thank you.

**Comment by Nevcairiel** [comment]
This is not something LAV does. The only explanation would be that your player is overriding the options.

**Comment by clsid2** [comment]
Correct. MPC-HC stores the settings in a different location if you use LAV as an internal filter.

You can access the settings of the active instance through:
MPC-HC menu > Play > Filters

**Comment by ArcAngelRyse** [comment]
It wasnt doing this before but it doesnt matter since i had to reinstall win10 broken os was corrupt.

Signed,
Jirou
________________________________
