### ISSUE TITLE
D3D device Created by Unity app,How to use same device?

### ISSUE THREAD

**Issue by TopPlay** [Nevcairiel/LAVFilters#179]
hello:
I uses lav Video decoder on dx11 or dx9 device,but device created by main Application,and my player plugin uses this device create Texture and render it;can you throught this interface:ID3D11DecoderConfiguration pass device to decoder?

`
if (pD3D11DecoderConfiguration)
  {
    hr = pD3D11DecoderConfiguration->ActivateD3D11Decoding(pDeviceContext->device,pDeviceContext->device_context, pDeviceContext->lock_ctx, 0);
    SafeRelease(&pD3D11DecoderConfiguration);
    m_bReadBackFallback = FAILED(hr);
  }
`

so i  do not have to copy Texture buffer to another device's texture!

**Comment by Nevcairiel** [comment]
LAV Video will always create the device. You can use that device to pass it to a rendering engine and use it that way, but you cannot give LAV a device to use.
