### ISSUE TITLE
LAV-Decoder improvements

### ISSUE THREAD

**Issue by FrankMarcus** [Nevcairiel/LAVFilters#180]
Here are three issues concering the LAV-decoder:
1. The registry-setting seems to be user-dependent. Using the LAV-decoder with non-standard settings inside a service or inside a ISAPI-module is quite hard. Is there a chance to change this into a hardware-dependent registry settings? Or, for example, a new hardware-dependent registry-key decides between these two options. Or an alternative configuration file inside the application path.

2. The Mainconcept-Decoder has a setting to ignore frames with errors (e.g. RTP paket lost), they call it "Error concealment -> Don't show frames with errors". This is really great when the video stream has lots of damaged frames. Instead of displaying blurry frames they skip it. It would be great when the LAV-decoder will do it too!

3. When using the GPU (DXVA, CUDA) to decode multiple video streams there's no chance to check if the GPU-load or -memory is already at it's limit and the decoding fails. Is there a possibility to switch automatically to CPU-decoding when the GPU is not more available?

**Comment by Nevcairiel** [comment]
1) You can specify settings in HKLM manually, which will be used when no user-specific settings are present. Applications don't have write access to HKLM by default, so LAV can't automatically store system-wide settings.

If you use LAV through code and want to configure it, I would recommend looking into runtime configuration instead.

2) Not all decoder backends propagate the information if a frame is broken, or partially broken, so such a task is not easy. Even if it would, how much breakage can be considered watchable? With complex codecs like H264 a missing reference frame could result in very minor glitching, or it could result in the entire frame going bad - its really hard to tell from the outside which of those is the case.

So currently, there are no plans to do this.

3) I don't know the capabilities of the hardware either. It could be capable of processing dozens of streams or only a few, I don't know that. So not really something I can influence.

**Comment by FrankMarcus** [comment]
Thanks for your quick reply.

Using HKLM is a solution. Does it means that when i delete all user settings before application start , HKLM settings will be read instead? 

Concerning the broken frames there's a problem. Windows 10 seems to be buggy when usings overlays/dxva2. Former versions are displaying the actual broken frame but with version 10 we see an older frame from memory. Sometimes this frame is older than one hour. We use LAV together with live streams from CCTV cameras. A frame drop in the case of a broken frame may prevent from this. As i read in former issues (e.g. latency) you limit LAV's usage together with file playback applications and there's no focus on live streaming. As i know LAV is more and more used inside TV-streaming and other live streaming applications. Inside a live stream a broken frame is the reality and the user should be not see it.

Concerning point 3: Just LAV knows if there are enough (dxva) ressources during the initialization/connection process. When we open several 4k streams over an unknown, system dependend limit, the application is blocked or crashes without any chance to avoid this.

**Comment by Nevcairiel** [comment]
Yes, HKLM is used when no other settings are found.

I can't comment on your problems with seeing old frames, thats definitely not LAVs fault. If a frame is broken, then LAV will still output a frame, it may just be corrupted - ie. be partially black or grey, or have motion artifacts (ie. from a missing reference frame). Showing an hours old frame is definitely not something LAV can do.

LAV also doesn't know how many DXVA resources exist or are still available. Multiple instances don't talk to each other, and the hardware doesn't tell me when its close to failing. When the resources run out, thats just that.
