### ISSUE TITLE
Regression MPEG-4 decoding in 0.70.2

### ISSUE THREAD

**Issue by JoelHarhellier** [Nevcairiel/LAVFilters#181]
I have a MPEG-4 Stream (flagged as XVID) which decodes correctly in 0.69 and fails in 0.70.2. In the latter, nothing is output from the decoder. Attached is a short AVI and a directShow graph which shows the issue.
The file can be read by VLC, WMP and LAV 0.69 but not with 0.70.2.
[mpeg-4.zip](https://github.com/Nevcairiel/LAVFilters/files/1685925/mpeg-4.zip)

**Comment by Nevcairiel** [comment]
This appears to be a regression in FFmpeg, please report this there (see https://ffmpeg.org/bugreports.html)

**Comment by JoelHarhellier** [comment]
A ticket has been submitted to ffmpeg. The regression appeared between 3.3.1 and 3.3.2
https://trac.ffmpeg.org/ticket/7005

**Comment by JoelHarhellier** [comment]
The issue has been fixed. See ticket https://trac.ffmpeg.org/ticket/7005#comment:3

**Comment by Nevcairiel** [comment]
I saw, will pick the fix into LAVs copy of ffmpeg for the next release.
