### ISSUE TITLE
video skips first 5 seconds or so

### ISSUE THREAD

**Issue by sdsucks** [Nevcairiel/LAVFilters#184]
MPC-HC+LAVVIDEO(DXVA2/D3D11)+MADVR+youtube VP9 files

video skips first 5 seconds and displays a frame for 5 seconds which is located after 5 seconds from the start while audio is being played fine from the start.
this is a little bit hard to describe.
I hope you understand.
you will see what I mean once it is reproduced.

LAVVIDEO 0.71 is ok
DXVA2CopyBack mode is ok
Software decoder mode is ok
Renderers other than MADVR(evr/evr cp) are ok
Using MPCVideoDec.ax as external decoder is ok
MPC-BE+LAVVIDEO(DXVA2/D3D11)+MADVR has the same problem

nvidia driver is 388.71
it happens also with 390.77 and 391.01
it happens with almost all youtube vp9 files that I have

**Comment by clsid2** [comment]
Latest MPC-HC contains LAV 0.71:
https://forum.doom9.org/showthread.php?t=175209

**Comment by sdsucks** [comment]
I know that
0.71 is ok
I'm talking about  0.71.0.10

**Comment by clsid2** [comment]
Upload a sample file to http://www.datafilehost.com

**Comment by sdsucks** [comment]
ok, here it is
https://www.datafilehost.com/d/568bdb4c

**Comment by clsid2** [comment]
I can confirm the problem happens with DXVA2 Native. The 'freeze' with Madvr is approx 3.5 seconds here. With EVR-CP I get a black screen at the start for same duration.

Subsequent plays (play > stop > play) don't have a problem.

**Comment by Nevcairiel** [comment]
This should be fixed.
