### ISSUE TITLE
Cuvid hardware acceleration (32bit version)

### ISSUE THREAD

**Issue by leonardonencioni6** [Nevcairiel/LAVFilters#185]
Cuvid hardware acceleration doesn’t work on HEVC videos and with Nedi

**Comment by leonardonencioni6** [comment]
*Cuvid hardware acceleration(of the 32bit version of the filter)doesn’t work on HEVC videos and with madvr’s NNEDI3 scaling algorithms (in MPC-HC).

**Comment by Hrxn** [comment]
?

AFAIK, NNEDI3 has been removed from madVR..

**Comment by Nevcairiel** [comment]
CUDA and OpenCL can conflict on 32-bit, there is nothing that can be done about that. That said, NNEDI3 has also been removed from madVR, so there is no chance of it using OpenCL anymore anyway.

**Comment by leonardonencioni6** [comment]
Ok thanks,I was using an older version of madvr,but i didn’t know about that conflict.
Excuse my ignorance.
