### ISSUE TITLE
for too long mpc hc with aac file

### ISSUE THREAD

**Issue by lukjan32** [Nevcairiel/LAVFilters#186]
I am using the mpc hc 1.7.15 program, I have given the aac file for the rehearsal, and there is such a thing, it's about time:
![1](https://user-images.githubusercontent.com/17565773/36894448-a4de9862-1e0b-11e8-9879-2cce48035bc1.jpg)

**Comment by Nevcairiel** [comment]
If a MKV file shows a wrong duration, then the file is probably invalid.

**Comment by lukjan32** [comment]
good, another aac file, the same. in mpc be, it is good.

**Comment by Nevcairiel** [comment]
This is not an "aac file", clearly your file is named ".mkv"

**Comment by lukjan32** [comment]
what should I do?

**Comment by clsid2** [comment]
He is using an .aac as audio dub.

Should be reported here:
http://trac.ffmpeg.org/report
They require the .aac file, so upload it to http://www.datafilehost.com

**Comment by Nevcairiel** [comment]
Duration of raw audio files cannot be determined accurately, just don't use such files.
If MPC-HC modifies the playback duration of the video because of a secondary audio file, then thats a bug in the player.

**Comment by lukjan32** [comment]
@clsid2 I do not have an account there

@Nevcairiel then you need to improve mpc hc.

**Comment by clsid2** [comment]
Then create an account.

**Comment by lukjan32** [comment]
Yet mpc hc, has lav, not ffmpeg.

**Comment by clsid2** [comment]
LAV uses FFmpeg

**Comment by lukjan32** [comment]
good
