### ISSUE TITLE
D3D11 not working on Windows 10

### ISSUE THREAD

**Issue by zdzdz** [Nevcairiel/LAVFilters#188]
I have Windows 10 nVidia GT 430.
LAV Video, audio, splitter + MADVR + MPC-HC
DXVA2 and CUVID are working, but when I choose D3D11 I see messsage:
D3D11 requires Windows 8 or newer and is not supported on this OS.
Windows 10 is newer. What's going on?

![alt text](https://i.imgur.com/bg25OKL.png)
![alt text](https://i.imgur.com/VLyDlIP.png)
![alt text](https://i.imgur.com/sNj5OKS.png)

**Comment by Nevcairiel** [comment]
Make sure you're not running your player in compatibility mode or anything like that, as that can cause Windows to claim to be Windows 7. LAV asks Windows which version it is, and I have to trust that value.

**Comment by zdzdz** [comment]
Wow I found what's the problem. All of my videos I download with uTorrent 2.2.1 and play them directly from there. It appears uTorrent was set to compability mode with Windows Vista. After disabling it everything works fine. Thanks a lot.
