### ISSUE TITLE
Question: Is there any way or any planing on Windows Dolby Atmos support

### ISSUE THREAD

**Issue by cdytoby** [Nevcairiel/LAVFilters#189]
Windows 10 has been supported the Dolby Atmos natively, and there is a "Dolby Atmos for Headphone" feature. Is that possible that the filter deliver the Atmos soundtrack directly to windows and let windows to handle it?

Is that possible current? or is it on roadmap?

**Comment by Nevcairiel** [comment]
This is not something LAV would ever control, its an audio decoder, talking to Windows is done by the renderer.
