### ISSUE TITLE
Some mp4 file are roated 90°

### ISSUE THREAD

**Issue by wj985712588** [Nevcairiel/LAVFilters#190]
some mp4 file are roated 90° when i play it by player

**Comment by wj985712588** [comment]
the video format is .mp4 and Vertically shot on an Android phone

**Comment by Nevcairiel** [comment]
You need a renderer that supports rotation, like madVR, or MPC-BE's EVR-CP.

**Comment by wj985712588** [comment]
when i play the same video with ffmpeg in  cmd(ffplay ****.mp4),it performs normally.
