### ISSUE TITLE
Problem with DXVA2 hardware decoding HEVC 5K Videos

### ISSUE THREAD

**Issue by Vislike** [Nevcairiel/LAVFilters#192]
Hi, i am having a issue that it would be nice to get your input on.

When trying to play a 5K HEVC Video with DXVA2 hardware decoding it fails and switches back to software that makes the framerate tank. This makes it so video players that use DirectShow gets really bad fps.

But the same video works both if using mpc-hc with dxva2 and lav filters with nvidia cuvid instead of dxva2, i think mpc-hc has some internal rendering magic, that maybe you know more than me about. But as i want to use other DirectShow player instead of mpc-hc, it would be really nice to get dxva2 working with lav filters.

Edit:
Some more info, lower then 5K HEVC works fine with dxva2, e.g. 4K. 4K AVC content also works fine, don't have any 5k AVC content, but i may be able to try to re-encode the 5K with x264 myself if that would be any help if i can check if that works or not with dxva2.

I have created 3 screenshots with my settings and what mpc-hc displays.
Frist screenshot is when playing the video with dxva2 and it displays no hardware acceleration.
Second is same video with cuvid instead, and it works fine.
Third is same video in mpc-hc with dxva2, and there it works fine.

![screen01](https://user-images.githubusercontent.com/37211685/37428198-c284c70a-27cb-11e8-80f4-7bb322b4f281.png)
![screen02](https://user-images.githubusercontent.com/37211685/37428204-c5fc9cc8-27cb-11e8-9a2c-e961bfd7e006.png)
![screen03](https://user-images.githubusercontent.com/37211685/37428210-c7f6505a-27cb-11e8-8da1-e7f1e4806e16.png)

**Comment by Nevcairiel** [comment]
LAV asks the hardware what it supports, if this fails for a given resolution, software decoding is used.

**Comment by Vislike** [comment]
Is there any advanced options someway to try to force play it using dxva2? I wonder how mpc-hc does it because it seam to work there.

**Comment by Nevcairiel** [comment]
Maybe thats not the reason DXVA2 fails. DXVA2-Native requires a renderer which is compatible to it, maybe whatever other DirectShow player you use does not set this up properly.

**Comment by Vislike** [comment]
Ok, well i now very little about that. Don't know if it matters but i get the same result with dxva2(copy-back) and D3D11 also.

If i use the program GraphStudioNext it gives me this information, and i won't get hardware acceleration in that program either:
![screen04](https://user-images.githubusercontent.com/37211685/37429537-ed279fb0-27cf-11e8-9e3c-8cb6e4db78fd.png)

**Comment by Nevcairiel** [comment]
The generic "Video Renderer" does not support DXVA2.

**Comment by Vislike** [comment]
I am not saying that you are wrong, but if i open a 4K HEVC or AVC video in the above program i get the same generic video renderer and it plays fine with hardware acceleration dxva2(native).

**Comment by Vislike** [comment]
But now i manged to get even more confused. If I set lav filters to use dxva2(copy-back) then GraphStudioNext manged to play the 5K video with hardware acceleration but not with dxva2(native). And if i try windows media player it won't use hardware acceleration for neither of those two settings.

Well i guess that support your renderer theory, maybe i have to contact the video player developer.
