### ISSUE TITLE
LAV Video Decoder Chroma Interlaced artefacts when converting YUV 4:2:0 to 4:2:2 

### ISSUE THREAD

**Issue by TonyMay71** [Nevcairiel/LAVFilters#193]
Hi,

I am using the LAV Source Splitter with the LAV Video decoder and a renderer that supports the v210 YUV format (DirectShow filter for an AJA SDI output card). When this filter graph decodes an H.264  4:2:0 interlaced source, interlace artefacts can be seen in the 4:2:2 output chroma channel. I have seen this issue a reasonable amount in various video products, and it results from failing to account for the interlaced nature of the video when scaling the 4:2:0 chroma channels to 4:2:2. I have not gone through the code, but if the LAV Video Decoder is a wrapper around ffmpeg, then the following option needs to be used when scaling interlaced content in this way:
-vf scale=interl=1
The above is the command line option I would use; I am not sure how this option is set when calling ffmpeg via a library API. More information on this filter option can be found on the ffmpeg filters documentation page:
https://ffmpeg.org/ffmpeg-filters.html#toc-scale-1

Regards,

Tony

**Comment by Nevcairiel** [comment]
LAV Video is first and foremost a decoder, its designed around native output, and as such the chroma conversion functions are usually quite slow and only of basic quality. Interlaced scaling is not supported, and not planned.

If you need  interlaced scaling, you're better off using an actual video processing framework.

LAV is not a wrapper around ffmpeg, it uses certain parts of the ffmpeg API, but quite differently then the ffmpeg commandline utility.

**Comment by TonyMay71** [comment]
Thanks for your quick response. The combination of LAV Filters and DirectShow provides quite a convenient video processing framework.

Are you able to recommend other video processing frameworks that you think may be better suited to interlaced processing?

Incidentally, the Microsoft DTV-DVD decoder also incorrectly scales interlaced YUV 4:2:0 to 4:2:2, but there is less chance of me repairing that.
