### ISSUE TITLE
Lav decoder hangs while playing movies having  DD+ audio ( EAC3)

### ISSUE THREAD

**Issue by quartzdoll** [Nevcairiel/LAVFilters#194]
windows 10 x64, AMD 2400g cpu with Vega Graphics and Realtek 8 channel audio.

using Lav decoder 0.71 build 16 on pot player 64 bit 1.7.8557 

splitter, video and audio decoder all are set to Lav only.

movies having Dolby Digital Plus or DD+ Audio ( EAC3 ) hangs randomly. video freezes and audio continue to play. when i select inbuilt ffmpeg audio decoder in potplayer , movie playing correctly.

**Comment by Nevcairiel** [comment]
If audio keeps playing but video hangs, what makes you think the audio is even related?

**Comment by Nevcairiel** [comment]
Closed due to lack of feedback, samples or any technical information. Please re-open if you can supply any information.
