### ISSUE TITLE
DirectShowSource and LAVFilters

### ISSUE THREAD

**Issue by anoosi** [Nevcairiel/LAVFilters#195]
hi,
simply, how to make DirectShowSource connect direct to lavfilters without doing register lav?
like put lavfilters dll in the same dir of DirectShowSource.dll, jsut like portable.
thanks

**Comment by micha137** [comment]
What about https://stackoverflow.com/questions/11191996/using-a-directshow-filter-without-registering-it-via-a-private-cocreateinstance ?

**Comment by Nevcairiel** [comment]
This is up to DirectShowSource to do, not something LAV Filters controls.

**Comment by anoosi** [comment]
@Nevcairiel thanks for reply.
i just noob to build DSS ...
i used DSS2mod before, but i need DSS load lav without reg because DSS2mod has some issues and admin system permissions don't allow me reg or install DSS
anyway, thanks to make the mater clear to me
