### ISSUE TITLE
LAV decoding HEVC 10bit not using KabyLake HW decoder

### ISSUE THREAD

**Issue by XKCorp** [Nevcairiel/LAVFilters#196]
Hello,

I have an issue when viewing "The World in HDR 4K 10bit 60fps" demo:
http://4kmedia.org/the-world-in-hdr-uhd-4k-demo/

Using the lastest LAV nightly build and Intel drivers, with HD graphics 610 and 630 iGPU.
Checked with DXVAChecker, HEVC 10bit decoding is available up to 8K.

The LAV Video decoder configured to DXVA2 or D3D11 fallback to software decoding when playing this video in MPC-HC (external LAV filters selected, madVR renderer).

Of course the CPU is not fast enough for software decoding so the video playback is very choppy.

Thanks for your help.

**Comment by Nevcairiel** [comment]
I have a HD graphics 620 in my Ultrabook from the same generation, and it decodes the sample in hardware just fine.

So its probably something on your end, try changing drivers, or if your laptop is Optimus, then try messing with those settings.

**Comment by XKCorp** [comment]
I have resolved this issue by installing the LAV Filters 0.71 final release.

Bad news, I can watch the sample with the EVR renderer (washed colors), but the HD630 seems too slow to handle the playback with madVR for HDR->SDR conversion.

**Comment by Nevcairiel** [comment]
madVR is quite flexible and a lot of performance can be gained by toning it down, not sure if its enough for a mobile GPU though.

But good to hear decoding works.

**Comment by papmech** [comment]
I have this exact same issue on my intel i7-8550u where the video card is the Intel UHD620. On the latest release version of LAV Filters, I cannot engage the GPU on any setting (DXVA2 or D3D11, native or copy back). However, when I revert to 0.71 release, then it works. Something broke along the way?

**Comment by seankovacs** [comment]
I'm seeing this issue as well? I can't figure out for the life of me why HEVCm10 content isn't decoding using QS?

**Comment by Nevcairiel** [comment]
QuickSync is drepecated and does not support HEVC at all. Use DXVA2 or D3D11.
