### ISSUE TITLE
using IStreamSourceControl interface

### ISSUE THREAD

**Issue by TopPlay** [Nevcairiel/LAVFilters#197]
i uses my Custom sourcefiter +lavSplitter,when read HLS stream and seek to new position,sourcefilter supports IStreamSourceControl -> SeekStream to seek  , Sourcefilter get new HLS position ,but LavSplitter use it's self queue momery first!

**Comment by Nevcairiel** [comment]
Try with the next nightly (in ~4 hours), I found one case where old data may have been buffered.

**Comment by Nevcairiel** [comment]
Yes, as mentioned in the documentation of the interface, after using SeekStream it'll start reading from position 0, which is much simpler because I don't know the position one is supposed to be at after a time seek, and it lets the source filter handle all of that.

**Comment by TopPlay** [comment]
in my code ,when seek end, i put position=size,down filter get buffer will not use it's self position info;

**Comment by Nevcairiel** [comment]
I have no idea what your issue is. The interface is documented to work in a certain way. If you support seeking through SeekStream, then after the seek LAV will read from position 0. Thats just how it is defined. If you need any other logic, you can easily offset the position in the source filter itself.

**Comment by TopPlay** [comment]
i just tell you my source HLS seek logic, it work well now.
thank you !
 by the way,when i use lav function ILAVAudioSettings->SetRuntimeConfig(true); debug window output some info:can not find some window handle ,i guess it can not find setting window?

**Comment by Nevcairiel** [comment]
If the normal settings have the tray icon enabled, it may try to delete that. It can be safely ignored.
