### ISSUE TITLE
avcodec-lav-57.dll alert box

### ISSUE THREAD

**Issue by judgedreddd** [Nevcairiel/LAVFilters#198]
as is in the picture: **Unhandled exception occured[0xC0000005@0x000007FEDAD5F810] at avcodec-lav-57.dll Additional exception information has been stored locally and this application will be terminated.**

https://i.imgur.com/VjJfSRN.jpg?1

this ocurs when I try to play two different video segments linked via mkvmerge. first video is AVC and second video segment is HEVC

**Comment by Nevcairiel** [comment]
Error messages like that are not helpful. That said, segments have to have the same codec.

**Comment by Nevcairiel** [comment]
Closing due to lack of information, also as noted above mixing codecs in mkv segments is not supported.
