### ISSUE TITLE
Sub Can not show

### ISSUE THREAD

**Issue by TopPlay** [Nevcairiel/LAVFilters#200]
I uses LavSplitter+VSFilter+Custom EVR Render,Play blue-ray Movie; it's include some subtitles,but Always can not show;
Setting  screenshot:
[http://cloud.topplay.com.cn/Files/Software/1.png](url)
[http://cloud.topplay.com.cn/Files/Software/2.png](url)
[http://cloud.topplay.com.cn/Files/Software/3.png](url)

you can copy address to new IE to open;

**Comment by Nevcairiel** [comment]
Disable the option "Deliver only Forced Subtitles" in LAV Splitter, it should reall never be used outside of testing.

**Comment by TopPlay** [comment]
thanks..!

**Comment by TopPlay** [comment]
it 's working,thanks !
