### ISSUE TITLE
在使用8代HD630并且搭配独立显卡的情况，无法启用LAV核显HEVC硬解

### ISSUE THREAD

**Issue by 1265578519** [Nevcairiel/LAVFilters#201]
![1](https://user-images.githubusercontent.com/6442439/39153484-da205236-477d-11e8-8d40-bb371a0e6cd3.jpg)

**Comment by Nevcairiel** [comment]
I don't speak Asian, so I can only guess - but HEVC is not available in QuickSync. Use DXVA2 or D3D11 instead.
