### ISSUE TITLE
Sound quality of older LAV audio filters 0.66.0.33 or 0.65  is much better than newer.

### ISSUE THREAD

**Issue by alessast** [Nevcairiel/LAVFilters#206]
I noticed on a high end audiophile system that the sound quality of older LAV audio filters was much better especially the 0.66.0.33-git from Satsuki Decoder Pack 5.2.0 but also the LAV audio 0.65 filter. When i change LAv audio filters to 0.67 or even newer 0.70 or 0.71 audio filters the sound is less clear and less dynamic, and less melodious ..

I wonder why newer LAV audio filter seem to be of lesser quality?

I am using Reclock 1.8.4 upsampling to 32 bit IEEE float at 192khz wave out, there may have a connection..

**Comment by Nevcairiel** [comment]
LAV Filters outputs audio bit-perfect from decoding, if you let it, and the decoding has not changed. There is no quality difference between any versions.
