### ISSUE TITLE
TrueHD bitstreaming drop-outs on high bitrate Atmos streams

### ISSUE THREAD

**Issue by Nevcairiel** [Nevcairiel/LAVFilters#208]
TrueHD bitstreaming can cause audio to cut out briefly on high bitrate Atmos streams (as found on UHD Blu-rays).

This is caused by the individual frames being too large for the current logic that builds the MAT frame for HDMI transmission. Unfortunately the exact workings of the MAT format are unknown.

A few examples where this happens:

> - “Pirates of the Caribbean - Dead Men Tell No Tales” - Max Bit rate is 11.9 Mb/s : eg drops out a couple of times between 17:45 and 19:00 minutes into the movie
> - “Guardians of the Galaxy Vol II” - Max Bit rate is 11.3 Mb/s: eg drops out at 1:09:24 where TaserFace gets killed is one example.
> - “Maze Runner: The Death Cure” - Max Bit rate is 12.1 Mb/s: eg Right at the beginning of the Main Title when the 20th Century clip is running.  Drops outs so frequent that playback can actually stall.

**Comment by Nevcairiel** [comment]
I've been gathering information on this for a while and found some basic information how to do this properly, so here is a test version:

https://files.1f0.de/tmp/LAVFilters-0.71.0-39-truehd.exe

This version entirely replaces the TrueHD bitstreaming module, so any testing is appreciated, no matter if its on discs that previously had issues, or any other TrueHD audio, to ensure it still works.

**Comment by jmone1** [comment]
Testing on a Yami RX-A3060 connected to a JVC DLA-X7500 (this combination used to drop sound for about 7 sec on the high bitrate parts - eg the decoder on the Yami would turn off).  Title Playback looks good.  No drop outs and it seems pretty robust with seeks etc.  BD Menu Playback is not working as well.  Seeks will causes a series of drop outs on all disks and with the problematic ones (such as Maze Runner), you get a black screen while audio plays, and if you pause the video frame is from the end of the film.  If I turn off bitsteaming (eg decoding) then playback is fine.

**Comment by Nevcairiel** [comment]
I cannot reproduce any changes in behavior at all other then the drop outs being gone on my end. Seeking is a bit hiccup-y in bitstreaming mode, but thats not new, and probably unavoidable because it has quite some different requirements.

But perhaps I fixed something in further cleanup work? So here is the latest version:
https://files.1f0.de/tmp/LAVFilters-0.71.0-40-truehd.exe

**Comment by jmone1** [comment]
Thanks - no difference at my end.  Testing on Maze Runner:
- Title Mode: Plays fine with ATMOS Bitstreaming
- BD Menu: Select a non ATMOS Audio Track (eg one of the other audio tracks in the Menu) Plays Fine
- BD Menu: Turn Off Bitstreaming and ATMOS track plays fine
- BD Menu: ATMOS Bitstreaming = Audio starts playing from the start but no video (empty queues) and the seek position in the player (MC) is right at the very end.  AVR Decoder is dropping in and out.  Eventually playback stalls.  Trying to seek & play/pause does not help

Do you want MC Logs?

**Comment by Nevcairiel** [comment]
This doesn't seem to be a very likely result of my TrueHD changes.

**Comment by jmone1** [comment]
Could just be a coincidence on this disc as I get the same odd ATMOS Bitstreaming behaviour with LAV Nightly, LAV MC Version as well but with the drop outs.  I'll take the discussion on this disc back to the MC Forum.

**Comment by Nevcairiel** [comment]
There will be a new nightly available in about an hour from now with the TrueHD changes and some further improvements. Not that I'm all that confident to know whats going on, but it might be interesting to test.

**Comment by jmone1** [comment]
Thanks - I'll give that a go are re-test a bunch of discs.  The ATMOS drop-outs on file based playback looks fixed from my testing.  (fyi - I've posted a log over at JRiver on the issues when playing from the Menu)

**Comment by jmone1** [comment]
Latest nightly looks good on file based playback

**Comment by ManniGH** [comment]
Hi Nev, happy to confirm that the issue is solved here, at least testing with GoftheG Vol 2.
nVidia 1080Ti HDMI bitstream to Denon X8500H.
I tested before upgrading and I did have the issue with former versions, so thanks for fixing.
