### ISSUE TITLE
Lav VideoDec DX11 mode invalid in Win7?

### ISSUE THREAD

**Issue by TopPlay** [Nevcairiel/LAVFilters#209]
Kodi Player can Decode Media Use DX11 Under Win7 , why Lav Video  Recognition  Decoder DX11 invalid？

**Comment by Nevcairiel** [comment]
D3D11 video decoding is not available on Windows 7.

**Comment by TopPlay** [comment]
you can run Kodi Player Decoder 4K Media, and launch DXVAChecker tools to View decoder info ..
I'm sure it uses dx11 decoder..
