### ISSUE TITLE
how lav Video Decoder processing 3D Video and Render With Custom  EVR Render?

### ISSUE THREAD

**Issue by TopPlay** [Nevcairiel/LAVFilters#210]
I write custom EVR render, i find decode 3D Media in Media Foundation Frame, each Video Sample output 2 buffer(left and right), But I haven't encountered such a 3D Media yet； lav video decoder output two buffer in a Sample in Directshow mode ?Or custom evr render handle it myself?

**Comment by Nevcairiel** [comment]
3D is handled using an extension of IMediaSample, see here:
https://raw.githubusercontent.com/Nevcairiel/LAVFilters/master/developer_info/IMediaSample3D.h

The renderer would need to be able to understand this sample format, and most importantly provide a sample allocator that actually creates them.

I do not know if you can do this with EVR.

**Comment by TopPlay** [comment]
thanks ,i find lav video decoder user this interface in <CLAVVideo::DeliverToRenderer(LAVFrame *pFrame)>
how i query this interface from lav videoDec?

**Comment by TopPlay** [comment]
look like this function :HRESULT CLAVVideo::Receive(IMediaSample *pIn);
I need to write a custom transform filter to set every sample two buffer?

**Comment by TopPlay** [comment]
EVR Process Sample Output use this struct:
`  _MFT_OUTPUT_DATA_BUFFER = record
    dwStreamID:   DWORD;           // [in] which stream is this for
    pSample:      IMFSample;       // [in/out] can be NULL
    dwStatus:     DWORD;           // [out] MFT_OUTPUT_DATA_BUFFER_FLAGS (INCOMPLETE, etc.)
    pEvents:      IMFCollection;   // [out] Can be NULL.  Zero or more events produced by the MFT
  end;
`
can i process  pSample as IMediaSample3D  and set it's 3DEnable in EVR's IMFTransform.ProcessOutput function ?

**Comment by TopPlay** [comment]
I find sample allocator code in win7 sdk, i be curious how  lav distinguish 3D format media,i want app control 3D output by ueser self.

**Comment by TopPlay** [comment]
i need implement IMediaSample3D and CbaseAllocator,too much work to do!
…o…
