### ISSUE TITLE
Decoding error when playing H264 UHD file

### ISSUE THREAD

**Issue by jiavictor** [Nevcairiel/LAVFilters#211]
I downloaded Life_of_ Pi_draft_Ultra-HD_HDR.mp4 for testing with UHD playback and re-encoded with x264 core:152 r2851 ba24899 (CRF 20).
When plays the file with LAV Video Decoder 0.71.0.48-git, the image is broken (see attached image, I compressed, for the original is larger than 10MB).
I tried copy-back, native, D3D11 and CUVID, all not work.
When uses ffplay 4.0, the image is normal.
![life_of_ pi_draft_ultra-hd_hdr_264](https://user-images.githubusercontent.com/6112653/40950140-0e539b84-68a4-11e8-8182-b77c13163be1.jpg)

**Comment by jiavictor** [comment]
https://share.weiyun.com/524KhHm

**Comment by Nevcairiel** [comment]
Works fine if you use software decoding in LAV, and the same corruption can be seen with FFmpeg 4.0 if you use hardware decoding.

The bitrate is probably too high, H264 Level 6.0 is not usually supported by hardware.

**Comment by jiavictor** [comment]
Hello @Nevcairiel 
Yes, you are right.
Thanks very much.

**Comment by Syst3mSh0ck** [comment]
Tool is available to change the IDC to any profile here: http://www.avsforum.com/forum/attachment.php?attachmentid=18112&d=1338355472

You could try changing it to L5.1/4.1 then retest with DXVA2-Native/CB acceleration enabled. You haven't said what GPU nor the Driver version that you are using.

**Comment by Nevcairiel** [comment]
The profile/level isn't even communicated to the driver, so changing the value would have absolutely no impact. However it is quite likely that the bitrate exceeds the capability of the hardware, since its not designed to decode 6.0 streams.

**Comment by Syst3mSh0ck** [comment]
I see. Thanks for the clarification!

**Comment by jiavictor** [comment]
It may not with the profile, maybe it's about RefFrames.
I re-encoded with 4 ref-frames and all goes well.

My display adapter is NVidia Geforce GTX 680 and the driver version is 397.93.

The info of the re-encoded file is:

General
Complete name               : C:\Life_of_ Pi_draft_Ultra-HD_HDR_x264.mp4
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom (isom/avc1)
File size                   : 254 MiB
Duration                    : 54 s 420 ms
Overall bit rate mode       : Variable
Overall bit rate            : 39.1 Mb/s
Encoded date                : UTC 2018-06-11 01:43:25
Tagged date                 : UTC 2018-06-11 01:43:25
Writing application         : StaxRip 1.7.0.6

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L5.1
Format settings             : CABAC / 4 Ref Frames
Format settings, CABAC      : Yes
Format settings, ReFrames   : 4 frames
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 54 s 375 ms
Bit rate                    : 38.8 Mb/s
Maximum bit rate            : 64.2 Mb/s
Width                       : 3 840 pixels
Height                      : 2 160 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 24.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.195
Stream size                 : 251 MiB (99%)
Writing library             : x264 core 152 r2851 ba24899
Encoding settings           : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=20.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Encoded date                : UTC 2018-06-11 01:43:25
Tagged date                 : UTC 2018-06-11 01:43:27
Color range                 : Limited
Color primaries             : BT.2020
Transfer characteristics    : PQ
Matrix coefficients         : BT.2020 non-constant

Audio
ID                          : 2
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format profile              : LC
Codec ID                    : mp4a-40-2
Duration                    : 54 s 420 ms
Bit rate mode               : Variable
Bit rate                    : 384 kb/s
Maximum bit rate            : 392 kb/s
Channel(s)                  : 2 channels
Channel(s)_Original         : 6 channels
Channel positions           : Front: L C R, Side: L R, LFE
Sampling rate               : 48.0 kHz
Frame rate                  : 46.875 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 2.47 MiB (1%)
Language                    : Chinese
Encoded date                : UTC 2018-06-11 01:36:35
Tagged date                 : UTC 2018-06-11 01:43:27

**Comment by Nevcairiel** [comment]
Your re-encoded file also happens to be Level 5.1. The DPB for Level 5.1 has room for only 4 reference frames at 4K resolution, so using any more frames would already push it to level 6, and then exceed the hardwares capability to manage.

**Comment by jiavictor** [comment]
So you mean
capacity = min(floor(MaxDpbMbs / (PicWidthInMbs * FrameHeightInMbs)), 16)

min(floor(184320/(240*136)), 16) = 5

I see, thanks.
