### ISSUE TITLE
Decoding error on a 1080p 4:4:4 h264 file

### ISSUE THREAD

**Issue by Dayllann** [Nevcairiel/LAVFilters#212]
On 0.70.2 this file plays fine, but 0.71.0 or nightlys are give me this:

![snapshot](https://user-images.githubusercontent.com/8220569/41186266-0a6bca28-6b6a-11e8-8150-fb672bb235c2.png)

This problem occurs on both a Windows10 1803 with an AMD R7 250 and a Windows10 1709 with an AMD HD 7450.

Link for a 10s sample: https://mega.nz/#!HBtCgRrA!cAzbLYzj_OoeOAjcySrGmO7UI9s8uhY2FV1xFbTUaIw

**Comment by Nevcairiel** [comment]
Your file is basically invalid. It was encoded with an old buggy version of x264 but the metadata that would allow identifying the file as such a buggy encode is missing, and as such it cannot be automatically handled.

**Comment by Dayllann** [comment]
Thanks.
But.. why the old lav (0.70.2) reproduce this file, and not the new ones (0.71.0+)?

**Comment by lvqcl** [comment]
0.70.2 is old and contains old unpatched version of h264 decoder. It can decode old incorrect videos, but cannot decode new videos that were created after the bug was fixed.

**Comment by Dayllann** [comment]
Oh... I see. Thank you very much for the info :)
