### ISSUE TITLE
H.265 decoder support for Intel Quick Sync (QSV)

### ISSUE THREAD

**Issue by shamarin** [Nevcairiel/LAVFilters#213]
Make a support for H.265 HEVC video decoding via Intel Quick Sync QSV. Now only H.264 AVC is supported. FFMPEG library support H.265 for QSV.

**Comment by Nevcairiel** [comment]
The Intel QuickSync decoder that LAV uses is an external component, which has ceased to be further developed, and I do not plan to put any work into that myself.

You can use DXVA2 or D3D11 on Intel GPUs just fine though, there really is no reason for QSV to even exist anylonger.

**Comment by Nevcairiel** [comment]
There is absolutely no reason to prefer QSV over DXVA2 or D3D11 for decoding only.

**Comment by shamarin** [comment]
Why? QSV is fully decoded on hardware.

**Comment by shamarin** [comment]
Advanced features are for example Deinterlacing.

**Comment by shamarin** [comment]
In CUVID and QSV we can select advanced HW adaptive deinterlacing. With others we can't.

**Comment by 1265578519** [comment]
QSV可以在独立显卡中使用HD630来起到省电效果
