### ISSUE TITLE
LAV Splitter crashes on certain AVI files

### ISSUE THREAD

**Issue by tunahfish** [Nevcairiel/LAVFilters#216]
I'm using LAV Splitter (v 0.72 x86) and have a huge amount of different AVI files, some of which cause a crash.
Playback of those files are fine, ie a graph like this:
FileSource -> LAV Splitter -> LAV Decoder -> Video renderer

But I can make LAV splitter crash by doing this:
FileSource -> LAV Splitter -> AVI Mux -> Null renderer
The reason I want to do this is to crop some of those files and it works for some of them.
I have narrowed it down to it being caused by the audio stream, so I have created a small AVI file with only audio in it that will reproduce the crash.
Should be fine to reproduce with a graph like this:
"crash.avi" -> LAV Splitter -> AVI Mux -> Null renderer.

[crash.zip](https://github.com/Nevcairiel/LAVFilters/files/2185563/crash.zip)

Stack trace:
>	ntdll.dll!77e8e8cd()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for ntdll.dll]	
 	ntdll.dll!77e8f801()	Unknown
 	qcap.dll!5b3f5505()	Unknown
 	avutil-lav-56.dll!59c76b3c()	Unknown
 	avcodec-lav-58.dll!59dcf141()	Unknown
 	LAVSplitter.ax!Packet::`scalar deleting destructor'(unsigned int)	C++
 	LAVSplitter.ax!CMediaPacketSample::Release() Line 76	C++
 	LAVSplitter.ax!CLAVOutputPin::DeliverPacket(Packet * pPacket=0x007f8b38) Line 545	C++
 	LAVSplitter.ax!CLAVOutputPin::ThreadProc() Line 415	C++
 	LAVSplitter.ax!CAMThread::InitialThreadProc(void * pv=0x007f3bc8) Line 124	C++
 	LAVSplitter.ax!thread_start<unsigned int (__stdcall*)(void *)>(void * const parameter=0x007f43a8) Line 115	C++

**Comment by Nevcairiel** [comment]
Should hopefully be fixed.

**Comment by tunahfish** [comment]
Can no longer reproduce the crash, thank you!
