### ISSUE TITLE
AC3/DTS Encoding Needed

### ISSUE THREAD

**Issue by george-emerald** [Nevcairiel/LAVFilters#218]
LAV Audio Decoder needs an on-the-fly encoding option. My AV receiver can only play surround sound if an untouched AC3 or DTS stream is bitstreamed to it. When I have files with 5.1 FLAC there is no way for me to send all the channels to the receiver. Ffdshow had that option and I tried using it, but for some reason LAV filters are forced even if I disable the Internal Filters on my K-Lite custom MPC-HC. Please tell me how I can use ffdshow on such cases, because I don't wanna use it all the time since it's outdated. Though, it would be even better if you could add AC3 encoding to LAV.

**Comment by george-emerald** [comment]
Thanks for the quick response. I didn't know I could use LAV audio and ffdshow audio processor so I blocked LAV audio and used ffdshow decoder and processor. If I do what you suggest it won't up mix anything to 5.1, right? I want stereo and mono to be sent as-is, I just need to encode 5.1 flac.

**Comment by clsid2** [comment]
LAV Audio decoder is better than ffdshow decoder.

ffdshow audio processor will convert everything that isn't already being bitstreamed into 5.1 AC3. But don't worry, for stereo/mono input it will just add silent channels.
If you enable the expand option, then it will copy the input to the back channels as well.

**Comment by george-emerald** [comment]
One last question. My receiver also supports 6.1 with one surround back channel. Whenever I happened to find a video in that format LAV would bitstream it as 6.1. Will that still happen or will ffdshow audio processor down mix it to 5.1?

**Comment by george-emerald** [comment]
Also, really sorry for pestering you, but my setup is a laptop connected to a TV via hdmi which is connected to my receiver via optical, my receiver is 9.1 setup but the highest I've been able to send it is 6.1. Can I somehow get my PC to stream 7.1 or does the optical connection not have enough bandwidth to support it?

**Comment by Nevcairiel** [comment]
That would require HDMI to carry the audio. You would have to go Laptop -> Receiver -> TV all over HDMI to carry HD audio with 7.1 channels, but I'm guessing your receiver doesn't have HDMI, because that would be the only reason one might set it up like this?

**Comment by george-emerald** [comment]
Yeah, it's pretty old. What's the best the optical connection can do? 6.1?

**Comment by george-emerald** [comment]
I'm guessing True HD and DTS-HD are also not gonna transfer over optical?

**Comment by Nevcairiel** [comment]
You can transfer anything that fits into normal AC3 or normal DTS. For DTS that can be 6.1 with core extensions. HD formats like DTS-HD or TrueHD do not work over optical.

**Comment by george-emerald** [comment]
Okay. So, if my video file has a 6.1 DTS will it bitstream untouched or will it be converted to 5.1 AC3 by ffdshow? I have enabled the passthrough in ffdshow and LAV Audio, but the mixer on ffdshow is set on 5.1.

**Comment by clsid2** [comment]
DTS will bitstream untouched.

**Comment by george-emerald** [comment]
Thanks for the support guys.

**Comment by zrav** [comment]
IMO this feature is still needed in LAV, simply because ffdshow is dead.

**Comment by Tamaniha** [comment]
I agree, this feature is really needed.
I tried @clsid2's setup and it works fine on files that have a single audio stream but doesn't when I have more than one stream.

e.g., when I open a file that has two audio streams:
1: 7.1 truehd dolby atoms stream 
2: 5.1 ac3 dd stream

It opens the 7.1 stream by default and downmix it to 5.1 then bitstreams it. However, when I change to the 5.1 stream it outputs the sound from my PC speakers and I can't change the output to the audio system (clicking on it in mpc audio renderer does nothing).
The only way to bitstream the 5.1 stream in such files is to disable ffdshow audio processor and reopen the file.
