### ISSUE TITLE
Wrong aspect ratio

### ISSUE THREAD

**Issue by zappepappe** [Nevcairiel/LAVFilters#219]
Since 71.0 WMV videos are are displayed with SAR when using the Microsoft WMV9 DMO decoder. If I disable the Microsoft decoder or downgrade to 70.2 it's displayed with DAR, as it should be.

**Comment by Nevcairiel** [comment]
Without a sample video, there is nothing I can do. As far as I can tell, everything works fine.

**Comment by Nevcairiel** [comment]
Should be resolved. The problem is that WMV/VC-1 can have different ways to signal the aspect ratio, either in the stream itself or on a container level. And the container level variant was getting lost here.
