### ISSUE TITLE
Win10 (Intel GPU) + EVR renderer doesn't display full range video correctly

### ISSUE THREAD

**Issue by fireattack** [Nevcairiel/LAVFilters#221]
I recently noticed a bug that only happens on my Win 10 laptop.

The setup is **LAV+EVR**. I tested on **MPC-HC** (both internal LAV and external), **MPC-BE** and **PotPlayer**, same result. 

I can reproduce the bug with either software decoding or D311 HW decoding (below are using software decoding).

The problem is when playing full range video, the color is clipped.

A sample file is here: https://my.mixtape.moe/tfoonl.mp4

There is no bug on my Win7 computer with nVidia GPU (not sure if GPU is relevant).

The OSD info from PotPlayer is attached below for your investigation 
(I use PotPlayer just to show a better OSD. It can be reproduced in any players I mentioned above. Also, I've turned off all Pot's built-in filters/processing.)

Win 7 + nV (working):

![win7](https://user-images.githubusercontent.com/4130991/44287552-dcb95c80-a232-11e8-8d67-fe5fed5ff5da.png)

Win 10 + Intel (incorrect):

![win10](https://user-images.githubusercontent.com/4130991/44287673-3e79c680-a233-11e8-8f36-d82409d90d04.png)

As you can see, the major difference is in first one, the "mixer" part is still NV12, but in second part it was in "XRGB". I assume for some reason the conversion between YUV and RGB happened at different place which causes the problem.

I can work around this problem by forcing LAV to only output RGB.

**Comment by Nevcairiel** [comment]
This is most likely caused by the driver or the renderer itself. LAV is providing the same information in either case, which is correct, as it wouldn't work otherwise on any system.
