### ISSUE TITLE
This got installed to my System32 folder, I dont want it anymore but theres no uninstaller I can see

### ISSUE THREAD

**Issue by RogShotz** [Nevcairiel/LAVFilters#222]

**Comment by richardpl** [comment]
Only option is to reinstall Windows.

**Comment by Nevcairiel** [comment]
If you installed it manually using the official installer, there will be an uninstaller. If another application installed it as part of its setup, then that application would need to take care about cleaning up after itself.

**Comment by clsid2** [comment]
You can disable/unregister the filters with Codec Tweak Tool. After that you can just remove the files.
