### ISSUE TITLE
LAV splitter crush inside double Avisynth 

### ISSUE THREAD

**Issue by DeniR** [Nevcairiel/LAVFilters#223]
LAV splitter crush inside double Avisynth (any version).
avisynth-stage1-with-MTS.avs
DirectShowSource("Video.MTS")
deshaker(VirtualDub) - Ok

avisynth-stage2-with-MTS.avs
DirectShowSource("avisynth-stage1-with-MTS.avs") - crush

Work ok with Haali, not LAV splitter.

VirtualDub crash report -- build 35491 (release-AMD64)
--------------------------------------

Disassembly:
7ffdb82ca5e0: 2301            and    eax, [rcx]
7ffdb82ca5e2: 0000            add    [rax], al
7ffdb82ca5e4: 4d8b5008        mov    r10, [r8+08h]
7ffdb82ca5e8: 4d85d2          test   edx, r10
7ffdb82ca5eb: 7527            jnz    1b82ca614
7ffdb82ca5ed: 33d2            xor    edx, edx
7ffdb82ca5ef: 418b4010        mov    eax, [r8+10h]
7ffdb82ca5f3: f7f3            div    eax, ebx
7ffdb82ca5f5: ffc2            inc    edx
7ffdb82ca5f7: 4863c2          movsxd rax, edx
7ffdb82ca5fa: 3bd3            cmp    edx, ebx
7ffdb82ca5fc: 7316            jnc    1b82ca614
7ffdb82ca5fe: 488d04c7        lea    rax, [rdi+rax*8]
7ffdb82ca602: 4c8b10          mov    r10, [rax]
7ffdb82ca605: 4d85d2          test   edx, r10
7ffdb82ca608: 750a            jnz    1b82ca614
7ffdb82ca60a: ffc2            inc    edx
7ffdb82ca60c: 4883c008        add    rax, 08h
7ffdb82ca610: 3bd3            cmp    edx, ebx
7ffdb82ca612: 72ee            jc     1b82ca602
7ffdb82ca614: 418b00          mov    eax, [r8]
7ffdb82ca617: 99              cdq    
7ffdb82ca618: 41f7fc          idiv   eax, esp
7ffdb82ca61b: 4c63e2          movsxd r12, edx
7ffdb82ca61e: 4863f0          movsxd rsi, eax
7ffdb82ca621: 488bce          mov    rcx, esi
7ffdb82ca624: 490fafce        imul   ecx, esi
7ffdb82ca628: 4903cd          add    ecx, ebp
7ffdb82ca62b: 468b0ca1        mov    r9d, [rcx]
7ffdb82ca62f: 418bc9          mov    ecx, ecx
7ffdb82ca632: c1e910          shr    ecx, 10h
7ffdb82ca635: 440fb6c1        movzx  eax, cl
7ffdb82ca639: 418bc9          mov    ecx, ecx
7ffdb82ca63c: c1e908          shr    ecx, 08h
7ffdb82ca63f: 440fb6d9        movzx  ebx, cl
7ffdb82ca643: 410fb6c1        movzx  eax, cl
7ffdb82ca647: 4d85ff          test   edi, r15
7ffdb82ca64a: 0f84a6000000    jz     1b82ca6f6
7ffdb82ca650: 66410f6ed8      movd   xmm3, eax
7ffdb82ca655: f30f            db     0fh
7ffdb82ca657: e6db            out    0dbh, al
7ffdb82ca659: 66410f6ee3      movd   xmm4, ebx
7ffdb82ca65e: f30f            db     0fh
7ffdb82ca660: e6e4            out    0e4h, al
7ffdb82ca662: 660f6ee8        movd   xmm5, eax
7ffdb82ca666: f30f            db     0fh
7ffdb82ca668: e6ed            out    0edh, al
7ffdb82ca66a: 660f            db     0fh
7ffdb82ca66c: 1f              db     1fh
7ffdb82ca66d: 440000          add    [rax], al
7ffdb82ca670: 49634f10        movsxd rcx, [r15+10h]
7ffdb82ca674: 4d8b3f          mov    r15, [r15]
7ffdb82ca677: 488b05c2382000  mov    rax, [1b84cdf40]
7ffdb82ca67e: 488b14c8        mov    rdx, [rax+rcx*8]      <-- FAULT
7ffdb82ca682: 8b4a04          mov    ecx, [rdx+04h]
7ffdb82ca685: 2bce            sub    ecx, esi
7ffdb82ca687: 8b02            mov    eax, [rdx]
7ffdb82ca689: 412bc4          sub    eax, esp
7ffdb82ca68c: 0fafc0          imul   eax, eax
7ffdb82ca68f: 0fafc9          imul   ecx, ecx
7ffdb82ca692: 03c1            add    eax, ecx
7ffdb82ca694: 660f6ec0        movd   xmm0, eax
7ffdb82ca698: f30f            db     0fh
7ffdb82ca69a: e6c0            out    0c0h, al
7ffdb82ca69c: 660f28d6        movapd xmm2, xmm6
7ffdb82ca6a0: f20f5ed0        divsd  xmm2, xmm0
7ffdb82ca6a4: 660f28c3        movapd xmm0, xmm3
7ffdb82ca6a8: f20f59c2        mulsd  xmm0, xmm2
7ffdb82ca6ac: f20f584208      addsd  xmm0, [rdx+08h]
7ffdb82ca6b1: f20f114208      movsd  [rdx+08h], xmm0
7ffdb82ca6b6: 660f28cc        movapd xmm1, xmm4
7ffdb82ca6ba: f20f59ca        mulsd  xmm1, xmm2
7ffdb82ca6be: f20f584a10      addsd  xmm1, [rdx+10h]
7ffdb82ca6c3: f20f114a10      movsd  [rdx+10h], xmm1
7ffdb82ca6c8: 660f28c5        movapd xmm0, xmm5
7ffdb82ca6cc: f20f59c2        mulsd  xmm0, xmm2
7ffdb82ca6d0: f20f584218      addsd  xmm0, [rdx+18h]
7ffdb82ca6d5: f20f114218      movsd  [rdx+18h], xmm0
7ffdb82ca6da: f20f585220      addsd  xmm2, [rdx+20h]
7ffdb82ca6df: f200000000      add    [rax], al

Built on Althena on Sun Oct 27 16:00:02 2013 using compiler version 1400

Windows 6.3 (Windows 7 x64 build 9600) []
Memory status: virtual free 134212006M/134217728M, commit limit 56240M, physical total 49072M

RAX =         34add040
RBX =              3f1
RCX =                0
RDX =              77d
RSI =               c6
RDI =         250bd010
RBP =         3edbf450
R8  =               24
R9  =           241a1a
R10 =         4747de50
R11 =               1a
R12 =              77d
R13 =         342e5040
R14 =             1e00
R15 =         24fdfa60
RSP =         3edbf350
RIP =     7ffdb82ca67e
EFLAGS = 00010206

Crash reason: Access Violation

Crash context:
An out-of-bounds memory access (access violation) occurred in module 'Veedub64'...

...reading address 0000000034ADD040.

Pointer dumps:

RAX   34add040: 6e06b199 be9f2db7 a0f91a8e 3b141b67 9e95bcf5 fb0fb38f c5865ef4 7a43dd38
RDI   250bd010: 4748c340 00000000 47489770 00000000 4748b040 00000000 47486ba0 00000000
RSP   3edbf350: 000003f1 00000000 00000001 00000000 00000010 00006aaa 0000000a 00000000
      3edbf370: 00000004 00000000 00000000 00000000 b8485f10 00007ffd 250bd010 00000000
      3edbf390: 000003f1 00000000 00000e24 00000000 00000000 00000000 4748bb20 00000000
      3edbf3b0: 0000000a 00000000 00000050 00000000 2318fde0 00000000 25008b40 00000000
RBP   3edbf450: 00000000 00000000 ffffffff ffffffff 020007d0 00000000 00000000 00000000
      3edbf470: 001fa400 001fa400 b843c870 00007ffd 00000000 00000000 ffffffff ffffffff
      3edbf490: ffffffff 00000000 00000000 00000000 00000000 00000000 020007d0 00000000
      3edbf4b0: b8485ef0 00007ffd 00000000 00000000 00000000 00000000 00000000 00000000
R10   4747de50: 000012d4 00000000 00000000 00000000 04d41c4c 00000000 00001424 00000000
R13   342e5040: 000a0605 000a0605 000a0605 000a0605 00090504 000a0605 000a0605 000a0404
R15   24fdfa60: 24fdfa78 00000000 24fdfa48 00000000 00000001 00000000 24fdfa90 00000000

Thread call stack:
7ffdb82ca67e: Deshaker_64!VirtualdubFilterModuleDeinit [7ffdb82b0000+2db0+178ce]
7ffdb82bcc0d: Deshaker_64!VirtualdubFilterModuleDeinit [7ffdb82b0000+2db0+9e5d]
7ffdb82cd898: Deshaker_64!VirtualdubFilterModuleDeinit [7ffdb82b0000+2db0+1aae8]
7ffdb82b86b6: Deshaker_64!VirtualdubFilterModuleDeinit [7ffdb82b0000+2db0+5906]
7ffdfbea2669: VDubFilter!00002669
7ffdfe9e81e3: MSVCP140!??0?$basic_ios@DU?$char_traits@D@std@@@std@@QEAA@PEAV?$basic_streambuf@DU?$char_traits@D@std@@@1@@Z [7ffdfe9a0000+47c00+5e3]
7ffdfbea2a4e: VDubFilter!00002a4e
7ffdc5e337a8: AviSynth!000637a8
7ffdc5e585ed: AviSynth!avs_vsprintf [7ffdc5dd0000+87e50+79d]
7ffdc5e57023: AviSynth!avs_get_frame [7ffdc5dd0000+86ff0+33]
7ffdc3cb5cf8: avformat-lav-57!avio_close_dyn_buf [7ffdc3c80000+350e0+c18]
7ffdc3e55353: avutil-lav-55!av_murmur3_final [7ffdc3e30000+24700+c53]
7ffdc3cb5f46: avformat-lav-57!avio_close_dyn_buf [7ffdc3c80000+350e0+e66]
7ffdc3e55353: avutil-lav-55!av_murmur3_final [7ffdc3e30000+24700+c53]
7ffdc3d7c6ea: avformat-lav-57!avformat_open_input [7ffdc3c80000+fbee0+80a]
7ffdc3e55353: avutil-lav-55!av_murmur3_final [7ffdc3e30000+24700+c53]
7ffdc3e55353: avutil-lav-55!av_murmur3_final [7ffdc3e30000+24700+c53]
7ffe0b3caa25: ntdll!LdrGetDllHandleEx [7ffe0b390000+3a7c0+265]
7ffe0b3eaa12: ntdll!RtlInitializeCriticalSectionEx [7ffe0b390000+5a4f0+522]
7ffdc3e55353: avutil-lav-55!av_murmur3_final [7ffdc3e30000+24700+c53]
7ffe0b3a32be: ntdll!RtlAllocateHeap [7ffe0b390000+124f0+dce]
7ffdc3d7faeb: avformat-lav-57!av_add_index_entry [7ffdc3c80000+ff7d0+31b]
7ffdc3e55353: avutil-lav-55!av_murmur3_final [7ffdc3e30000+24700+c53]
7ffe0b3a265b: ntdll!RtlAllocateHeap [7ffe0b390000+124f0+16b]
7ffdc3d80ae8: avformat-lav-57!av_read_frame [7ffdc3c80000+100830+2b8]
7ffdcb6a5663: LAVSplitter!OpenConfiguration [7ffdcb6a0000+1390+42d3]
7ffdcb6cc99e: LAVSplitter!DllCanUnloadNow [7ffdcb6a0000+1e8f0+e0ae]
7ffdcb6a7048: LAVSplitter!OpenConfiguration [7ffdcb6a0000+1390+5cb8]
7ffdcb6ac8a6: LAVSplitter!OpenConfiguration [7ffdcb6a0000+1390+b516]
7ffdcb6c1fcc: LAVSplitter!DllCanUnloadNow [7ffdcb6a0000+1e8f0+36dc]
7ffdcb6f0035: LAVSplitter!DllCanUnloadNow [7ffdcb6a0000+1e8f0+31745]
7ffe0a4b3034: KERNEL32!BaseThreadInitThunk [7ffe0a4a0000+13020+14]
7ffe0b401431: ntdll!RtlUserThreadStart [7ffe0b390000+71410+21]

-- End of report

**Comment by Nevcairiel** [comment]
The crash is somewhere deep in your Deshaker_64 filter. I cannot help with that.

Note that LAV uses AviSynth directly, while previous implementations used it through VfW, so there is inherent behavior differences, so comparisons to some other filters doesn't make much sense.
