### ISSUE TITLE
4 2 2 H.264 can't see picture added video please fix 

### ISSUE THREAD

**Issue by pop-dahaka** [Nevcairiel/LAVFilters#224]
Hi ,
I record 10 seconds for channel with broken picture its H.264 4:2:2 please fix lav ,
Am using windows 7 64bit 
http://www.mediafire.com/file/of11185yvja3jyc/4_2_2_picture.rar/file

**Comment by pop-dahaka** [comment]
Media info says 

Video
ID                                       : 101 (0x65)
Menu ID                                  : 1 (0x1)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High 4:2:2@L4
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 3 frames
Codec ID                                 : 27
Duration                                 : 860 ms
Bit rate mode                            : Constant
Nominal bit rate                         : 16.4 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:2
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan type, store method                  : Separated fields
Scan order                               : Top Field First
Bits/(Pixel*Frame)                       : 0.317
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

**Comment by pop-dahaka** [comment]
I see lav video settings --> output formats --> 4:2:2 -->
Don't include  YUV  
The video attached Color space : YUV 
Can you please support it ?

**Comment by Nevcairiel** [comment]
The file looks severly corrupted. Sounds to me like your channel does not have enough reception.

**Comment by pop-dahaka** [comment]
Hi ,
Thanks for analyses the file , 
Found the problem related to tevii dvbs2 driver 5183 and 5185 not support high bitrate 84.3 , The driver 5193 partially support high bitrate but a lot of problems with low symbolrate 5300 and 7120 and 7200 .
Am not recommend tevii dvbs2 hard ware . 

The problem not related to lav .

Thank you very much .
