### ISSUE TITLE
Color flags in the presence of container color information

### ISSUE THREAD

**Issue by mkver** [Nevcairiel/LAVFilters#226]
Hello,

there is something odd going on when a container (at least when it is a Matroska container) contains color information of its own: This information doesn't simply precede/masks the relevant information at the bitstream level, but it also masks the other color information contained in the DXVA2_ExtendedFormat structure. 
[Here](https://github.com/Nevcairiel/LAVFilters/files/2347216/Tests.with.Matroska.Color.Information.zip) are some samples:
1. The sample "Test.with.Matroska.Color.Information.mkv" contains chroma location information at the container level. At the bitstream level, it is composed of two parts, the first of which uses BT.709 color matrix, the second uses BT.601 color matrix (via in-band SPS). The dwcontrolflags were 0x00000000 during both parts.
2. The sample "Test.without.Matroska.Color.Information.mkv" is the same sample, but with all color information removed from the container level. During the first half of the file, dwControlFlags is 0x0000a581 (i.e. MPEG2-chroma; limited color range; BT.709 color matrix), which turns to 0x00012581 in the second half (MPEG2-chroma, limited color range; BT.601 color matrix). That's how it should be.
3. The sample "Test.with.Matroska.Color.Information.2.mkv" is again the same sample as 1., but with primaries ITU-R BT.470M specified at the container level, too (in addition to the chroma location). In both parts the dwControlFlags are 0x00c00581 (i.e. both the primaries and the chroma location are right, but the matrix from the bitstream isn't sent).
4. "Test.with.Matroska.Color.Information.3.mkv" is again the same sample, but this time only with ITU-R BT.470M primaries at the container level (no chroma location etc.). The 
dwControlFlags are 0x00c00081 (i.e. only ITU-R BT.470M primaries, no matrix) during both parts.

So besides the masking of bitstream things that actually shouldn't be masked the chroma location is weird because it only masks the things from the bitstream, but isn't set in the dwcontrolflags when alone.

Greetings
mkver

**Comment by Nevcairiel** [comment]
I've changed the logic so that container information will only overwrite bitstream information if the container information is actually set, so that you can have a partial set in the container to overwrite partial information in the bitstream.

This does make it impossible to "unset" bitstream information (ie. return it to "unknown"), but thats probably not a very useful feature to begin with.
