### ISSUE TITLE
With LAV 60 fps HEVC UHD videos stutter but run smothly with ffdshow (that cannot decode It)

### ISSUE THREAD

**Issue by SMH17** [Nevcairiel/LAVFilters#227]
I have tried to change all hardware decoding modes, disabling all deinterlacing features whatever configuration I use I experience high jitter and stuttering.
I have achieved the best result using CUVID rather than DXVA2 on my Nvidia powered configurations but I see this issue on different hardware configurations.

Configurations used for my test:

-> Intel Core i7 3630QM, Nvidia GTX660M (4GB VRAM), 16Gb DDR3 RAM **[ Issue Present with LAV ] [ No issue with ffdshow ]**

-> AMD Ryzen 5 2400G Radeon RX Vega11 APU, 32GB RAM DDR4 **[ Issue Present with LAV ] [ No issue with ffdshow ]**

-> Intel Core i7 8700HQ Nvidia GTX1060 32Gb DDR4 **[ No issue ]**

The first configuration doesn't support HEVC\H265 hardware decoding so clearly have to use the computational resources intensively on software mode, but with ffdshow I can achieve a smooth playback with LAV no way. 
The second configuration has native HEVC\H265 support but cannot reproduce smoothly the video with LAV, and this is even more weird since the hardware is well equipped for the codec used.
Only in latest configuration LAV was able to handle the video smoothly but with pretty high resource usage. Since ffdshow doesn't support H265 decoding, when I use ffdshow instead of LAV my OS switch on a more efficient decoding configuration, so there is something in LAV that doesn't manage optimally such videos. Also note that the lags appears every 2-3 seconds as micropauses while the fps stats are pretty high on average. 
  
**Note that even my smartphone and my Smart TV that have much less computational power than all configurations above are perfectly able to play smoothly the videos used for my test.**

Here a sample file:
http://4kmedia.org/samsung-x-redbull-see-the-unexpected-hdr-uhd-4k-demo/

**Comment by clsid2** [comment]
ffdshow does not support HEVC, so actually another decoder is being used.

For Intel and AMD GPUs you should select DXVA2 NATIVE. That works smoother than Copy-back.

**Comment by SMH17** [comment]
@clsid2 I'm aware ffdshow doesn't support HEVC\H265 as I have already stated in my post.

DXVA2 native works smother than DXVA2 copy back with all configurations tested, but with both DXVA2 modes, on Nvidia system the issue is more accentuated than Cuvid as explained before (but with Cuvid active the CPU and GPU usage is much higher).

Anyway CPU  and GPU usage is pretty low during playback (especially with DXVA2 native) and FPS are very high with these lags that are repeated in a period of 2-3 seconds so the cause of the problem here seems an un-optimal management of the decoding pipeline masked by high enough performance systems rather than "not enough computational power".

**Comment by Nevcairiel** [comment]
Why would you even compare to something that clearly doesn't even support the codec? You are comparing to some unnamed component that takes over. If you want your comparison to be meaningful, you need to know and tell us which component that is.

I've played 4K content on pretty low end systems perfectly smooth with LAV. Its quite possible your configuration is just off. Especially in DXVA2-Native mode there isn't much work left to anyone but the hardware, and the hardware decoders are quite fast.

**Comment by SMH17** [comment]
@Nevcairiel Not all 4k HEVC video are the same. I also play 4k HEVC videos with no problem but some videos have shown this issue. Yes I use also madVR,
I'll check what are exactly the decoder that works fine when LAV is disabled, but regardless this, the point is that if some others decoder used as LAV replacement when I switch off It, can play the video this proofs that LAV has some problem that should be addressed. 
I haven't reported ffdshow to compare It in something that cannot decode, just when I disable LAV I use It and despite It cannot decode HEVC videos, still It manages the audio decoding of the audio track of the video files.

**Comment by Wishbringer** [comment]
Its a real abnormality but very difficult to pin down exactly.
I get it using MPC-HC, madVR and LAVFilters.
Settings doesn't seem to matter much.

**Comment by Nevcairiel** [comment]
If you're experiencing such issues with madVR, then the first thing you should do is check in the madVR OSD if the "decoder queue" is actually running empty. Because if that one is always filled during such glitches, then its not a decoder performance issue.

**Comment by Wishbringer** [comment]
I did try turning off madVR, it had no effect.

**Comment by clsid2** [comment]
MediaInfo (Shift+F10 in MPC-HC) can show details about the video. 10-bit requires more processing power than 8-bit. HDR adds even more overhead.

Try the standard EVR as video renderer in MPC-HC. That is more efficient than EVR-CP, which MPC-HC uses by default. EVR uses DXVA scaling, which uses the lowest amount of resources. On some systems, that is the only way to get smooth playback.

MadVR also offers the option of using DXVA scaling.

**Comment by SMH17** [comment]
Using the sample video linked above:

- If I use LAV  with standard EVR the framerate is stable on 60 FPS with no jitter, but audio goes out of sync (regardless A\V sync setting in LAV audio).

- If I use LAV with EVR-CP the framerate stats changes continuously between 55 and 90 FPS with the issue mentioned above (video looks smooth till micropauses every 2-3 second). 

- If I totally switch off LAV and use MainConcept HEVC decoder, no issue.

- If I use Lentoid HEVC decoder (selected automatically if I switch the selection on Windows merit value) similar problem.


PS 
Do you use default Microsoft VC compiler as explained in the readme?  In my experience most of the times Intel compiler is better in generating binaries that use newer instructions set and could give higher performance (and much higher if you use also the Intel Math Kernel Library included in Parallel Studio).

**Comment by lvqcl** [comment]
Do you use 64-bit player? Or 32-bit one?

**Comment by SMH17** [comment]
64 bit player

**Comment by clsid2** [comment]
That sample play fine here with hardware acceleration enabled (NVIDIA GTX 960). Without it doesn't because my CPU is too slow.

Your 3630QM Intel GPU does not have full acceleration for HEVC. It only has hybrid acceleration, which is much slower. Often not enough to consistently reach 60 fps. For example VLC player has even blacklisted such Intel GPUs so that hardware acceleration is not used for HEVC on such systems.

So it seems like an obvious performance issue based on your symptoms. But it is almost fast enough for smooth playback. The MainConcept decoder performs just a little bit better on your system and for that specific file.

The decoder of LAV is compiled with GCC. Using ICC won't make it faster. Certainly not when using hardware acceleration.

The A\V sync setting in LAV is for dealing with big gaps in timestamps. It can't fix sync issues due to performance issues.

**Comment by SMH17** [comment]
@clsid2 The 3630QM + GTX660M although hasn't hardware h265 decoding has enough computational power to reproduce this video and the same issue happens even on Ryzen 5 2400G + Radeon RX Vega 11 configuration (that fully support H265 hardware decoding) as explained in the first post. Both GPU and CPU are underutilized during the playback with all configurations reported.

**Comment by Nevcairiel** [comment]
The first hardware setup is definitely just plain too slow to fully decode and process 60 fps UHD HEVC. No Hardware decoding, and a mobile CPU, there is just no chance unless a clip is extremely low bitrate. It is possible that other decoders are faster, but making software/CPU decoding faster is something that would have to happen as part of FFmpeg, not LAV.

For the Vega APU, I have absolutely no personal experience using any of those, but I've heard bad stories about its GPU performance.

**Comment by SMH17** [comment]
@Nevcairiel I'm aware this is a complex problem that involves different software components but whatever stories you have heard I can see such problematic videos perfectly played on a Amlogic Android SmartTV box of 40$, on a 4 years old smartphone, and others devices with hardware MUCH less powerful, so something certainly isn't working properly. And since the CPU\GPU usage doesn't reach even the 30% during the playback, It's even more clear that most of computational power isn't the bottleneck and the reason is some bug and\or unoptimal resource usage. (and the very strange jitter behavior shown when you switch from EVR-CP to EVR seems a further confirm that something isn't working properly)

**Comment by Nevcairiel** [comment]
You cannot compare the performance of a fully integrated SoC and a dedicated GPU. Purpose-built hardware that was designed for one specific task is always going to be much faster at it. Its not a matter of computational power, because if you make fixed function hardware to do one task and only one task, then thats something else entirely.

**Comment by SMH17** [comment]
As I have said Ryzen 24000G APU has H265 hardware decoding and although you cannot compare directly different architectures this united to the fact that with MainConcept the video hasn't problem, should give you an hint that something isn't implemented optimally that should not liquidated with "not powerful enough".
