### ISSUE TITLE
Not supporting "Dolby Atoms for Headphones"

### ISSUE THREAD

**Issue by jason1208419** [Nevcairiel/LAVFilters#229]
When playing video with Dolby TrueHD with Dolby Atmos (A_TRUEHD) and "Dolby Atoms for Headphones" is turned on, [Purchased feature in  Dolby Access app of Microsoft Store in Windows 10 PC]
the decoder is not detecting and only using TureHD as input, outputting PCM 7.1.
In a result, "Dolby Atoms for Headphones" only down-mixing a normal surrounded sound, but not using Atmos content.
Hoping LAV can detect "Dolby Atoms for Headphones" is turned on in Windows 10 or let user tick the option of using "Dolby Atoms for Headphones" in Windows 10. Then LAV can pass the Atmos content to "Dolby Atoms for Headphones" correctly.

**Comment by Syst3mSh0ck** [comment]
Dolby Atmos for Headphones on Windows 10 uses Media Foundation Transform (MFT) - Msauddecmft.dll

I understand that it down-mixes the TrueHD 7.1 source to stereo with simulated/artificial 3D positional audio using metadata embedded in the Atmos track. I don't think ffdshow/LAV supports parsing the Atmos metadata, however it can pass it through to a DSP on an AV Receiver over HDMI that can.

Seeing as Dolby charge royalties for their Atmos tech, I can't see it being added to ffdshow any time soon, unless said implementation can be proved to be white room reverse engineered.

**Comment by Nevcairiel** [comment]
LAV just outputs all the data to the audio renderer, including Atmos bitstream information if thats enabled. If anyone would do such processing, it should IMHO be the audio renderer, not the decoder.
