### ISSUE TITLE
the problem with the image on the movies

### ISSUE THREAD

**Issue by lukjan32** [Nevcairiel/LAVFilters#233]
I watch movies in the codec of x265, in every movie there is a blurred picture and it becomes, then it is fine. Is this a LAVFilters error?

**Comment by Hrxn** [comment]
Impossible to say without any samples to do reproduction attempts..

**Comment by lukjan32** [comment]
and the screen can be?

**Comment by clsid2** [comment]
It is just a poor quality video with low bitrate. Depending on encoding settings, there can be huge quality differences between frames.

**Comment by lukjan32** [comment]
ok, thank
