### ISSUE TITLE
Defaulting to a Different English Subtitle Track

### ISSUE THREAD

**Issue by xreic** [Nevcairiel/LAVFilters#234]
As the title states, I want MPC to load a different subtitle track in the same language (English).
For example, I want to default to the third subtitle track in the image below.

![1](https://user-images.githubusercontent.com/32492656/48456184-f2c3b400-e772-11e8-97fe-fbc205002c74.png)

**Comment by clsid2** [comment]
MPC-HC options > Playback > Default Track Preference > Subtitles > 3

This will select third track.

**Comment by xreic** [comment]
Thanks!

**Comment by Nevcairiel** [comment]
I don't think rules to select subtitle tracks by index are particularly useful, since its extremely specific to each file which index a track has - in which case it might be easier for you to just switch the "default" flag to whichever track you want to be the default.
