### ISSUE TITLE
Faulty_clips

### ISSUE THREAD

**Issue by Luke6077** [Nevcairiel/LAVFilters#236]
Hi,

I'm beta testing the Ao no kiseki game on Linux and I've come across a crash issue over some in game movie clips.

On Chapter 4 Day 2 there is 3 movie clips.
On 0.72. I can have the game skip movie 1, play movie 2 but crash at movie 3.
On 0.73 and 0.73.1 It plays movie one but crashes on movie 2.

I've added the files here
https://www48.zippyshare.com/v/CRZbyJgM/file.html

Have a nice day.

**Comment by clsid2** [comment]
Both clips play OK here with 0.73.1 on Windows 7.

**Comment by Luke6077** [comment]
I've already tested it on both Linux and Windows.
I forgot to mention that sorry.

Game works fine on Windows both in and out of the game.
On Linux works perfectly fine out of the game but in game is where the issue is.
As stated above.

**Comment by Nevcairiel** [comment]
LAV is software for Windows. Linux is not supported.
