### ISSUE TITLE
hardware vp9 decode on raven ridge apu not working

### ISSUE THREAD

**Issue by jakky567** [Nevcairiel/LAVFilters#237]
Hardware decoding for vp9 is not working at all on my amd 2700u, despite it supporting fixed-function vp9 decoding via dxva2 and d3d11. Default filters work on mpc-be, and chrome will recognize decoding capabilities. I'm running windows 10 1809 and lav 73.1

**Comment by Nevcairiel** [comment]
There is no specific support for any hardware in LAV. If a driver properly supports DXVA2 VP9, then it would work in LAV.

**Comment by jakky567** [comment]
I know the driver supports DXVA2. It says so in dxva checker. It even matches my nvidia gpu on my desktop with the name and the guid of VP9_VLD_Profile0. I'm willing to send logs as well. Chrome and MPC BE internal filters will use DXVA2, but VLC will not. I just want to know the issue so I can send it to the proper authorities.
