### ISSUE TITLE
How do I get the file buffer progress value?

### ISSUE THREAD

**Issue by hurryboylqs** [Nevcairiel/LAVFilters#238]
I  render a network file(http url) and want to get the download progresss,use the IAMOpenProgress::QueryProgress
can not get it! why?

**Comment by Nevcairiel** [comment]
Typical network buffering status is not available, and won't be. LAV is first and foremost a file-based filter, network related functionality is offered as-is and is not given a priority.

The only available buffer information is given in IBufferInfo

**Comment by clsid2** [comment]
Furthermore, LAV Splitter Source does not cache the (entire) file on disk, unlike Microsoft's "File Source (URL)" filter does.

**Comment by hurryboylqs** [comment]
> Furthermore, LAV Splitter Source does not cache the (entire) file on disk, unlike Microsoft's "File Source (URL)" filter does.

Like flash web players display buffering status, is there no way to get the progress of buffered data in LAV Splitter?
