### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Jonw82** [Nevcairiel/LAVFilters#239]
Apologies if this is in the wrong section, it's the best I've been able to find (so far).

I realise that there are much higher priorities in terms of more technical/core/fundamental matters with compatibility, optimisation and issues like this.. but please consider at some point the option for a graphic audio EQ.  It's very hard to find a directshow EQ in 64bit version.

Without installing other filters like ffdshow or AC3filter.. but I like LAV, it's my preferred decoder for audio and video.  I primarily use LAV with MPC-BE in WASAPI exclusive mode and it sounds great, especially with flac, but this option means having no audio eq'ing options available.  I haven't been able to find any (independant) external 64 bit filters.

I realise there are more important matters and it won't be possible anytime soon,but please consider it for the long term future.  Thanks and keep up the good work.

**Comment by Nevcairiel** [comment]
LAV is and will always remain first and foremost a decoder. Audio processing features like EQ are not planned, and basically out of scope for LAV. Sorry.
