### ISSUE TITLE
HLG support for HEVC

### ISSUE THREAD

**Issue by mplutka** [Nevcairiel/LAVFilters#240]
Since more and more satellite broadcasters are streaming HLG HDR encoded in HEVC, it would be great if LAVFilters would support this and set the necessary codec context parameters. I tried captured streams with a current version of mpv and they are displayed correctly in HLG HDR. Whenever the current version of LAVFilters get involved, only SDR is displayed.

**Comment by Nevcairiel** [comment]
There is no video renderer available that supports HLG, so there is nothing that LAV could do to make it work.

**Comment by mplutka** [comment]
So how does mpv do it then or am I mistaken?

**Comment by Nevcairiel** [comment]
It has its own video renderer. But LAV is only a decoder. You would need a separate DirectShow video renderer for that to work.
