### ISSUE TITLE
Playback of 4K HDR drops frames on Intel HD 620 past version 0.71

### ISSUE THREAD

**Issue by mhendu** [Nevcairiel/LAVFilters#242]
I've tested several versions of LAV filters with MPC-HC and MadVR on my MSI Cubi 2. Versions 0.71 and earlier play 4K HDR content just fine (although too slow to convert HDR via SW, passthrough works OK). However, once I install any version past 0.71 the computer starts dropping frames on playback. Looks like there are differences in the names of several files past that point, so must have been something significant that changed between versions. Also seems that leaving the newer files in the directory causes issues on playback as well, so if I install a newer version, then install version 0.71, I have to delete the newer files to get playback without dropped frames (the installer does not remove other versions of LAV filters). Uninstalling before installing also resolves this problem, of course.

**Comment by Nevcairiel** [comment]
> Also seems that leaving the newer files in the directory causes issues on playback as well, so if I install a newer version, then install version 0.71, I have to delete the newer files to get playback without dropped frames (the installer does not remove other versions of LAV filters). 

That sounds impossible. The files are referenced by name, and the sheer presence of other files will not influence playback.

**Comment by Nevcairiel** [comment]
I've tested 4K HDR playback on very low-end Intel systems, slower then a HD620 in fact, and it seems overall fine here.
