### ISSUE TITLE
Asynchronous video decoders

### ISSUE THREAD

**Issue by ibaCCTS** [Nevcairiel/LAVFilters#247]
Internally, the video decoders seems to use some kind of ring buffer mechanism where a decoded frame is only delivered when another frame is received for decoding. This results in a delay. From issue #112, I know that this delay can be manipulated by changing the number of threads (though, from what I can tell this only works if you don't use a hardware decoder). However, there's still a significant delay in my case. Would it be possible to implement some asynchronous functionality, which delivers the frames as soon as they are decoded?

**Comment by Nevcairiel** [comment]
The threading implementation is part of FFmpeg, and therefor any such work would need to happen there. LAV already does its best to avoid any added latency, and if you use single-threaded decoding, or native hwaccel, there should be none.
