### ISSUE TITLE
HEVC decoding problem

### ISSUE THREAD

**Issue by KillMeImSalty** [Nevcairiel/LAVFilters#248]
Never had an issue before with LAV, this the first time. I'm having a problem playing back a 1080p hevc 10bit file, still pictures look fine only the movement of the picture is corrupted. I'll provide a sample which is copied with ffmpeg which can decode it properly. I'm on version 0.73.1.
Link to sample: https://mega.nz/#!hRkz3SZC!N9I5lsHbXey3qYI2ElZzyzoksmV7gBJzy4U9Gc3-4Lo

**Comment by Nevcairiel** [comment]
The video appears to use too many reference frames. HEVC only allows up to 8 references to be used by any given frame, but this video uses up to 10. The hardware decoders have a strict limit in how many they can support.

If you turn off hardware decoding in LAV, it'll decode it just fine as well, just like FFmpeg. But there is no way to do it in hardware.

**Comment by F6DZP** [comment]
I I want to decode HEVC elementary stream, when video size is 1920x1080, LAV video renderer gives this result, but when video size is 1240x720, when decoding, LAV video renderer says that size is 1240x960.
