### ISSUE TITLE
AC3 Play on Windows 10

### ISSUE THREAD

**Issue by alfix0** [Nevcairiel/LAVFilters#252]
I´m playing files on a PC with stereo environment.

MKV files with AC3 files 2.0 or 5.1 play ok with Windows 10, but AC3 files of DVD don't play fine, it seems that some channels are losing on play, only music not dialogs.

On Windows 7 all's ok.

**Comment by Nevcairiel** [comment]
LAV Audio behaves identically on all OS versions. If a channel is being lost or something, thats typically the audio renderer or audio device being at fault.
