### ISSUE TITLE
LAV Splitter Source do not close file

### ISSUE THREAD

**Issue by roman-minyaylov** [Nevcairiel/LAVFilters#253]
Hi

I have a problem with LAV Splitter Source filter.

After opening a file and rendering filter pins (in code or GraphStudio), there are no ways to close source file except app exit. File will be opened even if filter will be removed from graph, or even if graph will be released.

Steps to reproduce:
1. Open GraphStudio / GraphEdit. Add LAV Splitter Source filter, specify some mp4 file.
2. Render audio / video pins using default rendering, so, any filter can be added to graph.
3. Remove all filters from graph.
4. Try to rename (or remove) source mp4 file. You'll not be able to do that because file still opened somewhere in LAV Splitter Source.
5. Close GraphStudio. Now you can rename / remove source mp4 file.

**Comment by Nevcairiel** [comment]
LAV definitely closes the file when its shut down, this can be easily tested with other DirectShow player applications. It is possible that GraphStudio is not fully closing down LAV until it is closed itself.

**Comment by roman-minyaylov** [comment]
Am I need to do something to release filter except releaing IBaseFilter interface and removing filter from graph?

I can made C++ demo to show an issue.

**Comment by Nevcairiel** [comment]
I can't comment on your code, but as soon as LAV Splitter is actually released, it'll close the file.
Typical reasons for this not working would be that something is still holding a reference somewhere that might not be expected.

**Comment by roman-minyaylov** [comment]
Here is my code.

I'm adding LAV Splitter Source, LAV Video Decoder, VMR-9 renderer, and connecting them.
That's all. If all rendered normally or not, I'm clearing the graph. Even not running it.

App created as console app, full app here - https://yadi.sk/d/Ojoz_NkKHN2Spg

I have no ideas where is a problem can be, tested with MP4 file.
For example, using GDCL demuxer not problems with the same code.

`
// {B98D13E7-55DB-4385-A33D-09FD1BA26338}
DEFINE_GUID(CLSID_LAVSplitterSource,
	0xB98D13E7, 0x55DB, 0x4385, 0xA3, 0x3D, 0x09, 0xFD, 0x1B, 0xA2, 0x63, 0x38);

// EE30215D-164F-4A92-A4EB-9D4C13390F9F
DEFINE_GUID(CLSID_LAVVideo, 0xEE30215D, 0x164F, 0x4A92, 0xA4, 0xEB, 0x9D, 0x4C, 0x13, 0x39, 0x0F, 0x9F);

// {51b4abf3-748f-4e3b-a276-c828330e926a}
DEFINE_GUID(CLSID_VideoMixingRenderer9,
	0x51b4abf3, 0x748f, 0x4e3b, 0xA2, 0x76, 0xC8, 0x28, 0x33, 0x0E, 0x92, 0x6A);

void DSRemoveAllFilters(IFilterGraph2* pGraph)
{
	try
	{
		// Enumerate the filters in the graph.
		IEnumFilters* pEnum = nullptr;
		const HRESULT hr = pGraph->EnumFilters(&pEnum);
		if (SUCCEEDED(hr))
		{
			IBaseFilter* pFilter = nullptr;
			while (S_OK == pEnum->Next(1, &pFilter, nullptr))
			{
				// Remove the filter.
				try
				{
					pGraph->RemoveFilter(pFilter);
				}
				catch (...)
				{
				}

				// Reset the enumerator.
				pEnum->Reset();
				pFilter->Release();
			}

			pEnum->Release();
		}
	}
	catch (...)
	{
	}
}

BOOL IsFilePlayable(LPCWSTR filename)
{
	BOOL result = false;
	IFilterGraph2* filterGraph2 = nullptr;
	ICaptureGraphBuilder2* captureGB = nullptr;
	IBaseFilter* source = nullptr;
	IBaseFilter* videoDecoder = nullptr;
	IBaseFilter* videoRenderer = nullptr;

	CoCreateInstance(CLSID_FilterGraph, nullptr, CLSCTX_INPROC_SERVER,
		IID_IGraphBuilder, (void **)&filterGraph2);
	CoCreateInstance(CLSID_CaptureGraphBuilder2, nullptr, CLSCTX_INPROC_SERVER,
		IID_ICaptureGraphBuilder2, (void **)&captureGB);
	captureGB->SetFiltergraph(filterGraph2);

	// add LAV splitter source
	HRESULT hr = CoCreateInstance(CLSID_LAVSplitterSource, nullptr, CLSCTX_INPROC_SERVER, IID_IBaseFilter, (void **)&source);
	if (FAILED(hr))
	{
		if (source)
			source = nullptr;
		result = false;

		goto clear;
	}

	filterGraph2->AddFilter(source, L"LAV Splitter Source");

	IFileSourceFilter* sourceFile = nullptr;
	source->QueryInterface(IID_IFileSourceFilter, (void**)&sourceFile);
	if (sourceFile)
	{
		sourceFile->Load(filename, nullptr);
	}

	// add LAV video decoder
	hr = CoCreateInstance(CLSID_LAVVideo, nullptr, CLSCTX_INPROC_SERVER, IID_IBaseFilter, (void **)&videoDecoder);
	if (FAILED(hr))
	{
		if (videoDecoder)
			videoDecoder = nullptr;
		result = false;

		goto clear;
	}

	// add VMR-9
	hr = CoCreateInstance(CLSID_VideoMixingRenderer9, nullptr, CLSCTX_INPROC_SERVER, IID_IBaseFilter, (void **)&videoRenderer);
	if (FAILED(hr))
	{
		if (videoRenderer)
			videoRenderer = nullptr;
		result = false;

		goto clear;
	}

	hr = captureGB->RenderStream(nullptr, &MEDIATYPE_Stream, source, videoDecoder, videoRenderer);
	if (hr != 0)
	{
		hr = captureGB->RenderStream(nullptr, &MEDIATYPE_Video, source, videoDecoder, videoRenderer);
		if (hr == 0)
			result = true;
	}
	else
	{
		result = true;
	}
clear:
	DSRemoveAllFilters(filterGraph2);

	if (source != nullptr)
	{
		source->Release();
		source = nullptr;
	}

	if (videoDecoder != nullptr)
	{
		videoDecoder->Release();
		videoDecoder = nullptr;
	}

	if (videoRenderer != nullptr)
	{
		videoRenderer->Release();
		videoRenderer = nullptr;
	}

	if (filterGraph2 != nullptr)
	{
		filterGraph2->Release();
		filterGraph2 = nullptr;
	}

	if (captureGB != nullptr)
	{
		captureGB->Release();
		captureGB = nullptr;
	}

	return result;
}

int _tmain(int argc, _TCHAR* argv[])
{
	CoInitialize(nullptr);

	if (argc < 2)
	{
		printf("Please use file name as first parameter.\n");
		return 0;
	}

	if (IsFilePlayable(argv[1]))
	{
		printf("File %ls is playable.\n", argv[1]);
	}
	else
	{
		printf("File %ls is not playable.\n", argv[1]);
	}
	   
	wchar_t newFile[255];
	wsprintf(newFile, L"%ls.new", argv[1]);
	int res = _wrename(argv[1], newFile);

	if (res == 0)
	{
		printf("File %ls is renamed.\n", argv[1]);
	}
	else
	{
		printf("File %ls is not renamed.\n", argv[1]);
	}

	getchar();

	return 0;
}`

**Comment by Nevcairiel** [comment]
You never release "sourceFile". Using QueryInterface creates a new reference, if you don't release them, the filter will be stuck active.

**Comment by roman-minyaylov** [comment]
Yes, very stupid error, all OK now. Sorry for waste of time.

Really, all my code written on C#, so, that's looks another problem with COM and RCW, and all OK in C# code.

Interesting, why GraphStudio do not release filter normally and do not allow to remove file.

Thank you for your great project!
