### ISSUE TITLE
resuming after long pause = corrupted audio

### ISSUE THREAD

**Issue by glc650** [Nevcairiel/LAVFilters#254]
I have the latest mpc-hc and external (also tried with internal) lav filters.  I bitstream all DD/DTS/HD audio to my AVR.  Recently, when resuming after being paused for a long time (20+ minutes?) the audio doesn't come back.  Instead I get all noise/static/distortion.  I noticed at this time my AVR now shows PCM on its display (before it showed DD/DTS).  Changing auto tracks (assuming there is more than one) and restarting the video seem to be the only fix.  Never had this issue before.  Only thing that has changed in my setup (besides latest mpc/lav/madvr software) is my video card (upgraded from AMD to Nvidia 1060).

Update: works as expected if I let lav audio do the decoding (no bitstreaming) so bitstreaming with lav causes the issue.  Doesn't do it every time either but 9 times out of 10 it will after 30+ minutes paused.

**Comment by Nevcairiel** [comment]
LAV only prepares the stream for bitstreaming, the actual bitstreaming task is done by the audio renderer. Note that bitstreaming  and long pauses has always been problematic, since many audio renderers do not in fact properly implement bitstream pause bursts.
