### ISSUE TITLE
AAC decoding issue

### ISSUE THREAD

**Issue by clsid2** [Nevcairiel/LAVFilters#255]
Sample:
https://www.sendspace.com/file/z6sz6f

Sound is silent. After seeking there is some output for a fraction of a second, then silence again.

**Comment by Nevcairiel** [comment]
The file doesn't actually contain any significant portions of audio. It contains two audio blocks of very short size, and nothing else. mkvinfo shows a lot of video and subtitle date, but no further audio data (track 1)

**Comment by clsid2** [comment]
Sorry for that. I made a too small cut. Audio is apparently badly interleaved.

Here is magnet link for full file:
magnet:?xt=urn:btih:6F00B920205B4002CD8E487AA17B002D80FD3D9F&dn=samplefile

**Comment by Nevcairiel** [comment]
If the interleaving is so bad that LAVs buffers fill up before any audio is being found, then this cannot be resolved, and the file should just be considered faulty.

**Comment by clsid2** [comment]
Increasing queue sizes made the audio play. I should have tried that before. But, you are right, it is a poorly created file.
