### ISSUE TITLE
YT live streaming

### ISSUE THREAD

**Issue by clsid2** [Nevcairiel/LAVFilters#256]
MPC-HC + youtube-dl.exe

On Youtube click on Live in left menu and open the URL any of the streams with MPC-HC. These streams will play for 1 second, then freeze for 30 seconds, and continues with this alternating play/freeze behavior.

If I copy the extracted URL from the MPC-HC playlist and play it with FFplay, then everything is ok.

Maybe it tries to buffer data that isn't available yet, timeouts, and then retries?

**Comment by Nevcairiel** [comment]
The SChannel based SSL protocol implemetnation used by ffmpeg in LAV is a bit flaky with some servers. Not sure if thats directly related, but I've definitely seen it before.

**Comment by Nevcairiel** [comment]
I did some quick hack to use GnuTLS, and it seems to solve the problem. So I'll work towards moving LAV to GnuTLS entirely in the future.

**Comment by Nevcairiel** [comment]
Should be resolved by b77842ed0d8e6fc088a695cf84e65668e8054b6a

**Comment by clsid2** [comment]
Awesome. Thanks for the quick fix!
