### ISSUE TITLE
Posible HEVC 10Bits random artifacts

### ISSUE THREAD

**Issue by DarkKinof** [Nevcairiel/LAVFilters#257]
Hi,
A few days ago i found random video corruption while recoding some videos.
I check storage, video material Checksum, view video with different players (MPCHC, VLC, etc) and didn´t detect any error.
I make another reencoding try and found random video corruption, in different positions of the same video.
To make the reencode i use AVISYNTH+ (with DirectShowSource) and FFMPEG and never found this problem.
I have two systems with the same SW version (SO, LAV Filter 0.73.1, AVISYNTH, FFMPEG, etc, etc), but yesterday i made the reencode with the second one, and finally the process finish without corruption.

Checking system differences, i found that the corruption appears when LAV don´t use HW Acceleration to decode HEVC 10bits.
In the first system i use a GTX680 and HEVC 10bits HW Decoding with CUDA is not supported => Corruption appears.
In the second system i use a GTX1060 and HEVC 10bits HW Decoding with CUDA is supported => Not corruption appears.

This is video source information:

ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L4.1@High
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 22 min 51 s
Bit rate                                 : 7 019 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling               : 4:2:0
Bit depth                                  : 10 bits

All other video sources (AVC 8 and 10Bits, WMV, etc) with or without HW Acceleration don´t create corruption.
Regards

**Comment by Nevcairiel** [comment]
Without a sample file, there is nothing I can do.

**Comment by DarkKinof** [comment]
Hi,
every file is about 1.28Gb.
Could i send you a MEGA link?
Regards

**Comment by Nevcairiel** [comment]
It should be possible to cut a smaller part of the files. But a mega link is fine.

**Comment by DarkKinof** [comment]
Hi,
here you have mega folder link.
https://mega.nz/#F!XMpWUATR!kz6qSBAtTESxqToPGD1A_w
You will find Original and Recompresed video, a text file with data about where you can find the corruption and my hw/sw specs.
I remove sound tracks from video files to make their more "slim".
This is one example, but i found the same problem on the 13 Original videos.
Thanks for your help and nice work.
regards.

**Comment by Nevcairiel** [comment]
I'm not seeing any corruption when decoding the original video. Do you see the corruption when just playing the original file with eg. MPC-HC, which uses LAV Filters?

The decoder should not behave any differently in a player then it should in AviSynth

**Comment by DarkKinof** [comment]
Hi,
when i use mpchc with eembedded lav filters i can´t "see" any artifacts.
i follow this procedure:
-Make an avs file:

LoadPlugin ("C:\AvsPlugins\KNLMeansCL.dll")
SetFilterMTMode("DEFAULT_MT_MODE", 2)
SetFilterMTMode("DirectShowSource", 3)
SetFilterMTMode("KNLMeansCL", 3)
DirectShowSource ("D:\OriginalVIDEO\[VCB-Studio] Lupin the Third Mine Fujiko to Iu Onna [04][Ma10p_1080p][x265_flac].mkv", audio=false,pixel_type="YV12")
KNLMeansCL(d=2, a=2, s=4, h=2 , device_type="GPU" , channels="Y")
Prefetch(4)

-Recompress the avs file with ffmpeg

ffmpeg.exe -i "D:\RecompresedVIDEO\[VCB-Studio] Lupin the Third Mine Fujiko to Iu Onna [04][Ma10p_1080p][x265_flac].avs" -c:v libx264 -crf 16 -preset slow -x264opts force-cfr "D:\RecompresedVIDEO\[VCB-Studio] Lupin the Third Mine Fujiko to Iu Onna [04][Ma10p_1080p][x265_flac].mkv"

When i follow this 2 steps on the GTX-680 system (with NO HW Decoding into Lav Filter Video properties page) the Reencoded video show artifacts.
When i follow this 2 steps on the GTX-1060 system (with HW Decoding into Lav Filter Video properties page) the Reencoded video don´t show artifacts.

My assumption (it can be a mistake) is that the problem source is Lav Filter 0.73.1 because is the only element that "change" between both systems.
Regards.

**Comment by Nevcairiel** [comment]
If there would be a problem decoding the video, it should show regardless if its being used in AviSynth or a video player.

What, for example, happens if you try to do the exact same thing on the second system? ie. disable hardware decoding on the second system, and see what happens then?

Software decoding is usually not dependent on the hardware or system it runs on, so if there is a problem with software decoding, it should show on any system, given the same settings.

**Comment by DarkKinof** [comment]
Hi,
We can be near now.
After set "Hardware Decoder" like "NONE" i reencode twice the video, and can´t detect any artifacts (on GTX-1060 system)
When i set "Hardware Decoder" like "NONE" and reencode the video on GTX-680 system, i and can´t detect any artifacts
But if i set "Hardware Decoder" like "NVIDIA CUVID" (i see OK near to DROPLIST) and reencode the video on GTX-680 system, the artifacts come back.

I try tomorrow more times to be sure, but i think it is the source of the problem.
I can´t set "Hardware Decoder" like "NVIDIA CUVID" on GTX-1060 system because as soon ffmpeg start encoding, "Active Decoder" change to "cuvid" and "Active Hardware Accelerator" show "GeForce GTX 1060"
Regards.

**Comment by Nevcairiel** [comment]
I would think it should safely fallback to software decoding without causing issues, but I don't know if it might cause any interference with other components.

In any case, you could simply disable the HEVC hardware checkbox on your first system, as it will never support any HEVC, and the problem should also go away, while still allowing hardware access for H264, for example.

Unfortunately I don't think I have a 600-series card around to test this.

**Comment by DarkKinof** [comment]
Hi,
finally i make a few more tests.
Unfortunatelly, disable HEVC Checkbox under "Codecs for HW Decoding" don´t solve the problem.
Every time i try, the reencoded video show artifacts.
The only way to avoid the artifacts is set None in "Hardware Decoder to use" Dropbox, but this option disables any kind of HW Decoding.
If you wish, i can use some LAV FILTER version than can generate any kind of log/report (i can't find any option in the different download options/versions)
Thanks for your time.
Regards.

**Comment by lvqcl** [comment]
Why you use "NVIDIA CUVID" decoder? And what happens if you set it to "DXVA2 (copy-back)"?

**Comment by DarkKinof** [comment]
Hi lvqcl,
i use always "NVIDIA CUVID" because long time ago, only this option worked fine with AVS+NvidiaGPU and give me HW Decoding.
i had seen new options when i had updated Lav Filters, like DXVA2 (copy-back), but i never use anyone.
Regards

**Comment by DarkKinof** [comment]
Hi,
I had read a few notes about DXVA2 (copy-back), but I didn't find a real conclusion.
what are the advantages of DXVA2 (copy-back) vs Nvidea CUVID?
both method give me the same video quality (<= it is always my priority)?
Thanks for your help.
Regards

**Comment by DarkKinof** [comment]
Hi, I finally followed your recommendation and use DXVA2 (copy-back).
After 3 tests, I found no artifacts and all worked fine.
Nevcairiel and Lvqcl, thanks for your help and amazing work.
Regards
