### ISSUE TITLE
Issue with LAV Audiio.

### ISSUE THREAD

**Issue by EcoSeis** [Nevcairiel/LAVFilters#258]
Hi;

First I'll start by saying that english isn't my native language, so I'll try my best to explain, and please forgive anything that doesn't make much sense.

I have encountered an issue with my setup for video reproduction, I've been using MPC-HC with LAV filters and Madvr for years, everything until yesterday was absolutlely fine, suddenly, I came for work, open a video, and it doesn't have any sound, I tried many files, and the only ones that have sound are the stereo, like an anime episode, movies or TV series episodes with 6 channel audio don't have any sound, but even the stereo ones aren't working correctly, only one speaker has sound.

I tried everything I can think of, I managed to make the sound work but only in one speaker like I said, if I change the output options in MPC to the speakers directly and not system default, but then, the sound will come from there even with the headphones plugged in, and also by enabling mixing in the LAV Audio options, but again, with only one speaker working.

Everything else on the system seems to be fine, I tried to install VLC, and no problem at all, everything is updated, and I uninstalled and installed again many times.

I would appreciate any help, and I thank you in advance for taking the time to read my complaint.

**Comment by Nevcairiel** [comment]
LAV Audio works rather predictably. It just decodes the audio and hands it off to the audio renderer, which is then responsible for handing it to the audio hardware. If something went wrong, its extremely unlikely to be something in LAV is affecting it, but rather the audio renderer.

I would recommend to inquire with the audio renderer, or the player. But if something just breaks without you changing anything, then a likely cause is a driver update or a windows update.
