### ISSUE TITLE
some https mkv no audio or video

### ISSUE THREAD

**Issue by 7sean68** [Nevcairiel/LAVFilters#260]
when I play files like this one [url](https://masrur.hi10anime.com/varian/Shows/[Hi10]_Sakurasou_no_Pet_na_Kanojo_[BD_720p]/(Hi10)_Sakurasou_no_Pet_na_Kanojo_-_02_(BD_720p)_(Coalgirls).mkv?jtoken=27b6f925b3) from url It gives me a black video with no audio and no sub, but when I download and play it plays correctly

**Comment by clsid2** [comment]
Increasing "Stream Analysis Duration" value in settings of LAV Splitter may solve this.

**Comment by 7sean68** [comment]
already 50000 ms

**Comment by Nevcairiel** [comment]
The file plays just fine for me with latest LAV nightly.

**Comment by 7sean68** [comment]
I'm using K-Lite Codec MPC-HC it is using version 0.73.1.28-git
and that's my settings It gives a black screen and no sound, although it reads the media properties correctly
The same file worked well when I downloaded it first
![Annotation 2019-03-11 182352](https://user-images.githubusercontent.com/9345129/54139771-e7d01600-442a-11e9-8cb5-6ad9cdc7b604.jpg)

**Comment by clsid2** [comment]
Plays fine here with latest K-Lite. Even with default LAV Splitter settings.
