### ISSUE TITLE
Crackling noise and embedded fonts not loaded

### ISSUE THREAD

**Issue by MadClown** [Nevcairiel/LAVFilters#261]
Hello,

I'm getting some weird crackling noises when using LAVFilters (0.73.1.37) in this file.  If I extract the opus file and play that back instead, it sounds just fine. I tested and it seems like it's only messed up when it's muxed in an mkv.

Also, LAV Splitter isn't loading the embedded fonts in this file as well. I tested it with MPC-BE and it doesn't have the sound issue, but it doesn't load the fonts either. PotPlayer's build-in filters load the embedded fonts and decodes the audio without any issues.

Thanks in advance
[sample.zip](https://github.com/Nevcairiel/LAVFilters/files/2968803/sample.zip)

**Comment by Nevcairiel** [comment]
The Opus stream has a lot of "Discard padding" metadata for a lot of the Opus audio frames, which results in the decoder dropping parts of that audio frame. This appears to be an issue with how the file was made.

Some other decoders may ignore such data, but in a perfectly valid file, this data may be required for proper playback, so there is nothing I can really do.

The fonts are also not properly marked as fonts, but as generic binary data - however they have a filename, so I can add some logic to try to check for a .ttf ending and assume its a font.

**Comment by clsid2** [comment]
If Discard Padding is only supposed to occur at end of file, wouldn't it make sense to ignore it?

https://trac.ffmpeg.org/ticket/4178

**Comment by Nevcairiel** [comment]
The specification makes no such limitations.
