### ISSUE TITLE
Youtube-DL & desync

### ISSUE THREAD

**Issue by Tharn** [Nevcairiel/LAVFilters#262]
With version 0.74, using Youtube-DL which simply passes through the file link to MPC-HC afaik, I'm seeing issues where a Youtube video may play fine for 10 or 20 minutes, then the video will start to stutter and lose a lot of frames while the audio continues as normal. This leads to the video lagging behind more and more as the file continues to play. Forcing the progress bar a few seconds ahead to re-seek may jump the video back into place.

**Comment by Nevcairiel** [comment]
YouTube videos typically come as two streams, a video and an audio stream, which are handled independently and not by one instance of LAV. As such, it cannot take care of syncing them, so if anything goes wrong in the stream, bad stuff happens, and LAV won't know anything about it.

The only way to fully resolve this would be using YTDL differently, and not just extracting the streams from the website info and directly streaming those, but actually using the DASH manifest to play them, and letting DASH sync them.

**Comment by Tharn** [comment]
So the bug report should rightly go to Youtube-DL then. Cheers!

**Comment by Nevcairiel** [comment]
Not really, no. Its just a tool that provides information, how that information is used is another matter entirely.

**Comment by Tharn** [comment]
The videos in question were VP9, for which stuff was fixed recently. I'll try it for a while and report back.

**Comment by Tharn** [comment]
I haven't seen any dropped frames since 0.74.1. Seems to have fixed the issue.
