### ISSUE TITLE
Black screen when watching VP9 Youtube stream (AMD) until scrubbing

### ISSUE THREAD

**Issue by Riotous** [Nevcairiel/LAVFilters#263]
Windows 10 64 bits, AMD graphics. MPC-HC 1.8.5 with LAV 0.74. Always happens with Software decoding and DXVA2. Also mostly but not always happens with DXVA2 (copy back).

1) Watch a VP9 Youtube stream with Opus audio using YDL or even a locally saved .webm download. Any Youtube link will do as long as it's VP9 with Opus.
2) Video shows as a perfectly black screen (no image at all) while audio plays fine.
3) Scrubbing anywhere else in the video brings playback back to normal.

Not sure if this is an MPC-HC issue but they said to report playback issues here first.

**Comment by Nevcairiel** [comment]
VP9 from YouTube plays fine for me. If software decoding is affected, its very likely a rendering or player problem.

**Comment by Riotous** [comment]
@Nevcairiel You may be right. I'll close this for now and re-open the issue at MPC-HC until we can pinpoint the cause of this issue. 

https://github.com/clsid2/mpc-hc/issues/83
