### ISSUE TITLE
About DX11 decoder!

### ISSUE THREAD

**Issue by TopPlay** [Nevcairiel/LAVFilters#264]
I uses MediaFoudation to play 4K media under DX11, lower cpu uses;
but decoder same media uses directShow by  lav dx11 decoder,hight cpu uses,
why?
win10 system;
by the way ,i uses custom evr render, can lav decoder uses same d3d device from render?

**Comment by Nevcairiel** [comment]
EVR in DirectShow does not have the ability to share D3D11 with the decoder. If you use EVR, you should use DXVA2 decoding.
