### ISSUE TITLE
Possible LAV Splitter issue with DVB-T audio disappearing after switching channels

### ISSUE THREAD

**Issue by epigramx** [Nevcairiel/LAVFilters#265]
I was instructed to report it here since it's possibly an issue with this project; the audio when running DVB-T at mpc-hc drops entirely after switching channels and the option  "Remove audio decoder on audio stream switch" doesn't seem to help.

Reference mpc-hc issue: https://github.com/clsid2/mpc-hc/issues/74

**Comment by Nevcairiel** [comment]
LAV Splitter is not used with DVB playback.

Also, when I'm testing DVB-T2 with MPC-HC, then audio remains fully functional for me, no matter if its the same codec, or switching codecs.
