### ISSUE TITLE
Dolby TureHD/Atmos decode fail and freezes MPC-BE

### ISSUE THREAD

**Issue by http403** [Nevcairiel/LAVFilters#268]
I tried to play a 4k movie backed up with MakeMKV which it offers a 16-ch atoms sound track. LAV audio decoder fails to decode it and freeze up MPC-BE at the moment the file was opened. Although I said freeze, it actually freeze in a wired state. The player remain responsive but unable to play the video and audio. Furthermore, there isn't any dialog box indicating the decode was failed and fall back to another track. I'm using all latest version of MPC-BE, LAV, and madVR. Currently I workaround the issue by using internal TrueHD decoder. Switching to other supported audio track, AC3 in my case, will enable the playback but it is not reliable.

I except LAV would play audio track with some sacrifice or display an error dialog box or automatically fall back to another track.

**Comment by Nevcairiel** [comment]
Please try another player to compare. TrueHD playback is otherwise known to work just fine.
Additionally, without a sample file, there is nothing I can do.

**Comment by http403** [comment]
I tried VLC and it played smoothly. I planned to play it in MPV tonight and see how it goes.

**Comment by Nevcairiel** [comment]
The point of this exercise was to use another player that uses LAV Filters to compare, not one that doesn't.

In any case, I need a sample file. I cannot go out any buy every disc.

**Comment by http403** [comment]
Well, I will setup PotPlayer tonight and see.

For the sample file. As I don't know how to edit a TrueHD track, I need to send you the whole file or instructions to do so. Do you mind we communicate off GitHub and arrange a secure transport method?

**Comment by Nevcairiel** [comment]
Are you bitstreaming to a AV Receiver, or actually decoding in LAV Audio?

**Comment by lvqcl** [comment]
> Well, I will setup PotPlayer tonight and see.

I thought that PotPlayer has its own decoders ?

**Comment by http403** [comment]
> 
> 
> Are you bitstreaming to a AV Receiver, or actually decoding in LAV Audio?

I'm not bitstreaming but decode in LAV audio

**Comment by http403** [comment]
Just done testing with PotPlayer latest x86 version and got more interesting result. PotPlayer will play the video without sound. However, it will freeze just like MPE if I disable the build-in audio transform filter. Also, if change the audio track back and forth, PotPlayer will freeze too. With default setting of PotPlayer, it will play smoothly.

**Comment by Nevcairiel** [comment]
I managed to get a small cut of that movie on UHD Blu-ray, and I cannot reproduce any problems at all.

**Comment by http403** [comment]
> 
> 
> I managed to get a small cut of that movie on UHD Blu-ray, and I cannot reproduce any problems at all.

That's interesting because I got some results in MPC and PotPlayer. I wonder is there a debug log so that I can look and examine...

**Comment by sylido** [comment]
@http403 I think it's because you are trying to play an ATMOS track over Stereo hardware or trying to output it to Stereo as seen in your second screenshot. I had something similar keep happening when I had my output changed to my headphones. If I default to my ATMOS enabled soundbar it actually works without the freeze. To try it out, maybe try switching to a non-ATMOS audio track while on the same sound output device - I think the player should "unfreeze" and you should be getting sound + video at that time.

**Comment by http403** [comment]
@sylido Sadly I only got a stereo headphone and a crappy Logitech 2.1 speaker set. Is there a way to down mix ATMOS to stereo while playback?

**Comment by sylido** [comment]
@http403 It sounds reasonable that there should be something that combines the streams into stereo, from your settings it seems like LAV Audio should be doing that. I am certain that AC3 tracks that usually come bundled with Atmos are 5.1+ and definitely get remixed to stereo. Maybe because of the nature of 3D sound that moves around you, you can't really map that easily to stereo and thus ATMOS doesn't work. Just an example, I was looking for a reason why my ATMOS all of a sudden stopped working - turns out it's the Display Port cable I'm using to run 2 TVs off of the same video card - only the pure HDMI cable can support the bandwidth necessary for 4k RGB + ATMOS.

**Comment by http403** [comment]
@sylido I can get it but imo a total freeze application is unacceptable. A graceful fallback should be provided like ignoring the ATMOS stream completely.

**Comment by clsid2** [comment]
Does the TrueHD track itself (without atmos) have 16ch? In that case you must use the internal audio renderer of MPC-HC/BE, because the standard DirectSound renderer doesn't like that many channels. LAV can downmix to stereo, but I don't know if that also works with that many channels.

Provide a sample file!

**Comment by Nevcairiel** [comment]
TrueHD is incapable of having that many channel.

I have been unable to reproduce any such issues, and if you're decoding and not bitstreaming such issues are even more uncommon, since TrueHD decoding has been flawless for years.

**Comment by http403** [comment]
@clsid2 Could you tell me how to edit TrueHD track alone ATMOS info in the free way? I would like to help but I don't know how to edit it into a sample size file.

**Comment by http403** [comment]
@Nevcairiel @clsid2 With some tries in `ffmpeg`, I managed to make a sample file with identical media info. Please review.

[Sample file](https://sharing.ams3.cdn.digitaloceanspaces.com/github-Nevcairiel_LAVFilters-issue268-sample.mka)

**Comment by clsid2** [comment]
That sample plays fine here with MPC-HC.

**Comment by http403** [comment]
Just downloaded MPC-HC to test. Internal LAV filter have zero issue to play but it stops working when using external LAV filter for few seconds and jump right to the end of the file.

**Comment by clsid2** [comment]
Internal or external should not matter. Any difference is because of the used versions of LAV.

LAV builds:
https://files.1f0.de/lavf/nightly/

MPC-HC 1.8.6 (with LAV 0.74.1):
https://github.com/clsid2/mpc-hc/releases

**Comment by http403** [comment]
To me it is weird why internal filter works while external doesn't being both at the same version. I'm now wondering if any other MPC-BE configuration cause this problem.

**Comment by ValZapod** [comment]
@http403 Just install https://www.codecguide.com/ It has latest LAV and MPC (Not BE, but mpc-hc).
With them your sample works fine. Of course, you should understand that "Meridian Lossless Packing FBA with 16-channel presentation" does not actually mean it is 16 channels inside. As you can see in mediainfo:
```
Audio
ID                          : 1
Format                      : MLP FBA 16-ch
Format/Info                 : Meridian Lossless Packing FBA with 16-channel presentation
Commercial name             : Dolby TrueHD with Dolby Atmos
Codec ID                    : A_TRUEHD
Duration                    : 30 s 24 ms
Bit rate mode               : Variable
Bit rate                    : 3 170 kb/s
Maximum bit rate            : 5 013 kb/s
Channel(s)                  : 8 channels
Channel layout              : L R C LFE Ls Rs Lb Rb
Sampling rate               : 48.0 kHz
Frame rate                  : 1 200.000 FPS (40 SPF)
Compression mode            : Lossless
Stream size                 : 11.3 MiB (98%)
Language                    : English
Default                     : Yes
Forced                      : No
Number of dynamic objects   : 15
Bed channel count           : 1 channel
Bed channel configuration   : LFE

```
there are actually only "Channel(s): 8 channels" with standard L R C LFE Ls Rs Lb Rb (Left, Right, Center, Low Frequency effects, Left Surround, Right Surround, Left rear surround, Right rear surround). Though of course it has fourth substream, which is atmos substream with atmos non-audio metadata (it encodes which sound is in height channels + so plus minimum 2 channels). But there is no software decoder of it!!! At all! The main problem is that only Windows now support Height channel API with no actual hardware without bitstreaming that support it. And though the standard for E-AC3 with Atmos is already present https://www.etsi.org/deliver/etsi_ts/103400_103499/103420/01.02.01_60/ts_103420v010201p.pdf
https://www.etsi.org/deliver/etsi_ts/103400_103499/103420/01.02.01_60/ts_103420v010201p0.zip
https://www.etsi.org/deliver/etsi_ts/102300_102399/102366/01.04.01_60/ts_102366v010401p.pdf
there is no such standard for TrueHD, which complicates this even further.

**Comment by http403** [comment]
@ValZapod As stated before, I had tried MPC-HC with its build in LAV filters and the results are good. However, once I switch to external with the same version in HC, it just stopped working.

**Comment by ValZapod** [comment]
@http403 BTW, look into this patch https://patchwork.ffmpeg.org/patch/13832/
As you can see in description "This change also makes MediaInfo no longer display the presence of Atmos
in the output of truehd_core."
ffmpeg does not support 16 channel presentation (in truehd) and before mistakenly wrote it to file.
So maybe this is it: you created your sample with ffmpeg without this patch...

BTW, I will try to download Blu-ray rip with Dolby Vision and check if 16 channel presentation is in it.

**Comment by ValZapod** [comment]
@http403 So is everything working for you now? BTW, I also read that you need to have windows 10 1903 which is the one where atmos finally started working good.

**Comment by http403** [comment]
@ValZapod I recently reinstalled my machine. Now I can confirm it played flawlessly. It is unfortunate that I can't make it clear on how to reproduce the issue. However, thank you all of you for guiding and helping me to solve this problem.
