### ISSUE TITLE
Build error :

### ISSUE THREAD

**Issue by DibyaTheXPFan** [Nevcairiel/LAVFilters#269]
First build script did not run . I have latest VS2017 installed ,
I opened .sln and it is saying intel quick sync decoder is missing 

1>------ Build started: Project: baseclasses, Configuration: Release Win32 ------
2>------ Build started: Project: libbluray, Configuration: Release Win32 ------
2>dirs_win32.c
1>amextra.cpp
1>amfilter.cpp
1>amvideo.cpp
1>arithutil.cpp
1>combase.cpp
1>cprop.cpp
1>ctlutil.cpp
1>ddmm.cpp
2>dir_win32.c
1>dllentry.cpp
1>dllsetup.cpp
1>mtype.cpp
1>outputq.cpp
1>perflog.cpp
1>pstream.cpp
1>pullpin.cpp
1>refclock.cpp
2>dl_win32.c
1>c:\users\administrator\desktop\lavfilters-master\common\baseclasses\dllentry.cpp(314): warning C4996: 'GetVersionExW': was declared deprecated
1>c:\program files (x86)\windows kits\8.1\include\um\sysinfoapi.h(442): note: see declaration of 'GetVersionExW'
1>renbase.cpp
1>schedule.cpp
1>seekpt.cpp
1>source.cpp
1>strmctl.cpp
1>sysclock.cpp
2>file.c
1>transfrm.cpp
2>filesystem.c
2>file_win32.c
1>transip.cpp
1>videoctl.cpp
1>vtrans.cpp
2>mount.c
1>winctrl.cpp
1>winutil.cpp
1>wxdebug.cpp
2>bdid_parse.c
2>bdmv_parse.c
2>clpi_parse.c
2>extdata_parse.c
2>index_parse.c
2>meta_parse.c
1>wxlist.cpp
2>mpls_parse.c
1>wxutil.cpp
2>navigation.c
2>sound_parse.c
2>uo_mask.c
2>bluray.c
2>c:\users\administrator\desktop\lavfilters-master\libbluray\src\libbluray\bluray.c(1406): warning C4101: 'env': unreferenced local variable
2>graphics_controller.c
2>graphics_processor.c
2>Compiling...
2>ig_decode.c
2>m2ts_demux.c
2>m2ts_filter.c
2>pes_buffer.c
2>pg_decode.c
2>rle.c
2>textst_decode.c
2>textst_render.c
2>aacs.c
2>bdplus.c
2>dec.c
2>disc.c
1>c:\users\administrator\desktop\lavfilters-master\common\baseclasses\wxutil.cpp(753): warning C4996: 'GetVersionExW': was declared deprecated
1>c:\program files (x86)\windows kits\8.1\include\um\sysinfoapi.h(442): note: see declaration of 'GetVersionExW'
2>c:\users\administrator\desktop\lavfilters-master\libbluray\src\libbluray\disc\disc.c(494): warning C4244: 'function': conversion from 'int64_t' to 'size_t', possible loss of data
2>properties.c
2>c:\users\administrator\desktop\lavfilters-master\libbluray\src\libbluray\disc\properties.c(73): warning C4244: 'function': conversion from 'int64_t' to 'size_t', possible loss of data
2>hdmv_vm.c
2>mobj_parse.c
2>mobj_print.c
2>register.c
2>array.c
2>bits.c
2>event_queue.c
2>Compiling...
2>logging.c
2>mutex.c
2>refcnt.c
2>strutl.c
2>time.c
1>baseclasses.vcxproj -> C:\Users\Administrator\Desktop\LAVFilters-master\bin_Win32\lib\strmbase.lib
1>Done building project "baseclasses.vcxproj".
3>------ Build started: Project: DSUtilLite, Configuration: Release Win32 ------
3>Git not found
3>stdafx.cpp
2>   Creating library C:\Users\Administrator\Desktop\LAVFilters-master\bin_Win32\libbluray\libbluray.lib and object C:\Users\Administrator\Desktop\LAVFilters-master\bin_Win32\libbluray\libbluray.exp
2>Generating code
3>BaseDSPropPage.cpp
2>All 684 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
3>CueSheet.cpp
3>DSMResourceBag.cpp
3>MediaSampleSideData.cpp
3>PopupMenu.cpp
3>BaseTrayIcon.cpp
3>ByteParser.cpp
3>CSSauth.cpp
3>CSSscramble.cpp
3>DeCSSInputPin.cpp
3>DShowUtil.cpp
2>Finished generating code
3>c:\users\administrator\desktop\lavfilters-master\ffmpeg\libavutil\common.h(45): fatal error C1083: Cannot open include file: 'libavutil/avconfig.h': No such file or directory (compiling source file ByteParser.cpp)
3>filterreg.cpp
3>FontInstaller.cpp
3>H264Nalu.cpp
3>locale.cpp
3>registry.cpp
3>c:\users\administrator\desktop\lavfilters-master\ffmpeg\libavutil\common.h(45): fatal error C1083: Cannot open include file: 'libavutil/avconfig.h': No such file or directory (compiling source file DShowUtil.cpp)
3>Done building project "DSUtilLite.vcxproj" -- FAILED.
2>libbluray.vcxproj -> C:\Users\Administrator\Desktop\LAVFilters-master\bin_Win32\libbluray\libbluray.dll
4>------ Build started: Project: LAVAudio, Configuration: Release Win32 ------
5>------ Build started: Project: LAVVideo, Configuration: Release Win32 ------
2>Copy .dll/.lib into library path
2>C:\Users\Administrator\Desktop\LAVFilters-master\bin_Win32\libbluray\libbluray.dll
2>1 File(s) copied
2>C:\Users\Administrator\Desktop\LAVFilters-master\bin_Win32\libbluray\libbluray.lib
2>1 File(s) copied
2>Done building project "libbluray.vcxproj".
6>------ Build started: Project: Demuxers, Configuration: Release Win32 ------
4>stdafx.cpp
5>stdafx.cpp
6>stdafx.cpp
4>c:\users\administrator\desktop\lavfilters-master\ffmpeg\libavutil\common.h(45): fatal error C1083: Cannot open include file: 'libavutil/avconfig.h': No such file or directory
4>Done building project "LAVAudio.vcxproj" -- FAILED.
5>c:\users\administrator\desktop\lavfilters-master\ffmpeg\libavutil\common.h(45): fatal error C1083: Cannot open include file: 'libavutil/avconfig.h': No such file or directory
5>Done building project "LAVVideo.vcxproj" -- FAILED.
6>c:\users\administrator\desktop\lavfilters-master\ffmpeg\libavutil\common.h(45): fatal error C1083: Cannot open include file: 'libavutil/avconfig.h': No such file or directory
6>Done building project "Demuxers.vcxproj" -- FAILED.
7>------ Build started: Project: LAVSplitter, Configuration: Release Win32 ------
7>stdafx.cpp
7>c:\users\administrator\desktop\lavfilters-master\ffmpeg\libavutil\common.h(45): fatal error C1083: Cannot open include file: 'libavutil/avconfig.h': No such file or directory
7>Done building project "LAVSplitter.vcxproj" -- FAILED.
========== Build: 2 succeeded, 5 failed, 0 up-to-date, 0 skipped ==========

**Comment by Nevcairiel** [comment]
You need to build the included ffmpeg before building LAV itself. Hence the errors bout avconfig.h not found.
