### ISSUE TITLE
Latest LAV not working properly

### ISSUE THREAD

**Issue by Ding-adong** [Nevcairiel/LAVFilters#270]
The hardware acceleration area doesn't show the correct info.
![lav1](https://user-images.githubusercontent.com/46300740/55406797-b98ab580-5554-11e9-9325-ec05079dc5e1.jpg)

Click on arrow and the option don't open fully. When it did before it showed automatic then rx570 twice. I have no idea which one i am suppose to select when I have monitor plus TV.
![lav2](https://user-images.githubusercontent.com/46300740/55406974-02db0500-5555-11e9-85dd-dd8fa1fe92b7.jpg)

My gpu card is working and doing all the Madvr fancy scaling etc.
![lav3](https://user-images.githubusercontent.com/46300740/55407094-52b9cc00-5555-11e9-8b94-52df87d2c9bd.jpg)

However it is hit and miss, sometimes works and then not. I can't figure it out. The last time it worked properly was 2 weeks ago.

**Comment by Nevcairiel** [comment]
Just select Auto, if you only have one card anyway there is no reason to do anything else, and can cause issues.

In any case, if it worked and then stopped without any changes in LAV, then its not a problem I can solve.

**Comment by Ding-adong** [comment]
What about the info. Active decoder and active hardware accelerator are wrong.

**Comment by Nevcairiel** [comment]
Its never wrong, it tells you exactly what is in use right now. Its possible the video isn't hardware compatible, or your driver is not cooperating.

**Comment by lvqcl** [comment]
The dialog window has a caption "KMP Built-in LAV Video...". Also, it has an option "HEVC10" which is absent in the original LAV Filters 0.74.1.

So, these filters were modified by developers of KMP (and who knows what exactly they did), so IMHO it's better to ask them about bugs.

**Comment by Nevcairiel** [comment]
Oh yeah, I didn't notice that. Can't really support modified versions.

**Comment by Ding-adong** [comment]
What are the HWaccel reg entries suppose to look like when DVXA2 is in used?

**Comment by clsid2** [comment]
It looks like there is a scrollbar in the dropdown. So try pressing up to change the selected value.

Hardware acceleration doesn't work with all video formats. For example 10-bit H.264 will always use software decoding. In case of 10-bit HEVC you need to enable the HEVC10 checkbox.

**Comment by Ding-adong** [comment]
The drop down works sometimes then it doesn't. I can't seem to find the cause.
All my vids are hvec 8 bits - codec id hev1. If someone can post their win 7 reg or similar of lav reg, I can do a comparison.
