### ISSUE TITLE
madVR not deinterlacing in d3d11 native mode.

### ISSUE THREAD

**Issue by iAM261917** [Nevcairiel/LAVFilters#271]
My video is interlaced, and when I'm using D3D11-Native mode, it looks like:
![11](https://user-images.githubusercontent.com/42721712/55446782-b1358780-55f3-11e9-9cc9-c589ae4754d6.png)
Using DXVA2-Native looks like:
![dxva](https://user-images.githubusercontent.com/42721712/55446783-b1ce1e00-55f3-11e9-9e08-26cd387d5118.png)
I'm not sure it is madVR's problem or LavFilter's problem, but is it possible you can fix it? I guess it would be harder because madVR isn't open-source.
I will contact madshi too.

**Comment by iAM261917** [comment]
Well I tried PotPlayer's D3D11 decoder and get same result, so I think it's probably madVR's problem or some limit of D3D11 decoding.

**Comment by Nevcairiel** [comment]
Its not a limit as such, but since D3D11 is entirely different, it needs to be implemented specifically for it - and thats not done in madVR yet.
