### ISSUE TITLE
Duplicate lines

### ISSUE THREAD

**Issue by Ding-adong** [Nevcairiel/LAVFilters#272]
https://github.com/Nevcairiel/LAVFilters/blob/0e1a386bcc2b5a9e51db12d4bb0b33569328f988/decoder/LAVVideo/LAVPixFmtConverter.h#L35

Is it necessary to have 2 lines with the same comment?

**Comment by Ding-adong** [comment]
https://github.com/Nevcairiel/LAVFilters/blob/0e1a386bcc2b5a9e51db12d4bb0b33569328f988/decoder/LAVVideo/decoders/dxva2dec.cpp#L275

Spelling error.

**Comment by Nevcairiel** [comment]
Thanks.
