### ISSUE TITLE
Some potential erros to look into.

### ISSUE THREAD

**Issue by Ding-adong** [Nevcairiel/LAVFilters#273]
Why is Lav reading VideoInfo2: YUY2 1024X404 when the file is 720x404?
Why is Lav showing 50 fps when it is 25 fps? This happens when I press Tab to display info on KMPlayer. Previously fps is 25/25 and now 50/25.
My GPU is busy processing the video and yet Dxva2 copy-back shows active decoder as avcodec and not dxva2cb and active hardware accelerator as none. Previously both info were displayed correctly.

[Primary Filtergraph]

0) - KMP Built-in LAV Source
1) - LAV Audio Decoder
2) - LAV Video Decoder
3) - Madshi's Video Renderer
4) - DirectSound: 4 - Panasonic-TV (AMD High Definition Audio Device)

[Video Info]
Decoder -(HVC1) LAV Video Decoder
Format -Major Type: Video - Sub Type: YUY2
VideoInfo2: YUY2 1024X404, 16 bits

[Audio Info]
Decoder -(AAC) LAV Audio Decoder
Format -Major Type: Audio - Sub Type: IEEE_FLOAT
WaveFormatEx: PCM_IEEE_FLOAT(0x3), 48000 Hz, 32 Bits, 2 Ch

[Basic Video DSP]
Internal brightness: 100%

[Advanced Video DSP]
+PictureProperty(S/W Process)
  -LumGain: 128
  -LumOffset: 0
  -Gamma: 100
  -HUE: 0
  -Saturation: 64

[Audio DSP]
+Pre amplification: Main: (100%)
+Voice Emphasis
+Auto Volume Control
+Audio Plugin

[Subtitle Settings]
+Draw Mode(Selected): Image
+Draw Mode(In use): VMR(Renderless)
+Text Rendering Method: Rasterizer
+Support HTML Tags(SMI)

[KMPlayer]
+Version: 4.2.2.24(15,052,008, 01/04/2019 06:47:52)
+libcodec.dll: (4,548,096, 26/12/2018 02:45:28)
+libmplay.dll: (538,112, 26/12/2018 02:45:36)
+PProcDLL.dll: 1.0.0.1(1,769,472, 26/12/2018 02:45:44)
+LibDTS.dll: (178,174, 26/12/2018 02:45:44)
+liba52.dll: (73,063, 26/12/2018 02:45:44)
+libfaad2.dll: (335,155, 26/12/2018 02:45:44)
+libmad.dll: (123,036, 26/12/2018 02:45:40)
+libmpeg2.dll: (154,644, 26/12/2018 02:45:44)
+theora.dll: (200,864, 26/12/2018 02:45:28)
+OggVorbis.dll: (1,165,312, 26/12/2018 02:45:44)
+xviddll.dll: (758,319, 26/12/2018 02:45:44)
+Old_QUARTZ.DLL: 6.01.05.0319(770,048, 26/12/2018 02:45:44)
+AboutDll.dll: (105,472, 26/12/2018 02:45:44)
+DTView.dll: (98,304, 26/12/2018 02:45:48)
+ImLoader.dll: (856,064, 26/12/2018 02:45:44)
+MediaInfo.dll: 18.12.0.0(5,041,664, 10/03/2019 11:00:00)

D:\Star Trek Voyager - 5x15.mp4
  General
    Complete name : D:\Star Trek Voyager - 5x15.mp4
    Format : MPEG-4
    Format profile : Base Media
    Codec ID : isom (isom/iso2/mp41)
    File size : 586 MiB
    Duration : 1 h 28 min
    Overall bit rate mode : Variable
    Overall bit rate : 931 kb/s
    Writing application : Lavf57.29.101

  Video
    ID : 1
    Format : HEVC
    Format/Info : High Efficiency Video Coding
    Format profile : Format Range@L3@Main
    Codec ID : hev1
    Codec ID/Info : High Efficiency Video Coding
    Duration : 1 h 28 min
    Bit rate : 761 kb/s
    Width : 720 pixels
    Height : 404 pixels
    Display aspect ratio : 16:9
    Original display aspect ratio : 16:9
    Frame rate mode : Constant
    Frame rate : 25.000 FPS
    Color space : YUV
    Chroma subsampling : 4:2:2
    Bit depth : 8 bits
    Scan type : Progressive
    Bits/(Pixel*Frame) : 0.105
    Stream size : 479 MiB (82%)
    Writing library : x265 2.0:[Windows][GCC 4.9.3][32 bit] 8bit

  Audio
    ID : 2
    Format : AAC LC
    Format/Info : Advanced Audio Codec Low Complexity
    Codec ID : mp4a-40-2
    Duration : 1 h 28 min
    Bit rate mode : Variable
    Bit rate : 164 kb/s
    Maximum bit rate : 192 kb/s
    Channel(s) : 2 channels
    Channel layout : L R
    Sampling rate : 48.0 kHz
    Frame rate : 46.875 FPS (1024 SPF)
    Compression mode : Lossy
    Stream size : 103 MiB (18%)
    Default : Yes
    Alternate group : 1

[System Info]
CPU 0: 3192MHz, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, Intel64 Family 6 Model 158 Stepping 10
CPU 1: 3192MHz, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, Intel64 Family 6 Model 158 Stepping 10
CPU 2: 3192MHz, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, Intel64 Family 6 Model 158 Stepping 10
CPU 3: 3192MHz, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, Intel64 Family 6 Model 158 Stepping 10
CPU 4: 3192MHz, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, Intel64 Family 6 Model 158 Stepping 10
CPU 5: 3192MHz, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, Intel64 Family 6 Model 158 Stepping 10
CPU 6: 3192MHz, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, Intel64 Family 6 Model 158 Stepping 10
CPU 7: 3192MHz, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, Intel64 Family 6 Model 158 Stepping 10
CPU 8: 3192MHz, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, Intel64 Family 6 Model 158 Stepping 10
CPU 9: 3192MHz, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, Intel64 Family 6 Model 158 Stepping 10
CPU 10: 3192MHz, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, Intel64 Family 6 Model 158 Stepping 10
OS: Windows NT(Version 1955035993.194 Build 30560) Service Pack 37680.1187
Video: Radeon RX 570 Series

DirectX: 9.0c(4.09.00.0904)
Memory: All: 4,194,304 KB, Available: 4,194,304 KB, Used: 0%
CodePage: 1252, Charset:1
Instruction: MMX MMX2 SSE SSE2 SSE3 64Bits

**Comment by Nevcairiel** [comment]
- The video size is normal, renderers request such padding for better hardware access. It does not actually change the video image (no scaling)
- 4:2:2 video cannot be hardware accelerated, hence using avcodec instead of dxva2cb.
- FPS displays are a bit meaningless. Ultimately the video timestamps is what matters.

**Comment by Ding-adong** [comment]
`* The video size is normal, renderers request such padding for better hardware access. It does not actually change the video image (no scaling)`

I am not sure what you are trying to say. Scaling is done by madvr. Are you saying that the video is too small to activate dxva2cb?

` * 4:2:2 video cannot be hardware accelerated, hence using avcodec instead of dxva2cb.`

Never knew that, cheers. I tried 4:2:0 and still using avcodec.
