### ISSUE TITLE
feature request: override default ffmpeg user agent("Lavf/<version>")

### ISSUE THREAD

**Issue by dongjuanyong** [Nevcairiel/LAVFilters#274]
I opened an issue in clsid2's MPC-HC ( https://github.com/clsid2/mpc-hc/issues/91 ) about some sites blocking accesses with the default user agent used by MPC-HC. Then he told me that it was LAV Splitter which using UAs like "Lavf/58.26.101" and I found this was inherited from upstream project ffmpeg. Since ffmpeg provided an option "user_agent" to override the UA header when calling http request, is it possible to have an option in LAV Splitter to customize the UA? I found clsid2 talked about this some time before. ( https://github.com/Nevcairiel/LAVFilters/issues/199#issuecomment-381939412 )

**Comment by lifegpc** [comment]
Add support to pass custom http headers is very helpful for play some video links.
clsid2/mpc-hc#564

**Comment by ale5000-git** [comment]
It would be nice if there was an interface where the player can pass User-Agent to LAV Filters per-video (not globally).

**Comment by NothingCtrl** [comment]
Please consider support agent param in `.m3u` file, example with VLC: `#EXTVLCOPT::http-user-agent="..."`

**Comment by zhouxinghong** [comment]
+1

**Comment by zhouxinghong** [comment]
+1

**Comment by Nevcairiel** [comment]
I've added a dedicated interface to open URLs with a specified user-agent and referer for the next update
https://github.com/Nevcairiel/LAVFilters/blob/master/include/IURLSourceFilterLAV.h

**Comment by zhouxinghong** [comment]
For example: most movie channel streaming requires additional HTTP header information to be played successfully.

```
#EXTINF:0 group-title="Sport",Some Cool Name
https://some.host.it/foobar/index.m3u8|Referer="https://some.host.it/"&User-Agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)"&Origin="https://some.host.it"
```

Because some applications directly support this format, it automatically sends these required HTTP headers to the remote host.

```
mpc-hc64 --referrer="https://some.host.it/" --user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --headers="Origin: https://some.host.it" "https://some.host.it/foobar/index.m3u8"

Or

mpc-hc64 --referer="https://some.host.it/" --user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --headers="Origin: https://some.host.it" "https://some.host.it/foobar/index.m3u8"

Or

mpc-hc64 --Referrer="https://some.host.it/" --user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --headers="Origin: https://some.host.it" "https://some.host.it/foobar/index.m3u8"

Or

mpc-hc64 --Referer="https://some.host.it/" --user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --headers="Origin: https://some.host.it" "https://some.host.it/foobar/index.m3u8"
```

Please parse the above format
Parameter names that support parsing are recommended to include the following naming styles:
referrer, Referrer, referer, Referer should all be accepted.


```
test link one
https://ss191.nebuato.com/stream/A/AA/CJISq12nW9MvvHmm8934XbkngZZ96XEBSUQWF9oX/hls1080/CJISq12nW9MvvHmm8934XbkngZZ96XEBSUQWF9oX1080.m3u8

test link two
https://cdn-bgocihpmovcae3c6b49a0959a83az1b8.streamfastpro.com/621bf60fa4b05c0ab63e38087a9a1423/1/2/zoNoIGs4NfvDYO9BpUaI8Q/zoNoIGs4NfvDYO9BpUaI8Q.m3u8
```

Computer operating environment:
Windows 10 19044
This parameter setting applies to all media players that use LAVFilters for video rendering

**Comment by zhouxinghong** [comment]
![image](https://github.com/Nevcairiel/LAVFilters/assets/54253524/ff942654-21f0-4abf-95ea-4b60aee32aba)
