### ISSUE TITLE
Could not play RTSP and RTMP

### ISSUE THREAD

**Issue by tan102** [Nevcairiel/LAVFilters#275]
Play RTSP and RTMP when blocked and jammed, then crashed

**Comment by Nevcairiel** [comment]
This issue needs far more information. Unfortunately "it doesn't work" does not help me to try to fix it.

**Comment by tan102** [comment]
I tested that a good network environment is OK, the network will not work when the network is not good, for example, the network is delayed for more than 5 seconds.
