### ISSUE TITLE
Can you Add Synchronous Video Frame on Multiple Client play Same Media?

### ISSUE THREAD

**Issue by TopPlay** [Nevcairiel/LAVFilters#276]
use TCP or UDP Synchronous Decoder Same Media File,like mplayer (-udp-master -udp-ip {_networkIp} -udp-port {_masterPort} -nogui -cache 1024 -framedrop video.mp4
)

also I can write it in evr custom render!but 4K or 8K media to All video frame decoder at every client uses too much Resources!

**Comment by TopPlay** [comment]
MPlay:
Multiple instances of MPlayer can synchronize playback over a network. This is useful for creating "video walls" with multiple screens controlled by different computers. Each MPlayer instance can play a different video, but they all will try to stay at the same time offset in the file. It is recommended but not necessary to encode the video files using the same codec and parameters.
http://www.mplayerhq.hu/DOCS/HTML/en/networksync.html

**Comment by Nevcairiel** [comment]
LAV has no control over when audio or video is being output. Typically this is controlled by a reference clock, which sets the timing when renderers show frames or output  audio. LAV has no influence over this.

You could probably do this with a custom reference clock that syncs on some network time source, outside of LAV.
