### ISSUE TITLE
Audio not playing with ProRes 16ch audio files

### ISSUE THREAD

**Issue by sarek9** [Nevcairiel/LAVFilters#277]
When opening Apple ProRes files containing 16ch of audio a DirectShow warning is displayed and no audio is rendered. Audio is, to my experience, usually contained in the first two tracks though. These files are surprisingly common when receiving files from someone that has edited them in Final Cut and made a miss in the export.

Sample movie attached (audio is just low frequency hum in this file).

[16ch.sample.zip](https://github.com/Nevcairiel/LAVFilters/files/3063366/16ch.sample.zip)

**Comment by clsid2** [comment]
The file contains uncompressed audio, so no audio is being decoded. LAV Filters is working correctly.

Solution is to use a different audio renderer. Renderer and decoder are different things.

**Comment by Nevcairiel** [comment]
That is indeed the truth. You would need an audio renderer that supports 16 channel, whereelse would the audio go.
