### ISSUE TITLE
Compile favour.

### ISSUE THREAD

**Issue by Ding-adong** [Nevcairiel/LAVFilters#278]
Could some provide a compiled build of these two so i can compile lav filters. If there isn't any then compile these two for me. I can't get my head around this. Thanks in advance.

http://git.1f0.de/gitweb?p=ffmpeg.git;a=summary
http://git.1f0.de/gitweb?p=libbluray.git;a=summary

**Comment by Nevcairiel** [comment]
This is for bugs, not requests.
