### ISSUE TITLE
Script issue

### ISSUE THREAD

**Issue by DibyaTheXPFan** [Nevcairiel/LAVFilters#279]
build_ffmpeg_msvc.sh is not running with visual studio command prompt. How can I run it ? Please elaborate

**Comment by Nevcairiel** [comment]
Any scripts and the build system is provided as-is. Its really not that hard to use if you have any experience with building FFmpeg and the related environments (MSYS2, GCC, MSVC), but please understand that I cannot provide one-on-one support on how to use it.
