### ISSUE TITLE
Feature request: Get installer working with Wine?

### ISSUE THREAD

**Issue by yaomtc** [Nevcairiel/LAVFilters#280]
Steam's Proton, a custom version of Wine, can be used to launch the VR video player DeoVR. The app launches fine, except its core functionality - video playback - depends on libraries that Wine/Proton don't come with. I tried installing this in vanilla Wine and into Proton's Wine folder, but it fails at the point of registering files:

> C:\Program Files (x86)\LAV Filters\x64/LAVAudio.ax
> 
> Unable to register the DLL/OCX: RegSvr32 failed with exit code 0x3.
> 
> Click Retry to try again, Ignore to proceed anyway (not recommended), or Abort to cancel installation.

From [lavfilters-wine-output.txt](https://github.com/Nevcairiel/LAVFilters/files/3119484/lavfilters-wine-output.txt)

```
002b:err:ole:CoGetClassObject class {a2a9545d-a0c2-42b4-9708-a0b2badd77c8} not registered
002b:err:ole:CoGetClassObject no class object {a2a9545d-a0c2-42b4-9708-a0b2badd77c8} could be created for context 0x1
002b:err:ole:CoGetClassObject class {a2a9545d-a0c2-42b4-9708-a0b2badd77c8} not registered
002b:err:ole:CoGetClassObject no class object {a2a9545d-a0c2-42b4-9708-a0b2badd77c8} could be created for context 0x1
002b:err:ole:CoGetClassObject class {a2a9545d-a0c2-42b4-9708-a0b2badd77c8} not registered
002b:err:ole:CoGetClassObject no class object {a2a9545d-a0c2-42b4-9708-a0b2badd77c8} could be created for context 0x1
```

[I've also reported this to Wine just now.](https://bugs.winehq.org/show_bug.cgi?id=47075)

I will understand if this is outside the scope of your Windows project, but I figured I'd let you know.

**Comment by Nevcairiel** [comment]
I can't really support Wine, I don't even know if enough of the DirectShow infrastructure is present for this to work if you manage to install LAV itself. It typically requires a multitude of OS-provided components, which are of course available on Windows, but on Wine .. who knows.

The wine log posted above seems unrelated however, those classes are for start menu things, not sure what LAV would do with that.

**Comment by clsid2** [comment]
Adding the "32bit" and "64bit" flags in the install script for the files that need to be registered should fix this problem. Wine 4.7 fails if 32-bit regsvr32 is used for 64-bit dlls.

**Comment by marcussacana** [comment]
@Nevcairiel maybe include the regsvr32 in the next version should help a lot, you can also search for the wine_get_version function in ntdll to verify if the installer is under wine
