### ISSUE TITLE
Issue Playing Certain Files

### ISSUE THREAD

**Issue by dojima** [Nevcairiel/LAVFilters#283]
Bear with me, as I know little to nothing about how this all works, but I've noticed an issue where playback of certain files is crippled seemingly only when LAV filters are in use.  If I play [[this](https://vod-metro.twitch.tv/86ed8e8ec44bd0d3e3f8_himechar_33883912960_1186398165/chunked/0.ts)] file with MPC-BE's internal filters, it plays back normally, but if I use LAV filters, it barely plays at all.  I'm guessing it has something to do with a "malformed AAC bitstream," since FFmpeg complains about that when downloading the entire playlist of which that file is a part.  The file also plays fine when placed into a different container using FFmpeg.   Unfortunately, because MPC-BE isn't capable of handling HLS streams natively, I have to rely on LAV filters, but when I do, the streams with these malformed bitstreams are unwatchable.

Thanks for any assistance.

**Comment by lvqcl** [comment]
What version of MPC-BE and LAV filters do you use?  MPC-BE 1.5.3 plays this file fine, with or without LAV filters.

(Although... If I use MPC-BE own splitter, then I have slightly smaller pauses when seeking in this file)

**Comment by dojima** [comment]
MPC-BE 1.5.3 with 0.74.1 LAV filters.

Just to make sure I'm using them correctly, I went to 'Add Filter...' under the 'External Filters' section of MPC-BE's options and browsed for LAVSplitter.ax.  Then I set LAV Splitter and LAV Splitter Source to Prefer.  Is that correct?  After doing that, playback results in the sound playing fine, but the video is about 1 frame per 5 seconds.  Without anything specified in External Filters, the file plays as expected.

**Comment by lvqcl** [comment]
Yes, I can reproduce it, but only if I set video renderer to EVR custom presenter. It plays more or less ok with MadVR or plain EVR,  without custom presenter (that's why I didn't notice the problem earlier).

Also, if LAV Splitters are unactive, MadVR reports that the movie has 23.976 fps. When LAV Splitters are active, it says that the movie has 90090.090 fps. Oops.

**Comment by dojima** [comment]
Ah, that is interesting.  Hadn't thought to try changing the video renderer.  I'm not sure what's to blame, but I guess that's a fine workaround.

Thanks for the help.
