### ISSUE TITLE
Taiga fails to load the nyaa.si rss feed

### ISSUE THREAD

**Issue by Artins90** [Nevcairiel/LAVFilters#284]
I have been experiencing a strange issue since yesterday, the torrents tab stays empty when pressing the Check new torrents button or when triggered by the automatic timer.
The rss update seems to work only once every 20-25 tries when pressing the check button repeatedly. 
The connectivity to the the rss feed https://nyaa.si/rss?c=1_2&f=0 works fine via Chrome at the first try.  
So far I have tried to reinstall Taiga, I have emptied all the cache categories under settings and I have attempted a second install to a different drive to no avail.

I own only 1 PC so I would appreciate if someone could confirm this issue.
Thank you for your time.

**Comment by chros73** [comment]
Wrong project.

**Comment by Nevcairiel** [comment]
Indeed.  Wrong Project.

**Comment by Artins90** [comment]
This explains a lot, I couldn't find my issue report on the Taiga project.
Sorry about this mishap,, I had 2 tabs open and title aside github pages are pretty much identical.
Btw LAVFilters rocks, keep up the great work.
