### ISSUE TITLE
Audio Decoder - incorrect set Discontinuity flag

### ISSUE THREAD

**Issue by Aleksoid1978** [Nevcairiel/LAVFilters#286]
Audio Decoder - when corrected A/V sync set Discontinuity flag to packet. It's not right.
https://docs.microsoft.com/en-us/previous-versions/ms785996(v%3Dvs.85)
`The SetDiscontinuity method specifies whether this sample represents a break in the data stream.`

When A/V sync correction don't need set Discontinuity flag.

**Comment by Nevcairiel** [comment]
If A/V Synchronization has to kick-in, that means that there is a gap or an overlap in the audio data - which means that there is a break in the stream. Just what the description says.

**Comment by Aleksoid1978** [comment]
You are wrong - A/V sync not mean that is a gap or an overlap in the audio data.
I can upload sample file - it's "have" A/V sync ~every second(somebody put audio from 25fps to video 23.97 fps), but audio data is not gap.

And more - you set Discontinuity flag on packet, but new timing(after A/V correction) is setup only to the next packet.

**Comment by Aleksoid1978** [comment]
I also test with Microsoft DTV-DVD Audio Decoder - it don't set Discontinuity flag when correct A/V.

**Comment by Nevcairiel** [comment]
I've changed it so that timestamp change and discontinuity are on the same sample.

And I don't care what you believe, but as soon as that logic has to engage, it'll result in a break in the stream, and as a result nolonger be perfectly continuous. And that is a fact. Any sample that has to engage it is already broken, as it doesn't have a continous audio stream.

**Comment by Aleksoid1978** [comment]
It's drop working AudioRenderer. When a/v correct in decoder - renderer change clock but audio data is smooths. When discontinuity - renderer drop packet for old timestamp or pad silence for smooths plsyback. As result - incorrect audio output and broken sound.

**Comment by Aleksoid1978** [comment]
Here is https://yadi.sk/d/SWbz3IMPXm7BsQ - 2 sample, that "have" A/V correction on on solid data, without gaps.
