### ISSUE TITLE
bad video size when decoding HEVC

### ISSUE THREAD

**Issue by F6DZP** [Nevcairiel/LAVFilters#287]
If I want to decode HEVC elementary stream, when video size is 1920x1080, LAV video renderer gives this size, but when video size is 1240x720, when decoding, LAV video renderer says that size is 1240x960.

Thank you if you can solve this issue.

**Comment by Nevcairiel** [comment]
That is not possible. You are probably mis-interpreting some values.

**Comment by F6DZP** [comment]
Yes perhaps I do something wrong, but (for the same video to decode) when I use the Elecard HEVC video decoder or Mainconcept HEVC video decoder the pinout says that size is 1240x720, but if I just replace in the graph the Elecard HEVC video decoder by the LAV video decoder , its pinout says that size is 1240x960 ? ( so the video renderer doesn't take by default the right size).
If I am wrong, where is my mistake?
thanks

**Comment by F6DZP** [comment]
result using my software:
![HEVC decoded by Elecard](https://user-images.githubusercontent.com/26501319/58328889-c88a3780-7e22-11e9-9bf5-f1d96d7a2066.jpg)
![HEVC using LAV videodecoder_](https://user-images.githubusercontent.com/26501319/58328902-d0e27280-7e22-11e9-8b09-e0c1b403f234.jpg)

**Comment by Nevcairiel** [comment]
You should look at the other values in the media type. VIDEOINFOHEADER2 has rcSource and biWidth/biHeight, both of which convey different types of information.

**Comment by F6DZP** [comment]
result using my software:
( TS => Microsoft Mpeg2 demultiplexer  ==> Elecard HEVC video decoder ==> Video renderer (VMR9)
![HEVC decoded by Elecard_](https://user-images.githubusercontent.com/26501319/58329134-59f9a980-7e23-11e9-95d8-b41ea34c65a2.jpg)

( TS => Microsoft Mpeg2 demultiplexer  ==> LAV video decoder ==> Video renderer (VMR9)
![HEVC using LAV videodecoder_](https://user-images.githubusercontent.com/26501319/58329170-73025a80-7e23-11e9-871f-d023e572ef07.jpg)

Why I gat this difference?
thanks

**Comment by F6DZP** [comment]
I can also say that LAV video decoder gives always the good size using H264 or Mpeg2, whatever is the video size.
This strange result is only when we decode HEVC/H265 and only for specific size: 1920x1080 is well found, but 1240x720 is indicated as 1240x 960...
With the same graph, using same procedure.
Yes perhaps I am wrong, but search where?
