### ISSUE TITLE
LAV解码器，4K HEVC HDR10倍速播放会导致声音断流，画面异常等问题

### ISSUE THREAD

**Issue by 1265578519** [Nevcairiel/LAVFilters#288]
i9 9900K
64G DDR4 3200
GTX 1080TI
860 EVO 1TB SSD
potplayer 和 MPC-BE下都有这个毛病，切换播放器自带的解码器无异常。起步判断是lav出毛病了。
CPU资源占用都不高，显卡负载也非常低，排除硬件问题
解码模式用的dxva2 copy-back，挂的svp滤镜，启用倍速播放，就会复现问题，1X速度无任何毛病
用dxva2 native模式下进行倍速播放，正常，但是会引起9900K cpu百分百，进程占用99%过高问题。

概要
完整名称                                     : E:\迅雷下载\美国队长.Captain.America.The.First.Avenger.2011.2160p.UHD.BluRay.HEVC.Atmos.TrueHD.7.1-DiY\BDMV\PLAYLIST\00800.mpls
格式                                       : Blu-ray Playlist
文件大小                                     : 1.14 KiB
持续时间                                     : 2 小时 4 分
平均混合码率                                   : 1 b/s

视频
ID                                       : 4113 (0x1011)
菜单ID                                     : 1 (0x1)
格式                                       : HEVC
格式/信息                                    : High Efficiency Video Coding
格式名称                                     : HDR10
格式概况                                     : Main 10@L5.1@High
编解码器ID                                   : 36
持续时间                                     : 2 小时 4 分
码率                                       : 58.4 Mb/s
宽度                                       : 3 840 pixels
高度                                       : 2 160 pixels
画面比例                                     : 16:9
帧率                                       : 23.976 (24000/1001) FPS
色彩空间                                     : YUV
色度抽样                                     : 4:2:0 (Type 2)
位深                                       : 10 bits
数据密度【码率/(像素×帧率)】                         : 0.294
流大小                                      : 50.7 GiB
色彩范围                                     : Limited
基色                                       : BT.2020
传输特质                                     : PQ
矩阵系数                                     : BT.2020 non-constant
控制显示基色                                   : Display P3
控制显示亮度                                   : min: 0.0020 cd/m2, max: 1000 cd/m2
最大内容亮度等级                                 : 595 cd/m2
最大帧平均亮度等级                                : 494 cd/m2
format_identifier                        : HDMV
源                                        : 00294.m2ts

音频 #1
ID                                       : 4352 (0x1100)
菜单ID                                     : 1 (0x1)
格式                                       : AC-3 MLP FBA 16-ch
格式/信息                                    : Audio Coding 3 + Meridian Lossless Packing FBA with 16-channel presentation
格式名称                                     : Dolby TrueHD with Dolby Atmos
混合模式                                     : Stream extension
编解码器ID                                   : 131
持续时间                                     : 2 小时 4 分
码率模式                                     : 动态(VBR) / 恒定(CBR)
码率                                       : 640 kb/s
最大码率                                     : 7 644 kb/s
声道                                       : 8 channels / 6 channels
Channel layout                           : L R C LFE Ls Rs Lb Rb
采样率                                      : 48.0 kHz
帧率                                       : 31.250 FPS (1536 SPF)
位深                                       : 16 bits
压缩模式                                     : 有损压缩
流大小                                      : 568 MiB
语言                                       : 英语 (English)
服务类别                                     : Complete Main
Number of dynamic objects                : 13
Bed channel count                        : 1
Bed channel count                        : 1 channel
Bed channel configuration                : LFE
bsid                                     : 6
dialnorm                                 : -27
dialnorm                                 : -27 dB
compr                                    : -0.28
compr                                    : -0.28 dB
dynrng                                   : -0.14
dynrng                                   : -0.14 dB
acmod                                    : 7
lfeon                                    : 1
dialnorm_Average                         : -27
dialnorm_Average                         : -27 dB
dialnorm_Minimum                         : -27
dialnorm_Minimum                         : -27 dB
dialnorm_Maximum                         : -27
dialnorm_Maximum                         : -27 dB
dialnorm_Count                           : 676
compr_Average                            : 5.50
compr_Average                            : 5.50 dB
compr_Minimum                            : 0.53
compr_Minimum                            : 0.53 dB
compr_Maximum                            : 6.02
compr_Maximum                            : 6.02 dB
compr_Count                              : 673
dynrng_Average                           : 5.64
dynrng_Average                           : 5.64 dB
dynrng_Minimum                           : 0.27
dynrng_Minimum                           : 0.27 dB
dynrng_Maximum                           : 6.02
dynrng_Maximum                           : 6.02 dB
dynrng_Count                             : 675
format_identifier                        : AC-3
源                                        : 00294.m2ts

音频 #2
ID                                       : 4353 (0x1101)
菜单ID                                     : 1 (0x1)
格式                                       : AC-3
格式/信息                                    : Audio Coding 3
格式名称                                     : Dolby Digital
编解码器ID                                   : 129
持续时间                                     : 2 小时 4 分
码率模式                                     : 恒定(CBR)
码率                                       : 320 kb/s
声道                                       : 2 channels
Channel layout                           : L R
采样率                                      : 48.0 kHz
帧率                                       : 31.250 FPS (1536 SPF)
位深                                       : 16 bits
压缩模式                                     : 有损压缩
流大小                                      : 284 MiB
语言                                       : 英语 (English)
服务类别                                     : Complete Main
bsid                                     : 6
dialnorm                                 : -27
dialnorm                                 : -27 dB
compr                                    : 0.53
compr                                    : 0.53 dB
dynrng                                   : 0.78
dynrng                                   : 0.78 dB
dsurmod                                  : 1
dsurmod                                  : Not Dolby Surround encoded
acmod                                    : 2
lfeon                                    : 0
dialnorm_Average                         : -27
dialnorm_Average                         : -27 dB
dialnorm_Minimum                         : -27
dialnorm_Minimum                         : -27 dB
dialnorm_Maximum                         : -27
dialnorm_Maximum                         : -27 dB
dialnorm_Count                           : 677
compr_Average                            : 4.55
compr_Average                            : 4.55 dB
compr_Minimum                            : 0.53
compr_Minimum                            : 0.53 dB
compr_Maximum                            : 6.02
compr_Maximum                            : 6.02 dB
compr_Count                              : 526
dynrng_Average                           : 3.88
dynrng_Average                           : 3.88 dB
dynrng_Minimum                           : 0.00
dynrng_Minimum                           : 0.00 dB
dynrng_Maximum                           : 6.02
dynrng_Maximum                           : 6.02 dB
dynrng_Count                             : 677
format_identifier                        : AC-3
源                                        : 00294.m2ts

音频 #3
ID                                       : 4354 (0x1102)
菜单ID                                     : 1 (0x1)
格式                                       : AC-3
格式/信息                                    : Audio Coding 3
格式名称                                     : Dolby Digital
编解码器ID                                   : 129
持续时间                                     : 2 小时 4 分
码率模式                                     : 恒定(CBR)
码率                                       : 640 kb/s
声道                                       : 6 channels
Channel layout                           : L R C LFE Ls Rs
采样率                                      : 48.0 kHz
帧率                                       : 31.250 FPS (1536 SPF)
位深                                       : 16 bits
压缩模式                                     : 有损压缩
流大小                                      : 568 MiB
语言                                       : 法语 (French)
服务类别                                     : Complete Main
bsid                                     : 6
dialnorm                                 : -27
dialnorm                                 : -27 dB
compr                                    : -0.28
compr                                    : -0.28 dB
dynrng                                   : -0.14
dynrng                                   : -0.14 dB
acmod                                    : 7
lfeon                                    : 1
dialnorm_Average                         : -27
dialnorm_Average                         : -27 dB
dialnorm_Minimum                         : -27
dialnorm_Minimum                         : -27 dB
dialnorm_Maximum                         : -27
dialnorm_Maximum                         : -27 dB
dialnorm_Count                           : 676
compr_Average                            : 5.30
compr_Average                            : 5.30 dB
compr_Minimum                            : 0.53
compr_Minimum                            : 0.53 dB
compr_Maximum                            : 6.02
compr_Maximum                            : 6.02 dB
compr_Count                              : 673
dynrng_Average                           : 5.62
dynrng_Average                           : 5.62 dB
dynrng_Minimum                           : 0.27
dynrng_Minimum                           : 0.27 dB
dynrng_Maximum                           : 6.02
dynrng_Maximum                           : 6.02 dB
dynrng_Count                             : 675
format_identifier                        : AC-3
源                                        : 00294.m2ts

音频 #4
ID                                       : 4355 (0x1103)
菜单ID                                     : 1 (0x1)
格式                                       : E-AC-3
格式/信息                                    : Enhanced AC-3
格式名称                                     : Dolby Digital Plus
格式概况                                     : Blu-ray Disc
混合模式                                     : Stream extension
编解码器ID                                   : 132
持续时间                                     : 2 小时 4 分
码率模式                                     : 恒定(CBR)
码率                                       : 1 024 kb/s
声道                                       : 8 channels / 6 channels
Channel layout                           : L R C LFE Ls Rs Lb Rb / L R C LFE Ls Rs
采样率                                      : 48.0 kHz
帧率                                       : 31.250 FPS (1536 SPF)
压缩模式                                     : 有损压缩
流大小                                      : 909 MiB
语言                                       : 法语 (French)
服务类别                                     : Complete Main
bsid                                     : 16
dialnorm                                 : -27
dialnorm                                 : -27 dB
compr                                    : -2.87
compr                                    : -2.87 dB
acmod                                    : 7 / 5
lfeon                                    : 1 / 0
dialnorm_Average                         : -27
dialnorm_Average                         : -27 dB
dialnorm_Minimum                         : -27
dialnorm_Minimum                         : -27 dB
dialnorm_Maximum                         : -27
dialnorm_Maximum                         : -27 dB
dialnorm_Count                           : 1355
compr_Average                            : 5.32
compr_Average                            : 5.32 dB
compr_Minimum                            : -2.87
compr_Minimum                            : -2.87 dB
compr_Maximum                            : 6.02
compr_Maximum                            : 6.02 dB
compr_Count                              : 1347
dynrng_Average                           : 3.60
dynrng_Average                           : 3.60 dB
dynrng_Minimum                           : -2.32
dynrng_Minimum                           : -2.32 dB
dynrng_Maximum                           : 6.02
dynrng_Maximum                           : 6.02 dB
dynrng_Count                             : 1355
format_identifier                        : AC-3
源                                        : 00294.m2ts

音频 #5
ID                                       : 4356 (0x1104)
菜单ID                                     : 1 (0x1)
格式                                       : E-AC-3
格式/信息                                    : Enhanced AC-3
格式名称                                     : Dolby Digital Plus
格式概况                                     : Blu-ray Disc
混合模式                                     : Stream extension
编解码器ID                                   : 132
持续时间                                     : 2 小时 4 分
码率模式                                     : 恒定(CBR)
码率                                       : 1 024 kb/s
声道                                       : 8 channels / 6 channels
Channel layout                           : L R C LFE Ls Rs Lb Rb / L R C LFE Ls Rs
采样率                                      : 48.0 kHz
帧率                                       : 31.250 FPS (1536 SPF)
压缩模式                                     : 有损压缩
流大小                                      : 909 MiB
语言                                       : 西班牙语 (Spanish)
服务类别                                     : Complete Main
bsid                                     : 16
dialnorm                                 : -27
dialnorm                                 : -27 dB
compr                                    : -2.50
compr                                    : -2.50 dB
acmod                                    : 7 / 5
lfeon                                    : 1 / 0
dialnorm_Average                         : -27
dialnorm_Average                         : -27 dB
dialnorm_Minimum                         : -27
dialnorm_Minimum                         : -27 dB
dialnorm_Maximum                         : -27
dialnorm_Maximum                         : -27 dB
dialnorm_Count                           : 1355
compr_Average                            : 5.32
compr_Average                            : 5.32 dB
compr_Minimum                            : -2.50
compr_Minimum                            : -2.50 dB
compr_Maximum                            : 6.02
compr_Maximum                            : 6.02 dB
compr_Count                              : 1347
dynrng_Average                           : 3.61
dynrng_Average                           : 3.61 dB
dynrng_Minimum                           : -1.97
dynrng_Minimum                           : -1.97 dB
dynrng_Maximum                           : 6.02
dynrng_Maximum                           : 6.02 dB
dynrng_Count                             : 1354
format_identifier                        : AC-3
源                                        : 00294.m2ts

音频 #6
ID                                       : 4357 (0x1105)
菜单ID                                     : 1 (0x1)
格式                                       : E-AC-3
格式/信息                                    : Enhanced AC-3
格式名称                                     : Dolby Digital Plus
格式概况                                     : Blu-ray Disc
混合模式                                     : Stream extension
编解码器ID                                   : 132
持续时间                                     : 2 小时 4 分
码率模式                                     : 恒定(CBR)
码率                                       : 1 024 kb/s
声道                                       : 8 channels / 6 channels
Channel layout                           : L R C LFE Ls Rs Lb Rb / L R C LFE Ls Rs
采样率                                      : 48.0 kHz
帧率                                       : 31.250 FPS (1536 SPF)
压缩模式                                     : 有损压缩
流大小                                      : 909 MiB
语言                                       : 德语 (German)
服务类别                                     : Complete Main
bsid                                     : 16
dialnorm                                 : -27
dialnorm                                 : -27 dB
compr                                    : -2.50
compr                                    : -2.50 dB
acmod                                    : 7 / 5
lfeon                                    : 1 / 0
dialnorm_Average                         : -27
dialnorm_Average                         : -27 dB
dialnorm_Minimum                         : -27
dialnorm_Minimum                         : -27 dB
dialnorm_Maximum                         : -27
dialnorm_Maximum                         : -27 dB
dialnorm_Count                           : 1355
compr_Average                            : 5.29
compr_Average                            : 5.29 dB
compr_Minimum                            : -2.50
compr_Minimum                            : -2.50 dB
compr_Maximum                            : 6.02
compr_Maximum                            : 6.02 dB
compr_Count                              : 1347
dynrng_Average                           : 3.61
dynrng_Average                           : 3.61 dB
dynrng_Minimum                           : -1.97
dynrng_Minimum                           : -1.97 dB
dynrng_Maximum                           : 6.02
dynrng_Maximum                           : 6.02 dB
dynrng_Count                             : 1354
format_identifier                        : AC-3
源                                        : 00294.m2ts

音频 #7
ID                                       : 4358 (0x1106)
菜单ID                                     : 1 (0x1)
格式                                       : E-AC-3
格式/信息                                    : Enhanced AC-3
格式名称                                     : Dolby Digital Plus
格式概况                                     : Blu-ray Disc
混合模式                                     : Stream extension
编解码器ID                                   : 132
持续时间                                     : 2 小时 4 分
码率模式                                     : 恒定(CBR)
码率                                       : 1 024 kb/s
声道                                       : 8 channels / 6 channels
Channel layout                           : L R C LFE Ls Rs Lb Rb / L R C LFE Ls Rs
采样率                                      : 48.0 kHz
帧率                                       : 31.250 FPS (1536 SPF)
压缩模式                                     : 有损压缩
流大小                                      : 909 MiB
语言                                       : 义大利语 (Italian)
服务类别                                     : Complete Main
bsid                                     : 16
dialnorm                                 : -27
dialnorm                                 : -27 dB
compr                                    : -2.50
compr                                    : -2.50 dB
acmod                                    : 7 / 5
lfeon                                    : 1 / 0
dialnorm_Average                         : -27
dialnorm_Average                         : -27 dB
dialnorm_Minimum                         : -27
dialnorm_Minimum                         : -27 dB
dialnorm_Maximum                         : -27
dialnorm_Maximum                         : -27 dB
dialnorm_Count                           : 1295
compr_Average                            : 5.27
compr_Average                            : 5.27 dB
compr_Minimum                            : -2.50
compr_Minimum                            : -2.50 dB
compr_Maximum                            : 6.02
compr_Maximum                            : 6.02 dB
compr_Count                              : 1287
dynrng_Average                           : 3.58
dynrng_Average                           : 3.58 dB
dynrng_Minimum                           : -1.97
dynrng_Minimum                           : -1.97 dB
dynrng_Maximum                           : 6.02
dynrng_Maximum                           : 6.02 dB
dynrng_Count                             : 1294
format_identifier                        : AC-3
源                                        : 00294.m2ts

音频 #8
ID                                       : 4359 (0x1107)
菜单ID                                     : 1 (0x1)
格式                                       : E-AC-3
格式/信息                                    : Enhanced AC-3
格式名称                                     : Dolby Digital Plus
格式概况                                     : Blu-ray Disc
混合模式                                     : Stream extension
编解码器ID                                   : 132
持续时间                                     : 2 小时 4 分
码率模式                                     : 恒定(CBR)
码率                                       : 1 024 kb/s
声道                                       : 8 channels / 6 channels
Channel layout                           : L R C LFE Ls Rs Lb Rb / L R C LFE Ls Rs
采样率                                      : 48.0 kHz
帧率                                       : 31.250 FPS (1536 SPF)
压缩模式                                     : 有损压缩
流大小                                      : 909 MiB
语言                                       : 日语 (Japanese)
服务类别                                     : Complete Main
bsid                                     : 16
dialnorm                                 : -27
dialnorm                                 : -27 dB
compr                                    : -2.50
compr                                    : -2.50 dB
acmod                                    : 7 / 5
lfeon                                    : 1 / 0
dialnorm_Average                         : -27
dialnorm_Average                         : -27 dB
dialnorm_Minimum                         : -27
dialnorm_Minimum                         : -27 dB
dialnorm_Maximum                         : -27
dialnorm_Maximum                         : -27 dB
dialnorm_Count                           : 1355
compr_Average                            : 5.32
compr_Average                            : 5.32 dB
compr_Minimum                            : -2.50
compr_Minimum                            : -2.50 dB
compr_Maximum                            : 6.02
compr_Maximum                            : 6.02 dB
compr_Count                              : 1347
dynrng_Average                           : 3.61
dynrng_Average                           : 3.61 dB
dynrng_Minimum                           : -1.97
dynrng_Minimum                           : -1.97 dB
dynrng_Maximum                           : 6.02
dynrng_Maximum                           : 6.02 dB
dynrng_Count                             : 1354
format_identifier                        : AC-3
源                                        : 00294.m2ts

文本 #1
ID                                       : 4768 (0x12A0)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 英语 (English)
源                                        : 00294.m2ts

文本 #2
ID                                       : 4769 (0x12A1)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 法语 (French)
源                                        : 00294.m2ts

文本 #3
ID                                       : 4770 (0x12A2)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 法语 (French)
源                                        : 00294.m2ts

文本 #4
ID                                       : 4771 (0x12A3)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 西班牙语 (Spanish)
源                                        : 00294.m2ts

文本 #5
ID                                       : 4772 (0x12A4)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 德语 (German)
源                                        : 00294.m2ts

文本 #6
ID                                       : 4773 (0x12A5)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 义大利语 (Italian)
源                                        : 00294.m2ts

文本 #7
ID                                       : 4774 (0x12A6)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 日语 (Japanese)
源                                        : 00294.m2ts

文本 #8
ID                                       : 4775 (0x12A7)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 挪威语 (Norwegian)
源                                        : 00294.m2ts

文本 #9
ID                                       : 4776 (0x12A8)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 瑞典语 (Swedish)
源                                        : 00294.m2ts

文本 #10
ID                                       : 4777 (0x12A9)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 英语 (English)
源                                        : 00294.m2ts

文本 #11
ID                                       : 4778 (0x12AA)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 法语 (French)
源                                        : 00294.m2ts

文本 #12
ID                                       : 4779 (0x12AB)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 法语 (French)
源                                        : 00294.m2ts

文本 #13
ID                                       : 4780 (0x12AC)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 西班牙语 (Spanish)
源                                        : 00294.m2ts

文本 #14
ID                                       : 4781 (0x12AD)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 德语 (German)
源                                        : 00294.m2ts

文本 #15
ID                                       : 4782 (0x12AE)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 义大利语 (Italian)
源                                        : 00294.m2ts

文本 #16
ID                                       : 4783 (0x12AF)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 日语 (Japanese)
源                                        : 00294.m2ts

文本 #17
ID                                       : 4784 (0x12B0)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 中文 (Chinese)
源                                        : 00294.m2ts

文本 #18
ID                                       : 4785 (0x12B1)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 中文 (Chinese)
源                                        : 00294.m2ts

文本 #19
ID                                       : 4786 (0x12B2)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 中文 (Chinese)
源                                        : 00294.m2ts

文本 #20
ID                                       : 4787 (0x12B3)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 中文 (Chinese)
源                                        : 00294.m2ts

文本 #21
ID                                       : 4788 (0x12B4)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 中文 (Chinese)
源                                        : 00294.m2ts

文本 #22
ID                                       : 4789 (0x12B5)
菜单ID                                     : 1 (0x1)
格式                                       : PGS
编解码器ID                                   : 144
持续时间                                     : 2 小时 4 分
语言                                       : 中文 (Chinese)
源                                        : 00294.m2ts

菜单
00:00:00.000                             : Chapter 1
00:08:11.949                             : Chapter 2
00:08:12.033                             : Chapter 3
00:14:56.562                             : Chapter 4
00:14:56.645                             : Chapter 5
00:24:21.293                             : Chapter 6
00:24:21.376                             : Chapter 7
00:30:38.878                             : Chapter 8
00:30:38.962                             : Chapter 9
00:38:39.608                             : Chapter 10
00:38:39.692                             : Chapter 11
00:45:51.915                             : Chapter 12
00:45:51.999                             : Chapter 13
00:51:57.906                             : Chapter 14
00:51:57.989                             : Chapter 15
00:57:55.388                             : Chapter 16
00:57:55.472                             : Chapter 17
01:03:59.085                             : Chapter 18
01:03:59.168                             : Chapter 19
01:12:22.379                             : Chapter 20
01:12:22.463                             : Chapter 21
01:19:10.412                             : Chapter 22
01:19:10.495                             : Chapter 23
01:28:26.801                             : Chapter 24
01:28:26.884                             : Chapter 25
01:33:52.752                             : Chapter 26
01:33:52.835                             : Chapter 27
01:42:20.092                             : Chapter 28
01:42:20.175                             : Chapter 29
01:50:44.804                             : Chapter 30
01:50:44.888                             : Chapter 31
01:53:46.069                             : Chapter 32
01:53:46.152                             : Chapter 33
02:04:09.900                             : Chapter 34
02:04:09.984                             : Chapter 35

**Comment by Nevcairiel** [comment]
Bug reports must be submitted in English. I cannot read anything else.
