### ISSUE TITLE
LAV filters can't play some VP9 8K video in fluid HW accelerated mode.

### ISSUE THREAD

**Issue by Cumberiron** [Nevcairiel/LAVFilters#289]
Hello guys!

LAV filters can't play some VP9 8K video in fluid HW accelerated CUVID mode, It can play only in DXVA mode.  When I chose DXVA decoding, than I can play 8K VP9 without problem, but LAV DXVA mode is not good for some 10bit HEVC 4:4:4 NVENCC (Rigaya) created video, because it reverted to SW playing.. Despite the new Turing-based cards have this feature.

See NVDEC support matrix on the official page of NVIDIA: https://developer.nvidia.com/video-encode-decode-gpu-support-matrix

VLC media player (with its own codecs) play it with HW accelerated way without any problem.
Lav filters has serious problems with it.

Can you allow it for Turing cards  (RTX cards and GTX 1660 series)

Here you can download the 8K VP9 sample video here: (132 MB) https://sendgb.com/dFSZ9g8Ty6V

You can download the NVENCC 10bit HEVC 4:4:4 1080p video here: 
https://sendgb.com/iCF2cmp0EZl  (58 Mbyte)

Thank you for your reply and help!

**Comment by Nevcairiel** [comment]
DXVA is more efficient then CUVID, there is likely nothing that can be done.

**Comment by Nevcairiel** [comment]
For that matter, CUVID in LAV does also not support 4:4:4 decoding.

**Comment by Cumberiron** [comment]
Hello Nevcairiel!

DXVA is not more efficient in the new Turing cards, maybe around the same. DXVA **was** really more efficient in the era of Pasal and earlier Geforce cards.

ButCUVID can support 4:4:4 HW decoding (for example the internal ffmpeg based CUVID in the Potplayer can play this video with HW acceleration.

So if they could do it, it means that it is possible!

Thank you for your reply!

Best regards!

Alexander

**Comment by Nevcairiel** [comment]
This has nothing to do with GPU generation. DXVA2-Native or D3D11-Native is **always** going to be more efficient then CUVID could ever be. This can make a huge difference if you play something like 8K.

**Comment by Cumberiron** [comment]
Dear Nevcairiel!

Go to the other topic?
What is the problem with cuvid based 4:4:4 HW HEVC decoding? Since the Nvidia made the NVDEC chip for that.
If ffmpeg version of CUVID could do it, than you can do it too, Don't you? You enough clever guys in this field.

Thank you for your reply!

Best regards!

Alexander

**Comment by Nevcairiel** [comment]
I'm not currently interested in further development of the CUVID decoder at this time, because D3D11 is just far more efficient. Besides, HEVC 4:4:4 content basically does not exist.

Maybe I might replace it with a NVDEC encoder in the future, but not now.

**Comment by Cumberiron** [comment]
Since Nvidia introduced the HW 4:4:4 compression, it exist. It is better to compress 4:2:0 videos in 4:4:4 10bit HEVC than compress them in 4:2:0. Yes you will say that the color space trasformation is a loss, but the HEVC 4:4:4: compression is more efficient, so finally looks much better than the 4:2:0 compression.
