### ISSUE TITLE
problem decoding some videos in dxva2n mode (dxva2cb and cuvid work fine)

### ISSUE THREAD

**Issue by F1ReB4LL** [Nevcairiel/LAVFilters#291]
Basically, the issue looks somewhat similar to the closed #64 one (though, the result looks way worse than there), but I'm using the 0.74.1 version.

dxva2n
![dxva2n](https://user-images.githubusercontent.com/39680140/58887214-e3e02700-86ed-11e9-8112-c7b1000b1598.png)
dxvac2b
![dxvac2b](https://user-images.githubusercontent.com/39680140/58887230-e93d7180-86ed-11e9-8f1d-7a600fda549d.png)
cuvid
![cuvid](https://user-images.githubusercontent.com/39680140/58887241-ee022580-86ed-11e9-9417-da66a1a413ec.png)

https://www.sendspace.com/file/7twcvy -- the video itself (it's from youtube, so, should be more or less legal to share, I guess).

**Comment by chros73** [comment]
Have you tested it with d3d11? Yesterday I saw similar issues sometimes with hevc content (although I'm not sure whether it was in the source or not).

**Comment by F1ReB4LL** [comment]
Yes, it switches to avcodec in D3D11 and no problems there.
Btw, certain H.264 videos are always played with avcodec regardless of the selected decoder, is it the correct behavior?

![avcodec](https://user-images.githubusercontent.com/39680140/58893415-cc5a6b80-86f8-11e9-8c37-77c4cfc306eb.png)

**Comment by clsid2** [comment]
This file plays correctly with dxva2n here on an NVIDIA GPU. So might be a driver issue on your side.

Not all H.264 can be hardware decoded. For example 10-bit video can not.

**Comment by F1ReB4LL** [comment]
> This file plays correctly with dxva2n here on an NVIDIA GPU. So might be a driver issue on your side.

Weird. I was on 430.64, now reverted to 398.11 - no change.

**Comment by Nevcairiel** [comment]
Which player are you using? Its certainly possible the renderer is just mis-handling the DXVA2 image.

**Comment by F1ReB4LL** [comment]
https://github.com/clsid2/mpc-hc/releases/tag/1.8.6 - this one (x64 build).

**Comment by F1ReB4LL** [comment]
> This file plays correctly with dxva2n here on an NVIDIA GPU. So might be a driver issue on your side.

Yeah, it seems the problem is deeper. I've uninstalled LAVFilters completely, installed good old CoreAVC and:

![coreavc_cuda](https://user-images.githubusercontent.com/39680140/59552497-6b505480-8f90-11e9-819a-eda686f3ba2a.png)

![coreavc_dxva](https://user-images.githubusercontent.com/39680140/59552500-72776280-8f90-11e9-9937-670ea1edaa2c.png)

The fun thing is that right now it's the only problematic video I can find (there were a couple of others, but they were only glitching in older versions of LAVFilters, not in the latest one). Is there anything in it that makes it so special, some unusual flag or something?

**Comment by F1ReB4LL** [comment]
Aha! Found the problem! This happens when the "Noise Reduction" setting is enabled in the NVidia Control Panel :)

**Comment by Nevcairiel** [comment]
Interesting. Such options can mess with the decoding, but I've never seen it cause this kind of issue. Anyway mystery solved.
