### ISSUE TITLE
MSVC Build Mising zlib.h

### ISSUE THREAD

**Issue by sirhaden** [Nevcairiel/LAVFilters#293]
Cannon compile the msvc build using MSYS or MSYS2 with MinGW.  The MSVC toolkit does not cross-compile zlib.  Adding the --disable-zlib flag has no effect.

**Comment by Nevcairiel** [comment]
zlib.h is required. You need to provide it.
Please don't report the same issue multiple times. This is not a bug, its quite simply required.

**Comment by sirhaden** [comment]
It was provided, and it won’t build due to use of the msvc toolchain…
