### ISSUE TITLE
H265 Files Not Playing Properly

### ISSUE THREAD

**Issue by timeakesmarky** [Nevcairiel/LAVFilters#295]
Here is a sample file. It plays as though the speed has been reduced to 0.1x
https://drive.google.com/open?id=1cAjIbb8v8qWNrp5RdJGPJOVnhlksT1qP

I'm using GOM Player (x64) with LAV Video Filters (x64). Some files play with 0.1x speed.
OS: Windows 10 Enterprise LTSC x64
Processor: i7 7700HQ and Nvidia 1050

**Comment by iAM261917** [comment]
I think that just something wrong on your side, not LAV.
Because there's no problem with my player, using PotPlayer. LAV Video, LAV Audio and madVR.

**Comment by timeakesmarky** [comment]
Are you sure? I have contacted gom company regarding this. Let me see what they have to say.

**Comment by timeakesmarky** [comment]
I got a response from Gom player team and they had the file playing smoothly with LAV filters.

But the problem is still with LAV Filters. Finally I found the cause of the problem. This issue occurs when I use NVIDIA CUVID as the decoder from Lav video settings. I hope this can be fixed.

**Comment by Nevcairiel** [comment]
CUVID is deprecated. It'll not get fixes. Use any of the others.

**Comment by timeakesmarky** [comment]
Oh ok. I didn't know.
