### ISSUE TITLE
No sound bitstream dts-ma on MPC LAV Audio codec

### ISSUE THREAD

**Issue by Petterhisc** [Nevcairiel/LAVFilters#296]
Hello

I have installed MPC (64bit) latest version and installed LAV splitter, audio and video in the external filter 0.74.1. 
The TrueHD format works great but the dts-ma does not.
When selecting a movie with dts-ma soundtrack the receiver recognizes the format but the dts light "blinks and twitches" and there is no sound.

I followed this guide https://www.youtube.com/watch?v=3o_TlYVnyG4

Hope there is an easy fix to this :)

Thanks for replies.

**Comment by Nevcairiel** [comment]
Don't use Haali anymore, it's years out of date. Try with LAV splitter

**Comment by Petterhisc** [comment]
Still the same problem with LAV Splitter, the dts-ma just blinks.
Could the problem be that MPC is 64 bit?

**Comment by Petterhisc** [comment]
I think the mistake I made was not installing the LAV Filters installer and pointing the MPC to the updated filters. I just pointed the MPC at the .ax files in the LAV folder, this worked for TrueHD but not for dts-ma.
The problem is now solved.

**Comment by clsid2** [comment]
You actually also are not using latest version of MPC-HC.
https://github.com/clsid2/mpc-hc/releases

**Comment by ValZapod** [comment]
@Petterhisc You **actually** should use https://www.codecguide.com/
Because it updates both LAV and MPC-HC.
