### ISSUE TITLE
LAVFilters 0.74.1 Dolby True HD issue

### ISSUE THREAD

**Issue by actualfredsmith** [Nevcairiel/LAVFilters#297]
Stuttering and distortion on some Dolby True HD audio tracks (for example Celine Dion's A New Day concert) with LAVFilters 0.74.1. Going back to LAVFilters 0.73.1 solves problem.

**Comment by Nevcairiel** [comment]
Try with the latest nightly version from here https://files.1f0.de/lavf/nightly/ - there were some fixes for badly authored TrueHD discs.

**Comment by actualfredsmith** [comment]
Thanks. Tried:
LAVFilters-0.74.1-18.exe  
LAVFilters-0.74.1-20.exe
Problem not fixed. Again gone back to 0.73.1 and all good.

**Comment by Nevcairiel** [comment]
Is this from an original Blu-ray disc, not a rip? Rips can be broken or done with bad tools.

**Comment by actualfredsmith** [comment]
Good point. It's a rip. 
I'll stick with older LAVFilters for time being as they work fine.
