### ISSUE TITLE
Support for MPD manifests

### ISSUE THREAD

**Issue by 3dyd** [Nevcairiel/LAVFilters#305]
MPD manifests describing fragmented DASH streams are supported by ffmpeg. It would be great to have support for them in LAV Splitter.

`dash` demuxer must be enabled to achieve this. As far as I understand it gets implicitly added to demuxers only with this `./configure` option:
```
  --enable-libxml2         enable XML parsing using the C library libxml2, needed
                           for dash demuxing support [no]
```

**Comment by clsid2** [comment]
Yes, this would be useful for streaming video playback using youtube-dl and MPC-HC. Currently these DASH streams need to be ignored due to the lack of playback support.

**Comment by Nevcairiel** [comment]
This should now be supported.
