### ISSUE TITLE
HLS playback problem after seeking to the beginning

### ISSUE THREAD

**Issue by 3dyd** [Nevcairiel/LAVFilters#306]
How to reproduce: start HLS stream playback, then seek to zero position (`SetPositions(0, Absolute,..)`). Video and audio stops delivering.

I tracked it down to this code:
```
STDMETHODIMP CLAVFDemuxer::Seek(REFERENCE_TIME rTime)
{
  int seekStreamId = m_dActiveStreams[video];
  int64_t seek_pts = 0;
retry:
  // If we have a video stream, seek on that one. If we don't, well, then don't!
  if (rTime > 0) {
    if (seekStreamId != -1) {
      AVStream *stream = m_avFormat->streams[seekStreamId];
      seek_pts = ConvertRTToTimestamp(rTime, stream->time_base.num, stream->time_base.den);
    } else {
      seek_pts = ConvertRTToTimestamp(rTime, 1, AV_TIME_BASE);
    }
  }
```
`rTime` is zero so `seek_pts` stays zero as well, but in current case `ConvertRTToTimestamp` would return nonzero value because `m_avFormat->start_time` is nonzero.

Removing `if (rTime > 0)` statement fixes this issue though I am not sure if this is sufficient since this check was explicitly added in 9fbf56df5b1c5cc3e9fb4ad46f5164148d9efd95.

HLS example I was given: [link](http://cache11.tvigle.ru/28/hls/2018/08/31/a6c1e896-5ad9-4eac-b366-fe4fc3694247.mp4/index-v1-a1.m3u8?expire=1566897639&key=6BpZqJWIrLY6ZqKxsZQc_g&video_id=5737107&owner_id=24&pad_id=0&slink=v2&quality=). Not sure if it is permanent so you can also get it via `youtube-dl -J https://www.tvigle.ru/video/chiko-i-rita/`

**Comment by SlazE888** [comment]
I'm noticed that these video examples also have issues after seeking through "LAV Splitter Source". To reproduce- try to did LeftMouseButton click on any place of timeline in GraphStudio and you can see endless stuttering playback:
[http://tvpro-online.ru/data/video/files/301_file.mp4](url)
[http://tvpro-online.ru/data/video/files/290_file.mp4](url)

**Comment by Nevcairiel** [comment]
This should be resolved now.

**Comment by clsid2** [comment]
Removing the `(rTime > 0)` check also solved this issue. Are there any situations where we do want to seek to pts zero and ignore value of start_time?

**Comment by ale5000-git** [comment]
@Nevcairiel
A thing to note: in the original change [here](https://github.com/Nevcairiel/LAVFilters/commit/9fbf56df5b1c5cc3e9fb4ad46f5164148d9efd95) there wasn't the **retry** label and the original change was:
`int64_t seek_pts = 0; if (rTime > 0) { ... }`
so when **rTime** was 0 it was actually settings **seek_pts = 0** (since it was default value) without calling **ConvertRTToTimestamp**; but now with **retry** label the behaviour is changed and it doesn't set 0 when passing from **retry**.

**Comment by Nevcairiel** [comment]
rTime is constant in that function, if its zero in the first try, then its still zero at the second try, and seek_pts would always be zero, and if rTime is greater then zero, seek_pts is set accordingly in both the normal and the retry case.

**Comment by SlazE888** [comment]
> This should be resolved now.
Fixed in LAVFilters_v0.74.1-98. Many thanks Nev!
