### ISSUE TITLE
LAV Splitter cannot demux MP4 files with MPEG-2 video created by MP4Box

### ISSUE THREAD

**Issue by filler56789** [Nevcairiel/LAVFilters#307]
On the other hand, it accepts the files created by FFmpeg. Surely that's a regression because the few MP4 files containing MPEG-2 video that I had created with MP4Box used to open normally in MPC-HC.

Sample files: http://www.mediafire.com/file/5oyqn0056fg28ek/Matsuoka-Riko-MP4s-samples.zip/file

P.S.: recent MPlayer opens them and decodes them, but with some errors. But if I use the switch "-demuxer lavf" it fails.

**Comment by filler56789** [comment]
Update: LAV Splitter v0.69.0.76 works as expected.

**Comment by filler56789** [comment]
UPDATE 2:
actually the last working version is 0.70.2.88.

**Comment by Nevcairiel** [comment]
Fixed
