### ISSUE TITLE
Can't DXVA2(copy-back) and D3D11 Native on MPEG2 High Profile.

### ISSUE THREAD

**Issue by Aleksoid1978** [Nevcairiel/LAVFilters#308]
Sample - https://yadi.sk/i/tHeBjqFbRRHcyA
DXVA2 Native working good.
1) The reason is that ffmpeg when opened MPEG1/2 don't read/parse extradata and don't fill level/profile/pix_fmt. But when use DXVA2(copy-back) or D3D11 Native - init decoder(second time) after decode first frame and profile is fill(FF_PROFILE_MPEG2_HIGH value) and decoder reject using H/W decoder.

MPEG2 High Profile normally is decoding using H/W, why you reject it ?

**Comment by Aleksoid1978** [comment]
2. D3D11 Native after reject - Video Renderer(madVR as example) can't working and handle data from decoder. The reason is that the decoder does not report in any way that switch to software decoding mode and VR think that using D3D11 native and reject calling ::GetAllocator().

**Comment by Aleksoid1978** [comment]
Any progress ?

**Comment by Nevcairiel** [comment]
MPEG-2 High Profile is not included in the DXVA2 MPEG-2 specification, therefor there are no guarantees that any given hardware can decode it - and High profile is also rather rare, so I don't feel like violating the specification for something that practically doesnt exist anyway.
