### ISSUE TITLE
Hardware acceleration for some videos not working from version 0.71.x to newest version

### ISSUE THREAD

**Issue by cshong87** [Nevcairiel/LAVFilters#311]
Sample video: https://drive.google.com/open?id=12OcJL7XZOsAUA48DU08Cfbsqe9j9LsYT

Please download the video instead of playing it inside the web browser.

This video was recorded by using my smartphone.

Here are the video information:

Format                         : MPEG-4
Format profile                 : Base Media / Version 2
Codec ID                       : mp42 (isom/mp42)
File size                      : 61.0 MiB
Duration                       : 12 s 23 ms
Overall bit rate               : 42.6 Mb/s
Encoded date                   : UTC 2019-09-15 08:27:59
Tagged date                    : UTC 2019-09-15 08:27:59
com.android.version            : 8.0.0

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : Baseline@L5.1
Format settings                : 1 Ref Frames
Format settings, CABAC         : No
Format settings, ReFrames      : 1 frame
Format settings, GOP           : M=1, N=30
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 12 s 23 ms
Source duration                : 12 s 48 ms
Bit rate                       : 41.9 Mb/s
Width                          : 3 840 pixels
Height                         : 2 160 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Variable
Frame rate                     : 29.715 FPS
Minimum frame rate             : 17.258 FPS
Maximum frame rate             : 30.060 FPS
Standard                       : NTSC
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.170
Stream size                    : 59.9 MiB (98%)
Source stream size             : 60.1 MiB (99%)
Title                          : VideoHandle
Language                       : English
Encoded date                   : UTC 2019-09-15 08:27:59
Tagged date                    : UTC 2019-09-15 08:27:59
Color range                    : Full
Color primaries                : BT.601 NTSC
Transfer characteristics       : BT.601
Matrix coefficients            : BT.601
mdhd_Duration                  : 12023
Codec configuration box        : avcC

Audio
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : mp4a-40-2
Duration                       : 12 s 10 ms
Bit rate mode                  : Constant
Bit rate                       : 96.0 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Stream size                    : 141 KiB (0%)
Title                          : SoundHandle
Language                       : English
Encoded date                   : UTC 2019-09-15 08:27:59
Tagged date                    : UTC 2019-09-15 08:27:59
mdhd_Duration                  : 12010

I had tried to play the video file by using MPC-HC with the following LAV filter version as external filter:

1. LAV filter version 0.69: DXVA2 hardware acceleration works fine.
2. LAV filter version 0.70: DXVA2 hardware acceleration works fine.
3. LAV filter version 0.70.2: DXVA2 hardware acceleration works fine.
4. LAV filter version from 0.71 to the latest nightly build version: DXVA2 and D3D11 hardware acceleration NOT working.

Other player tested:
1. Windows 10 built-in video player "Film & TV": Hardware acceleration working.
2. Kodi version 18.4: Hardware acceleration working.
3. Other players which use LAV filter version between 0.71 to the latest: Hardware acceleration not working.

Here is some of my computer spec:
Type: Laptop
OS: Windows 10 (64-bit)
CPU: Intel Core i5-8250U
GPU: Intel UHD Graphics 620 / NVIDIA GeForce MX150 (Optimus)
Intel UHD Graphics 620 driver version: 26.20.100.6890
NVIDIA GeForce MX150 driver version: 25.21.14.1972

Note: I did not enable NVIDIA Optimus for video players. So, most video players will use the Intel GPU.

Please fix this issue.

**Comment by sirdanielk** [comment]
Works for me
I have hd 620 + optimus.
You messed with codec settings probably

**Comment by cshong87** [comment]
> Works for me
> I have hd 620 + optimus.
> You messed with codec settings probably

Did you try to test with the sample video I uploaded?

I had checked the settings for version <= 0.70.x and the latest version. All settings are identical.

Later, when I have access to my own personal computer, I will upload the screenshot of the video decoder setting to show you.

I do not know which changes in version >= 0.71.x made the problem occur.

I had tested another video with the same format but different profile. Both are h.264 videos with AVC codec. For video with Baseline@L5.1 profile, DXVA2 hardware acceleration working on older LAV filters version <= 0.70.x, but not working in newer LAV filters version. For video with HIGH profile, DXVA2 hardware acceleration works on all LAV filters version I tested.

The only workaround is to set hardware decoder to Intel QuickSync. But, I want to use either DXVA2 or D3D11. That is the reason I report this bug.

**Comment by cshong87** [comment]
> Works for me
> I have hd 620 + optimus.
> You messed with codec settings probably

![image](https://user-images.githubusercontent.com/55344914/65441006-3a6b9f80-de5c-11e9-882f-3c46e7a346f0.png)

Above is the current settings. Anything messed? Or, anything wrong?

**Comment by Nevcairiel** [comment]
Are you using LAV Splitter as well, or only LAV Video?

**Comment by Nevcairiel** [comment]
Oh, I know why it doesn't work, its "baseline" profile. "baseline" is not fully compatible with hardware decoding. As weird as it may sound based on the profile name, but "baseline" actually allows a whole array of weird bitstream features to be used, which hardware cannot deal with, and LAV has no way to tell if these are in use.

The only supported profiles for hardware decoding H.264 are:
- "constrained baseline"
- "main"
- "high"

For the first, the distinction is important, as "constrained baseline" does not allow those crazy features.

The smartphone should really flag it as "constrained baseline" if thats what it actually is, instead of "baseline". Any compliant hardware decoder *should* refuse it, but many ignore the profile check. But personally, I rather use software for some videos then fail decoding some others.

**Comment by sirdanielk** [comment]
Well then. @cshong87 try to install igfx_win10_100.7158 since i tested this drivers and Your sample and h/a worked.

**Comment by cshong87** [comment]
> Oh, I know why it doesn't work, its "baseline" profile. "baseline" is not fully compatible with hardware decoding. As weird as it may sound based on the profile name, but "baseline" actually allows a whole array of weird bitstream features to be used, which hardware cannot deal with, and LAV has no way to tell if these are in use.
> 
> The only supported profiles for hardware decoding H.264 are:
> 
> * "constrained baseline"
> * "main"
> * "high"
> 
> For the first, the distinction is important, as "constrained baseline" does not allow those crazy features.
> 
> The smartphone should really flag it as "constrained baseline" if thats what it actually is, instead of "baseline". Any compliant hardware decoder _should_ refuse it, but many ignore the profile check. But personally, I rather use software for some videos then fail decoding some others.

I have doubt on this. Hardware decoding works on Kodi, and Windows 10's "Films & TV". Why is that?

**Comment by cshong87** [comment]
> Oh, I know why it doesn't work, its "baseline" profile. "baseline" is not fully compatible with hardware decoding. As weird as it may sound based on the profile name, but "baseline" actually allows a whole array of weird bitstream features to be used, which hardware cannot deal with, and LAV has no way to tell if these are in use.
> 
> The only supported profiles for hardware decoding H.264 are:
> 
> * "constrained baseline"
> * "main"
> * "high"
> 
> For the first, the distinction is important, as "constrained baseline" does not allow those crazy features.
> 
> The smartphone should really flag it as "constrained baseline" if thats what it actually is, instead of "baseline". Any compliant hardware decoder _should_ refuse it, but many ignore the profile check. But personally, I rather use software for some videos then fail decoding some others.

Just for your information. Hardware decoding work on VLC player as well.

**Comment by Nevcairiel** [comment]
As said in the previous post:

Any compliant hardware decoder should refuse it, but many ignore the profile check. But personally, I rather use software for some videos then fail decoding some others.

A "baseline" video can work in hardware, but it can also not work. There is no way to tell the difference. This is why baseline is not hardware compatible - it CAN contain features that cannot be decoded by hardware, and you can't tell beforehand - thus baseline is refused.

**Comment by cshong87** [comment]
> As said in the previous post:
> 
> Any compliant hardware decoder should refuse it, but many ignore the profile check. But personally, I rather use software for some videos then fail decoding some others.
> 
> A "baseline" video can work in hardware, but it can also not work. There is no way to tell the difference. This is why baseline is not hardware compatible - it CAN contain features that cannot be decoded by hardware, and you can't tell beforehand - thus baseline is refused.

If that is the case, I have a suggestion.

Software decoding uses CPU. My laptop use 8th generation intel core i5. When using software decoding for playing the file, the CPU usage can grow to 20++, 30++, and sometimes even 50++ percent. Imagine that if that video file being played on computer with i3, intel celeron, Intel Atom or any lower end processor, what will happen?

Some computers, the GPU support playing 4K or higher quality video when using hardware decoding, but the CPU may not support playing such high quality video using software decoding. This need to be considered.

When using hardware decoding, my CPU usage is very low.

So, I have a suggestion. Implement an option to use hardware decoding for H264 baseline profile. You can make it being disabled by default. Users like me can enable it ourselves, and disable it when we face issue.
