### ISSUE TITLE
Installer should not downloads components

### ISSUE THREAD

**Issue by wrzwicky** [Nevcairiel/LAVFilters#313]
x264-3D component is missing from the installer, and is downloaded during installation. This should instead be moved into the installer file.

1. This can break the installer in the future if that component goes missing.
2. This opens the door to viruses if someone can replace the component on the source site.
3. This makes it harder for people on metered connections to manage their usage.
4. This makes the installer more complicated to build and deploy for your unpaid open-source workers.
5. This option is enabled by default, so most users download the component anyway.
6. And yes, it looks like the installer is secretly installing malware.

**Comment by Hrxn** [comment]
> This option is enabled by default, so most users download the component anyway.

You sure about that? Did not happen with my installation, if I recall it correctly.

**Comment by wrzwicky** [comment]
Sorry, I may be wrong on #5. Running the installer now, H.264 3D is NOT enabled by default.

However the first time I ran this today, it came up in "Custom" mode with H.264 3D already enabled.

**Comment by Nevcairiel** [comment]
There are no plans to change this.
