### ISSUE TITLE
D3D11 Native produces green screen on Intel HD 530

### ISSUE THREAD

**Issue by khaveesh** [Nevcairiel/LAVFilters#314]
I have an Intel i5 6500 processor and GTX 1660 GPU. When I use D3D11 Native hardware decoder with my integrated graphics, MPC-HC always gives a green screen with the audio still playing in the background. But with my GTX 1660, the same works perfectly fine. Is this an issue on Intel's side or with LAV.

Player: MPC-HC + madVR

**Comment by Nevcairiel** [comment]
Its probably an issue with Intel, but with Native mode there is little I can investigate. Perhaps its also an issue in madVR, since it is responsible for extracting the image for rendering.

Did you try D3D11 Copy-Back, ie. by selecting a specific device in LAV settings?

**Comment by sirdanielk** [comment]
@khaveesh 
Not enough input data.
madvr has option to enable dx11 too,
try with other renderer like EVR
try other files coded differently
download and diagnose system with dxvachecker. Make sure hardware acceleration is exposed, and available for D3d11 (Decoder device and processor device tabs).
