### ISSUE TITLE
can not use  Graphics card decode 8k files,plz add

### ISSUE THREAD

**Issue by Loukky** [Nevcairiel/LAVFilters#315]
cpu:i7 8700
card:1060 3GB.
when i play 8k files, cpu`s useage is 100%,look like the graphics card is not decode,
but when i play 8k video at youtube,graphics works very fine.
there have this 8k video details.
or you need any other informations?

---------------------------------------------------------------------
General
Unique ID                      : 195522599975888909686808491811453544612 (0x93184873549061E58165AEF4B59828A4)
Complete name                  : E:\MV\[8K超清MV] 江南Style.16in1.x264.Hi10P.4320p.160Mbps.60fps.mkv
Format                         : Matroska
Format version                 : Version 4
File size                      : 4.01 GiB
Duration                       : 3 min 34 s
Overall bit rate mode          : Variable
Overall bit rate               : 160 Mb/s
Encoded date                   : UTC 2010-02-22 21:41:31
Writing application            : mkvmerge v5.9.0 ('On The Loose') built on Dec  9 2012 15:37:01
Writing library                : libebml v1.3.0 + libmatroska v1.4.0

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High 10@L5.2
Format settings                : CABAC / 8 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 8 frames
Muxing mode                    : Header stripping
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 3 min 34 s
Nominal bit rate               : 152 Mb/s
Width                          : 7 680 pixels
Height                         : 4 320 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 59.940 (60000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 10 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.076
Title                          : Project 'Reply Octa-Core'
Writing library                : x264 core 129 r2230 1cffe9f
Encoding settings              : cabac=1 / ref=8 / deblock=1:-1:0 / analyse=0x3:0x133 / me=umh / subme=9 / psy=1 / psy_rd=1.00:0.20 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-3 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=4 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=1 / weightp=2 / keyint=300 / keyint_min=30 / scenecut=40 / intra_refresh=0 / rc_lookahead=12 / rc=2pass / mbtree=1 / bitrate=152000 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=81 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=350000 / vbv_bufsize=80000 / nal_hrd=none / ip_ratio=1.40 / aq=2:0.80
Default                        : Yes
Forced                         : No

Audio #1
ID                             : 2
Format                         : FLAC
Format/Info                    : Free Lossless Audio Codec
Codec ID                       : A_FLAC
Duration                       : 3 min 34 s
Bit rate mode                  : Variable
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 44.1 kHz
Bit depth                      : 24 bits
Compression mode               : Lossless
Delay relative to video        : 89 ms
Title                          : clip01-mv
Writing library                : libFLAC 1.2.1 (UTC 2007-09-17)
Default                        : Yes
Forced                         : No

Audio #2
ID                             : 3
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 384 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 12 ms
Stream size                    : 9.83 MiB (0%)
Title                          : clip02-0715
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #3
ID                             : 4
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 384 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 5 ms
Stream size                    : 9.83 MiB (0%)
Title                          : clip03-0722
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #4
ID                             : 5
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 384 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 19 ms
Stream size                    : 9.83 MiB (0%)
Title                          : clip04-0729
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #5
ID                             : 6
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 384 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 19 ms
Stream size                    : 9.83 MiB (0%)
Title                          : clip05-0805
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #6
ID                             : 7
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 384 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 21 ms
Stream size                    : 9.83 MiB (0%)
Title                          : clip06-0812
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #7
ID                             : 8
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 384 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 6 ms
Stream size                    : 9.83 MiB (0%)
Title                          : clip07-0819
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #8
ID                             : 9
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 384 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 6 ms
Stream size                    : 9.83 MiB (0%)
Title                          : clip08-0826
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #9
ID                             : 10
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 448 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 31 ms
Stream size                    : 11.5 MiB (0%)
Title                          : clip09-0901
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #10
ID                             : 11
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 384 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 12 ms
Stream size                    : 9.83 MiB (0%)
Title                          : clip10-0902
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #11
ID                             : 12
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 448 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 20 ms
Stream size                    : 11.5 MiB (0%)
Title                          : clip11-0904
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #12
ID                             : 13
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 384 kb/s
Channel(s)                     : 6 channels
Channel layout                 : L R C LFE Ls Rs
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 9 ms
Stream size                    : 9.83 MiB (0%)
Title                          : clip12-0914
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #13
ID                             : 14
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 384 kb/s
Channel(s)                     : 6 channels
Channel layout                 : L R C LFE Ls Rs
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 10 ms
Stream size                    : 9.83 MiB (0%)
Title                          : clip13-0914_encore
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #14
ID                             : 15
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 192 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 5 ms
Stream size                    : 4.92 MiB (0%)
Title                          : clip14-0919
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #15
ID                             : 16
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Muxing mode                    : Header stripping
Codec ID                       : A_AC3
Duration                       : 3 min 34 s
Bit rate mode                  : Constant
Bit rate                       : 384 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Delay relative to video        : 31 ms
Stream size                    : 9.83 MiB (0%)
Title                          : clip15-1007
Service kind                   : Complete Main
Default                        : No
Forced                         : No

Audio #16
ID                             : 17
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : A_AAC-2
Duration                       : 3 min 34 s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 44.1 kHz
Frame rate                     : 43.066 FPS (1024 SPF)
Compression mode               : Lossy
Delay relative to video        : 6 ms
Title                          : clip16-mvhyuna
Default                        : No
Forced                         : No

**Comment by Nevcairiel** [comment]
This is 10-bit H264, no hardware supports this.
