### ISSUE TITLE
LAVSplitterSource can't load 14MB.png file

### ISSUE THREAD

**Issue by steve90815** [Nevcairiel/LAVFilters#318]
LAVFilters developers-

I've just incorporated LAV filters into my DirectShow application, and I love it!

I came across a single PNG file that LAVSplitterSource can't load.  I attached a screenshot of the GraphStudioNext error, and a zipped copy of the problem PNG file.

Is there something I can do so LAVSplitterSource will load this PNG?

Thank you,

Steve

![LAVSplitterSource can't load 15MB png](https://user-images.githubusercontent.com/47338207/68039860-454ef680-fc8a-11e9-8cb2-bc1b519b0cf9.png)

[14MBpng.zip](https://github.com/Nevcairiel/LAVFilters/files/3798720/14MBpng.zip)

**Comment by lvqcl** [comment]
Actually it's a PSD file. The extension is incorrect.

**Comment by steve90815** [comment]
Wow!  Thank you.
Steve


    On Friday, November 1, 2019, 01:20:12 PM PDT, lvqcl <notifications@github.com> wrote:  
 
 
Actually it's a PSD file. The extension is incorrect.
