### ISSUE TITLE
Feature request: force loading of ffdshow raw filter

### ISSUE THREAD

**Issue by chainikdn** [Nevcairiel/LAVFilters#321]
Found the [same request on Doom9](http://forum.doom9.net/showthread.php?s=3ea1e8fc7c72e001d815050446dbc4df&p=1507103#post1507103) ages ago but dunno if that one was rejected or just forgotten.

This could be extremely useful for a VR video players (e.g. DeoVR, Whirligig) to enable frame interpolation. Currently the only option they have is to force ffdshow video decoder as a default one, which is, obviously, not the best solution today.

**Comment by Nevcairiel** [comment]
DirectShow Graph Building should be left to the player. Filters forcing other filters in the graph has a lot of problems.
