### ISSUE TITLE
EC_VMR_RECONNECTION_FAILED disturb VideoWindow in fullscreen

### ISSUE THREAD

**Issue by tantegrete** [Nevcairiel/LAVFilters#322]
I successfully build a DVD-graph with LAV-A+V filters latest version. Works fine in windowed-mode, but with some DVD-source i got multiple DS-error: EC_VMR_RECONNECTION_FAILED special when DVD-navigator changes to VideoManagerMenu or VideoTilteSetMenu.

So far no prob, but when video window is in fullscreen-mode, i got an smaller resized windowless video window.
This seems a problem of LAV-audiofilter because other decoders (e.g. ffdshow) don't produce such an error and will play the fullscreen properly.

**Comment by Nevcairiel** [comment]
This sounds like an issue in the player software you are using.
