### ISSUE TITLE
D3D11 VP90 HW Acceleration Didn't Work On AMD Vega

### ISSUE THREAD

**Issue by bagusnl** [Nevcairiel/LAVFilters#323]
D3D11 HW encoding didnt trigger on VP90 MKV video
edit: Copy-Back (Override Automatic Hardware Device) didn't give any luck

CPU : AMD Ryzen 3 3200U APU
GPU : Vega 3
Driver : 19.12.1
LAV Video : 0.74.1.30
MPC-HC : 1.8.8.14 (x64)
Renderer : madVR 0.92.17 (Using DX11 Renderer, lancoz4AR)
Windows 10 1909
Splitter : LAV Splitter Source

> Video: VP90 1280x720 60fps [V: vp9 profile 0, yuv420p, 1280x720 [default]]
> Audio: Opus 48000Hz stereo 3072kbps [A: opus, 48000 Hz, stereo [default]]

Image contains screenshot of LAV, MPC File Properties, and DXVA Checker
![image](https://user-images.githubusercontent.com/28079733/70595958-4a06b300-1c17-11ea-8f26-80f6068ba4ab.png)

Edit: added madVR details

**Comment by bagusnl** [comment]
PINOUT :

Filter : LAV Splitter Source - CLSID : {B98D13E7-55DB-4385-A33D-09FD1BA26338}

- Connected to:

CLSID: {EE30215D-164F-4A92-A4EB-9D4C13390F9F}
Filter: LAV Video Decoder
Pin: Input

- Connection media type:

Video: VP90 1280x720 60fps

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: Unknown GUID Name {30395056-0000-0010-8000-00AA00389B71}
formattype: FORMAT_VideoInfo2 {F72A76A0-EB0A-11D0-ACE4-0000C0CC16BA}
bFixedSizeSamples: 0
bTemporalCompression: 1
lSampleSize: 1
cbFormat: 128

VIDEOINFOHEADER:
rcSource: (0,0)-(1280,720)
rcTarget: (0,0)-(1280,720)
dwBitRate: 0
dwBitErrorRate: 0
AvgTimePerFrame: 166667

VIDEOINFOHEADER2:
dwInterlaceFlags: 0x00000000
dwCopyProtectFlags: 0x00000000
dwPictAspectRatioX: 16
dwPictAspectRatioY: 9
dwControlFlags: 0x00000000
dwReserved2: 0x00000000

BITMAPINFOHEADER:
biSize: 56
biWidth: 1280
biHeight: 720
biPlanes: 1
biBitCount: 12
biCompression: VP90
biSizeImage: 1382400
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 00 05 00 00 d0 02 00 00 ............Ð...
0010: 00 00 00 00 00 00 00 00 00 05 00 00 d0 02 00 00 ............Ð...
0020: 00 00 00 00 00 00 00 00 0b 8b 02 00 00 00 00 00 ...............
0030: 00 00 00 00 00 00 00 00 10 00 00 00 09 00 00 00 ................
0040: 00 00 00 00 00 00 00 00 38 00 00 00 00 05 00 00 ........8.......
0050: d0 02 00 00 01 00 0c 00 56 50 39 30 00 18 15 00 Ð.......VP90....
0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0070:|76 70 63 43 01 00 00 00 00 00 82 02 02 01 00 00 vpcC...........

- Enumerated media type 0:

Set as the current media type

**Comment by zlhdd108** [comment]
I'm Vega 56 ,same as you

**Comment by irvinren** [comment]
VP9 HW acceleration not working on nvidia gt1030. Dxva2 native / D3D11 + madvr 0.92.17 will result in avcodec software acceleration. D3D11 + EVR will result in dxva copy back.
