### ISSUE TITLE
Lavfilters failed to play m2ts and Dolby TrueHD encoded audio

### ISSUE THREAD

**Issue by hitechlover** [Nevcairiel/LAVFilters#324]
Dear Developer,
Your Lavfilter failed to play m2ts video format with WMP12 on Windows 10 v1909. It also failed to play videos with audio encoded in Dolby TrueHD MLP FBA. 
Here is the link to the site I download all those high quality videos encoded in 8 channels and and higher for testing:
https://thedigitaltheater.com/dolby-trailers/

Pick a video encoded in Dolby TrueHD 7.1 and test play it with Lavfilters. Also pick a trailer called Pufferfish which was encoded in h265 with m2ts file format. These video and audio types cannot be played with Lavfilters. All other audio types play fine, except those mentioned. Please fix your filter to support these file types.

Plus, your filter cannot play videos with audio encoded in dtsx or DTS:X. The audio fail to play but the video works though.

Please fix these issues as soon as possible.

Thank You,

Brian

**Comment by clsid2** [comment]
Those files all play perfectly fine with LAV Filters.

Your problem is that WMP isn't actually using LAV Filters. It uses the crappy codecs from Windows.

To solve that you need to disable Media Foundation with Codec Tweak Tool:
http://codecguide.com/download_other.htm#codectweaktool

**Comment by hitechlover** [comment]
After I disable Media Foundation, the video playback uses 100% CPU cycles which brings my laptop down to a crawl. I tested all settings and nothing works at reducing it down to normal below 10%. 

Can you add a feature to enable WMP12 64 bit by default on Win10? The 32 bit version uses high cpu than the 64 bit. Also add an option to disable Media Foundation in Lavfilters. Also when I install it, give us an option to only install codecs that is not available on Windows 10 by default. I don't want to install something that already available and works fine.

I don't want to install K Lite Codec pack or Shark007 codec because they are bloated with things I don't need, they just take up space. I like Lavfilters better because it is lightweight without bloated features I don't want. I just need those 2 options added mentioned above, that's all.

Thank You

**Comment by clsid2** [comment]
You can make WMP 64-bit default here:
Codec Tweak Tool > Various Tweaks

If you want a good player, use MPC-HC instead of WMP. Then you don't need hacks and workarounds to make things play properly.

These workarounds don't belong in LAV Filters.

**Comment by hitechlover** [comment]
Ok, I tried MPC-HC and it failed to play this mp4 video encoded in dtsx audio with 10 channels and 48 kHz. It plays the video but no audio. 
Here is a video taken directly from DTS Sound Unbound app:
https://www.dropbox.com/s/exltsrgn86svhqf/Kinsetsu_Microsoft_5p1p4.mp4?dl=0

You can test out this video and it also failed to play with Lavfilters. The Movies & TV app also failed to play it. Also videos encoded in Dolby TrueHD failed to play. Pretty much DTSX and Dolby TrueHD encoded audio inside mkv and mp4 videos with h265 failed to play by most players.

A disappointment by MPC-HC player is it cannot play 4K HDR 10bit videos. It will be the best player if they can built it in without third party plugins. I like this player because it opens and loads all videos instantly. Other codecs and players stall for about 4 seconds before playing those videos with DTSX and Dolby TrueHD encoded in h265.

What is the best media player that can play 4K HDR 10bit videos do you recommend?

Thanks

**Comment by clsid2** [comment]
MPC-HC supports 4K HDR 10bit just fine. You need to use a video renderer that supports HDR. The recommended renderer for that is madVR.

**Comment by pat357** [comment]
If you take a good look at the site you referred to (https://thedigitaltheater.com/dolby-trailers/) , it states that MPC-HC is the recommended player and these files were tested using both MPC-HC and Plex. !!

"To playback the MKV files in DTS-HD Master Audio you will need a media player such as **Media Player Classic Home Cinema (MPC-HC)** or a Media Server such as Plex that can output the Lossless stream via HDMI to an AV Receiver that supports DTS-HD Master Audio. **These files have been tested with both MPC-HC and Plex."**

**Comment by hitechlover** [comment]
Thanks, I already used MPC-HC and it works for M2TS and Dolby TrueHD.
However, it still failed to play mp4 with DTSX audio stream. It's like DTS
has their own thing and monopolized it. I don't know any player or codecs
can play mp4 with DTSX encoded audio stream. Only way I can get it to play
through Movies & TV app is to install DTS Sound Unbound app from MS Store
with a DTS compatible headset such as SteelSeries Arctis 7 that I have.
DTSX audio stream is extremely picky..lol.
