### ISSUE TITLE
Potplayer issue

### ISSUE THREAD

**Issue by Hsys7272** [Nevcairiel/LAVFilters#328]
Might be similar to this, https://github.com/Nevcairiel/LAVFilters/issues/149

It says "HEVC/H265 decoding is not supported in S/W mode.
Please click 'Find codec' to install the necessary codec." More info below.
https://pastebin.com/iCAn8vra

Is there a codec here that I can download to play the file?

**Comment by Nevcairiel** [comment]
This sounds like a PotPlayer question, not a LAV question
