### ISSUE TITLE
No audio with live .m3u8 streams using MPC-HC.1.9.1.x86

### ISSUE THREAD

**Issue by Phar-Lap** [Nevcairiel/LAVFilters#331]
Using MPC-HC.1.9.1.x86 and the following URL as an example:

http://kitdigitaioslive-i.akamaihd.net/hls/live/219671/skyracing_live_mob/ssr_low@219671-audio.m3u8

The last version to produce audio was Media Player Classic Home Cinema 1.7.10.

All versions after 1.7.10 have no audio and show an icon with a x in the lower right:

![No Audio with Muted Icon](https://user-images.githubusercontent.com/61812089/76063802-83fc1100-5fdc-11ea-9dc1-f47980dddfb9.png)

The link works, but probably only in Australia.
Try through a VPN set for Australia.
All my .m3u8 links are probably region locked to Australia and they all suffer from this audio problem.

Is there a way to extract the required filter from Media Player Classic Home Cinema 1.7.10 and use it with Media Player Classic Home Cinema 1.9.1.

**Comment by clsid2** [comment]
This should fix it:
Options > Internal Filters > Splitter > Set "Stream Analysis Duration" to 2000 ms

**Comment by Phar-Lap** [comment]
Yes that fixed it.
Some of my other HD stream required 2001 ms, so i just set it to 2100.

Can you make an auto setting which would start streaming after the the analysis is fully completed?

**Comment by clsid2** [comment]
That is not possible. It doesn't know when it has gained "complete" knowledge of the stream contents. A stream could be video only.
