### ISSUE TITLE
Downstream filter still receives unchecked output formats

### ISSUE THREAD

**Issue by CrendKing** [Nevcairiel/LAVFilters#332]
I'm writing a filter called AviSynth Filter. Repo is at https://github.com/CrendKing/avisynth_filter. This filter basically feeds the incoming samples to AviSynth and sends processed frames to downstream. Because some AviSynth filters can only support 8-bit formats, I tried to uncheck P010 and P016 in LAV video decoder's output formats matrix. However, when I play a 10-bit video, I'm still seeing P010 as the output format of LAV video decoder.

The filter chain is like this: <input video> -> LAV Splitter -> LAV video decoder -> AviSynth Filter -> madVR. I tested on both MPC-HC 1.9.1 and MPC-BE 1.5.5.

When connecting pins, my filter just takes the enumerated media types of upstream's output pin (and in order). I was expecting that if P010 is unchecked, `MEDIASUBTYPE_P010` should not appear in the enumerated types, or at least not as preferred as other checked types such as NV12.

The only way to get NV12 samples is by rejecting P010 in my `CheckInputType()`. Is this expected?

![Filters](https://user-images.githubusercontent.com/975235/76694374-09ac3c00-662f-11ea-9169-d6e97ecfd4f7.jpg)
![Decoder settings](https://user-images.githubusercontent.com/975235/76694369-0618b500-662f-11ea-8478-99c816c038cc.jpg)
![Pin Info](https://user-images.githubusercontent.com/975235/76694370-07e27880-662f-11ea-9e7e-b2d80f2f7635.jpg)

**Comment by Nevcairiel** [comment]
You have hardware decoding on in Nativem ode, which forces NV12 and P010 to be enabled, since in Native mode no conversions can be performed.
