### ISSUE TITLE
painting color need fix the issue please .

### ISSUE THREAD

**Issue by pop-dahaka** [Nevcairiel/LAVFilters#334]
please fix the issue with this video attached , painting color 

[TV220200319-194244.zip](https://github.com/Nevcairiel/LAVFilters/files/4359127/TV220200319-194244.zip)

General
ID                                       : 1 (0x1)
Format                                   : MPEG-TS
File size                                : 9.05 MiB
Duration                                 : 3 min 25 s
Start time                               : UTC 2020-03-19 17:45:52
End time                                 : UTC 2020-03-19 17:49:07
Overall bit rate mode                    : Variable
Overall bit rate                         : 368 kb/s

Video
ID                                       : 3002 (0xBBA)
Menu ID                                  : 760 (0x2F8)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : 27
Duration                                 : 3 min 25 s
Bit rate mode                            : Constant
Nominal bit rate                         : 700 kb/s
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive

Audio
ID                                       : 3003 (0xBBB)
Menu ID                                  : 760 (0x2F8)
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 2
Muxing mode                              : ADTS
Codec ID                                 : 15-2
Duration                                 : 3 min 26 s
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -24 ms

Menu
ID                                       : 7600 (0x1DB0)
Menu ID                                  : 760 (0x2F8)
Duration                                 : 3 min 25 s
List                                     : 3002 (0xBBA) (AVC) / 3003 (0xBBB) (AAC)
Service name                             : SATube-TV2
Service type                             : digital television

**Comment by Nevcairiel** [comment]
This recording seems to simply be corrupted due to bad receiption or something like that.

**Comment by pop-dahaka** [comment]
It was shown by Smartdvb as **H.222** , the signal was perfect , now the frequency stop broadcasting , I'll send you again when its back on .
