### ISSUE TITLE
No smooth decoding of vlc3.0.8

### ISSUE THREAD

**Issue by xmt82** [Nevcairiel/LAVFilters#335]
1、Using the latest LAV + qtplayer test, when decoding 4K h.265, compared with vlc3.0.8, there is no smoothness of VLC, and there is jamming.
2、Test hardware windows7 + Interl i5-4600

**Comment by clsid2** [comment]
This is not the fault of LAV.

Qt player uses the default DirectShow video renderer (VMR7) and that renderer is not compatible with DXVA2 native hardware acceleration. It does work with DXVA2 copyback, but Intel hardware is usually not powerful enough to give smooth playback with copyback mode.

This could be used instead:
https://github.com/wang-bin/QtAV
