### ISSUE TITLE
Fatal error (libudfread.git) while cloning LAVFilters

### ISSUE THREAD

**Issue by bfoos** [Nevcairiel/LAVFilters#336]
This issue was brought up on [MPC-HC github; Issue#319](https://github.com/clsid2/mpc-hc/issues/319) and I've seen it mentioned in the LAVFilters thread over at Doom9 forums. Apparently the URL for libudfread.git has been changed upstream and the cloning produces the following error...

`Submodule 'contrib/libudfread' (git://git.videolan.org/libudfread.git) registered for path 'libbluray/contrib/libudfread'
Cloning into 'E:/source/repos/LAVFilters/libbluray/contrib/libudfread'...
fatal: remote error: access denied or repository not exported: /libudfread.git
fatal: clone of 'git://git.videolan.org/libudfread.git' into submodule path 'E:/source/repos/LAVFilters/libbluray/contrib/libudfread' failed
Failed to clone 'contrib/libudfread'. Retry scheduled
Cloning into 'E:/source/repos/LAVFilters/libbluray/contrib/libudfread'...
fatal: remote error: access denied or repository not exported: /libudfread.git
fatal: clone of 'git://git.videolan.org/libudfread.git' into submodule path 'E:/source/repos/LAVFilters/libbluray/contrib/libudfread' failed
Failed to clone 'contrib/libudfread' a second time, aborting
Submodule path 'qsdecoder': checked out 'd1c57d8388dc68a8925ef4c6416371fb900d1192'
Failed to recurse into submodule path 'libbluray'`

As this issue was brought up on @clsid2 MPC-HC repository and he mentioned you @Nevcairiel I figured I'd take it upon myself to post it here directly.

**Comment by Nevcairiel** [comment]
They moved the repository, but libudfread was not used in the old version, so it was not a critical problem. I've since updated libbluray which now points to the correct repository.
