### ISSUE TITLE
Issues with 5K (5040x2520) VR files

### ISSUE THREAD

**Issue by KuroChloe** [Nevcairiel/LAVFilters#337]
I'm trying to use LAVFilters to decode my VR files but it always opts to use avcodec even if CUVID is selected.

**Comment by Nevcairiel** [comment]
Hardware can have resolution limits. Also ensure you're using a 64-bit player, as some resolution limits are even stricter on 32-bit due to memory concerns.

**Comment by KuroChloe** [comment]
I've tried several players and I most of them are 64-bit.
Not sure how familiar you are with VR players but: DeoVR, Whirligig, Skybox.
And also tried just on regular MPC-HC (64-bit) and hwdec fails to start there too.

**Comment by Nevcairiel** [comment]
What graphics card are you using?

**Comment by KuroChloe** [comment]
RTX 2070, so it shouldn't be an issue..

**Comment by Aleksoid1978** [comment]
Upload short sample.

**Comment by KuroChloe** [comment]
Here you go:
https://send.firefox.com/download/fb239ccbdd24453c/#ewMRhWRvo3ysLB34We4s7g
Password is: "github", and the download link expires in 24 hours or after 3 downloads.
While not obscene, it's not safe for work.

**Comment by Nevcairiel** [comment]
The maximum resolution for H264 on NVIDIA is 4096 × 4096, only H265 or VP9 can use resolutions up to 8K. You could convert your videos to H265 or VP9 if you require them to be hardware decodable.

**Comment by KuroChloe** [comment]
Appreciate it.
If I can still use this thread to ask, is maximum resolution for H264 higher on AMD and what program would you recommend for converting, easy way to do it on ffmpeg?

**Comment by Nevcairiel** [comment]
As far as I know, AMD does not support anything above 4K in any codec, so not H265/VP9 either.

If you are not accustomed to converting videos, a graphical tool like HandBrake is probably a good choice.

**Comment by KuroChloe** [comment]
Gonna give it a go if my ffmpeg convert fails, trying with these settings:
ffmpeg -i input.mp4 -c:v libx265 -crf 16 -c:a copy output_h265.mp4

Anyway, I thank you for the help and all the work you've done.
