### ISSUE TITLE
LAV Splitter - Add support for SetTimeFormat( &TIME_FORMAT_FRAME )

### ISSUE THREAD

**Issue by cowtung** [Nevcairiel/LAVFilters#338]
Our software allows our users to SetPositions() to specific frames. Whenever LAV splitter ends up in their graph, SetTimeFormat( &TIME_FORMAT_FRAME ) fails, so we have to hold their hand through uninstalling LAV filters (usually in K-Lite). We've tried just using TIME_FORMAT_MEDIA_TIME and doing the math to get to the right frame, but in practice, it is inconsistent, and we cannot create an algorithm which reliably gets us to the correct frame in every graph. Please add TIME_FORMAT_FRAME support. if there is anything I can do to assist in this, feel free to reach out. <3

**Comment by Nevcairiel** [comment]
There is no way to reliable do that, since the majority of containers do not contain enough information for frame-accurate seeking, and considering the extremely niche use-case of this I won't be working on this.
