### ISSUE TITLE
Cineform decoder is broken

### ISSUE THREAD

**Issue by Ph0rk0z** [Nevcairiel/LAVFilters#341]
Lav decodes CFHD to black. I had to uncheck it as a preference to get videos to play.

**Comment by Aleksoid1978** [comment]
Upload short sample.

**Comment by Ph0rk0z** [comment]
Sample of cineform encoded video?

www.filedropper.com/spiderclearlywaiting

That would not play, its the smallest vid I have at ~40MB

**Comment by Aleksoid1978** [comment]
Is not supported by ffmpeg.

**Comment by Ph0rk0z** [comment]
There was a check box inside for CFHD, maybe it's dynamically added? I see mention of support in general so not sure as the codec source is out there.
https://forum.doom9.org/showthread.php?t=173154

**Comment by richardpl** [comment]
Does it play in ffplay?

**Comment by richardpl** [comment]
File plays just fine in ffplay.

**Comment by Ph0rk0z** [comment]
Wasn't working in media player classic.

**Comment by richardpl** [comment]
Works fine in mpv and ffplay.

**Comment by Nevcairiel** [comment]
Works in the latest nightly of LAV in any case.
