### ISSUE TITLE
All Dolby audio formats are being sent as stereo or multichannel stereo to receiver. DTS bitstreams fine

### ISSUE THREAD

**Issue by eng0505999** [Nevcairiel/LAVFilters#342]
This is an odd one, I have been unable to get any multichannel sound to be output from Windows. Regardless of the speaker and spacial sound setup, all that is being sent to my receiver (Denon AVR720W) is stereo, or Multi channel stereo.

What's even odder is that, when I am trying to bitstream audio using the LAVAudio decoder, all of the Dolby audio formats suffer the same issue (DD, DD+, TrueHD, Atmos), while DTS formats are being sent to the receiver as they should be (DTS, DTSX, DTS-HD).

Using my XBoxONE X, Atmos bitstreaming works without issue, as to the other Dolby formats. 

I updated all my drivers, reinstalled the LAVAudio decoder, Dolby Access, and even switched the HDMI cable, to no effect. Enabling or disabling exclusive mode (in both Windows, and player (tried with MPC-HC, MPC-BE, and VLC).

LAV Filter Version: 0.74.1

K-Lite Codec Pack: 15.4.4

I'm currently running Windows 10 19041.1(vb_release).
CPU: i9-7900X
Mobo: Asus Prime X299
RAM: 32GB
GPU: Nvidia 1080Ti
Receiver: Danon AVR720W
Display: Vizio P50-C1

Any help is appreciated, as I am a complete neophyte when it comes to this topic.

**Comment by clsid2** [comment]
This might be fixed by Windows 10 update KB4557426.
