### ISSUE TITLE
Spatial Audio

### ISSUE THREAD

**Issue by Viscerous** [Nevcairiel/LAVFilters#344]
Forgive me for bringing this up again but you clearly didn't feel like properly reading in #343 
> Windows spatial audio basically re-encodes audio back to Atmos, so you might as well bitstream the original stream.

This is only partially true, this is essentially the fallback mode I also mentioned that takes any 7.1 or 5.1 source and encodes it back into Atmos, yes. But there are actual spatial sound APIs that supported games make use of along with supported encoded files using metadata. These seem to come with various codecs, here is an E-AC3 stream [from Dolby's own website](https://www.dolby.com/us/en/guide/dolby-atmos-trailers.html) with accompanying Atmos metadata:

```
Audio
ID                             : 2
Format                         : E-AC-3 JOC
Format/Info                    : Enhanced AC-3 with Joint Object Coding
Commercial name                : Dolby Digital Plus with Dolby Atmos
Codec ID                       : ec-3
Duration                       : 1 min 3 s
Bit rate mode                  : Constant
Bit rate                       : 448 kb/s
Channel(s)                     : 6 channels
Channel layout                 : L R C LFE Ls Rs
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Stream size                    : 3.39 MiB (5%)
Service kind                   : Complete Main
Default                        : Yes
Alternate group                : 2
Encoded date                   : UTC 2018-05-03 17:08:46
Tagged date                    : UTC 2018-05-03 17:08:46

;This here is the Atmos Metadata
Complexity index               : 16
Number of dynamic objects      : 15
Bed channel count              : 1 channel
Bed channel configuration      : LFE
```

This is working as intended when decoding with the MFT audio decoder, even on my simple 3.5mm PCM output. LAV 'works' but only uses the 6 channel fallback re-encoded back to Atmos, it doesn't use the metadata and definitely sounds different.

EDIT: Worth mentioning that this is for Dolby Atmos for Headphones and obviously home theatres with Atmos should simply be bit-streamed.

**Comment by Nevcairiel** [comment]
> Forgive me for bringing this up again but you clearly didn't feel like properly reading in #343

Being disrespectful is not going to give you better results.

> This is working as intended when decoding with the MFT audio decoder, even on my simple 3.5mm PCM output. LAV 'works' but only uses the 6 channel fallback re-encoded back to Atmos, it doesn't use the metadata and definitely sounds different.

And the MFT might know how to decode Atmos data, as its closed-source  and may have paid Dolby for this information and the permissions to use it. Unless the information is made available and a decoder included in FFmpeg, this behavior cannot be replicated.

So I suggest to use the MFT then instead.

> So if I take this right, TrueHD 7.1 decoder exists but Atmos decoder doesn't exist?

That is correct. There is no information how to decode the Atmos data to pass it anywhere, other then passing it entirely untouched through HDMI for bitstreaming.
