### ISSUE TITLE
HEVC YUV 4:4:4 HW playback problem on TURING GPUs

### ISSUE THREAD

**Issue by Cuberlain** [Nevcairiel/LAVFilters#345]
Hello  Nevcairiel !

There is a HEVC YUV 4:4:4 HW decode problem on TURING GPUs, There are problems even with the YUV  4:4:4 videos which were encoded by NVENC engine too.

 The HW decoding of 4:4:4 videos are in the list of Video Encode and Decode GPU Support Matrix for TURING GPUs. Here you can read it: https://developer.nvidia.com/video-encode-decode-gpu-support-matrix

 

I can play 4:4:4 files only with the help of CPU, the usage of NVDEC is 0%, when I checked it in the Windows Task Managger / Performance / GPU

There is no problem with the traditional 4:2:0 videos, In this case the task manager also shows the GPU Decode usage too.

I don't know that the problem is caused by the Nvidia drivers or the lack of support in the codecs.

Here is my uploaded NVENC encoded video sample file: https://sendgb.com/9yezHBckOdT

Can you investigate this problem?

Thank you very much!

Thank you for your reply!

**Comment by Nevcairiel** [comment]
4:4:4 video is not currently supposed to be supported. DXVA/D3D11 does not specify any support for it, and the CUVID decoder is quite an old design and would need modernization to support this.

See also issue #285

**Comment by Cuberlain** [comment]
Okay, I understand.
Can you answer the question about the origin of the problem? Is it caused by the lack of support in  Nvidia driver (NVDEC) or it is related only to the lack of codec support?

Thank you for your reply!

**Comment by Cuberlain** [comment]
Nevcairiel , the VLC player can play HW accelerated 4:4:4 HEVC,.
When will you exactly make the LAV Filters to do the same?

**Comment by Nevcairiel** [comment]
I do not provide a timeline for future changes.
