### ISSUE TITLE
The audio and video are out of sync, releases 0.74.1

### ISSUE THREAD

**Issue by Heporis** [Nevcairiel/LAVFilters#346]
potplayer+LAVFilters
The video stream of some videos(some recorded live videos) was sped up, but the audio stream was normal. When I use the built-in decoder of potplayer or the newest releases of ffplayer, everything goes well. Does updating  the ffmpeg of LAVFilters work？
BTW, why did you not release a new version after such a long time?

**Comment by clsid2** [comment]
You can find latest development builds here (with newer FFmpeg):
https://files.1f0.de/lavf/nightly/

Monitor your CPU usage during playback. If it is very high, then is a performance issue and not a bug.

**Comment by Heporis** [comment]
Thank you.
Finally, I found this to be a Intel QuickSync hardware decoder problem. After I use other hardware decoder, everything goes well.

> You can find latest development builds here (with newer FFmpeg):
> https://files.1f0.de/lavf/nightly/
> 
> Monitor your CPU usage during playback. If it is very high, then is a performance issue and not a bug.
