### ISSUE TITLE
H.264 MVC 3D Decoder download not working

### ISSUE THREAD

**Issue by BaconCatBug** [Nevcairiel/LAVFilters#350]
Certificate Expired on the 20th.

**Comment by BaconCatBug** [comment]
So, erm, is this going to be fixed?

**Comment by Nevcairiel** [comment]
It already was, which is why the issue was closed.

**Comment by BaconCatBug** [comment]
Well, it wasn't fixed when I made the bug report, so instead of just
closing it without comment, perhaps say "We've now fixed this"?
