### ISSUE TITLE
Hardware accelerated decoding on Arrandale CPU

### ISSUE THREAD

**Issue by maa7** [Nevcairiel/LAVFilters#351]
Hello,
I know that Quick Sync was introduced with the Sandy Bridge CPU microarchitecture.
But in this table https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video#Hardware_decoding_and_encoding
i see that Clarkdale/Arrandale support AVC(H264) fixed-function hardware decoding.
_"Clarkdale/Arrandale microarchitecture had hardware video decoding support (but no hardware encoding support), it was known as Intel Clear Video."_

How to use this with LAV Video Decoder?
On my Arrandale CPU i can't use "Intel QuickSync" (LAV Video Decoder show "N/A").
Also i do not see "Intel Clear Video" hardware decoder in drop-down list.
Only DXVA2 working.

**Comment by Nevcairiel** [comment]
You should practically never use QuickSync anyway. DXVA2 is fine, use that.
