### ISSUE TITLE
Intel Quick Sync can not play 4K 60 FPS HEVC video with LAV Filters

### ISSUE THREAD

**Issue by Cuberlain** [Nevcairiel/LAVFilters#352]
Hello!

Intel Quick Sync can not play 4K 60 FPS HEVC video prperly with LAV Filters.

LAV Filters play the videos only with 30FPS, It can play only 30fps 4K HEVC videos videos without problem

Despite Kaby Lake processors supports it.

Here is the Fixed-function Quick Sync Video format support chart:

https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video#Hardware_decoding_and_encoding

during the playback of 60p 4K videos, Lav Filters uses only the 20-30% of the Quick Synk Engine engine,

Can you fix it?

Thank you!

**Comment by Nevcairiel** [comment]
QuickSync in LAV Filters is deprecated and will not be developed any further. Instead you should use DXVA2 or D3D11, which are vendor-agnostic APIs that access the exact same hardware.
