### ISSUE TITLE
Support for ReplayGain for audio

### ISSUE THREAD

**Issue by jzelinskie** [Nevcairiel/LAVFilters#353]
I use [ReplayGain][wiki] for all of my music playback and it's truly a boon for controlling volume levels with dynamic range. This feature is slightly different than regular normalization (which I believe is already available in LAV Filters).

I tried searching to see if MPC-HC or LAV Filters supported this functionality and only a dead link came up (because MPC's trac issue tracker is now dead). I figure that this is the correct place to make the feature request, anyways.

It's interesting to me that this functionality seems fairly ubiquitous for music when it was originally intended to be used in for the 
audio alongside video content.

[wiki]: https://en.wikipedia.org/wiki/ReplayGain

Let me know if this is the proper place to track this request and thanks to everyone who has contributed to this amazing project.

**Comment by Nevcairiel** [comment]
LAV is designed for video playback, not audio. I'm not interested in audio-centric features like that, sorry.
All metadata included in the files are exposed within reason, so a player could implement this when using LAV.
