### ISSUE TITLE
MOV Pro-Res cannot decode to uncompressed RGB formats

### ISSUE THREAD

**Issue by Zelex** [Nevcairiel/LAVFilters#357]
Something wrong with the demuxer integration there. It won't convert to uncompressed RGB via the Windows Media Foundation (other formats work fine)

See sample code. 

[wmf_decode.zip](https://github.com/Nevcairiel/LAVFilters/files/4984173/wmf_decode.zip)

**Comment by Nevcairiel** [comment]
LAV Filters is a DirectShow decoder, it has nothing to do with Media Foundation.
