### ISSUE TITLE
Feature request: Change audio decoder properties by hotkey or command line utility

### ISSUE THREAD

**Issue by cdb000** [Nevcairiel/LAVFilters#358]
Our media setup can be either 2 speakers of 5 speakers. By opening "LAV Audio decoder Properties" I can set the output speaker configuration appropriately, but to do so on the HTPC is a major pain as it has no keyboard or mouse, just a MCE-type remote control. When set for 5.1 audio and feeding 2 speakers the dialogue is lost as there is no center speaker and my 6 year old shouts for me to fix it... 
Would it be possible to have some Audio Decoder presets and to be able to switch between them on-the-fly, eg. by hotkey or by a command line utility which could be invoked by Event Ghost in response to a remote control keypress?

**Comment by clsid2** [comment]
The output from LAV gets processed by the Windows audio mixer (unless using exclusive mode). So you might have a wrong speaker configuration in the Windows Sound settings.

If you use two different audio output devices, then there are tools to easily switch:
https://www.raymond.cc/blog/easily-change-or-switch-the-default-audio-sound-output-in-windows-vista-and-xp/

**Comment by cdb000** [comment]
The setup looks like this:    PC ==HDMI=> Receiver ==HDMI=> TV

When the receiver is in use, all works well. For this to be the case, Windows has to be set up for 5.1 audio as does the LAV audio decoder.

There are many occasions when there is no need for high quality audio, and the receiver uses quite a lot of power so it is desirable to be able to use it only some of the time. When the receiver is set to its "standby" mode, it passes HDMI video and audio through to the TV set.

The problem is that the TV set ignores audio other than the front left and right channels. It appears to be unable to downmix 5.1 to stereo.

Changing the speaker configuration in the Windows Sound setting does indeed work, but is insanely clumsy on a machine without a mouse or keyboard, I have not been able to find a way to automate this and, after a lot of looking, have come to the conclusion that this is likely to be impossible.

Changing the mixer configuration in the LAV decoder also works. Windows continues to send 6 channels of audio over HDMI, but LAV decoder has downmixed to stereo, which the TV set outputs correctly.

Now, Event Ghost can detect whether the receiver is in use (via network) and adjust the LAV filter registry settings. This works, but requires that the user stop and reload the media playback. The LAV filter can change audio mixer "on the fly" but to do so during media playback requires mouse or keyboard actions which are tricky to automate.

If there was a way to have a running instance of the LAV filter re-read its settings from the registry and change settings on the fly, then switching audio from "stereo via TV" and "5.1 via receiver" and back would be achieved by setting the receiver from "standby" to "on" and back. That would be nice!

**Comment by Nevcairiel** [comment]
I'm sorry, but I don't have any plans to offer any such control. All LAV settings are exposed through an API, so a player could offer such functionality to you when its using LAV.
