### ISSUE TITLE
Feature Request: Pass MediaSideData to EVR Custom Allocator (not the Renderer)

### ISSUE THREAD

**Issue by coldboot-damikez** [Nevcairiel/LAVFilters#362]
Is it possible to pass the MediaSideData to Custom Allocators (custom implementations of `IMFVideoPresenter`)? I'm fairly new to this, but based on what I understand with LAVVideo, the MediaSideData is "attached" to `IMediaSample` and is not accessible to custom allocators as it uses `IMFSample`.

**Comment by Nevcairiel** [comment]
LAV Video has no specific limitations on supporting any specific renderers. It would work with any renderer that can accept our custom IMediaSample. If thats not possible to get working in a custom EVR allocator, then it cannot work.

This data needs to be per-packet accessible, and IMediaSample is the only structure we have in DirectShow for this purpose.

**Comment by coldboot-damikez** [comment]
Thanks for the info. I'm using a custom allocator / presenter through the
EVR Renderer. I've been looking around the internet and I can't seem to
find a way to get an `IMediaSample` from my custom allocator presenter.
Since I'm using a custom allocator / presenter, all I have access to is
`IMFSample`, can you point me out to how to access an `IMediaSample` from
my custom allocator / presenter? Thanks again!

**Comment by Nevcairiel** [comment]
I have no experience with customizing EVR. It may not even be possible.
