### ISSUE TITLE
H.264 Level 6.0+ support for 4K 120fps video

### ISSUE THREAD

**Issue by chungexcy** [Nevcairiel/LAVFilters#363]
In your recent comment, you disabled the hw decoding for any h264 with profile >= 6.0.

This should not affect 4K <=60fps video. But for 4k 120fps, the profile is 6.0. I understand you may think we don't need to support 8k on H264. But can you bring profile 6.0 back for hw decoding? 120fps will most likely become popular as the high frame rate display/TV/next gen console become more available in the coming years.

**Comment by Nevcairiel** [comment]
Profile 6.0 is not supported by hardware. I rather have every stream play properly and some not run on hardware rather then have some decode with corruption.

I recommend you use HEVC for high resolution or high framerate content, where it is officially supported on hardware.
