### ISSUE TITLE
[feture request] av1 HW decoding support for RTX 3000 Series.

### ISSUE THREAD

**Issue by fuchanghao** [Nevcairiel/LAVFilters#364]
NVIDIA says RTX 3000 Series support AV1 HW decoding.

https://www.nvidia.com/en-us/geforce/news/introducing-rtx-30-series-graphics-cards/

> they’re the first discrete GPUs with support for the AV1 codec

Is that possible to add av1 HW decoding support for RTX 3000 Series?

**Comment by MelonGx** [comment]
I second this.
I have a 8K HDR video file in AV1 format. But LAV b1db418 can't hardware decode it.

**Comment by Nevcairiel** [comment]
You are free to send me the required hardware to do this. Otherwise, it'll simply have to wait until I have access to it.

**Comment by MelonGx** [comment]
If you lived in Japan I'd like to.
