### ISSUE TITLE
Missing HDR metadata when using NVIDIA CUVID

### ISSUE THREAD

**Issue by CrendKing** [Nevcairiel/LAVFilters#365]
I noticed when using NVIDIA CUVID in the video decoder, downstream filter will not receive any HDR side data. Even directly connects the video decoder to madVR and play HDR video, madVR reports HDR unknown properties. Other hardware acceleration methods work fine. Is this a known limitation of CUVID?

**Comment by Nevcairiel** [comment]
Yes, it is, the decoding API in user there does not provide this information. You are generally better off using DXVA2 or D3D11
