### ISSUE TITLE
8K resolution support for hardware resolution

### ISSUE THREAD

**Issue by irvinren** [Nevcairiel/LAVFilters#366]
My graphic card can support video playback at  8k resolution . But I couldn't use it. Is there anyway to enable it in lavfilters?

**Comment by Nevcairiel** [comment]
8K is supported when the GPU supports it, but do note that due to memory limitations its only supported in 64-bit.

**Comment by MelonGx** [comment]
https://github.com/Nevcairiel/LAVFilters/issues/364
