### ISSUE TITLE
Splitter: Maximum Queue Packets too Low freezes video with QT and Win Platform

### ISSUE THREAD

**Issue by ltbam** [Nevcairiel/LAVFilters#367]
Hello,

I've been struggling some times with this issue but finally came to a resolution.

I use QMultimedia library with python on Windows platform. I use the LAV Filters in direct show to play some H264 mpeg-ts movies. Some os these videos files plays very well, and others just freeze. I mean by freezing that if you press the play button, the player display the first frame and just hang forever (no matter which LAV Filters version).

After a long search I've been able to solve the problem by raising the LAV Splitter "Maximum Queue Packet" from its default 350, to 3000.

I would be very grateful if you can consider this fix in the next release.

Best Regards

Rémy

**Comment by Nevcairiel** [comment]
It sounds to me like either the files are broken or badly authored, or the player is not very well behaved. Without access to such a file, I cannot say either way, however the queue size is tuned the way it is for a balance of multiple factors, and a massively larger queue has several downsides that I will not using as a default value.

If you have a particular file that is not playing correctly, please report the files individually, ideally with a clear case to reproduce so it can be investigated. A blanket default queue size change is not a solution I will simply do with no clear evidence I can produce on my side.
