### ISSUE TITLE
Please help With LAV video settings

### ISSUE THREAD

**Issue by Aqua3247** [Nevcairiel/LAVFilters#369]

**Comment by Aqua3247** [comment]
In my lav video settings i have selcted dxva2 copy back and hardware device to use NVIDIA Geforce GT 710
but it shows active decoder "inactive" and active hardware accerelator "none"
Please help me i am a rookie and using LAV filters for the first time with pot player
Both of them are of latest build

**Comment by Aqua3247** [comment]
[](url)https://imgur.com/ZcpbMAG

**Comment by clsid2** [comment]
You are looking at an inactive instance of the filter. You need to access an active instance through the player to see which hardware decoder is used.

In case of MPC-HC you can do that through:
Menu > Play > Filters

Potplayer probably has something similar in its menus.

**Comment by Aqua3247** [comment]
Thank you it fixed my issue.
And thank you for providing us with lav filters it is one of the best filters to use.
