### ISSUE TITLE
Fallback to audio decoding if bitstreaming fails

### ISSUE THREAD

**Issue by Nevcairiel** [Nevcairiel/LAVFilters#37]
For convenience, LAV Audio should fallback to decoding if bitstreaming fails

**Comment by JoseHidalgo** [comment]
I completely support this, and I hope it will be done soon.
I have a laptop with MPC-HC and LAV.
When at home, the laptop is connected to an USB audio card, connected via S/PDIF to a 5.1 audio system with decoding capabilities (Logitech Z-680), so I passthrough the audio to my audio system.
When on the road, I just use my headphones, so no passthrough.
It's very inconvenient to be forced to switch between bitstreaming and "no bitstreaming" all the time. Fallback would definitely be a nice workaround. Thanks !

**Comment by kathampy** [comment]
This is usefeul for headphones - especially Windows Sonic / Atmos for headphones.
