### ISSUE TITLE
Wmv file cannot get Key Frames

### ISSUE THREAD

**Issue by sudongg** [Nevcairiel/LAVFilters#372]
Hello,
All Wmv files in my PC cannot get Key Frames, no matter whether they are in wmv3 format or VC-1 format.
But I tried to play with MPV, which can do Key Frames seek very well.

Use MPC-HC 1.9.7, LAV Filters 0.74.1.

![image](https://user-images.githubusercontent.com/7007181/96574932-af7d0300-1302-11eb-9558-34a793c0424d.png)

**Comment by Nevcairiel** [comment]
Key Frame seeking is not a guaranteed feature, many formats do not support it. It does typically not depend on the codec, but the container to provide this information. WMV/ASF is not a format I'm eager to spend time on, sorry.

**Comment by sudongg** [comment]
@Nevcairiel 
Thank you for your reply. 
This problem has existed for a long time. I knew that you were not interested in it. I just want interested people to help me solve it. I hope you don't close it.
