### ISSUE TITLE
Please Help Me !!!!!!!!!

### ISSUE THREAD

**Issue by Aqua3247** [Nevcairiel/LAVFilters#373]
Hi! I am using lav filters on windows 7 but the support of windows 7 ended and i tried to install windows 8.1/10 on my low end pc.
Windows 8.1 uses about 1.1 gb out of 2gb ram and Windows 10 uses about 1.3gb out of 2gb ram, which disables me too even run my web browser smooth.
I am thinking to switch to linux but lav filters is my favourite H-W decoder.
But I have come to know that lav is not available for linux.
Can you please please release lav filters for linux in its next build ??
Please!!!!!!!
That would mean a lot if you release it for linux.

**Comment by Underground78** [comment]
Someone already told you that this is not possible. LAVFilters is a
DirectShow filter and DirectShow is a Windows component which does not
exist on Linux.

You can use other players like VLC or many others that use the same
decoding engine as LAVFilters.

**Comment by Aqua3247** [comment]
Thanks
