### ISSUE TITLE
Performance problems with HW acceleration enabled on 1080ti

### ISSUE THREAD

**Issue by Damitrix** [Nevcairiel/LAVFilters#376]
Heyo,
Since a year or so, I've had video playback problems on my 1080ti using LAV Filters.
I'm positive, that HW acceleration is turned on, I can see the GPU usage going up to 100% in Task Manager.
Switching to cuvid doesn't help.
I've just recently completely reinstalled windows, but that didn't fix it either.
**If I try the same file in MPC-BE with it's own internal filters, it will play just fine, making the GPU usage only go up to 20%.**

I'd be fine with just using MPC-BE, if it wasn't for my VR Videos, which have a horrible performance when using LAV.

**Comment by Damitrix** [comment]
> Test playback with MPC-HC, which uses LAV Filters.
> 
> It is probably a bug in your VR application:
> https://steamcommunity.com/app/837380/discussions/0/1744516107485633970/

Huh, it actually works fine with MPC-HC, but every other Player (probably the ones that use the external LAV Filters) struggles heavily.
Switching to anything other than dxva native will show the same performance problems in MPC-HC.
Additionally, when I open the Video in my VR player and open up the LAV Video Decoder control Panel, the active decoder is avcodec, even when selecting dxva native. MPC-HC shows dxva2n.

Is there a workaround, or is my only hope to bug the dev of the player?

**Comment by clsid2** [comment]
DXVA2 Native only works in combination with a compatible video renderer. This means that the player that you use needs to use "Enhanced Video Renderer". It currently probably uses the system default renderer, which is the ancient "Video Mixing Renderer 7".

DXVA2 Copyback and CUVID work with all renderers, but are less efficient than native due to the extra copyback step.

**Comment by Damitrix** [comment]
Alright, I guess that's for the individual app developers to fix then. Thank you for your help.
