### ISSUE TITLE
LAV Audio fails to detect bitstreaming support if extending to a second display

### ISSUE THREAD

**Issue by MarcG2** [Nevcairiel/LAVFilters#377]
I have a situation where one of my video outputs is connected to my AVR solely for transmitting audio.  When playing a movie, it converted the audio to PCM when instead bitstreaming it.   Unchecking the "fall back to PCM" option will cause the audio to bitstream as expected.

**Comment by Nevcairiel** [comment]
LAV does not detect support, it just offers all the options to the audio renderer - with or without PCM fallback depending on the option. But if the option works for you, not sure what exactly you are reporting here?

You can probably make it work without it by specifically selecting the right audio device in your players settings.

**Comment by clsid2** [comment]
If case you have ffdshow or AC3Filter installed, you should remove them or at least disable their PCM processing abilities. Otherwise they can trigger the PCM fallback in LAV.

**Comment by MarcG2** [comment]
> 
> 
> LAV does not detect support, it just offers all the options to the audio renderer - with or without PCM fallback depending on the option. But if the option works for you, not sure what exactly you are reporting here?
> 
> You can probably make it work without it by specifically selecting the right audio device in your players settings.

It bitstreams as expected when I was using a single display. So I just thought it was odd that something would trigger it to convert the audio to PCM unnecessarily if a second display was active.  You can ahead close this if it's outside LAV.


> 
> 
> If case you have ffdshow or AC3Filter installed, you should remove them or at least disable their PCM processing abilities. Otherwise they can trigger the PCM fallback in LAV.

I'm using the K-lite standard pack, so those aren't installed
