### ISSUE TITLE
LAV Audio Decoder fails to sync an external audio with video

### ISSUE THREAD

**Issue by EvgenKo423** [Nevcairiel/LAVFilters#378]
I came across this problem like 4 years ago and ditched it back then, but yesterday I finally tracked it down.
I have updated K-Lite Codec Pack from `12.0.1` (LAV Filters `0.67-142-gb9999`) to `15.8.0` (LAV Filters `0.74.1-75-gb1db4`) and it's still there. 

I have an MKV file with built-in audio (`AVC 1920x1080 8 bit @ ~5500 kb/s`; `FLAC 2.0 48.0 kHz 16 bit`) and an MKA file with alternative audio (`AC-3 5.1 48.0 kHz 32 bit`? (says In pin) `@ 448 kb/s`). I've played this video through MPC-HC with LAV Splitter + Audio Decoder (A/V Sync on) + Video Decoder (DXVA2 copy-back) + madVR renderer.
When I play it with built-in audio track the audio is in sync. However, when I play it with an alternative audio track the audio continually starts to play earlier than the video (or visa versa), but it becomes synced again if I rewind it.
CPU usage up to 10%, GPU usage up to 75%.

Considering built-in audio case I guess it's not a video playback issue. Moreover, I can play other H.264 1080p videos with double bitrate or bit depth of 10 bits and 5.1 audio (both internal and external) with no issues.
Anyway, I've tried all kinds of options to fix this problem:
* disabling audio driver post-processing;
* increasing splitter queue memory;
* disabling A/V Sync;
* trying different hardware acceleration options (including no);
* changing video renderer options and the renderer itself;
* changing audio renderer;

nothing helped...
Finally, the problem is gone when I've changed the LAV Audio Decoder to ffdshow with Jitter Correction enabled.

Let me know if you need more info.

**Comment by Nevcairiel** [comment]
I would need a sample to reproduce.

**Comment by clsid2** [comment]
Perhaps the file has an audio delay set?
https://forum.doom9.org/showthread.php?p=1918808#post1918808

**Comment by EvgenKo423** [comment]
@Nevcairiel Here it is: [LAV_Sync_test_sample.zip](https://github.com/Nevcairiel/LAVFilters/files/5469308/LAV_Sync_test_sample.zip) (not sure if copyright owners are OK with it, though).

@clsid2 I don't see any delay field in MediaInfo or mkvinfo. Anyway, it's not like the audio is out of sync to begin with, it becomes so after some play time.
However, I also tried to merge this sample into a single container and, as stated in your post, A/V Sync works as expected for me as well if both sources are in the same container.

**Comment by Nevcairiel** [comment]
The external audio file you are using seems to have rather screwed up timestamps and audio gaps, apparently. Not sure why or how, but it is what it is. A/V sync can usually fix them, but when its running as an external file it doesn't manage to reference the video track to sync against.

**Comment by Nevcairiel** [comment]
The changes in 06f75fc302c8ef59720fe485618b5ae55826c8e3 should help, but your audio track is still very weird. Audio is usually not so hard to keep without huge gaps.

**Comment by EvgenKo423** [comment]
Wow, that was fast... I'll give it a try when the next build arrives.

**Comment by EvgenKo423** [comment]
It's fixed now, thanks!
