### ISSUE TITLE
Blinking black cursor-like square on top of the video each second

### ISSUE THREAD

**Issue by purenoise** [Nevcairiel/LAVFilters#379]
So while on LAVFilters [ only] while playing video this cursor-like black square keeps blinking,
and for each type of video appears in different places, but it blinks every second.

**Comment by clsid2** [comment]
That is not the fault of LAVFilters. Maybe it is actually your mouse cursor that is rendered badly due to graphics driver bug.

**Comment by purenoise** [comment]
![black_blinking_cursor](https://user-images.githubusercontent.com/4173913/97889716-5b781280-1d35-11eb-92ee-a2e25743338d.jpg)

It's only appears when using LAVFilters, and 
no marker in the original video - tested by opening in the
video editor.
When using MPC Video Decoder, 'black cursor gone'.
So you should look into it.

**Comment by clsid2** [comment]
That is an issue with madVR, your graphics driver, or some third party application that is interfering with the video.

It is NOT the fault of LAVFilters. You might not get the same issue with other decoders because of hardware decoding settings. Try with DXVA2 Copyback if you currently use Native. That avoids DXVA2 processing issues in madVR.

**Comment by purenoise** [comment]
Ok,
did few testing, and  this 'black cursor' appears when
i in LAVFilters \ Video Decoder \ Properies \ Hardware Device to use:
select 'Intel HD Graphics' and
Option 'Hardware Decoder to use' does not matter.
Note: madVR not installed.
Attach: my setup
![1a](https://user-images.githubusercontent.com/4173913/97901580-0c39de00-1d45-11eb-8f3a-4317e470650a.png)
![2a](https://user-images.githubusercontent.com/4173913/97901581-0cd27480-1d45-11eb-941c-16521b8d39c2.png)

So this is Intel HW decoder issue ?

**Comment by clsid2** [comment]
Yes, issue with Intel driver.
