### ISSUE TITLE
OPUS low bitrate speech distortions

### ISSUE THREAD

**Issue by Artofeel** [Nevcairiel/LAVFilters#38]
I have some weird sound distortions bug with OPUS encoded on very low bitrate
Decoding opus with opusdec gives normal sound. No distortions. So it definitely something with LAV Audio Decoder
on 2 chanels it's start from < 48kbps
on 6 chanels it's start from < 224kbps
here is samples
http://www.mediafire.com/download/tiab1o4w6wtb6j3
encoding on high bitrates is not an option since opus is designed for low bitrates (better then to use aac for compatibility)
also 0.62 version doesn't have this bug, so I fall back LAVAudio.ax to it and it's sounds OK

PS: yea.. now there is "issues" section finally :)

**Comment by Nevcairiel** [comment]
I've forwarded the issue to the developer of the opus decoder, and he is looking into it.

**Comment by Nevcairiel** [comment]
After a bunch of back and forth, the developers of the opus codec seem to be in agreement that the decoder is fine, and it was a bug in the encoder, which was fixed.

I suggest you switch to the 1.1.1-rc encoder, and hopefully the problem will vanish.

**Comment by Artofeel** [comment]
well... I think I will stay on 0.62 version of audio decoder, since I don't see much difference (except this thing)
old decoder only have this distortions on seeking (and only on very "chaotic" seeking), but it so small and quick disappear, so it definitely better that new one
good to now that bug in encoder is fixed, but I'm not happy to transcode lossy sound
anyway, can you just use old decoding algorithm (v0.62) for this kind of files, or it's impossible to track them? I believe that the "good" decoder must (have to try) bypass any encoder errors :)

**Comment by Nevcairiel** [comment]
I cannot. The encodes are buggy, that is all. Its pure luck that the old decoder sounds better.

**Comment by Nevcairiel** [comment]
Note that only the 1.1.1-beta encoder was broken, 1.1 was fine, so the reason is simply using beta-quality software for encoding audio. Problems are bound to happen.

1.1.1 final has also been released now.
