### ISSUE TITLE
Update NVCUVID to NVDECODE for better NVIDIA hw acceleration?

### ISSUE THREAD

**Issue by OneOfMany07** [Nevcairiel/LAVFilters#381]
I ran across these pages about an updated API for accessing NVIDIA accelerators for video encode and decode.  As an NVIDIA card owner (1080 ti) who'd hoped for low system usage in video playback, I've been sad to hear their CUVID support in Windows 10 apparently has issues.  I never did figure out what those were...and most posts were from a long time ago.

Could an API change/update help?  Seems like NVIDIA thinks FFMPEG is already using it by an advertisement on their download page.

https://developer.nvidia.com/nvidia-video-codec-sdk

Appreciate all the work you have already put in, and any time you can spend to investigate it.

**Comment by Nevcairiel** [comment]
This is the same API, they just rebranded it. Nevertheless there are some plans in the future to re-work how CUVID/NVDEC works in LAV Filters, but thats mote of a long-term goal.
