### ISSUE TITLE
Audio Track not detected in MPEG-PS format

### ISSUE THREAD

**Issue by SunMaungOo** [Nevcairiel/LAVFilters#383]
I am using **0.69.0.7-git** version and the **MPC-HC** detect the two audio track in the **MPEG-PS** format.  When I upgrade the LAV filter to the latest release version (**0.74.1**) and play the same **MPEG-PS** file again, the **MPC-HC** only detect the single audio track even though it should detect two audio track.

I have attach the log file generated by the **media info** tool. I notice that in log file, the **media info** detect two audio track.  Is the problem related to LAV filters or it is the problem with **MPC-HC** player? 

Logs file

[0.69.0.7-git.txt](https://github.com/Nevcairiel/LAVFilters/files/5618633/0.69.0.7-git.txt)
[0.74.1.txt](https://github.com/Nevcairiel/LAVFilters/files/5618634/0.74.1.txt)

**Comment by clsid2** [comment]
Upload sample file somewhere. For example [Sendspace](https://www.sendspace.com/)

**Comment by SunMaungOo** [comment]
@clsid2 
 
I have upgrade to LAV filter **0.74.1.90-git** version by installing K-Lite codec pack **15.9.0** which have LAV filter of **0.74.1-90-gb7d7f** and the problem is solved. 

I have attach the log file generated by **media info** below for reference.

Log file

[0.74.1.90-git.txt](https://github.com/Nevcairiel/LAVFilters/files/5642571/0.74.1.90-git.txt)
