### ISSUE TITLE
D3D11 Issue with New NVIDIA'S 30 Series GPU

### ISSUE THREAD

**Issue by ndimz** [Nevcairiel/LAVFilters#386]
Experiencing a non-play issue with mkv files and Nvidia's new RTX 3070 with latest drivers. Switching to CUVID did resolve this however.

Hope this input pans out helpful . Thanks

**Comment by Nevcairiel** [comment]
You would have to provide information about the file, which version of LAV you are using, and preferably a sample file for this to be an actionable issue.

**Comment by ndimz** [comment]
Nvidia's latest Hotfix v460.97 fixed the non-playback using D3D11 for me somehow. We can close this issue
