### ISSUE TITLE
Feature request: MSI Installer

### ISSUE THREAD

**Issue by maxi07** [Nevcairiel/LAVFilters#387]
Hey there, is there any way that you can also package a MSI installer for enterprise distribution? We are using Microsoft Intune for application distribution and I would love to spread your software across our machines.

**Comment by clsid2** [comment]
You can wrap .exe installer into a .intunewin file for deployment. Google how to do that.

For installer use /verysilent command-line switch.
For uninstaller use /silent

**Comment by Nevcairiel** [comment]
I do not plan to add this directly.

**Comment by shubhank008** [comment]
Question, can we package the .exe installer with our app/zip and run it with above command line switch (/verysilent) to install it ? Would love to ship LAV with our app to our users who face codec issues with mkv but are too amateurs to direct them to manually install LAV, as such we wanted to package it with our app's folder itself and provide a in-app button to install the codecs.  

One way I figured would be to include the zip file/folder and run the .bat files, but if .exe can work it would be better.  

PS: Do you still need administrative power to install via .exe ?
