### ISSUE TITLE
QuickSync Memory leak

### ISSUE THREAD

**Issue by lbolster** [Nevcairiel/LAVFilters#39]
Hello,
firt of all...good work nevcairiel! LAV filters are my favourite.
I play regularly short 4k or HD clips on my tv in my living room for deco reasons, using a small Haswell miniITX computer and a r7 radeon and VVVV software. I noticed that after a long time  the VVVV patch suddenly closed always, and tracked the problem due to a shortage of memory. I then reproduced the problem playing them in MPC, and had the same results. The problem is when VVVV or MPC loads a new/different video, it's ram footprint get bigger and bigger (maybe 500kb or 1 MB each new video). This ony occurs if QuickSync HW acceleration is enabled. I also want to point out that the intel iGPU does not render as the TV is plugged to the radeon. And that I use Haali Splitter and Mkv/H264 videos, some with audio and no subtitles at all.
Attached is Graph I use and some other info I got from my computer. I tried LAV filter 0.65 and 0.66.
If you need any other info please tell me.

https://www.dropbox.com/s/rhynuwbsu8hqnni/memory_leak_mpc_con%20haali_splitter.zip?dl=0

Thanks for making these awesome filters.

**Comment by Nevcairiel** [comment]
The QuickSync decoder is a third-party component, and not developed by myself. Either report it to the author directly (http://sourceforge.net/projects/qsdecoder/), or switch to DXVA2-CopyBack, which is the recommended HW decoding mode.
