### ISSUE TITLE
Feature request: Logoaway - like in FFDSHOW

### ISSUE THREAD

**Issue by greyboxgt** [Nevcairiel/LAVFilters#390]
Feature request: Logoaway - like in FFDSHOW. This will help a lot with the screens burn-in problem.

![logoaway](https://user-images.githubusercontent.com/11550307/105080790-30ed4a00-5a46-11eb-9ce0-b8420fd4667d.JPG)

**Comment by Nevcairiel** [comment]
LAV Filters does not plan to support video processing/filtering.
