### ISSUE TITLE
Will you compile a new release?

### ISSUE THREAD

**Issue by casperfrx** [Nevcairiel/LAVFilters#393]
Hi there,

I was wondering whether you were willing to compile a new release here on Github seeing how you're nearing almost 100 new commits on the master branch. :)

Thanks!

**Comment by PA4WD** [comment]
Here you can download the latest nightly builds
https://files.1f0.de/lavf/nightly/

**Comment by casperfrx** [comment]
> Here you can download the latest nightly builds
> https://files.1f0.de/lavf/nightly/

Thanks! Very helpful. You're building this yourself? I couldn't get it the ffmpeg to build using the VC shell file using all the VC path bats.

Anyway got a binary now, thanks!

**Comment by PA4WD** [comment]
I think Nevcairiel owns the server.
I only know the url from http://forum.doom9.org/showthread.php?t=156191
Nightly's are automatic build after a commit in this repro.

**Comment by Nevcairiel** [comment]
A new release is planned to be released in March.
