### ISSUE TITLE
please add support ProRes4444XQ 

### ISSUE THREAD

**Issue by igitlin** [Nevcairiel/LAVFilters#394]
please add support ProRes4444XQ id ap4x
all other Prores is a works - ProRes LT, 422, 422HQ, 4444

**mediainfo:**
Format : MPEG-4
Format profile : QuickTime
Codec ID : qt 2005.03 (qt )
File size : 47.4 GiB
Duration : 5 min 15 s
Overall bit rate mode : Variable
Overall bit rate : 1 292 Mb/s
Encoded date : UTC 2021-01-16 20:54:05
Tagged date : UTC 2021-01-16 20:54:05
Writing library : Apple QuickTime

Video
ID : 1
Format : ProRes
Format version : Version 1
Format profile : 4444 XQ
HDR format : SMPTE ST 2086, HDR10 compatible
Codec ID : ap4x
Duration : 5 min 15 s
Bit rate mode : Variable
Bit rate : 1 278 Mb/s
Width : 3 840 pixels
Height : 2 160 pixels
Display aspect ratio : 16:9
Frame rate mode : Constant
Frame rate : 24.000 FPS
Color space : YUV
Chroma subsampling : 4:4:4
Scan type : Progressive
Bits/(Pixel*Frame) : 6.422
Stream size : 46.9 GiB (99%)
Writing library : afl0
Language : English
Encoded date : UTC 2021-01-16 20:54:05
Tagged date : UTC 2021-01-16 20:54:05
Color primaries : BT.2020
Transfer characteristics : PQ
Matrix coefficients : BT.2020 non-constant
Mastering display color primaries : Display P3
Mastering display luminance : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level : 1000 cd/m2
Maximum Frame-Average Light Level : 400 cd/m2

**Lav spletter:LAV Splitter Source (internal)::Video**
Media Type 0:

Video: AP4X 3840x2160 24fps 1336790kbps

AM_MEDIA_TYPE:
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: Unknown GUID Name {78347061-0000-0010-8000-00AA00389B71}
formattype: FORMAT_VideoInfo {05589F80-C356-11CE-BF01-00AA0055595A}
bFixedSizeSamples: 0
bTemporalCompression: 1
lSampleSize: 1
cbFormat: 88

VIDEOINFOHEADER:
rcSource: (0,0)-(3840,2160)
rcTarget: (0,0)-(3840,2160)
dwBitRate: 1336790188
dwBitErrorRate: 0
AvgTimePerFrame: 416667

BITMAPINFOHEADER:
biSize: 40
biWidth: 3840
biHeight: 2160
biPlanes: 1
biBitCount: 24
biCompression: ap4x
biSizeImage: 24883200
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 00 0f 00 00 70 08 00 00 ............p...
0010: 00 00 00 00 00 00 00 00 00 0f 00 00 70 08 00 00 ............p...
0020: ac cc ad 4f 00 00 00 00 9b 5b 06 00 00 00 00 00 ¬Ì­O....�[......
0030: 28 00 00 00 00 0f 00 00 70 08 00 00 01 00 18 00 (.......p.......
0040: 61 70 34 78 00 b0 7b 01 00 00 00 00 00 00 00 00 ap4x.°{.........
0050: 00 00 00 00 00 00 00 00 ........

 sample: [https://yadi.sk/i/d8kCjFCCx0vRJQ](https://yadi.sk/i/d8kCjFCCx0vRJQ)

**Comment by ValZapod** [comment]
It is unplayable on anything not from last year.

You can just use mpv for that.
