### ISSUE TITLE
Stuttering video with TV channel "ZDFinfo HD" (H.264)

### ISSUE THREAD

**Issue by Stephaen** [Nevcairiel/LAVFilters#396]
I'm using LAVFilters 0.74.1 with DVB Viewer Pro 7.0.2.0 (last version) on Windows 10 (20H2)  to decode SD and HD TV channels. I have a problem with one German channel: "ZDFinfo HD" (H.264). On this channel (and apparently only this one), video stutters every 1 second. The only way to get rid of the problem is to use another decoder (ffdshow Video Decoder or ffdshow DXVA Video Decoder).

Is this something that you can fix?

Note: I tried the 0.74.1.92-git beta version but it didn't solve the problem. 

Thanks in advance,

Stephaen

**Comment by Olddriverdad** [comment]
Thanks

**Comment by Nevcairiel** [comment]
I've just tuned into that channel, and not experiencing any issues with the latest version.
Can you elaborate on your settings, which hardware settings, if any?

**Comment by Stephaen** [comment]
The problem doesn't appear anymore. The only thing I did was to update to the latest 21.2.3 version of the AMD Radeon software. Not sure if it was the culprit or not, maybe the TV channel changed something too. Anyway, thanks for the attention.

Best regards.
