### ISSUE TITLE
Dolby Pro Logic II - Mix Stereo To Center

### ISSUE THREAD

**Issue by vdrfan** [Nevcairiel/LAVFilters#40]
Dolby Pro Logic II is not working as it should.
is there anything planed to support Dolby Pro Logic II like in ffdshow.
it is horrible when dialogue is not at Center (for Stereo Soruces only).
regards, onur

**Comment by Nevcairiel** [comment]
LAV does not offer any upmixing, Dolby Pro Logic or otherwise. The DPL mixing options are for down mixing only, for 5.1 to stereo.

There are no plans for a DPLII decoder.
