### ISSUE TITLE
Support for embedded .vtt subtitles (WebVTT)

### ISSUE THREAD

**Issue by fosam** [Nevcairiel/LAVFilters#400]
- Embedded `vtt` (WebVTT) subtitles in a video are not displaying even if the subtitles are enabled and the language is selected as in the screenshot below:

![Capture 18_03_2021_02_04_28](https://user-images.githubusercontent.com/52612348/111559436-cd0aa780-8790-11eb-93bb-762f75285c4d.png)

- If the `vtt` subtitiles are converted to another format then it won't be possible for `ffmpeg` to merge them with the video.

![Capture 18_03_2021_02_37_51](https://user-images.githubusercontent.com/52612348/111560772-836f8c00-8793-11eb-9747-7ab07a6677aa.png)

- **_vtt subtitles have become very common nowadays._**

- If this issue is not possible to fix, can someone at least make the `vtt` subtitles display as text so that we won't have to switch to a different player with `vtt` support?

- **_Tested using mpc-hc_**

- @clsid2 Is there any solution to this at all?

**Comment by clsid2** [comment]
The only fix needed in LAV Splitter is setting the correct subtype.
{C886D215-F485-40BB-8DB6-FADBC619A45D} = MFSubtitleFormat_WebVTT

Once that is done I can enable support for it in MPC-HC.

**Comment by fosam** [comment]
Almost all other players that don't include LAV filters by default have natine embedded `vtt` support.

I have been waiting for over 5 years for embedded `vtt` support to come to MPC-HC but without luck even to this day, switching from MPC-HC to something else is a very tough decision.

I think it is in time for LAV filters to support embedded `vtt` and i hope they can really implement this very soon.

@clsid2 Thanks!

**Comment by clsid2** [comment]
I have made a patch:
https://github.com/clsid2/LAVFilters/commits/master

**Comment by fosam** [comment]
Great!

I can confirm that embedded `.vtt` subtitles are now working properly. ✔

Couple of questions:

It seems you are using your forked version of LAVFilters instead of this one, right?

Did you also release .exe's of MPC-HC Development Build that contain this fix? because i noticed K-Lite Codec Pack released just now has this fix, how did this go so quickly?

![Capture 20_03_2021_00_21_30](https://user-images.githubusercontent.com/52612348/111851338-12ef7900-8913-11eb-81a8-5f386fc585c0.png)

**Comment by clsid2** [comment]
Development build of MPC-HC is available here:
https://github.com/clsid2/mpc-hc/releases

**Comment by fosam** [comment]
But how was it released to K-Lite Codec Pack in no time?

**Comment by ale5000-git** [comment]
Maybe he has fast PC and fast connection ;)

**Comment by fosam** [comment]
I doubt it has something to do with the PC and connection, now i don't know who K-Lite Codec Pack are, but i think they compile the code as soon as it is released and then update the codec pack with the new fixes, but i'm not sure..

**Comment by ale5000-git** [comment]
If you meant that, I took it for granted that you know that it is the same person.

He is that author of the K-Lite Codec Pack, the one that maintain the fork of MPC-HC, LAVFilters, ffmpeg (forked from Nevcairiel ones) and also the one that was maintaining the fork of Media Player Classic years ago.

**Comment by fosam** [comment]
Do you mean **clsid2** is the owner of  K-Lite Codec Pack too? if yes, then i did not know that, there's no way i could tell 🤔

**Comment by ale5000-git** [comment]
Yes, by following the messages in the K-Lite Codec Pack forum became obvious, but maybe it isn't without it.

**Comment by fosam** [comment]
He might be just a member of K-Lite Codec Pack team.

**Comment by ale5000-git** [comment]
They is just one Admin in the forum, but really we are off-topic.

**Comment by fosam** [comment]
Thanks.

**Comment by Nevcairiel** [comment]
WebVTT in Matroska is quite a mess, with two competing formats (from WebM and Matroska), which is why its not as simple (and ill-advised) to simply export it without further considerations, because I can 100% guarantee that the format will change when I add proper support similar to other subtitle codecs.

If MPC-HC insists on rushing this out, its on them to deal with any future changes to the format.

**Comment by Nevcairiel** [comment]
Basic implementation in 7fa9eca9201c6b8068e548dc13c8d253498754a2.

Due to lack of comprehensive WebVTT support in DirectShow, I may leverage FFmpeg to convert it into ASS, but thats for a future update.

**Comment by fosam** [comment]
That's at least a slight improvement, Thanks!
