### ISSUE TITLE
Default flag for audio stream always overrides the "Prefer Audio Stream with the highest quality" option

### ISSUE THREAD

**Issue by DecalicatanDecalicatan** [Nevcairiel/LAVFilters#405]
With "Prefer Audio Stream with the highest quality" ON in LAV Splitter, the (preferred) audio stream with the highest quality should be played automatically instead of the (preferred) audio stream with the default flag when both streams have the same language code.

For example a mkv file with 2 audio streams:
1-  [eng] flac 2.0 (48kHz, 16bits) stream flagged as default
2- [eng] TrueHD 5.1 (48kHz, 24bits). 

Expected behavior: the stream 2 is automatically selected
Actual behavior: the stream 1 is automatically selected

Or maybe a check box could be added to force the selection ("Default flag over Highest quality" versus Highest quality over Default flag"

**Comment by Nevcairiel** [comment]
The Matroska specification is pretty clear about the intended behavior, and I'm not too keen on trying to override it.

**Comment by DecalicatanDecalicatan** [comment]
Too bad :(

I agree it's better the default behavior ( even with the option checked) is in line with the Matroska specs. 
The ideal solution may be an additional check box so the user can change the behavior to the preferred one (Highest quality over Default flag" in my case). But it may be too much a hassle for something nearly nobody ask for ^^

But if you have some time to lose, one day, when you have nothing else to do  with LAV Splitter development ...
