### ISSUE TITLE
AV1 hardware decode not being used on Tigerlake (warning lots of images). 

### ISSUE THREAD

**Issue by nathanielcwm** [Nevcairiel/LAVFilters#406]
The built in filters on clsid2/MPC-HC 1.9.10.44 were replaced with the release of 0.75
Using a test clip I observed that frames were being dropped and that the video was unable to be played in sync with the audio.

![image](https://user-images.githubusercontent.com/22572406/113121640-6e8c0180-9245-11eb-857d-2232f5082a49.png)

Forced on D3D11:
![image](https://user-images.githubusercontent.com/22572406/113120761-81520680-9244-11eb-8d3f-8d90f025ea75.png)

Forced on DXVA2 copy:
![image](https://user-images.githubusercontent.com/22572406/113121558-5caa5e80-9245-11eb-98c6-568366ddc6c2.png)

Only video processing is loaded not video decode:
![image](https://user-images.githubusercontent.com/22572406/113120906-a8a8d380-9244-11eb-8d51-62f8e716da0a.png)

Same video being played on the Microsoft shit:
![image](https://user-images.githubusercontent.com/22572406/113121012-c6763880-9244-11eb-8f0e-09dad6852c3c.png)

Video being played through Edgium:
![image](https://user-images.githubusercontent.com/22572406/113121224-03422f80-9245-11eb-9a2d-420242725d7f.png)

i5-1135G7
Windows 10 20H2

**Comment by nathanielcwm** [comment]
BTW looks like Tigerlake supports grain synthesis in hardware. Using the Netflix Sparks test clip a noticable amount of grain is added when played through the Microsoft app. 

CPU usage remains < 5% throughout the entirety of playback unlike when played through VLC,which doesn't support hardware acceleration of AV1, where CPU is always around 5-20%

It looks like the Netflix sparks clip plays fine with hardware acceleration in MPC-HC so here's the test clip that I was using:
https://cdn.discordapp.com/attachments/677266163994198020/800842367929286676/llama-song.webm

**Comment by nathanielcwm** [comment]
If I switch to madVR the issue goes away so it may be a problem with MPC-HC's directshow output.

**Comment by clsid2** [comment]
D3D11 native is only supported by madVR and MPC-VR. Other video renderers will use D3D11 copyback.

**Comment by nathanielcwm** [comment]
With LAVFilters 75-2 I can confirm that forcing copy back for D3D11 makes it use hardware decode. @clsid2 
![image](https://user-images.githubusercontent.com/22572406/113318661-41257d80-9343-11eb-9a7e-f4285771996b.png)

Unfortunately it's still experiencing video freezing and desyncs that aren't experienced with madVR.

DXVA2 native and copyback still doesn't appear to be working
![image](https://user-images.githubusercontent.com/22572406/113318794-6619f080-9343-11eb-835b-239ca1fe661c.png)
![image](https://user-images.githubusercontent.com/22572406/113318959-8e095400-9343-11eb-8ea4-756801eb3821.png)

**Comment by nathanielcwm** [comment]
Something else I found that's extremely weird. Even with forced copyback on D3D11 using both EVR and madVR H264 is not using hardware acceleration. Both native and copyback DXVA2 use hardware acceleration perfectly fine tho...

**Comment by clsid2** [comment]
EVR-CP is an inferior renderer compared to madVR and MPC-VR.

If either DXVA2 or D3D11 is not working, you need to go complain to Intel to fix their drivers. Only test with 8-bit H264, because acceleration is not possible with 10-bit.

**Comment by nathanielcwm** [comment]
Yes as I said in my comment it was an 8 bit H264 track.

**Comment by Nevcairiel** [comment]
I heard some talk about Intel discontinuing D3D9/DXVA2 support. Not sure if thats true.

**Comment by nathanielcwm** [comment]
Chromium only supports AV1 decode with DXVA2 rn so I doubt that a lack of support is the issue.

Looks like DXVA2 is broken in madVR too.

**Comment by nathanielcwm** [comment]
Unfortunately, both issues still persist on latest driver.

It looks like h264 being broken is exclusive to the test vid I was using tho...
https://billwurtz.com/might-quit.mp4

AV1 issues persist on other AV1 clips I have on this machine tho...

**Comment by Nevcairiel** [comment]
The driver probably rejects that file due to the odd dimensions, which are technically invalid for the format its using.

**Comment by nathanielcwm** [comment]
Strange that the Microsoft shit and VLC are using hardware decode...

**Comment by ale5000-git** [comment]
@clsid2: Why MPC-HC still saying `Playing [H/W]` even though hardware acceleration is not used?

Is this a bug?
