### ISSUE TITLE
How to set user agent

### ISSUE THREAD

**Issue by sudongg** [Nevcairiel/LAVFilters#409]
Some videos need to add request headers to play. Can request headers be added to LAV filter?

**Comment by sudongg** [comment]
I found a way to add  in AVDictionary.
```
AVDictionary *options = nullptr;
av_dict_sett(&options, "headers", ");
```
This requires modifying the source code. I hope it can be set directly in the ILAVFSettings interface.
There are many network streaming videos that need to set custom headers.
@Nevcairiel

**Comment by Nevcairiel** [comment]
I've added a dedicated interface to open URLs with a specified user-agent and referer for the next update
https://github.com/Nevcairiel/LAVFilters/blob/master/include/IURLSourceFilterLAV.h
