### ISSUE TITLE
Question about software decoder

### ISSUE THREAD

**Issue by bellgenius** [Nevcairiel/LAVFilters#414]
I have installed LAV 75.0 on Win10
I want to choose "none" on LAV video decoder for software decoding
but it will change to DXVA2(copy back)  every time I restart PC 
Does anyone know how to solve it?

**Comment by Nevcairiel** [comment]
LAV by itself uses software decoding by default and does not override your choices. Maybe another part is interacting with it, your player, or a codec pack.
