### ISSUE TITLE
Problem with left\right channel balance for ac3?

### ISSUE THREAD

**Issue by Owyn** [Nevcairiel/LAVFilters#415]
I've been having this issue for lots if not most movie files - translated audio stream has most sound effects shifted to left channel and right channel stays pretty much silent while the original or official DUB is totally fine in that term

can you check and say if it's a problem of my lav mixing software somehow or just that 90% of our translators are idiots and ruin the sound?

example original and TL stream attached:
```
Video: MPEG4 Video (H264) 1920x1080 23.976fps [V: English [eng] (h264 high L4.0, yuv420p, 1920x1080) [default]]
Audio: Dolby AC3 48000Hz 6ch 640kbps [A: LF [rus] (ac3, 48000 Hz, 5.1, 640 kb/s) [default]]
Audio: DD+ 48000Hz 6ch 640kbps [A: Eng [eng] (eac3, 48000 Hz, 5.1, 640 kb/s)]
Subtitle: UTF-8 [S: SDH [eng] (subrip)]
Subtitle: UTF-8 [S: No subtitles]
```

[Leg_test_CUT.mkv.zip](https://github.com/Nevcairiel/LAVFilters/files/6413515/Leg_test_CUT.mkv.zip)

**Comment by clsid2** [comment]
It is not a problem in LAV. Left and right channel have similar sound here for the English track.

**Comment by Owyn** [comment]
Are you saying it sounds the same on both audio streams  for you? - that means the problem is in the LAV then?

cuz it sounds only balanced for me on ENG channel (2nd)

I can make a record via OBS studio of me playing the file to show the difference if needed, is it?

**Comment by clsid2** [comment]
I am saying there is NOT a problem in LAV.

If you disable the mixer in LAV then you can see volume levels of all channels on its status page in the settings window, which you can access through its system tray icon.

**Comment by Owyn** [comment]
I see, thought I just wanted to hear you say that it's the source's fault and not the software, that's all.
Neither confirming nor denying that the problem exists not only for me wasn't helpful at all...

**Comment by clsid2** [comment]
I already said that right channel has sound here with both audio tracks. There is no big difference in volume between left and right.

**Comment by ale5000-git** [comment]
@Owyn: It is also possible that the problem is just in your pc, with audio driver settings or other mixer settings that cause this.

**Comment by Owyn** [comment]
![kurilshik](https://user-images.githubusercontent.com/1309656/116887896-7e777680-ac33-11eb-9b63-09697f0b6046.jpg)
It's a rather big difference for me here, makes ears physically uncomfortable, so any kind of help would be much appreciated or at least where to look for clues

**Comment by Owyn** [comment]
Update: I just disabled muxing in settings and now it's perfectly normal for both audio streams including problematic one...  
![image](https://user-images.githubusercontent.com/1309656/116888799-8b489a00-ac34-11eb-834b-1d8077d0ef20.png)

are you sure it's how mixing is supposed to work (making left \ right channel totally unbalanced in the result) ?
here's my settings (pretty much default ones, no?):
![image](https://user-images.githubusercontent.com/1309656/116888955-b7641b00-ac34-11eb-9d6e-765ec0af3f62.png)

**Comment by clsid2** [comment]
Set matrix encoding to None.

**Comment by Owyn** [comment]
> Set matrix encoding to None.

Then sound becomes kinda flat and effects quite on 1st audio stream (but still normal for original eng one)

with just mixing disabled it's the same for both audios

**Comment by ValZapod** [comment]
DialNorm?

**Comment by Nevcairiel** [comment]
Dolby Pro Logic encoding will sound weird if you listen to it through speakers or headphones. Its designed to be decoded again by a Dolby Pro Logic compatible decoder. Don't use it if you don't have something like that in your audio chain.
