### ISSUE TITLE
8k60 AV1 HW decoding slow playback/low fps

### ISSUE THREAD

**Issue by chorong761** [Nevcairiel/LAVFilters#417]
When I try to use LAV video decoder (0.75.0-2) to play a youtube 8k60 av1 video (dxva copyback, lav video decoder settings untouched except for changing to copyback), the video playback would be slow. It would play back at around 30ish fps. I've tried changing video renderers but still doesn't help. CPU and GPU usage is not maxed out, no drop frames during the slowed down playback and audio works fine.

Disabling DXVA in potplayer would just cut the playback framerate in half. 

 If I revert to using potplayer built in codecs, it would playback fine at 60fps. Am I doing anything wrong or is there a bug?

Device specs: Ryzen 9 5900HS, RTX 3060 Mobile, 32GB RAM

Running latest stable potplayer 64bit (210428)

**Comment by Nevcairiel** [comment]
Don't use Copyback, you are most likely memory bandwidth bottlenecked at that point. Use Native, then it'll be much faster.
