### ISSUE TITLE
dav1d 0.9

### ISSUE THREAD

**Issue by nathanielcwm** [Nevcairiel/LAVFilters#420]
https://code.videolan.org/videolan/dav1d/-/releases/0.9.0

Much faster decoding of 10 bit content.

![image](https://user-images.githubusercontent.com/22572406/118798703-850f1a80-b8d0-11eb-9fb6-e576afcb032e.png)

**Comment by Nevcairiel** [comment]
I follow changes of note to the core components LAV uses, no need to open issues about it.
