### ISSUE TITLE
Unable to play local m3u8/HLS

### ISSUE THREAD

**Issue by FX8350** [Nevcairiel/LAVFilters#423]
Online m3u8/HLS works perfectly, but local m3u8/HLS cannot be played in MPC-HC. (clsid2/mpc-hc#1117)
The playlist segments are marked with relative paths, not URLs. (Please see the attached sample file).
In VLC, it can be played.
[test2.zip](https://github.com/Nevcairiel/LAVFilters/files/6563767/test2.zip)

**Comment by Nevcairiel** [comment]
The HLS stream plays just fine with LAV Splitter. When I try to play it in MPC-HC, it never even attempts to open it with LAV Splitter, and only sends the first .ts file to LAV. 

This needs to be fixed in MPC-HC.

**Comment by clsid2** [comment]
Fixed in MPC-HC
