### ISSUE TITLE
Glitch on FF/REW/dragging H.264 .TS dumped from legit Blu-ray Discs

### ISSUE THREAD

**Issue by MelonGx** [Nevcairiel/LAVFilters#424]
I redumped the disc but it still occured so I don't think it's a file error.
If I use non-LAV decoder, or use LAV's 2019 or earlier versions, or simply disable LAV's HD resolution's hardware decoding, then it doesn't happen.
I'll upload screenshot 3 hours later.

**Comment by clsid2** [comment]
You need to provide a sample file, and the timestamp at which a glitch occurs.

**Comment by MelonGx** [comment]
https://user-images.githubusercontent.com/7697767/120090078-b55d8100-c13a-11eb-9714-30344939cbbb.MP4

**Comment by ValZapod** [comment]
You use madvr.

**Comment by MelonGx** [comment]
> You are using madvr.
I changed madVR to MPCVR but the glitch still happens.
I uncheck HD box on LAV settings then the glitch disappears.
It's 100% LAV issue.

**Comment by Aleksoid1978** [comment]
Upload short sample.

**Comment by Nevcairiel** [comment]
Indeed an actual sample of the video file would be required. Not a screen capture of your player =)
