### ISSUE TITLE
lav can't play this video is it need update ?

### ISSUE THREAD

**Issue by pop-dahaka** [Nevcairiel/LAVFilters#426]
hi ,
thanks for your perfect work and wish you good life .

this channel is broadcasting (attached screen shot) but video black screen , attached record file for 1 minute .
![SCARE TV analyze2](https://user-images.githubusercontent.com/17509547/121234756-5b745e00-c894-11eb-9933-71bc6157e96f.png)

[SCARE TV analyze2.zip](https://github.com/Nevcairiel/LAVFilters/files/6618665/SCARE.TV.analyze2.zip)

> Video
ID                                       : 1608 (0x648)
Menu ID                                  : 8008 (0x1F48)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : M=4, N=24
Format settings, picture structure       : Frame
Codec ID                                 : 2
Duration                                 : 1 min 8 s
Bit rate mode                            : Variable
Bit rate                                 : 1 098 kb/s
Maximum bit rate                         : 15.0 Mb/s
Width                                    : 528 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.144
Stream size                              : 8.99 MiB (88%)

>

**Comment by Nevcairiel** [comment]
The video seems to decode just fine, but the content is just black. Are you sure there is meant to be an image there?

**Comment by pop-dahaka** [comment]
it was working and the second day there is no image about 10 days ago till now , so i doubt there is some changing in video stream . 
no am not sure about the image but you check it and the decode fine so the black screen from them .
thank you very much.

**Comment by gizmocuz** [comment]
I have analyzed the transport stream and the video is indeed black.
All PES frames contains stuffing data at the end (00) , so it looks like it's a 1.2Mbps video PID, but it's empty/stuffed
(Slice 36 is completely filled with 0x00)
