### ISSUE TITLE
LAV ignores mkv container AR for mpeg1 video

### ISSUE THREAD

**Issue by sneaker2** [Nevcairiel/LAVFilters#43]
Sample: https://www.sendspace.com/file/54t8z2

No matter how "Use Stream Aspect Ratio" in LAV Video is set, it will always use 160x120, not the 1000x130 set in the mkv container (crazy value for testing purposes).

**Comment by Nevcairiel** [comment]
mpeg1 uses [MPEG1VIDEOINFO](https://msdn.microsoft.com/en-us/library/windows/desktop/dd390700(v=vs.85).aspx) which does not allow communicating the AR from the container. This codec is not designed for such a use, apparently.
