### ISSUE TITLE
Output RGB fps 60 → 26

### ISSUE THREAD

**Issue by 28598519a** [Nevcairiel/LAVFilters#431]
When a 4K video is processed by LAV filiters, the FPS of the movie changes from 60 to 26, and the video changes into slow motion.

YV12、NV12 was tested and OK, only occurs in RGB32 and RGB24 when the video is more than 4096*2160.

PS. CPU usage less than 35%

**Comment by clsid2** [comment]
That is not a bug. Converting colorspace costs performance and afaik it isn't multi-threaded.

**Comment by ValZapod** [comment]
> performance and afaik it isn't multi-threaded.

It now is. https://github.com/FFmpeg/FFmpeg/commits?author=elenril

**Comment by clsid2** [comment]
LAV does not do any HDR conversion. That is left to the renderer to do.

It also doesn't use swscale for all conversions. It actually has its own code for some of the most common conversions.

**Comment by ValZapod** [comment]
> has its own code for some of the most common conversions.

Oh, well, you may wanna reinvestigate it now. :) Constant luminance BT.2020 matrix for example is done in mpv, but not here.

**Comment by Nevcairiel** [comment]
LAV is designed for as-is output, conversions are only supported for convenience and testing, but any video processing should ideally be done on the graphics card, as those are specifically designed for processing images.
