### ISSUE TITLE
SetPositions edge case issue when seeking to end

### ISSUE THREAD

**Issue by clsid2** [Nevcairiel/LAVFilters#432]
When current position is near the end, then a seek to the end does not work properly in some cases. As a result, the EC_COMPLETE graph event does not trigger, breaking for example repeat or automatic jump to next file.

To reproduce:
[Sample file](https://www.sendspace.com/file/pzkl1q)
Pause
Jump to 0:10:480
Jump to 0:10:800

After the first jump, the splitter reaches EOF when parsing:
`GetNextPacket(): End of File reached`
At that moment `m_rtCurrent` equals `108000000`. Even though playback itself is paused at `104800000`.
This causes the next jump to take this shortcut in SetPositionsInternal:
`if (m_rtCurrent == rtCurrent && m_rtStop == rtStop)`
Adding `&& rtCurrent != rtStop` there avoids the bug.
Then seek to end works (but video frame does not change). And a second seek to end triggers EC_COMPLETE. Not perfect yet, but at least better.

Any chance you can improve thise behavior? Ideally, seeking to end should just trigger EndOfStream directly.

**Comment by NanaMizukiAnother7** [comment]
I have encountered this bug a couple months ago. While I was doing my work with VEGAS Pro 16, this doesn't make me not feeling, but not good enough when I skipped to the end of the video.

However, this _never_ happen on AV Splitter. This will never be happened again when it was fixed!

**Comment by ale5000-git** [comment]
@clsid2: Link is dead

**Comment by clsid2** [comment]
[Sample](https://www.sendspace.com/file/p6htfr)

**Comment by NanaMizukiAnother7** [comment]
Looks like this latest one is not fixed yet...

**Comment by NanaMizukiAnother7** [comment]
This fixed it! THANK YOU!!
