### ISSUE TITLE
Cant play AVC1/HEVEC file

### ISSUE THREAD

**Issue by ivicask** [Nevcairiel/LAVFilters#434]
With combination of PotPlayer and latest LAV this file doesnt play while it plays fine with PotPlayer builting VIDEO decoder

`
Video
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L5@High
HDR format                     : SMPTE ST 2086, HDR10 compatible
Codec ID                       : V_MPEGH/ISO/HEVC
Duration                       : 2 h 22 min
Bit rate                       : 14.3 Mb/s
Width                          : 3 836 pixels
Height                         : 1 600 pixels
Display aspect ratio           : 2.40:1
Original display aspect ratio  : 2.40:1
Frame rate mode                : Constant
Frame rate                     : 23.976 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0 (Type 2)
Bit depth                      : 10 bits
Bits/(Pixel*Frame)             : 0.097
Stream size                    : 14.3 GiB (95%)
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.2020
Transfer characteristics       : PQ
Matrix coefficients            : BT.2020 non-constant
Mastering display color primar : Display P3
Mastering display luminance    : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level    : 1002 cd/m2
Maximum Frame-Average Light Le : 701 cd/m2

`

**Comment by clsid2** [comment]
This kind of files plays just fine for others, so the problem is likely on your end. Test playback with MPC-HC.

If you believe there truly is a problem with LAV Filters, then the only way to get it fixed is to provide a link to the file. The developer needs to be able to reproduce the problem.

**Comment by ivicask** [comment]
It plays fine on everything as long I don't select lav filter as decoder for it, also not sure how to provide this 14gb file to dev, I don't think it's allowed to link torrent files here?

**Comment by clsid2** [comment]
If the decoder gets loaded, but video is stuck, then disable hardware  decoding in the settings, or update your graphics driver.

You can post link. It will be removed if it is an issue.

**Comment by ValZapod** [comment]
You can just paste a magnet hash without actually mentioning it is a magnet.
