### ISSUE TITLE
H265 GUID does not match in UVC Camera

### ISSUE THREAD

**Issue by goldscu** [Nevcairiel/LAVFilters#436]
The GUID of H265 data read by UVC camera does not match. The GUID of DirectShow is {35363248-0000-0010-8000-00AA00389B71}, while the GUID of HEVC in LAV is {43564548-0000-0010-8000-00AA00389B71}, so it cannot Decoding, please solve this problem.

**Comment by clsid2** [comment]
The GUID that LAV uses is actually correct (FourCC "HEVC"). There are multiple FourCCs for same format. What you are asking is to additionally support FourCC "H265".

Upload a short sample file.
http://www.sendspace.com

**Comment by goldscu** [comment]
I can't upload a short sample file here, because I discovered this problem while debugging the uvc camera, and I need to debug with hardware equipment.
When using DirectShow, because the two GUIDs of the subtype of AM_MEDIA_TYPE are inconsistent, the decoder Pin cannot be connected with source filter's Pin. Other people’s inability to decode H265 should be caused by this problem. I mean can you support the GUID read by DirectShow{ 35363248-0000-0010-8000-00AA00389B71}

**Comment by clsid2** [comment]
I am not the developer. Just trying to help clarify things.

Which source filter are you using?

**Comment by goldscu** [comment]
The source filter is DirectShow offiial. When insert USB camera, the driver auto registed.
Thanks for you helping!

**Comment by goldscu** [comment]
I uploaded a picture when debuging use graphstudionext, the FourCC describe as MEDIASUBTYPE_H265{35363248-0000-0010-8000-00AA00389B71}. Can your additionally support it? Thanks!

**Comment by goldscu** [comment]
https://www.sendspace.com/file/vn3vwi

**Comment by goldscu** [comment]
![UVCSourceFilter](https://user-images.githubusercontent.com/13127889/128112697-74c74546-c309-4b61-b79b-e47638f0f5bd.png)

**Comment by ValZapod** [comment]
> Upload a short sample file.

I doubt there is any point to use this since dshow API is not yet good enough in ffmpeg.
