### ISSUE TITLE
Fails on FICV videos with atypical dimensions

### ISSUE THREAD

**Issue by TiberiumFusion** [Nevcairiel/LAVFilters#438]
I'm using LAVFilters 0.75.1 with A's Video Converter.
The LAV Video Decoder only seems to work on FICV videos with conventional resolutions (i.e. 1920x1080, 1280x720, etc). When given a video with an arbitrary resolution (like 1348x839), it immediately fails.

Test files:
[FICV Test Files.zip](https://github.com/Nevcairiel/LAVFilters/files/6997662/FICV.Test.Files.zip)

A's Video Converter is a really bad harness since it has absolutely zero tracing, but I don't know how else to invoke the LAV Video Decoder. I apologize in advance if this is rather an issue with A's Video Converter and not LAVFilters. I can't really tell from what I know (or rather don't know).

**Comment by Nevcairiel** [comment]
Neither of these files is supported by LAV Video currently, as this video codec is not supported.

**Comment by TiberiumFusion** [comment]
I am a bit confused now. Testing with A's Video Converter, the LAV Video Decoder decodes FICVs with typical resolutions just fine.

Is this compatibility just an incredible coincidence?
