### ISSUE TITLE
Management of 16 audio channel

### ISSUE THREAD

**Issue by francescoBLT** [Nevcairiel/LAVFilters#439]
Hi to all
It seems that LAV Splitter doesn't allow to select the output couple of audio channels (That is I want to ear only channel 7 and 8 in an 8 channel track).  There is  way to overcome ?
regards

**Comment by ValZapod** [comment]
What 16 channels? You mean in TrueHD? Or aac 24 channels? In last case only 9 channels can be selected for rematrixinh.

**Comment by francescoBLT** [comment]
There are mxf and mov files (usually encoded in DNxHD and prores) that have 16 audio tracks or a single audio tracks with 16 channels.   All audio is PCM (16 or 24 bit). I found that if I attempt to play an mxf file with 16 audio channels, the LAV output is correct (that is we have 16 audio channels as in the file) but windows doesn't render.  May be useful if we can select the output couple (that is 1,2 or 3,4 or 5,6 and so on).

**Comment by clsid2** [comment]
You need to use the Mixer if you are using an audio renderer that doesn't support 16 channels.

The developer is not going to implement selecting individual channels (or couples). Or any other new audio processing functionality.

**Comment by tebasuna51** [comment]
The [player mpc-hc]([url](https://forum.doom9.org/showthread.php?t=175209)) have in View -> Options -> Internal Filters -> Audio Switcher -> Enable custom channel mapping

That can help you francescoBLT?
![ChanMap](https://user-images.githubusercontent.com/23512903/161422057-528d0252-7079-4625-a5fa-4644da9abafc.png)

**Comment by francescoBLT** [comment]
I will check the code, thanks
