### ISSUE TITLE
Project IntelQuickSyncDecoder.vcxproj not found

### ISSUE THREAD

**Issue by francescoBLT** [Nevcairiel/LAVFilters#440]
Hi
I'm attempting to compile LAV filters with VS2019. I didn't found this project IntelQuickSyncDecoder.vcxproj when loading LAVFilters.sln.  Should I download and install Intel Media SDK ? Please can you supply detailed instruction for compiling ?  My target is to contribute (if you agree) adding  two methods to ILAVFSettings interface that allow to select between different audio tracks.  Usually mxf files have 8 or 16 audio tracks each one with 1 channel. When I play such mxf files the output pin gives only first track, so I can listen only 1 audio channel in track 1. Having two method:
STDMETHOD(GetAudioStreamsNumber)(int *iAudStrm) = 0;
STDMETHOD(SetCurrentAudioStream)(int iAudStrm) = 0;
Is possible to detect number of audio streams and select one of them.

**Comment by clsid2** [comment]
The filter already supports the standard IAMStreamSelect interface for selecting the audio track.

To fix compilation issues, use Git to clone the repository and checkout all submodules.

**Comment by francescoBLT** [comment]
Thanks for the fast response. The IAMStreamSelect is not reported in developer_info directory.  This is why I create this issue.

**Comment by Nevcairiel** [comment]
IAMStreamSelect is a standard Microsoft interface. Only custom interfaces are documented there.
