### ISSUE TITLE
Multiple video streams with same resolution and format

### ISSUE THREAD

**Issue by ale5000-git** [Nevcairiel/LAVFilters#442]
Hi,
when there are 2 video streams with the same format and resolution (bitrate is the only difference) it choose the first one not the one with best bitrate.

Sample: https://www.wittytv.it/temptation-island/terza-puntata-8-luglio/

**Comment by ale5000-git** [comment]
Should be fixed by https://github.com/Nevcairiel/LAVFilters/commit/567055708e942851270d70dd8909836fa109cc40
Thanks.

**Comment by ale5000-git** [comment]
I'm not sure why but the problem still happens with latest LAVFilters and latest MPC-HC @clsid2

**Comment by kasper93** [comment]
It is different case than my change. My was for program selection, here we have video stream selection.

And bitrate check is only enabled for realmedia... I don't know why, but to enable is one line change.

``` diff
diff --git a/demuxer/Demuxers/LAVFDemuxer.cpp b/demuxer/Demuxers/LAVFDemuxer.cpp
index 4136aaf3..18ab1a18 100644
--- a/demuxer/Demuxers/LAVFDemuxer.cpp
+++ b/demuxer/Demuxers/LAVFDemuxer.cpp
@@ -2780,7 +2780,7 @@ const CBaseDemuxer::stream *CLAVFDemuxer::SelectVideoStream()
             {
                 best = check;
             }
-            else if (m_bRM && checkPixels == bestPixels)
+            else if (checkPixels == bestPixels)
             {
                 int64_t best_rate = m_avFormat->streams[best->pid]->codecpar->bit_rate;
                 int64_t check_rate = m_avFormat->streams[check->pid]->codecpar->bit_rate;
```

**Comment by Nevcairiel** [comment]
The bitrate is not generically compared because the majority of containers don't carry any bitrate info, and avformats guesses for the bitrate are usually rather... useless.

**Comment by kasper93** [comment]
For this multi stream manifests it is generally right and `av_find_best_stream()` seems to take bitrate into account, but I don't mind either way as long as one can manually switch the stream if needed.
