### ISSUE TITLE
Crash in CLAVVideo::CompleteConnect()

### ISSUE THREAD

**Issue by clsid2** [Nevcairiel/LAVFilters#445]
Details taken from a MPC-HC crash dump.

![lav_crash_checkdirectmode](https://user-images.githubusercontent.com/4704996/140650122-7cc47c69-ed59-457d-ba53-8a05a50d00d5.png)

m_pDecoder is NULL, which causes crash in GetPixelFormat() call in CheckDirectMode().

I am not sure what the correct solution is. Refuse connection due to the HW decoder failure? Or just skip call to CheckDirectMode() in this situation? Or maybe m_pDecoder should never be NULL here and bug is elsewhere?

**Comment by Nevcairiel** [comment]
m_pDecoder really shouldn't be NULL at this point, indicating that an earlier failure wasn't handled properly.
I can still add a check to GetPixelFormat so it doesn't crash, however its not guaranteed that it won't run into the same issue later on somewhere.
