### ISSUE TITLE
MediaControl hangs when Lav Splitter source is setted in Timeline

### ISSUE THREAD

**Issue by Matrix86** [Nevcairiel/LAVFilters#45]
I'm using Lav Splitter Source on my project, but there is a problem.
I create a IAMTimelineObj to load a mp3 audio clip, next I set the Lav Splitter Source Filter on the timeline using the SetSubObjectGUID method.

Everything works fine, and if I load the audio clip and play a part of it (using IMediaSeeking.SetPositions on the renderer) the audio starts and stops correctly, but when the audio ends, the mediacontrol is blocked. I can't receive the complete event, and if I try to stop the Graph, the mediacontrol hangs on stop function.

Am I doing a something wrong? Or is there a bug on the splitter source?

**Comment by Nevcairiel** [comment]
Note that DirectShow Editing Services are not supported, as even Microsoft considers them unsupported and deprecated.

In any case, does it work if you play a full file, not specifying a start/stop at all?
Unfortunately I cannot test DSE at all.

**Comment by Matrix86** [comment]
Sorry I take IMediaSeeking from the graph. I have compiled and tested Lav Splitter code, and during the test I saw where the mediacontrol hangs.
I create a timeline with several media (photo and audio), next I pass it to the engine with SetTimelineObject function. If I play the timeline using SetPositions with Absolute Position on start and stop, I can see on Lav Logs that it receives only a set position with the start position setted but with stop position is null (::SetPositions() - seek request; caller: 0D7D0938, current: 0; start: 0; flags: 0x21, stop: -1; flags: 0x0).
 In this case seems the render engine blocks the playing on stop position, but the lav splitter hangs. It hangs on CLAVOutputPin::DeliverPacket method, on this call "CHECK_HR(hr = Deliver(pSample));".

I have found a possible workaround using SetRenderRange2 and ConnectFrontEnd functions on the renderengine each time the selection time was changed, and passing only the start position to the IMediaSeeking.SetPositions.

I hope this information can help you to find the problem. It could be a Directshow bug on the timeline (it pass to the filter only start position), but using other filters this problem doesn't occur, so the lav splitter should stop when the graph stops, I think.

If you need a sample project to test this behaviour I can send you it.

Thank you for your answer.

**Comment by Nevcairiel** [comment]
If Deliver hangs, then the hang is somewhere outside of LAV, as some filter downstream in the graph does not process the data any further.

A test project would be nice, maybe I can find something.

**Comment by Nevcairiel** [comment]
Please re-open this issue if you can provide clear instructions how to reproduce this problem, or even better a sample project to test it with, as you suggested before.
