### ISSUE TITLE
D3D12 Video API for LAV filters

### ISSUE THREAD

**Issue by NikosDi** [Nevcairiel/LAVFilters#450]
Hello Hendrik.

Any useful/ faster/ better/ richer features of D3D12 Video API for decoding, compared to the already implemented D3D11 of LAV filters ?

https://docs.microsoft.com/en-us/windows/win32/medfound/direct3d-12-video-overview

Thanks

**Comment by Nevcairiel** [comment]
There is nothing to gain there.
