### ISSUE TITLE
How to increase the preload size of mpeg-dash and other network streaming videos?

### ISSUE THREAD

**Issue by sudongg** [Nevcairiel/LAVFilters#455]
Hi,
I found that when playing an mpeg-dash video, it always loads to the current time + 6 to 9 seconds and then stops loading, unlike players such as mpv that will continue to load until the entire video is loaded.
When the network is freeze, it often leads to jamming, even disconnection, and will not automatically reconnect until I manually drag the seek bar.
Is it possible to read until the entire video is read like mpv, or increase the preload size?

**Comment by Nevcairiel** [comment]
The preload size can be controlled with the Queue Settings. Pre-loading the entire file is not recommended as it would all be stored in memory and you would potentially run out.

**Comment by sudongg** [comment]
@Nevcairiel 
What should be done, where are queue settings set?
I try to open reconnect in AVDictionary,  set buffer_size has invalid.
I want to increase the preload size and automatically reconnect after disconnection.

**Comment by sudongg** [comment]
I found SetMaxQueueSize in ILAVFSettings. Thank you!
