### ISSUE TITLE
ffmpeg compilation 

### ISSUE THREAD

**Issue by piousaggarwal** [Nevcairiel/LAVFilters#456]
can anyone provide me some document for the compilation of ffmpeg for lavfilters. I have tried several ways but I am unable to do that.
thanks

**Comment by kasper93** [comment]
Compilation of FFmpeg is well documented: https://trac.ffmpeg.org/wiki/CompilationGuide
And here is LAV Filters build script for it: https://github.com/Nevcairiel/LAVFilters/blob/master/build_ffmpeg.sh
Here is even script that builds everything: https://github.com/Nevcairiel/LAVFilters/blob/master/build.bat
Here is Nev's toolchain which is used to build official builds: https://files.1f0.de/mingw/

And the rest is up to you to figure up, it is more than enough information you need. And one of important skill is ability to search information by yourself.
