### ISSUE TITLE
LAV Compilation error

### ISSUE THREAD

**Issue by piousaggarwal** [Nevcairiel/LAVFilters#457]
Error	LNK1104	cannot open file 'avformat-lav.lib'
Error	LNK1104	cannot open file 'avformat-lav.lib'
Error	LNK1104	cannot open file 'avutil-lav.lib'
I am getting these errors while compiling LAV from where can I get these lib's.
Thanks!

**Comment by Nevcairiel** [comment]
These are generated when you compile ffmpeg correctly.

**Comment by piousaggarwal** [comment]
Can you please help in compiling ffmpeg as I am trying this for several days but I am failing in this.

**Comment by Nevcairiel** [comment]
You have already been given instructions in #456

**Comment by piousaggarwal** [comment]
Building ffmpeg in GCC x86 Release config...

gcc is unable to create an executable file.
If gcc is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

I am getting this error can you please guide me how to solve this.
Thanks

**Comment by piousaggarwal** [comment]
I have Compiled ffmpeg but now I am getting these errors.
Please guide me how can I solve these.
Thanks!

LNK2001	unresolved external symbol __head_libavformat_avformat_lav_lib
LNK2001	unresolved external symbol __head_libavutil_avutil_lav_lib
LNK2001	unresolved external symbol __head_libavcodec_avcodec_lav_lib
LNK2001	unresolved external symbol __head_libswresample_swresample_lav_lib
LNK2001	unresolved external symbol __head_libavformat_avformat_lav_lib
LNK2001	unresolved external symbol __head_libavutil_avutil_lav_lib
LNK2001	unresolved external symbol __head_libavcodec_avcodec_lav_lib
LNK2001	unresolved external symbol __head_libavfilter_avfilter_lav_lib
LNK2001	unresolved external symbol __head_libswscale_swscale_lav_lib
LNK2001	unresolved external symbol __head_libavcodec_avcodec_lav_lib
LNK2001	unresolved external symbol __head_libavutil_avutil_lav_lib
