### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by piousaggarwal** [Nevcairiel/LAVFilters#459]
I have Compiled ffmpeg but now I am getting these errors.
Please guide me how can I solve these.
Thanks!

LNK2001 unresolved external symbol __head_libavformat_avformat_lav_lib
LNK2001 unresolved external symbol __head_libavutil_avutil_lav_lib
LNK2001 unresolved external symbol __head_libavcodec_avcodec_lav_lib
LNK2001 unresolved external symbol __head_libswresample_swresample_lav_lib
LNK2001 unresolved external symbol __head_libavformat_avformat_lav_lib
LNK2001 unresolved external symbol __head_libavutil_avutil_lav_lib
LNK2001 unresolved external symbol __head_libavcodec_avcodec_lav_lib
LNK2001 unresolved external symbol __head_libavfilter_avfilter_lav_lib
LNK2001 unresolved external symbol __head_libswscale_swscale_lav_lib
LNK2001 unresolved external symbol __head_libavcodec_avcodec_lav_lib
LNK2001 unresolved external symbol __head_libavutil_avutil_lav_lib

**Comment by Nevcairiel** [comment]
Please stop opening new issues. This is not the place to obtain help building LAV.

**Comment by piousaggarwal** [comment]
sir its very important for me to build as I have to complete a college project and submit it by tomorrow. so please help me in this

**Comment by piousaggarwal** [comment]
please just guide me the reason for this error
