### ISSUE TITLE
Reselect Subtitle stream when audio stream changes

### ISSUE THREAD

**Issue by FCrane** [Nevcairiel/LAVFilters#46]
Hi!
I use the "advanced" options in LAV splitter for selecting subtitles in MPC-HC and it works fine. However, it'd be great if the advanced subtitle rules would be re-evaluated when I switch audio streams. 

E.g. an MKV (containing English and German Audio, English and German normal subtitles plus English and German forced subs) starts with English audio and LAV correctly selects the English forced subs according to my rule:

eng:eng|f ger:ger|f _:_|d

But when I then switch to German audio in MPC-HC, I'd expect the subtitle selection to switch to German forced subtitles automatically. This does not happen. It still uses the English ones that were activated when the player started.

So obviously, the only thing missing here is the option to re-check the LAV splitter subtitle options when the audio track is changed. Would be nice if this could be implemented!

Thanks!

**Comment by Nevcairiel** [comment]
This was requested before, but I think its somewhat problematic.
What if you just want to switch the audio track? You wouldn't be able to, it would always do the subs as well. Or an application wants to restore a saved stream selection, and everything gets jumbled up. So many pitfalls.

Its probably not very hard, maybe I'll make an option, not enabled by default.

**Comment by FCrane** [comment]
Yes an option would be ideal! You could even put it in the "Advanced" string like "+x" for automatic changing so that you wouldn't even have to change the configuration dialogs.

Thanks!

**Comment by Nevcairiel** [comment]
This has been implemented in 466a48a09348b39fe2f511902efe6e1964426610
