### ISSUE TITLE
Where Can I discuss the Errors

### ISSUE THREAD

**Issue by coder789456** [Nevcairiel/LAVFilters#461]
Sir can you please tell me where can I discuss the compilation errors. It's very important and also urgent for me.
hoping for a positive reply
Thanks

**Comment by coder789456** [comment]
It's important that's why I am asking again and again I can even pay for this help.

**Comment by clsid2** [comment]
Send $100 donation to Bitcoin address bc1qsctkttngdty2jzj970tweu2f4trsmfm6k3pqad and I will give you detailed instructions.

**Comment by coder789456** [comment]
Thanks but someone already provided me the solution
