### ISSUE TITLE
video decoder skips decode on some vp9 videos

### ISSUE THREAD

**Issue by sdsucks** [Nevcairiel/LAVFilters#462]
starting from LAVFilters-0.75.1-17, lav video decoder shows the first frame(still picture) for about 5 seconds and plays the rest of the video on some youtube vp9 videos

sample:
https://drive.google.com/file/d/1LBXpHTPlOYoyUN_103wtxfUOsvSp7n-r/view?usp=sharing

**Comment by Nevcairiel** [comment]
Cannot reproduce. The file plays fluidly all the way through for me.

**Comment by sdsucks** [comment]
hi, i did some more tests. seems like video renderer has something to do with this issue.

LAVVideo+madVR > skip
LAVVideo+EVR-CP > fine
MPCVideo+madVR > fine

madVR is latest beta 142

**Comment by lvqcl** [comment]
LAV Filters 0.75.1-44 + madVR beta 142 - no skips

**Comment by sdsucks** [comment]
one more thing i just found out;

LAVVideo(D3D11)+madVR > skip
LAVVideo(DXVA2)+madVR > fine

MPCVideo(D3D11/DXVA2)+madVR > fine

**Comment by lvqcl** [comment]
Maybe some bug in video drivers?

**Comment by sdsucks** [comment]
i have an nvidia card and use the latest geforce driver.

anyway, i tested with mavVR 0.92.17 and same thing.

i guess my bottom line is;
LAVVideo-0.75.1-17 and later in D3D11 mode with madVR skips the initial 5 seconds or so on some youtube vp9 videos.

**Comment by clsid2** [comment]
Press Ctrl+J to show to madVR statistics OSD and make a screenshot.

**Comment by sdsucks** [comment]
here you go;

https://ibb.co/GfmkNhd

**Comment by Nevcairiel** [comment]
I've added builds for -16 and -45 to the nightlies at https://files.1f0.de/lavf/nightly/ for testing. Would be good to know if either makes a difference.

**Comment by sdsucks** [comment]
the skip issue seems to be gone for both builds. i've tested on more than 100 videos.
and just for what it's worth, this issue doesn't seem to be related to a specific video codec.

**Comment by Nevcairiel** [comment]
If its gone with -45, then i'm happy, as thats the latest version. :)
