### ISSUE TITLE
CUVID breaks if SLI is enabled

### ISSUE THREAD

**Issue by threebyeight** [Nevcairiel/LAVFilters#47]
Selecting CUVID in LAV Video Decoder within MPC-HC prevents videos from playing when SLI is enabled. The behavior is prevented if SLI is disabled or DXVA is selected instead.

A similar ticket was opened here: https://github.com/ysh1101/lavfilters/issues/545

**Comment by Nevcairiel** [comment]
This is a known problem with the CUVID decoder, and not something I can fix. I recommend you use DXVA2-CB instead, its much less buggy than the CUVID decoder in many areas.

NVIDIA doesn't develop CUVID anymore, and its slowly accumulating bugs which are out of the control of someone thats just using NVIDIAs decoding API.

**Comment by threebyeight** [comment]
It's working suddenly. Did NVIDIA fix their drivers or was it something on your end?

**Comment by Nevcairiel** [comment]
I don't think I did anything, if I did, hooray? Well, hooray either way, I guess.
