### ISSUE TITLE
Does this work for ARM laptop？

### ISSUE THREAD

**Issue by jaoyina** [Nevcairiel/LAVFilters#473]
I have a Samsung galaxy book s laptop with ARM cpu, once I installed the filter, I am not able to find it in my mpc-be player, either 64 or x86 version. I am wondering, does this support ARM cpu?

**Comment by Nevcairiel** [comment]
LAV is x86 and x64 only. ARM is not supported. I do not know how emulation on these devices works.
For performance reasons, you should really use an ARM native video player though, as with emulation the performance is going to suffer real bad.
