### ISSUE TITLE
高分屏下软件看起来很小

### ISSUE THREAD

**Issue by luosaidage** [Nevcairiel/LAVFilters#479]
如图：
![image](https://user-images.githubusercontent.com/23243630/156953636-5c31f654-1ec9-4edf-a484-45aeffdfa971.png)
软件做得跟系统带的grove简直一模一样（外观），但是还有一些地方可以改进。
1、歌手那个按钮的功能好像还没实现。
2、我点击歌曲、歌手、专辑时字体会放大，这跟系统自带的有点不一样，而且由于我的高分屏，点击之后字大得有一部分看不到了。
3、系统自带得grove的左边条是半透明的。
4、高分屏下软件看起来很小。

**Comment by Masir01** [comment]
兄弟走错地方了
