### ISSUE TITLE
cannot be hard decoded, AVC 4K@120fps 

### ISSUE THREAD

**Issue by Masir01** [Nevcairiel/LAVFilters#480]
Use environment: 
    OS:                                  Win10 21H1
    player:                             Potplayer+LAVFilters+madVR
    Graphics:                         NVIDIA GeForce RTX 3050 Ti Laptop GPU
    Graphics driver version:  496.49
    Video info:  
![5U1P{MH$41N9FC{T J0J6U4](https://user-images.githubusercontent.com/32405103/157689241-9e57eca3-8492-4afb-9ef9-0cbc8c6984c2.png)
    LAV Video Decoder configure: 
![0 467N0K1_M6WB7_GR}9JHL](https://user-images.githubusercontent.com/32405103/157689733-8bb663c7-0e2e-49b3-ba79-fabca5aa59bc.png)
    Display info:
![H(9N(IM(RG1F6QU_5Z~{NQQ](https://user-images.githubusercontent.com/32405103/157689917-9367c9cd-0bca-445f-bf26-dd5caef9bc77.png)
    Demo: 
![6`E{(YZ1 {03X42__87AA(B](https://user-images.githubusercontent.com/32405103/157690143-a3bd8a9f-f16c-4c8f-ac8e-0015fd7e1668.png)

    note: 1,display: HDR=auto, madVR: HDR is automatically enabled during playback
             2,MPV Playing this video can be hard decoded
             3,I choose is DXVA2(native), and other options are only available for NVIDIA CUVID(old)

**Comment by Nevcairiel** [comment]
3840x2160 with 16 reference frames exceeds Level 5.1 and is not supported in hardware (level 5.1 only supports up to 5 reference frames). If you try, it might work, but it might also result in artifacts. LAV will not perform hardware decoding thats out of spec.

**Comment by Masir01** [comment]
NVIDIA CUVID(old) : OK
MPVplayer: OK
So is it because the LAV condition is exceeded?

**Comment by ale5000-git** [comment]
NVIDIA CUVID isn't DXVA2 so it has different limits (it may be more tolerant but it isn't interoperable, you can use it only on NVIDIA cards).
About MPVplayer I don't know what it use internally.
