### ISSUE TITLE
on movies and series, the image is broken

### ISSUE THREAD

**Issue by ghost** [Nevcairiel/LAVFilters#485]
I have a Dell S2421HN monitor, in movies and series, in full screen, there is a broken image (such a line with the image) at the top of the screen. i have mpc hc

**Comment by Lukjan38** [comment]
I have a built-in graphics card, amd ryzen 5 3400g

ps.
by the way, please unblock me at https://github.com/clsid2/mpc-hc/issues , I can't post

**Comment by Lukjan38** [comment]
however, mpc hc has a bug because, in other programs it's fine, the monitor has AMD FreeSync

**Comment by Lukjan38** [comment]
@clsid2 however, it has mpc hc or lav filters problem, because in other players it's fine
