### ISSUE TITLE
update all codec files

### ISSUE THREAD

**Issue by Lukjan38** [Nevcairiel/LAVFilters#489]
I'm writing here because on mpc hc, I can't write. I have a blockage, I don't know why.

please update all files in the LAVFilters64 folder, in mpc hc, because there is a difference between the size of files from mpc hc and the lav filters codec

**Comment by Nevcairiel** [comment]
Please stop using this as your personal dump on mpc-hc issues. I don't know nor care what your issue with mpc-hc is, but I'm not involved in its development.

**Comment by Lukjan38** [comment]
in mpc hc I do not know why, I can not write

**Comment by clsid2** [comment]
You are blocked because of your behavior.

MPC-HC already contains the very latest version of LAV Filters. There is nothing to update.
