### ISSUE TITLE
Issue playing mp4 containing E-AC-3 audio

### ISSUE THREAD

**Issue by egret85** [Nevcairiel/LAVFilters#49]
I have a file with E-AC-3 audio that when played, has no sound.  I can play the E-AC-3 track fine in VLC media player.  Also, If I switch LAV Splitter to use the alternate stereo AAC audio track, the audio plays. 

The following is the file media info:

General
Format                         : MPEG-4
Format profile                 : Base Media / Version 2
Codec ID                       : mp42
File size                      : 735 MiB
Duration                       : 5mn 34s
Overall bit rate               : 18.4 Mbps

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : Main@L4
Format settings, CABAC         : No
Format settings, ReFrames      : 2 frames
Format settings, GOP           : M=3, N=28
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 5mn 34s
Source duration                : 5mn 34s
Bit rate                       : 17.8 Mbps
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Variable
Frame rate                     : 30.000 fps
Minimum frame rate             : 29.791 fps
Maximum frame rate             : 30.151 fps
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.286
Stream size                    : 709 MiB (96%)
Source stream size             : 709 MiB (96%)
Color range                    : Limited
Color primaries                : BT.601 NTSC

Audio #1
ID                             : 2
Format                         : E-AC-3
Format/Info                    : Audio Coding 3
Format settings, Endianness    : Little
Codec ID                       : ec-3
Duration                       : 5mn 34s
Bit rate mode                  : Constant
Bit rate                       : 384 Kbps
Channel(s)                     : 6 channels
Channel positions              : Front: L C R, Side: L R, LFE
Sampling rate                  : 48.0 KHz
Bit depth                      : 16 bits
Compression mode               : Lossy
Stream size                    : 15.3 MiB (2%)

Audio #2
ID                             : 3
Format                         : AAC
Format/Info                    : Advanced Audio Codec
Format profile                 : LC
Codec ID                       : 40
Duration                       : 5mn 34s
Source duration                : 5mn 34s
Bit rate mode                  : Constant
Bit rate                       : 256 Kbps
Channel(s)                     : 2 channels
Channel positions              : Front: L R
Sampling rate                  : 48.0 KHz
Compression mode               : Lossy
Stream size                    : 10.1 MiB (1%)
Source stream size             : 10.1 MiB (1%)

The following is the input info for the LAV Audio Decoder pulled from MPC:

Filter : LAV Audio Decoder - CLSID : {E8E73B6B-4CB3-44A4-BE99-4F7BCB96E491}

- Connected to:

CLSID: {B98D13E7-55DB-4385-A33D-09FD1BA26338}
Filter: LAV Splitter Source
Pin: Audio

- Connection media type:

Audio: Dolby AC3 11025Hz stereo 12kbps

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Audio {73647561-0000-0010-8000-00AA00389B71}
subtype: MEDIASUBTYPE_DOLBY_AC3 {E06D802C-DB46-11CF-B4D1-00805F6CBBEA}
formattype: FORMAT_WaveFormatEx {05589F81-C356-11CE-BF01-00AA0055595A}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 256000
cbFormat: 18

WAVEFORMATEX:
wFormatTag: 0x2000
nChannels: 2
nSamplesPerSec: 11025
nAvgBytesPerSec: 1500
nBlockAlign: 8
wBitsPerSample: 16
cbSize: 0 (extra bytes)

pbFormat:
0000: 00 20 02 00 11 2b 00 00 dc 05 00 00 08 00 10 00 . ...+..Ü.......
0010: 00 00                                           ..

This looks off to me as the media type does not indicate E-AC-3 but instead show only AC3.  Also, the number of channels, sampling rate, and bit rate are way off.

**Comment by Nevcairiel** [comment]
Please provide a sample file that demonstrates the problem.  The  E-AC3 in MP4 which I have play fine.

**Comment by Nevcairiel** [comment]
Please re-open this issue if you can provide a non-working sample file.
