### ISSUE TITLE
Keyframe timestamps incorrect with this MP4

### ISSUE THREAD

**Issue by clsid2** [Nevcairiel/LAVFilters#491]
Sample file:
https://drive.google.com/file/d/1FuGTYRWhFnQOfU4Iq8ZrVxWUszkWkH1I/view?usp=sharing

Timestamps of the keyframes seem to be slightly inaccurate, resulting in a tiny lag after seeking with MPC-HC.

Example timestamps with MPC-HC/LAV:
1:32:54.874
1:32.56.999

MPC-BE internal splitter:
1:32:55.166
1:32.57.291

292ms difference in both cases.

**Comment by bibsp** [comment]
Seeking is fixed, but file launch time is now bit slower. Using latest development build of MPC-HC.
Can it he improved?

[Note]   There are many mp4s which didn't have seeking issue before, now they are also giving bit delay when opening.
You can compare launch time by seeing the taskbar animation in windows 10.

**Comment by bibsp** [comment]
I,m sorry but seeking is again kind of broken. It's not that much like before, but it has issue now.

MPC-HC 1.9.23.25 - Seeking was fine, but loading had issue.
1.9.23.27 - loading time fixed, but seeking issue.
Plus some other mp4s are having diffrent kind of seeking issue. When clicking on seekbar to seek the video then it takes some ms to go to that point. It's not like the above link I posted. Frame is not freezing. Just taking time.

clsid2 can you please check the keyframes of the above video in MPCHC 1.9.23.27 and 1.9.23.25. Are they similar?

https://user-images.githubusercontent.com/98865389/201266115-6fd665de-7518-41e8-8235-33533dce9919.mp4

**Comment by bibsp** [comment]
If it's difficult to fix then I will request Nevcairiel to revert the changes.
It's okay to have slighltly slower opening time than seeking issue.

**Comment by ale5000-git** [comment]
@bibsp
You should post the original video that cause the issue, the recording of the problem is useless.

**Comment by bibsp** [comment]
> Sample file:
> https://drive.google.com/file/d/1FuGTYRWhFnQOfU4Iq8ZrVxWUszkWkH1I/view?usp=sharing

Orginal is already posted.

**Now the problem is not limited to a specific file.** All other mp4s are affected after the latest patch, `Optimize MP4 ctts processing`.

**Comment by clsid2** [comment]
Fixed LAV is included in 1.9.23.28

**Comment by bibsp** [comment]
> Fixed LAV is included in 1.9.23.28

Yes, just checked. I think it's fixed now completely.
