### ISSUE TITLE
DTSHD,DTSHD MA not bitsreaming with MPC HC

### ISSUE THREAD

**Issue by PanosPav** [Nevcairiel/LAVFilters#492]
I have some mkv files (movies).
I recently upgraded from 1080TI to RTX3080.
Using RTX3080 I can't get DTSHD(MA)  audio to play.
The funny thing is that with 1080TI the audio was fine.
I clean installed Windows 11 and DTSHD(MA) stopped playing. 
The receiver (Yamaha Rxv686) displays pcm.
Using MPC-HC default audio renderer I am getting no audio.
Using Nvidia High Definition renderer I am getting PCM.
Connecting my avr to a hmi 2.0b Tv,dtshdma is ok.
As Dolby atmos ,Dolby digital and DTSHD(MA) is working fine.
is it easy or/and possible for a solution ?
I installed Ms Movie and TV player.The receiver dispays DTSHD(MA)!

**Comment by clsid2** [comment]
In the Windows Sound settings, set the HMDI device as the default audio device. Then open the device properties. On advanced tab, the exclusive mode options must be enabled. There should also be a formats tab where you can verify the bitstreamable formats.

**Comment by PanosPav** [comment]
Thanks for the reply, as you can see from the attached screenshot all tags are in place. Any other suggestion ? Sent from Mail for Windows From: clsid2Sent: Τετάρτη, 11 Μαΐου 2022 6:31 μμTo: Nevcairiel/LAVFiltersCc: PanosPav; AuthorSubject: Re: [Nevcairiel/LAVFilters] DTSHD,DTSHD MA not bitsreaming with MPC HC (Issue #492) In the Windows Sound settings, set the HMDI device as the default audio device. Then open the device properties. On advanced tab, the exclusive mode options must be enabled. There should also be a formats tab where you can verify the bitstreamable formats.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by PanosPav** [comment]
I forgot to indicate thatthe player crashes,I f I open a movie with DTS HD. Sent from Mail for Windows From: Panos PavlatosSent: Wednesday, May 11, 2022 9:52 PMTo: Nevcairiel/LAVFiltersSubject: RE: [Nevcairiel/LAVFilters] DTSHD,DTSHD MA not bitsreaming with MPC HC (Issue #492) Thanks for the reply, as you can see from the attached screenshot all tags are in place. Any other suggestion ? Sent from Mail for Windows From: clsid2Sent: Τετάρτη, 11 Μαΐου 2022 6:31 μμTo: Nevcairiel/LAVFiltersCc: PanosPav; AuthorSubject: Re: [Nevcairiel/LAVFilters] DTSHD,DTSHD MA not bitsreaming with MPC HC (Issue #492) In the Windows Sound settings, set the HMDI device as the default audio device. Then open the device properties. On advanced tab, the exclusive mode options must be enabled. There should also be a formats tab where you can verify the bitstreamable formats.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by PanosPav** [comment]
I have two avr one HDMI 2.0b and the other HDMI 2.1. I swap them a couple of tiimes, the problem occurs onlly when using HDMI 2.1.

**Comment by clsid2** [comment]
We can't help you. Go complain to NVIDIA.

This is in their driver release notes under known issues:
`[NVIDIA Ampere GPU]: With the GPU connected to an HDMI 2.1 audio/video receiver, audio may drop out when playing back Dolby Atmos. [3345965]`
