### ISSUE TITLE
Looks like the advanced subtitile selection mode doesn't work for specific language

### ISSUE THREAD

**Issue by soksanichenko** [Nevcairiel/LAVFilters#497]
Hello dear developers.
I tried to set rule `*:rus|n` for selection of subtitles, but it every time selects forced subtitle stream. But it works if I use `eng` or `ukr` in the rule. It selects non-forced and non-default subtitles.
Looks like it doesn't work for russian language.

**Comment by Nevcairiel** [comment]
The only reason it wouldn't work would be if the tracks are not actually flagged properly for that language. There is no handling whatsoever that even looks at what the code is, it just matches it with whatever is in the file - which is also whats shown in the stream selector for comparison.

**Comment by soksanichenko** [comment]
But player MPC-HC shows the stream as forced. And I tried the ruleset on many videos. How can I check flag of a stream with 100% guaranty?
Thank you.

**Comment by Nevcairiel** [comment]
If you specify |n, it will not allow forced streams, because |n means "normal", ie. not forced or default.

**Comment by soksanichenko** [comment]
I know it, but it I don't know why it doesn't work. 
I'll prepare a few screenshots as proof my issue later.

**Comment by soksanichenko** [comment]
I checked the streams by MediaInfo and what did I see?
I see that the "forced" streams are just titled as forced, but forced flag isn't set. Looks like the container is built not correctly.
The ticket can be closed.
