### ISSUE TITLE
Cannot decode 22.2 multi-channel

### ISSUE THREAD

**Issue by tkp206093** [Nevcairiel/LAVFilters#498]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/29872453/174585840-eee0f9df-aced-419c-a837-3c7c569db088.png">

I using this
[[BS4K][HLG 22.2聲道]第70回NHK紅白歌合戦「夢を歌おう」.torrent.zip](https://github.com/Nevcairiel/LAVFilters/files/8939952/BS4K.HLG.22.2.70.NHK.torrent.zip)

JP 4K TV 22.2 multi-channel

**Comment by Nevcairiel** [comment]
I'll hopefully get around to working on these issues within the next week or so.
