### ISSUE TITLE
MOV files Rotation support

### ISSUE THREAD

**Issue by motion-rocket** [Nevcairiel/LAVFilters#499]
Orientation (rotation) parameter in mov files created with mobile phones is not supported.

**Comment by Nevcairiel** [comment]
LAV can read rotation data from MOV files, but its up to the player to actually rotate them on display.
If your player supports rotation, but a certain kind of file doesn't work, then please share a sample.

**Comment by motion-rocket** [comment]
The rotation parameters are usually in the moov chunk at the end ov the mov file (I dont have much info)

I will be able to rotate the image without a problem if I can get this parameter from somewhere - either the LAV Splitter or LAV Filter headres - VIDEOINFOHEADER2, MPEG2VIDEOINFO, H264 Sequence, VUI or H264 Picture parameter headers don't appear to have that. I am looking at those with GraphStudioNext.
bellow are download links for the same video with different rotation parameter changed using ffmpeg
https://www.dropbox.com/s/29i68v411qo1tux/IMG_8775_0.MOV?dl=0
https://www.dropbox.com/s/gl432w4sx5zspnj/IMG_8775_90.MOV?dl=0
https://www.dropbox.com/s/bqmcyhoi4xowm3q/IMG_8775_270.MOV?dl=0
https://www.dropbox.com/s/cxt3nswlehia503/IMG_8775_180.MOV?dl=0

also if you have a min take a look at Issue #481

**Comment by kasper93** [comment]
The information you are looking for is available through property in LAVSplitter.
`IPropertyBag::Read("rotation", ...)`

And it is working properly in your samples, you can test in mpc-hc or any other player that supports automatic rotation.
