### ISSUE TITLE
h264 memory leak

### ISSUE THREAD

**Issue by sashayanin** [Nevcairiel/LAVFilters#50]
I am using LAV video decoder to decode mpeg-2/h264 streams received from network (multicast). 
It seems that there is a memory leak problem while decoding h264 streams. 

Memory leaks are especially strong when loss of input packets present. For test purposes, I stream video from VLC to my application that uses directshow graph. When I insert some "spoiling" of input stream (for example changing the playing position in VLC) memory consumption significantly increases. I was not sure that memory leak is in the decoder, but I did some testing with deleting filters from the graph manually and found that when I free up the decoder, almost all allocated memory is freed.

I aslo did some testing with VS2015 memory profiler (using LAV .pdb files). The picture below shows signiicant memory increase after several changings of playing position in VLC. (snapshot 2). Snapshot 1 - heap before "spoiling" input stream with VLC. Snapshot 3 - another, smaller portion of "spoiling".
![vs2015_mem1](https://cloud.githubusercontent.com/assets/15085938/11623224/7349b942-9cdc-11e5-84d0-829e6c452bbb.PNG)

Unfortunately, I can't see where exactly this leak appears, maybe because I don't have enough .pdb for all components of LAV filter. Blocks with leaked memory have "undetermined" type, and the module with leak is undefined too (VS 2015 shows the module with memory leak as "External"). Pictures below show it:
![vs2015_mem](https://cloud.githubusercontent.com/assets/15085938/11623415/cfb44fca-9cdd-11e5-8a79-f9a3ad355e15.PNG)
![vs2015_mem2](https://cloud.githubusercontent.com/assets/15085938/11623414/cfb40cea-9cdd-11e5-9ba3-8eb7c55ae46f.PNG)

I don't use any HW acceleration for video decoding.

When I do same things with mpeg-2 compressed video, I don't observe such problems.

**Comment by Nevcairiel** [comment]
Does it actually leak the memory? What if you close the LAV instance, does it get free'ed? 100mb of memory isn't something to worry about if its not actually leaked, and maybe just in-use.

**Comment by sashayanin** [comment]
Perhaps I used an incorrect term (memory leak). Indeed, consumed memory is freed when I close LAV video instance. However, another problem still exists. 
The problem is that memory consumption always grows while decoding h264, especially in case of "bad" stream, and it seems that it is never released. As a result, the application that uses LAV instance for h264 decoding will be anyway terminated by the system with "out of memory" exception.
Maybe such behaviour is ok if LAV is used for movie watching - in this case LAV is used only while the movie is being played and there will be not enough time for memory to finish. But my purpose is to use LAV for 24/7 video decoding from network - that's why I am worried about it.
You said that 100 mb of memory is ok, but that value was just for a couple of minutes of errorneous video decoding. 
From my point of view, I just do not understand such behaviour of h.264 decoder - the memory consumption and allocations only increase with time and released only when instance of decoder is closed. Why those huge amounts of already allocated memory cannot be reused somehow?

Have you performed some long-lasting tests of LAV video decoder with h264 videos?

**Comment by Nevcairiel** [comment]
The H264 decoder is the most common decoder to be used, on a daily basis by millions, not only in LAV but also through the FFmpeg project in many other applications - so if it had any big fundamental flaws, it would be known, trust me. :)

Without knowing where exactly the memory goes to, I cannot judge why it does that. But considering its not actually leaked, it seems to be functioning fine. Allocating memory it doesn't really need without leaking is rather unusual.

**Comment by Nevcairiel** [comment]
One simple idea, LAV has internal queues that it tries to fill as best as it can to ensure smooth playback. Obviously with real-time streaming, it won't be able to really fill the queues, because data arrives in realtime and is played in realtime.

However, if such a short stream "hiccup" occurs, it could feed a bit more data into the queues as audio and video have to sync again. If your stream is sufficiently high bitrate, this could accumulate over time.
Note that these queues have an upper limit and won't grow indefinitely.

LAV offers a maintenance interface to inspect the size of the queues through IBufferInfo (definition in developer_info), which lets you query the number of packets and the overall memory size of the queues. You could check that.

**Comment by Nevcairiel** [comment]
Closing due to lack of clear information. Its definitely not a leak, as the memory is free'ed when the LAV instance is closed.
