### ISSUE TITLE
Is there any plan to support xHE-AAC decoding?

### ISSUE THREAD

**Issue by lzy0702** [Nevcairiel/LAVFilters#501]
I received some audio files in xHE-AAC, and I cannot playback them with lavfilters.
Is there any plan to support this format?

**Comment by lvqcl** [comment]
LAV uses ffmpeg for decoding. If ffmpeg cannot decode xHE-AAC then LAV can't play it.

**Comment by clsid2** [comment]
http://trac.ffmpeg.org/ticket/8411

**Comment by pphh77** [comment]
https://github.com/pphh77/LAVFilters/releases/

**Comment by ObjectInSpace** [comment]
From the ticket, it sounds like this is possible via libfdk_aac, however ffmpeg can't distribute it due to the licensing. Would lav be able to make use of this to provide better decoding of these formats than can be provided by the native ffmpeg decoder, or does the same restriction apply here?
