### ISSUE TITLE
vvc(h.266) decoding feature support?

### ISSUE THREAD

**Issue by Coresi7** [Nevcairiel/LAVFilters#502]
Now I'm using klite codec pack 17.0 mega and it has lav splitter  0.76.1. But it does not support vvc.
Is there a timetable to add vvc support? Thanks!

**Comment by Coresi7** [comment]
An implementation of vvc decoding is here
https://github.com/fraunhoferhhi/vvdec

**Comment by clsid2** [comment]
LAV Filters uses FFmpeg for all its decoders. That does not yet support H266 and it currently doesn't look like it will anytime soon either. The Fraunhofer decoder or any other third party decoder will be not used.

**Comment by Coresi7** [comment]
> 

I see, I'll try to issue there. Thanks!

**Comment by F1ReB4LL** [comment]
> January 3rd, 2024, native VVC decoder
The libavcodec library now contains a native VVC (Versatile Video Coding) decoder, supporting a large subset of the codec's features.
https://ffmpeg.org/

Just a heads up :)

**Comment by gizmocuz** [comment]
Great! Hope it will be available soon....
