### ISSUE TITLE
Music play fast forward problem

### ISSUE THREAD

**Issue by Coresi7** [Nevcairiel/LAVFilters#503]
Hi there, here's a music demo, which play on WMP is fine, but play with MPC-HC with LAV Audio decoder, it will play extremely fast like I press the FF button.
Is there a plan to fix this?
LAV Filter version: 0.76.1.3
[7 AND 5 - Ascension.zip](https://github.com/Nevcairiel/LAVFilters/files/9264840/7.AND.5.-.Ascension.zip)

**Comment by clsid2** [comment]
Speed is normal here. But there is some glitches at the start.

FFmpeg is detecting some issues with the file, so there is possibly something wrong with it. MediaInfo also does not recognize it, and VLC fails to play completely.

```
[flac @ 0000000000465f40] Format flac detected only with low score of 1, misdetection possible!
[flac @ 0000000000467980] invalid sync code
[flac @ 0000000000467980] invalid frame header
[flac @ 0000000000467980] decode_frame() failed
```

**Comment by Coresi7** [comment]
> Speed is normal here. But there is some glitches at the start.
> 
> FFmpeg is detecting some issues with the file, so there is possibly something wrong with it. MediaInfo also does not recognize it, and VLC fails to play completely.
> 
> ```
> [flac @ 0000000000465f40] Format flac detected only with low score of 1, misdetection possible!
> [flac @ 0000000000467980] invalid sync code
> [flac @ 0000000000467980] invalid frame header
> [flac @ 0000000000467980] decode_frame() failed
> ```

It's spooky.... Windows Media Player will be fine for this. So is there any work around here?

**Comment by clsid2** [comment]
It could be a bug in FFmpeg. You need to wait until nevcairiel has time to comment on this.

**Comment by Nevcairiel** [comment]
The behavior looks fine to me, and it also plays fine here. But the file is somehow rather screwed up. It does not have a flac file header, instead it starts with a huge empty ID3 block, and the flac frame information seems to refer to wrong timestamps.
