### ISSUE TITLE
IPTV streaming - Error, slow starting

### ISSUE THREAD

**Issue by tantegrete** [Nevcairiel/LAVFilters#506]
I try to receive IPTV streams from ZATTOO.
5 stream types are offered:
hls7, hls7-fairplay, dash, dash-playready and dash-widevine.
After setting url to filesourcefilter foloowing issues appear:
- All dash streams results in error "Invalid floating point operation"
- hls7 fairplay takes approx 12 to 15s, no video
- hls7 takes approx. 7 to 9s, video OK
This seems to be verly slow !
Version is 0.76.1-git - also 0.75

Same behavior appeard when using libvlc in Version 3.0.16
After updating to 3.0.17.4, stream will play after less then 1-2 s !
Fixes info says:
- Major adaptive streaming stack overhaul

Same problem in LAV-filters ?

**Comment by tantegrete** [comment]
.. nearly a week ago.

Are there any intentions to speed-up loading IPTV-Streams ?
Your answer to an other issue was:
[Quote]
... Networking features in LAV Splitter are provided as-is for convenience, just because ffmpeg offers them...
[/Quote]
Probably many LAV-users use LAV to receive IPTV-streams and would be extremly delightful to have faster access.
VLC has worked up this issue in rev. 3.0.17.4 - a relly quantum jump !
Who wants a command line tool like ffmpeg when LAV-filters otherwise works absolutly great !?
The community and me might be extremly appreciate if this would be handled a.s.a.p.
A little extended convenience is desireable.

**Comment by clsid2** [comment]
FairPlay/PlayReady/Widevine are all DRM protected streams, so those obviously won't work. You need a compatible and licensed app/browser for such streams.

Best change to get improvements is to reproduce the playback start delay with FFmpeg.exe and then submit a bug report to FFmpeg. Any fixes they make will get inherited by LAV.

**Comment by tantegrete** [comment]
So this is not really a bug.
There are no probs with DRM protection when having e.g. a legal ZATTOO account (Basic is free) or derivated provider.
LAV/ffmpeg plays fine when extracted url is loaded, but ffmpeg has the same start delay with approx. 7 to 15s content & type depending.
Latest VLC will do then same (only hls) in less than 2 seconds ! (using the player or libvlc by app)
Where exactly to post such a "wish" ?
