### ISSUE TITLE
Non-HW decoding question

### ISSUE THREAD

**Issue by psyborg55** [Nevcairiel/LAVFilters#507]
When format is not supported to be hardware-decoded, e.g. h264 4:2:2 the decoder will utilize CPU to do decoding.
Is it possible to also utilze GPU at the same time in parallel with CPU to decode the stream? (the GPU use same method as CPU for decoding so acting as an additional CPU core)
How much of performance improvement could this bring in?

**Comment by Nevcairiel** [comment]
This is not possible.

**Comment by psyborg55** [comment]
Ok. Can you tell what is the limiting factor? Every GPU being different needing special code, or something else?

**Comment by clsid2** [comment]
The limiting factor is there is absolutely nobody interested in implementing such functionality for free in in open source project. Plus GPUs are not suitable for such tasks, so it would be pointless as well. If you want better performance, get a better CPU.
