### ISSUE TITLE
Audio decoding in DSD format is not supported

### ISSUE THREAD

**Issue by pth2000** [Nevcairiel/LAVFilters#508]
I am using QT to develop a music player. I found that when I tried using LavFilters it could decode formats like FLAC, WAV, etc., but I got errors when I tried DFF or DSF formats. 

For example: 
`DirectShowPlayerService: : doRender: Unknown error 0 x80040266.`

Is there any way to solve this problem? Thank you very much!

**Comment by Nevcairiel** [comment]
LAV Audio supports decoding DSD, but the output is a unusual high sample rate, and you'll need a audio renderer that is capable to accept it - most are not.

**Comment by clsid2** [comment]
If you use [MPC-HC](https://github.com/clsid2/mpc-hc/releases) player, then both `SaneAR` and `MPC Audio Renderer` support resampling such high sample rates.
Options > playback > Output > Audio Renderer

The default DirectSound renderer that is used by your application does not support it.
