### ISSUE TITLE
Video stuck at 0:00:00 without any error prompt

### ISSUE THREAD

**Issue by kazedev** [Nevcairiel/LAVFilters#51]
I don't know what you need, so all info that I can get from MPC HC.

Media info: http://pastebin.com/MkWyXSS8
Splitter video pin info: http://pastebin.com/aUARMtE1
Splitter audio pin info: http://pastebin.com/iVp6AfkB
Video in pin info: http://pastebin.com/4fHqrePE
Video out pin info: http://pastebin.com/TztKkua2
Audio "XForm" in pin info: http://pastebin.com/h3Jujnhw
Audio "XForm" out pin info: http://pastebin.com/wN2VxhQQ
Internal Audio Render Input0: http://pastebin.com/Zz3R2jE5
EVR Input0: http://pastebin.com/EAcW90P8
EVR Input1/2: Filter: In both only "Enhanced Video Renderer - CLSID : {FA10746C-9B63-4B6C-BC49-FC300EA5F256}"

What is going? File open in the MPC HC, but stuck on 0:00:00, it says it are playing, but nothing are playing and absolutely none progress on GUI.

All other video in various formats plays fine, but not it.

Edit: Oh fine, it occurs on 0.67.0.3-git and 0.67 stable as well.

**Comment by Nevcairiel** [comment]
The file is probably just broken somehow. Since you are using the MPC-HC internal filters, I would suggest to report to MPC-HC. Providing a sample of the problematic video is needed to do anything, though.

**Comment by kazedev** [comment]
Change hardware accel from QuickSync to DXVA2 make the original m2ts works...
With it I can to put the blame on Intel and its delay to release updates for drivers... But...
Cutting it into a .mkv with ffmpeg copy method make the video piece works well on QuickSync...
I really don't figure what's going, but by the way is not a problem in Lav, so...
I'm sorry for the inconvenience! Please continue with your great work!

**Comment by Nevcairiel** [comment]
QuickSync is not a recommended decoding mode in LAV anymore, since it strongly depends on Intels drivers and those have been having a sub-par quality for a long time. I recommend to stick to DXVA2-CopyBack.
