### ISSUE TITLE
[regression] Vorbis audio decoding

### ISSUE THREAD

**Issue by clsid2** [Nevcairiel/LAVFilters#515]
Bug since this [commit](http://git.1f0.de/gitweb/?p=ffmpeg.git;a=commitdiff;h=8fc2dedfe6e8fcc58dd052bf3b85cd4754133b17). A possible [solution](https://github.com/Aleksoid1978/MPC-BE/commit/92381d7f40bb0864417e7fff61a6c4ad5afcb073).

**Comment by Nevcairiel** [comment]
I can't act on a claim of a bug without any explanation, sample, or anything.

**Comment by clsid2** [comment]
http://samples.ffmpeg.org/ogg/Vorbis/test6.ogg

Audio decoding fails with any file containing Vorbis.
