### ISSUE TITLE
HD sound issue

### ISSUE THREAD

**Issue by HellsAngel79** [Nevcairiel/LAVFilters#517]
Hi,
ive got a weird issue with lav filters at first i thought this was a displayport so i tried a few things.
Ive got picture hooked up using hdmi to tv and using another displayport to hdmi cable to the avr just for sound.
using lav to bitstream sound over displayport doesnt work (dolby atmod dts-x) switching to e-arc so it goes through
tv works. tried vlc same story doesnt work.
dolby access app and netflix do work over displayport so luckily its not a limitation of the DP port.
so i tried mpc-hc again but instead of lav bitstreaming the audio i used ffdshow and this works downside is
its not being updated and every now and then the sound drops for half a second.
can lav be fixed so it can bitstream over displayport aswell?
ive noticed in its current state it errors it tried to stream it as pcm and result is no sound no pins found or something like that.

Thanks in advance.

**Comment by clsid2** [comment]
There is no difference in bitstreaming for HDMI or DisplayPort.

You are likely running into a (bandwidth) limitation of the ARC. ffdshow does not support atmos, so it only sends the truehd part.

You should go PC > AVR > TV

**Comment by HellsAngel79** [comment]
Its e-arc which works fine. (hdmi to tv)
its displayport _display port to hdmi cable to avr) that gives me problems with vlc and mpc-hc + lav filters that simply doesnt work.
but displayport and mpc-hc and ffdshow bitstreams dolby atmos just fine with a few drop outs of half a second.
i cant really do pc > avr > tv it gets this weird rainbow artifacting the joys of early adopter so this was the best idea
i could come up with.
to make it very clear this isnt a bandwidth issue everything is hdmi 2.1 gpu is a 4090 tv is hdmi 2.1 and so is the avr.
if it was a bandwidth or other specification problem which i was starting to suspect but isnt the case
then ffdshow netflix and dolby access app wouldnt work either.

**Comment by Nevcairiel** [comment]
LAV does not care about any of this. It just formats the audio into the required bitstream format. It would be the audio renderer that talks to the audio device and then sends the data in the appropriate format - eg. not something LAV has any control over.

**Comment by HellsAngel79** [comment]
That is what i thought to but when i use LAV and dolby atmos and display port its pin error and it shows it tries to do it as pcm.
changing nothing but using e-arc and hdmi everything is fine.
ffdshow audio is the only one that somewhat works but has a drop every now and then.
at this point i dont know what else i can try to get this working preferbly with LAV.

**Comment by clsid2** [comment]
You get a pin error when the audio renderer does not support any of the output mediatypes of the decoder.

If everything works with HDMI, then the problem is with the Displayport to HDMI adapter. If you google for your problem you find much information. For example that there are ACTIVE and PASSIVE adapters, and that an ACTIVE one might be needed to properly covert certain signals.

I already told you that ffdshow does not support ATMOS like LAV does. So whatever ffdshow is bitstreaming only contains the base audio format WITHOUT the atmos extension layer.

**Comment by HellsAngel79** [comment]
ifs a regular displayport to hdmi cable as far as i know the displayports on the gpu are dual mode so they do show up as hdmi in the control panel. if ffdshow didnt support atmos properly or screwed up anything in the bitstream the receiver wouldnt show atmos its quite picky and it does show as dolby hd + atmos.
if you have any ideas what i could try or use to solve this passive adaptor converts stuff so thats what i wanna avoid i really need bitstreaming.

**Comment by HellsAngel79** [comment]
Ok 0.77 is out installed that and dolby atmos now works without issue over displayport.

**Comment by HellsAngel79** [comment]
ok still an issue it seems dts-hd using displayport gets stuck on dts only even ffdshow.
but switching to hdmi it works.
is there any solution?
