### ISSUE TITLE
Win32 LocalInfect.2 

### ISSUE THREAD

**Issue by thorbjornj** [Nevcairiel/LAVFilters#518]
My antivirus flags a Win32.LocalInfect.2  alert when downloading v 0.77.

**Comment by Nevcairiel** [comment]
This is a false positive. LAV has been scanned by a large variety of scanners with no detections:
https://www.virustotal.com/gui/url/1e0ea6a22345e6f4ed02e3cf10e26e04caa7c6d99b27fa5003079c8ed40d7f38/detection
