### ISSUE TITLE
LAVvideo.ax won't register on Windows XP SP2.

### ISSUE THREAD

**Issue by YourFuture** [Nevcairiel/LAVFilters#53]
Then put that info on your website and put it in the installer and put a check in the installer instead of letting it trip all over itself and fuckup at the end of install!

Did nobody ever teach you responsible programming?

Wake up!

You would lose your job in the first week working on a real commercial software.

**Comment by Nevcairiel** [comment]
The next version will properly flag the requirement in the installer.

**Comment by YourFuture** [comment]
Thanks. Now how about - like all other software publishers do - putting the SP3 requirement onto your website & documentation so users without SP3 don't waste time downloading & attempting to install LAV Filters?

**Comment by Nevcairiel** [comment]
LAV doesn't actually have a website, just this GitHub repository. I was meaning to update the readme to look nicer anyway, maybe I should do that.

**Comment by YourFuture** [comment]
https://1f0.de/lav-splitter/
