### ISSUE TITLE
Please update gnutls、libtasn1 and gmp to latest version in avformat-lav-59.dll

### ISSUE THREAD

**Issue by heathleger** [Nevcairiel/LAVFilters#530]
...

**Comment by Nevcairiel** [comment]
GMP is up to date. GnuTLS is using the latest version of the stable 3.6 branch. libtasn1 is if anything pulled in directly by GnuTLS, and not under my direct control.

**Comment by heathleger** [comment]
Thanks, but i have searched the dlls are outdated.
gnutls 3.6.16 latest version 3.7.8,
libtasn1 4.16.0 latest version 4.19.0,
gmp 5.4.3 latest version 6.2.1.

**Comment by heathleger** [comment]
Your release pack is realy helpfull, i can not build a useable dll.
