### ISSUE TITLE
LAV Filters Selecting Best Audio

### ISSUE THREAD

**Issue by XXXBerto55** [Nevcairiel/LAVFilters#54]
Hello, I had to rebuild a computer and am pretty sure that I had it working this way before.  I make MP4 Files with three audio tracks.  AC3, AC3-Passthrough, and DTSHD-Passthrough.  I do this to make the files compatible with 360 Extenders, Android, and also to get the best audio when played in my basement home theater which is the computer I have the issue with.  If I select to bitstream all of the formats the files do not play.  If I uncheck all the bitstreaming options they will play.  Previously, I believe LAV would select the best audio and bitstream if applicable and not bitstream if not applicable.  I don't remember EVER having a file that wouldn't play on the computer.  Am I doing something wrong?  Has something changed?  I want LAV to select the best audio (HD if available and bitstream to my receiver).  Thanks in advance.  Forgot to mention....for kicks, I ripped a bluray with ONLY a HD track and it played brilliantly with all the boxes checked.

**Comment by Nevcairiel** [comment]
Sounds like your special files are weirdly broken. LAV has not changed, it still decodes and bitstreams as appropriate.

**Comment by XXXBerto55** [comment]
Nothing changed in my files and there really isn't anything special about
them. I they simply have multiple audio tracks. I have figured out the
problem is LAV crashes when it can't Bitstream and neither selects the
track that it can nor switches to decode. If a file only has a dts-hd track
it works.

**Comment by Nevcairiel** [comment]
LAV has always worked liked that - if you tell it to bitstream, and it cannot, then it'll just refuse to function. Its your responsibility to configure it correctly.

**Comment by XXXBerto55** [comment]
Yeah... I guess previously it was always decoding because I didn't have the
boxes checked. I honestly am not sure why I even want to Bitstream except
it's my impression that it will provide higher quality audio.

I suppose my only solution is to let it decode or create files for
Bitstream and a second set for xbox extenders. I appreciate your follow up.
I might suggest although I know little to nothing about programming that
you build a fall back that automatically selects an audio track it can use
or switches to decoding which I guess might be the same thing in most
cases..... Again I appreciate the help and the software... I'll find your
donate link when I'm not on mobile.

**Comment by XXXBerto55** [comment]
Sorry to bother again, but I am a bit confused if I solved my problem or
not.  I went in and deselected DTS and TrueHD in the formats that LAV
should decode.  It is selected to bit-stream those.  Is this really all I
had to do?  Will it now bitstream the best available audio and ignore
trying to decode these?
