### ISSUE TITLE
LAV Splitter: Instagram video hang

### ISSUE THREAD

**Issue by 1234G-G4321** [Nevcairiel/LAVFilters#548]
Using
[MPC - BE](https://github.com/Aleksoid1978/MPC-BE/) + LAV Splitter : Instagram video hang....

Link use: https://www.instagram.com/reel/CuUUeJDtJfV/

Without [LAV Filters](https://github.com/Nevcairiel/LAVFilters/) = work fine

https://github.com/Nevcairiel/LAVFilters/assets/120308983/2e3c855f-e729-424c-9f4c-f39ebd23d3bd

.
.
.

With [LAV Filters](https://github.com/Nevcairiel/LAVFilters/) = get problem

https://github.com/Nevcairiel/LAVFilters/assets/120308983/7b3e1455-acf9-4a4c-a6d5-e1e965c240fb

.
.
.

[MPC - HC](https://github.com/clsid2/mpc-hc) + LAV Filters: some problem
(Note: MPC-HC use LAV Filters By Default)

https://github.com/Nevcairiel/LAVFilters/assets/120308983/737fc597-c823-4171-9319-fdebe043273e

**Comment by 1234G-G4321** [comment]
@Nevcairiel

**Comment by Nevcairiel** [comment]
Works fine for me with the latest development version

**Comment by bibsp** [comment]
This issue is not fixed. Actually the problem is not with all instagram videos. Some plays fine, some has problem. Check this URL: https://www.instagram.com/reel/C06ZeiYv3tG/

**Comment by bibsp** [comment]
> https://www.instagram.com/reel/C06ZeiYv3tG/

@Nevcairiel It's not fixed, but closed as completed.
