### ISSUE TITLE
Huge PNG crashes LAVVideo.ax

### ISSUE THREAD

**Issue by motion-rocket** [Nevcairiel/LAVFilters#549]
![Sals Post CF](https://github.com/Nevcairiel/LAVFilters/assets/93405954/273c0c6d-2781-4d5e-95f5-ea95912938bc)
size: 35,281 x 5,346 (W x H)

**Comment by v0lt** [comment]
Are you sure that it is the LAVVideo.ax that is crashing?

Perhaps the problem is in the video renderer, which cannot create a texture with a side size greater than 16384.

**Comment by v0lt** [comment]
I recommend [MPC Image Source](https://github.com/v0lt/ImageSourceFilter/releases).

**Comment by motion-rocket** [comment]
I use a custom video renderer which transfers the data into a Dirext3D RGBA texture. In this case it will be split in bands to fill up the max size of supported texture on the 3d device. we do this for very long but narrow images for the fascia displays with adds at stadiums.

If you drop the file in graphstudionext64.exe the filter will fail to build. I think it is possible to debug the source if in graphstudio you attach to the process.

**Comment by motion-rocket** [comment]
> I recommend [MPC Image Source](https://github.com/v0lt/ImageSourceFilter/releases).

Thanks for the recommendation, It looks very promising.

**Comment by motion-rocket** [comment]
You were right the problem is in the custom video renderer,  in the IBaseFilter code where pin connection is made. My tests came to max pixel sizeof an image < 8192x8192 (not equal). also if width is > 16384 there are more problems.
As far as MPC Image Source - implemented that in the code but even the graphbuilder succeeds at certain sizes there are problems.

**Comment by motion-rocket** [comment]
no problem with LAVVideo.ax, Direct3D at some images will run out of memory and has to be reinitialized. You can close the issue. Thanks for your help.
