### ISSUE TITLE
unable to open AVISynth script

### ISSUE THREAD

**Issue by roman-minyaylov** [Nevcairiel/LAVFilters#55]
Hi

Latest version used, I'm trying to open .avs file in Windows Media Player and GraphStudio (using LAV Splitter Source). If AVISynth installed I can open .avs file without any issues.

So, maybe it's bug, maybe I'm doing something wrong, but as I see in changelists AVISynth file is supported.

Script is very simple 
>DirectShowSource("c:\samples\video.mp4", fps=25).ConvertToRGB32()

**Comment by Nevcairiel** [comment]
AviSynth needs to be installed for this to function, LAV doesn't re-implement AviSynth, it just integrates it with DirectShow
