### ISSUE TITLE
E-AC3 (DD+) & bitstreaming !

### ISSUE THREAD

**Issue by metagondria** [Nevcairiel/LAVFilters#554]
Hello,

Iam trying to convert the sound of many of my media files into E-AC3 !!  
The only problem of that is, the new encoded eac3 track doesn't bitstream (no sound)!!!  

Only when i choose to keep the core (AC3) it passthrough the sound to my receiver !!!

Although my receiver supports ALL DOlby formats (atmos included) !??

Is it impossible to re-encode EAC3 / DTS tracks from bluray sources to EAC3 and bitstream afterwards ?

If so, it's even wurse than the Sony cinavia protection !!!

cheers,
td

**Comment by metagondria** [comment]
Update:

I succesfully managed to recode a DTS track to E-AC3 and passthrough/bitstream it in MPC-HC and stand alone bluray player..
But can't seem to bitstream E-AC3 + DD+ in powerdvd !!???  Powerdvd 21 falls back to pcm !??

so software player x does it fine, while B refuses !?  Receiver / setting or audio encode can't be at fault here .. me thinks !?

But when i try to bitstream an EAC3 sample ive donwload from the net... Powerdvd bitstreamed without an problem !!!

WTF ?

cheers,
TD

**Comment by clsid2** [comment]
This is not the correct place to ask about Powerdvd problems.

**Comment by metagondria** [comment]
> This is not the correct place to ask about Powerdvd problems.

But it's a start... 
I mean Lav is involved in this too !   Because, by changing the bitrate the slightest, it happends in mpc too !?

Even though bitrate is way within bluray compliant !?

anyway, ive created thread at cyberlink hq.. but... don't think it ill get priority..


cheers,

**Comment by Nevcairiel** [comment]
If any official content fails to bitstream, feel free to report. Self-encoded content is equally likely to just not be compatible.
