### ISSUE TITLE
32bit FLAC audio cannot be correctly played in potplayer with lavfilters

### ISSUE THREAD

**Issue by Ptilopsis01** [Nevcairiel/LAVFilters#555]
As the title said, when I use lavfilters as splitter and audio decoder, it can not correctly play the 32bit flac audio in potplayer, but it works well when I change the splitter and audio decoder into build-in ffmpeg.

**Comment by v0lt** [comment]
Any samples?

**Comment by clsid2** [comment]
The (upstream) FFmpeg code in LAV Filters was last updated on 2022-11-06, while 32-bit FLAC support was added in FFmpeg on 2022-12-26.

So you need to wait until LAV Filters gets updated.

**Comment by Ptilopsis01** [comment]
> The (upstream) FFmpeg code in LAV Filters was last updated on 2022-11-06, while 32-bit FLAC support was added in FFmpeg on 2022-12-26.
> 
> So you need to wait until LAV Filters gets updated.

Thx, I hope to see a new version soon.

**Comment by Nevcairiel** [comment]
FFmpeg was updated in the latest nightly and should support 32-bit audio now. You can grab a test version from https://files.1f0.de/lavf/nightly/

**Comment by Ptilopsis01** [comment]
> FFmpeg was updated in the latest nightly and should support 32-bit audio now. You can grab a test version from https://files.1f0.de/lavf/nightly/

It runs properly with audio, but error happens when playing video
![image](https://github.com/Nevcairiel/LAVFilters/assets/93318731/3e6bcea6-a1ce-429c-839b-bc58ecf59325)

**Comment by Nevcairiel** [comment]
The latest nightlies are still rather work-in-progress, check back later, I fixed a crash just today.
