### ISSUE TITLE
YTB Av1 8K 

### ISSUE THREAD

**Issue by Masir01** [Nevcairiel/LAVFilters#557]
Cannot decode AV1 8K   
![微信图片_20230819103758](https://github.com/Nevcairiel/LAVFilters/assets/32405103/60eb8af9-f543-46a8-9810-87a95a4168db)
![image](https://github.com/Nevcairiel/LAVFilters/assets/32405103/ae90cbbd-3ac2-4fc3-a87a-45f938a65f91)

**Comment by Nevcairiel** [comment]
8K is only supported in 64-bit players. Otherwise it works fine for me.

**Comment by clsid2** [comment]
8k support might also be limited to 30fps video. The mediainfo example is 60fps.

**Comment by Nevcairiel** [comment]
The hardware does not even get told the FPS. It would just run slow. But a 8K 60 fps video certainly works fine for me assuming native decoding is used, its too slow on copy-back (but still "works")
