### ISSUE TITLE
Advanced stream selection not working fully

### ISSUE THREAD

**Issue by ViperCode7** [Nevcairiel/LAVFilters#561]
There seems to be an issue selecting hearing impaired subtitles from MKV media.
*:eng|h should in theory select the English subtitle shown as SDH in the streams or having been flagged as "Hearing impaired" in mkvtoolnix, but it doesn't, instead is switches to No subtitle. The other flags seem to work ok.

**Comment by Nevcairiel** [comment]
Those flags in Matroska are relatively new and not read from the container yet, so selection does not see them.

**Comment by tealkami** [comment]
Most files I saw with MediaInfo never use the "Hearing impaired" tag anyway, 99.9999% files use the **Title**, which can be picked by `*:eng@SDH`

Nevcairiel did update the doc. 7hours ago :D

**Comment by Nevcairiel** [comment]
I've added parsing for the MKV metadata for these flags, so if you actually have a file that is flagged like this, it should detect them and act on them now.
