### ISSUE TITLE
Equalizer - add it finally for krist-sake!!!!!!!

### ISSUE THREAD

**Issue by fafayqa** [Nevcairiel/LAVFilters#564]
Could you finally add at least some sort of simple equalizer? Jesus!!!! This is fuggin unbelievable that your filters still does not have any sort of eq at all...in yr 2023!!!!! Ridiculous, mega mega maga!!!

**Comment by Nevcairiel** [comment]
This is a decoder, not an audio processor. There will never be anything like this.

**Comment by clsid2** [comment]
https://sourceforge.net/projects/equalizerapo/
