### ISSUE TITLE
I had to revert libgnutls.a in order to build successfully

### ISSUE THREAD

**Issue by adipose** [Nevcairiel/LAVFilters#565]
See here: https://github.com/clsid2/mpc-hc/issues/2314

`c:/msys64/mingw/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../../thirdparty/64/lib/libgnutls.a(global.o):(.text+0xb8): undefined reference to 'pthread_mutex_lock' 

`

After reverting to previous version of libgnutls.a, it compiles ok.

**Comment by Nevcairiel** [comment]
Compilation is up to you. It obviously works here.

**Comment by adipose** [comment]
My mistake!
