### ISSUE TITLE
[BUG] PGS subtitles unavailable

### ISSUE THREAD

**Issue by ryehamstrawberry** [Nevcairiel/LAVFilters#567]
On the suggestion of MPC-HC dev clsid2, I am requesting a potential fix for reading PGS sub tracks that are currently not accessible via MPC-HC but are via VLC.

Original bug report with MediaInfo: [[Bug] PGS subtitles unavailable to enable #2342](https://github.com/clsid2/mpc-hc/issues/2342)
Please see attached video sample (78MB, uploaded to third-party host due to GitHub attachment limitation): https://we.tl/t-Gv6JJwDhSM (Fixed)

**Comment by clsid2** [comment]
Sample does not contain subs

**Comment by ryehamstrawberry** [comment]
> Sample does not contain subs

Fixed: https://we.tl/t-Gv6JJwDhSM

**Comment by Nevcairiel** [comment]
The three subtitle tracks are flagged as "enabled = false", meaning they are disabled, and according to the Matroska specification should not be made available for playback.
