### ISSUE TITLE
Can`t compile ffmpeg under cygwin with build_ffmpeg.sh

### ISSUE THREAD

**Issue by Freyr666** [Nevcairiel/LAVFilters#57]
I`m trying to compile ffmpeg with build_ffmpeg.sh under cygwin in windows 7 amd64, but getting:

Building ffmpeg in GCC x86_64 Release config...
ERROR: libspeex not found

libspeex.a is in ../thirdparty/lib64(lib32), can`t realize, what i`m doing wrong.

**Comment by Nevcairiel** [comment]
Cygwin is not a supported build environment for LAV. You could probably make it work somehow, but not with my bundled scripts and libraries. Its designed to work with mingw-w64 only.
