### ISSUE TITLE
Inquiry: Dolby Vision?

### ISSUE THREAD

**Issue by bluecat1024** [Nevcairiel/LAVFilters#571]
Hi,

I wonder if the LAVVideoDecoder can correctly parse the dynamic PRU mapping information from Dolby Vision to the input of the video renderer?
Thanks so much.

**Comment by clsid2** [comment]
Yes

There are just two compatible renderers at this moment:
MPC Video Renderer
Jriver Video Renderer

**Comment by kasper93** [comment]
Buy an advert or something. This is not the place to advertise some proprietary software. And for Dolby Vision support it uses Dolby Vision extensions, so you get exactly the same experience in native Windows media player, whatever it is called these days.

**Comment by Nevcairiel** [comment]
LAV already passes the RPU to renderers.
