### ISSUE TITLE
AV1 Hardware Decoding doesn't seem to work with DXVA2 + AMD Radeon 6600M

### ISSUE THREAD

**Issue by shanoaice** [Nevcairiel/LAVFilters#575]
When I selected the DXVA2 (native) mode in LAVFilter Video Config, hardware accleration does not work for AV1 encoded videos (no H/W mark on the player and the Video Config panel reported no active hardware accelerator), but when I switch to the D3D11 the H/W sign go back and the hardware accelerator indicated my discrete graphic is active.

Selecting DXVA2 (copy-back) and specifying AMD RX6600M as the device does not work either.

**Comment by shanoaice** [comment]
Any other ways to verify it? Such as ways to get a list of supported encoding from different APIs?

**Comment by kasper93** [comment]
https://bluesky-soft.com/en/DXVAChecker ?

**Comment by shanoaice** [comment]
Checked it with GPU-Z's DXVA2 stuff. It reported lots of extra UNKNOWN encoding in addition to common AVC/HEVC/VP9 but not AV1. Perhaps it's a driver issue -- I will submit a bug report for AMD and see whether they can help.

**Comment by nyanmisaka** [comment]
AMD and Intel didn't implement DXVA2 AV1 support in their driver.
Use D3D11VA instead, and D3D12VA is the future.
