### ISSUE TITLE
Questions regarding manual installation of LAVFilters

### ISSUE THREAD

**Issue by Bamajon1974** [Nevcairiel/LAVFilters#577]
I have some questions regarding the manual installation of the LAVFilters

1. Do both the x64 and x86 LAVFilters need to be installed if one uses just 64-bit media players such as PotPlayer or MP-BCE? 

2. What is the best location to copy the LAVFilters? "C:\LAVFilters" ? "C:\Program FIles\LAVFilters"? Or in a user folder such as %AppData% or "ProgramData"? Or does it matter? 

3. Do the 64-bit files need to be installed in a "x64" subfolder, such as "C:\LAVFilters\x64" or can they be placed in the main install folder, such as "C:\LAVFilters" ? 

4. Do the files in the "include" directory need to be copied into the LAVFilters folder as well? Or can they be left out? 

Thanks!

**Comment by Bamajon1974** [comment]
Not sure how much value the previous comment adds. Please don't be rude. I am asking for clarification and to make the installation instructions crystal clear.

**Comment by Hrxn** [comment]
1. No, only x64 for x64
2. Doesn't matter. As long as the path can be found and is accessible
3. No, doesn't matter.
4. Not sure, probably not. Try it.

But I concur with clsid2, why even do the manual installation in the first place?

**Comment by Nevcairiel** [comment]
The include folder is for developers, users don't need it. In any case, this is a bug tracker, not a questions forum, and your questions have been answered, so going to close this.

**Comment by Bamajon1974** [comment]
Thank you!
