### ISSUE TITLE
Frame rate calculation needs improvement

### ISSUE THREAD

**Issue by bibsp** [Nevcairiel/LAVFilters#578]
Problem mentioned here.
https://github.com/clsid2/mpc-hc/issues/2478
Additionally I have some videos, those are 30 fps, lav reports it as 60 fps. If you need that I will upload.
All other players show correct information.

**Comment by Nevcairiel** [comment]
The FPS field is informational only and playback should never rely on it. Your video itself is even variable fps, what should it report? 0 might be a valid choice if nothing really fits. Or some arbitrary average that doesn't actually match any content in the file.

I did some changes to the field for a future update, but in short, ignore it, and tell other players to also ignore it. Its an unreliable field at best, and as soon as a file is in any way not fully constant frame rate, it'll show whatever it likes.
