### ISSUE TITLE
MKV: A track which have a segmented chapter containing a different audio codec than the main track's audio wouldn't play properly

### ISSUE THREAD

**Issue by BobbyWibowo** [Nevcairiel/LAVFilters#58]
**The main track:**
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High 10@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 9 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 20mn 40s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
... *(and so on)*

Audio
ID                                       : 2
Format                                   : **AAC**
Format/Info                              : **Advanced Audio Codec**
Format profile                           : LC
Codec ID                                 : **A_AAC**
Duration                                 : 20mn 40s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Delay relative to video                  : 9ms
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No

**The segmented chapter:**
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 8 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1mn 31s
Bit rate                                 : 7 025 Kbps
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
... *(and so on)*

Audio
ID                                       : 2
Format                                   : **AC-3**
Format/Info                              : **Audio Coding 3**
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : **A_AC3**
Duration                                 : 1mn 31s
Bit rate mode                            : Constant
Bit rate                                 : 320 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 3.48 MiB (4%)
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No

When the episode was played, I could view the video track of the segmented chapter, but the audio wouldn't play. When I tried to play the segmented chapter itself, it would play perfectly, both video and audio track.

Also, I tried to use Haali Media Splitter instead of LAV Splitter (but still using LAV Filters), and the segmented chapters wouldn't appear at all on the player. But for another track which had the same audio codec for its segmented chapters, they'd load just fine.
I also tried using a portable VLC, but surprisingly the segmented chapters played just fine, both video and audio, despite the audio having different codec.

**Example files here:**
The main track: [An episode of an anime](http://seedbox.datascorner.com/shst.php?f=(project-gxs)_Toaru_Kagaku_no_Railgun_(720p_10bit_BD)/(project-gxs)_Toaru_Kagaku_no_Railgun_01_(10bit_BD_720p).mkv)
The segmented chapters: [First segment: opening of the episode](http://seedbox.datascorner.com/shst.php?f=(project-gxs)_Toaru_Kagaku_no_Railgun_(720p_10bit_BD)/(project-gxs)_Toaru_Kagaku_no_Railgun_OP1_(10bit_BD_720p).mkv), [Second segment: ending of the episode](http://seedbox.datascorner.com/shst.php?f=(project-gxs)_Toaru_Kagaku_no_Railgun_(720p_10bit_BD)/(project-gxs)_Toaru_Kagaku_no_Railgun_OP2_(10bit_BD_720p).mkv)
*Note: You'll probably have to skip the sh.st link first. The server appeared to be logging your referrer. So, unless you were referred from an sh.st link, you wouldn't be able to download, AFAIK.*

**Comment by Nevcairiel** [comment]
Changing audio codecs in linked segments is not supported (or any codecs, really). They need to be the exact same codec to work, and generally also of a compatible encode. There are no plans to change this. Seamless on-the-fly reconfiguration in a dynamic system like DirectShow is not very reliable, so rather not start pretending its supposed to work.

When it comes to linked segments, there is generally one answer: If it works with Haali, then its supposed to work - if it doesn't, then you are trying to do something that this concept was not designed for.

**Comment by BobbyWibowo** [comment]
Ah, I see. I was thinking along that point, but had nothing to hold my thought. Thanks! I've contacted the encoder about this.
