### ISSUE TITLE
Chipmunk voices or no sowftare volume control when using player built-in audio transform filter

### ISSUE THREAD

**Issue by bojkonil** [Nevcairiel/LAVFilters#582]
Hi,
I'm using potplayer and lav filters, but when I speed-up playback for slow-running shows it results in chipmunk voices. Ticking the option to use the built-in audio transform filter fixes the chipmunk voice issue but somehow causes windows and player volume controls not having any effect on audio volume.

**Comment by Nevcairiel** [comment]
This is not a LAV issue, it neither does the transform nor control volume.
