### ISSUE TITLE
Feature Request: Pitch Correction Support During Playback Speed Adjustments

### ISSUE THREAD

**Issue by MarsGao** [Nevcairiel/LAVFilters#584]
I'm using potplayer player, when audio decoding with ffmpeg and audio renderer with potplayer itself, accelerated playback of video files tone stays normal; when audio decoding and audio rendering are both with lav audio decoder, accelerated playback of video files tone can't stay normal. 
I would like to suggest the addition of a "Pitch Correction" feature to LAV Audio Decoder. This feature would maintain the original pitch of the audio even when the playback speed is increased or decreased.
Thank you for considering this request. I am looking forward to your thoughts on this suggestion.

Best regards,
MarsGao

**Comment by Nevcairiel** [comment]
Indeed, LAV has no concept of audio playback rate, all it does is decode the audio. Any adjustment should happen afterwards.
