### ISSUE TITLE
RTX HDR not working for alot of X265 videos 

### ISSUE THREAD

**Issue by chrisssj2** [Nevcairiel/LAVFilters#585]
Most of my X265 videos are not working with RTX HDR, using the mod version or nvidia control panel driver doesnt seem to matter.

I think i have a few X265 work with it, but most of the X265 don't seem to work for me. Anyone had similiar results? It just wont trigger it.

**Comment by Nevcairiel** [comment]
This is not a function related to LAV Filters

**Comment by chrisssj2** [comment]
> This is not a function related to LAV Filters
I was thinking it was related to decoding in some way. I wasnt too sure what part is responsible for it, since x264 seems to work but x265 not. is it a player issue then or nvidia/hardware maybe then?

**Comment by chrisssj2** [comment]
> The video format is irrelevant.
> 
> RTX HDR does not work with 10-bit video.

I see. Do you know why this is the case why 10 bit video is not working with RTX HDR?
