### ISSUE TITLE
Feature reqest: Add ffmpeg.exe and ffprobe.exe to the package

### ISSUE THREAD

**Issue by sergwish** [Nevcairiel/LAVFilters#588]
FFmpeg libraries with the most of useful codecs are already being built and included in LAV Filters package (and decoding is done through them on playback as I understand it). 

I suggest building ffmpeg.exe and ffprobe.exe in FFmpeg in shared mode and including them in LAV Filters package.

That would allow users to skip installing full FFmpeg package with _yet another_ set of FFmpeg libraries when they need executables for youtube-dl, foo-youtube, mpc-hc or other software.

It should cost about 0.5Mb in uncompressed size (no need to include both 64-bit and 32-bit executables in the same package).

No need to add directory with executables to the PATH (but it may be an installation option, unset by default).

**Comment by Hrxn** [comment]
How do you even "install" FFmpeg?

It's just three static binary files, just put them in a directory in your PATH and all other apps that you mention here etc. can use them.
