### ISSUE TITLE
Blacklist more mov/mp4 handler names

### ISSUE THREAD

**Issue by v0lt** [Nevcairiel/LAVFilters#591]
The mov/mp4 handler names blacklist was expanded in commit 4710e61.

I found a few more handler names:
```
SubtitleHandler
VideoHandle
SoundHandle
Apple Video Media Handler
Apple Sound Media Handler
Apple Video Mediensteuerung
Apple Ton Mediensteuerung
MP4 Video Media Handler
MP4 Sound Media Handler
Bento4 Video Handler
Bento4 Sound Handler
Mainconcept MP4 Video Media Handler
Mainconcept MP4 Sound Media Handler
#Mainconcept MP4 Sound Media Handler
X264 Video Media Handler
X264 Sound Media Handler
(C) 2007 Google Inc. v06.24.2007.
(C) 2007 Google Inc. v08.13.2007.
IsoMedia File Produced by Google, 5-11-2011
```

Please add them to your blacklist.

--- 

Did you plan to completely stop using `mdia/hdlr` (ffmpeg "handler_name") as a track name?
Perhaps then more people will use `udta/name` (ffmpeg "title") as recommended in the [MP4Box documentation](https://github.com/gpac/gpac/wiki/MP4Box).

**Comment by Nevcairiel** [comment]
I've added a more generic check in a7212ba2, might remove using it in the future entirely, now that udta/name can actually be handled (since 85e8bfe)
