### ISSUE TITLE
VVC support broken?

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [Nevcairiel/LAVFilters#592]
According to your release changelog, LAV Filters support VVC demuxing and decoding since version 0.79.

I've recently started checking all of these new-generation MPEG codecs (except LCEVC, since you have to be registered with Nova to get the codecs) and found myself an issue. I've compiled a version of FFMpeg with EVC and VVC support and used it to reencode a couple of different videos in VVC to check things like size and quality, but when I tried to play them back, issues ensued:

1. When using FFPlay, it returned the errors `Invalid value at vps_layer_id[i]: bitstream ended.` and `Failed to read unit 0 (type 14).` a couple of times, then set the window to the correct size, but played instead an spectrogram of the audio stream (i.e. failed to output any video).
2. When using VLC, it returned an error saying it couldn't decode codec ' '.
3. When using MPC-BE, LAV Splitter returned an error saying it couldn't connect some pins in the graph.
4. When using FFMpeg to try to restore the video stream, in case it was broken, using `-c copy`, it returned the same errors as FFPlay and the resulting video showed the exact same behaviour.
5. When I tried encoding the video stream only as a bitstream, FFPlay managed to read it correctly and output a video signal (although I had to force the correct framerate), but when I tried muxing that known working bitstream with an audio file, FFMpeg failed to recognize the file (it did recognize it as coded in VVC, though) and removed it from the output.

The issue went away (in MPC-BE only) when, as a last resort, I installed the patched LAV filters from VVCEasy (once installed, the "broken" videos played back without issue), which means the issue must lay with these filters (I had version 0.79.2 installed).

**Comment by Nevcairiel** [comment]
VVC support is still experimental. Please report failing files to FFmpeg, they are developing the decoder.
