### ISSUE TITLE
Artifacts in Some YouTube HDR Videos When Trying to Playback Using Hardware Decoding

### ISSUE THREAD

**Issue by DedZasshu** [Nevcairiel/LAVFilters#595]
- LAV Filters 0.79.2
- GPU: NVIDIA GeForce RTX 3080, drivers 552.44
- Windows 11 Home 23H2 22631.3593
- MPC-HC 2.2.1

I've noticed that in some YouTube videos, when trying to watch in HDR, they show blocky artifacts when trying to playback using hardware decoding on MPC-HC (or even MPV's d3d11va). They playback fine if I disable hardware decoding, which would make me assume that it's a hardware bug or something, but somehow YouTube can playback the same videos just fine using hardware decoding without any blocky artifacts.

[Here's one example of what's going on](https://www.youtube.com/watch?v=juC2l_X1rSQ):
![Gamut Rings_ A better way to measure color 5_19_2024 10_05_43 AM](https://github.com/Nevcairiel/LAVFilters/assets/100014532/62fb2f13-d2e4-4578-b5a2-74b0b7eb4214)

And here's the mediainfo for that video:
[mediainfo.txt](https://github.com/Nevcairiel/LAVFilters/files/15369872/mediainfo.txt)

**Comment by DedZasshu** [comment]
> Confirm. Blocky artifacts clearly visible. Most obvious segment 00:18 to 00.21 and starting at 01:48
> 
> Also happens with DXVA2-cb.

Yeah, I also tried using that and D3D11 (Copyback) and still got the same results.

**Comment by lvqcl** [comment]
I can see the artifacts when I use nvidia card to decode (d3d11 native or copyback), but not when I use integrated intel 750 (d3d11 copyback).

**Comment by DedZasshu** [comment]
> I can see the artifacts when I use nvidia card to decode (d3d11 native or copyback), but not when I use integrated intel 750 (d3d11 copyback).

My A380 can playback without much issues using d3d11 copyback, too. So it probably is some NVIDIA hwdec bug or something. Which, again, makes me wonder how YouTube got it to work porperly with NVIDIA hwdec...

**Comment by L4cache** [comment]
test with ffplay -hwaccel vulkan don't have the artifact

**Comment by DedZasshu** [comment]
> And browsers use Media Foundation interface, not DXVA/D3D11/D3D12.

So I'm guessing it's a DirectX/Direct3D related bug?

**Comment by DedZasshu** [comment]
> Media Foundation uses D3D11/12.
> 
> The main difference is the decoder implementation that feeds the hardware decoder. FFmpeg vs MS.

Ah, so it's an FFmpeg bug.

**Comment by Nevcairiel** [comment]
Please try https://files.1f0.de/lavf/nightly/LAVFilters-0.79.2-2.exe, it seems to work now on my end.

**Comment by kasper93** [comment]
There is also this patch https://patchwork.ffmpeg.org/project/ffmpeg/patch/CZHCF9QL07FJ.3VOACXA14QCVF@yukari.in/ that possibly fixes more hwdecs than patching in `dxva2_vp9.c`.

**Comment by DedZasshu** [comment]
> Please try https://files.1f0.de/lavf/nightly/LAVFilters-0.79.2-2.exe, it seems to work now on my end.

Oh wow, it works! Can't wait for it to be integrated into MPC-HC w/ K-Lite Codec Pack!

**Comment by DedZasshu** [comment]
Well, with that. I think this should be good enough to close this issue since it's been noticed and being taken cared of.

**Comment by Nevcairiel** [comment]
Issues are historically closed when fixed, releases happen when they happen.
