### ISSUE TITLE
VP9 and HEVC hardware accelleration support wrongly detected

### ISSUE THREAD

**Issue by Tlentlen** [Nevcairiel/LAVFilters#597]
Hi,
I have a i5-1035G1 CPU (Ice Lake 10th Gen) with annexed Intel UHD graphic.
An anomaly i've found is that the HW capabilities are not get correctly (MPC screen).
In my case VP9 and HEVC HW decoding are not detected

https://www.imagebam.com/view/METTU27

 while they are in hardware specs

https://www.intel.com/content/www/us/en/docs/onevpl/developer-reference-media-intel-hardware/1-0/overview.html#DECODE-OVERVIEW-10TH

and correctly signaled by Gpuz

https://www.imagebam.com/view/METTU28

https://www.imagebam.com/view/METTU2E

and Chrome debug too

https://www.imagebam.com/view/METTU44

The verification testing i've done is to play a VP9 video in Chrome and VLC and the
Performance monitor "GPU" in task manager, "Video Decode" panel
correctly states 10% in both cases while with MPC + Lav it states 0% with 40% CPU (while 10% in the other case).

Could you fix?

Thank you

**Comment by Tlentlen** [comment]
Before posting I've done any possible combination of Video Renderer in MPC and "Hardware decoder to use" in LAV.
The situation doesnt' change either with D3D11 or others.

Moreover it cannot be a driver issue because HW acceleration is correctly used in VLC (default configuration) and Chrome.

**Comment by Nevcairiel** [comment]
Intel hasn't supported full hardware acceleration on D3D9/DXVA2 for ages, so yes, use D3D11.

**Comment by Nevcairiel** [comment]
Also note that those checkboxes you highlight are configuration, not an indication of support. If they are unticked, you choose to not use that hardware support.

If you want VP9 hardware support, ensure it is ticked.

**Comment by Tlentlen** [comment]
> Also note that those checkboxes you highlight are configuration, not an indication of support. If they are unticked, you choose to not use that hardware support.
> 
> If you want VP9 hardware support, ensure it is ticked.

WTFJC you're right. I've NEVER thougt (in years and years i'm using it) they would be CHECKABLE OPTIONS.

Ahaha so strange and stupid. Why it was unchecked by default?? Never clicked on any of in my life.

BTW checking them it does fix.

You can delete this entire thing (or you can leave in case some other incur in my situation eheh).

Thank you for your support.
