### ISSUE TITLE
LAV Audio Mixing. Wrong channel mixing when use 5.1 to 2.0 (Stereo) downmix

### ISSUE THREAD

**Issue by ValoWaking** [Nevcairiel/LAVFilters#598]
Hi. The problem is wrong channel mixing when use downmix from 5.1 to 2.0 channels. Voice (center channel) is too quiet compared to other channels. "Normalize matrix" function is not work properly and not fix this. You need add front speakers volume configuration to mixing settings for right manual setup sound matrix. It is also necessary to expand the volume control of each channel separately from 0 to 2 for better control. Also you need add some manual setting for "Normalazi Matrix" cause now this work very bad

![lav](https://github.com/Nevcairiel/LAVFilters/assets/37003886/1ad3bb88-2b52-4678-9d0f-194cab95dc78)

**Comment by Nevcairiel** [comment]
There are no plans for any changes, the existing options cover all requirements.

**Comment by ValoWaking** [comment]
But if front channel have too much volume we can't normalize mixing matrix manually. And result of it - u can't hear central chanel and voice. Thats why function where u can decrease volume of front channel is really needed
