### ISSUE TITLE
Please support additional HTTP headers when streaming

### ISSUE THREAD

**Issue by zhouxinghong** [Nevcairiel/LAVFilters#599]
Hello! Please support additional HTTP headers when streaming

For example: most movie channel streaming requires additional HTTP header information to be played successfully.

```
#EXTINF:0 group-title="Sport",Some Cool Name
https://some.host.it/foobar/index.m3u8|Referer="https://some.host.it/"&User-Agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)"&Origin="https://some.host.it"
```

Because some applications directly support this format, it automatically sends these required HTTP headers to the remote host.

I carefully read the documentation of mpc-hc64 and found that the current mpc-hc64 is based on yt-dlp for streaming media processing and loading, so it should be able to accept command options, so that these headers can be added to requests sent by HTTP:

```
mpc-hc64 --referrer="https://some.host.it/" --user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --headers="Origin: https://some.host.it" "https://some.host.it/foobar/index.m3u8"

Or

mpc-hc64 --referer="https://some.host.it/" --user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --headers="Origin: https://some.host.it" "https://some.host.it/foobar/index.m3u8"

Or

mpc-hc64 --Referrer="https://some.host.it/" --user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --headers="Origin: https://some.host.it" "https://some.host.it/foobar/index.m3u8"

Or

mpc-hc64 --Referer="https://some.host.it/" --user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --headers="Origin: https://some.host.it" "https://some.host.it/foobar/index.m3u8"
```

Please parse the above format and pass parameter options to yt-dlp:
Parameter names that support parsing are recommended to include the following naming styles:
referrer, Referrer, referer, Referer should all be accepted.

Since the latest version of mpc-hc64 cannot send additional HTTP header information to the remote host, the process of playing streaming media always fails! So I hope you guys can consider this feature request and implement it in the next release. mpc-hc64 is a perfect video and audio tool. As a user, I would like to thank you very much for your continued support and continuous development of it so that it can be accepted and used by more and more users. 💗🎉👏🌹👍🏆😜

```
test link one
https://ss191.nebuato.com/stream/A/AA/CJISq12nW9MvvHmm8934XbkngZZ96XEBSUQWF9oX/hls1080/CJISq12nW9MvvHmm8934XbkngZZ96XEBSUQWF9oX1080.m3u8

test link two
https://cdn-bgocihpmovcae3c6b49a0959a83az1b8.streamfastpro.com/621bf60fa4b05c0ab63e38087a9a1423/1/2/zoNoIGs4NfvDYO9BpUaI8Q/zoNoIGs4NfvDYO9BpUaI8Q.m3u8
```

Computer operating environment:
Windows 10 19044
mpc-hc64 2.2.1

**Comment by Nevcairiel** [comment]
It sounds like you want to request this from mpc-hc64, LAV does not interact with yt-dlp.

**Comment by zhouxinghong** [comment]
and all media players based on LAV Filters for video rendering.

**Comment by zhouxinghong** [comment]
![image](https://github.com/Nevcairiel/LAVFilters/assets/54253524/ad4d9cfe-ac7f-4fd3-956f-1dd09ba4922c)
