### ISSUE TITLE
M4A audio file doesn't play

### ISSUE THREAD

**Issue by pihug12** [Nevcairiel/LAVFilters#60]
**Samples:**
- http://www.criticalmusic.com/podcast/episodes/CriticalPodcast32Emperor.m4a
- http://www.criticalmusic.com/podcast/episodes/CriticalPodcast33Enei.m4a
- http://www.criticalmusic.com/podcast/episodes/CriticalPodcastVol.40_Hosted_by_Signal.m4a

The player is blocked at 0:00. The artwork doesn't show up. The chapters are shown.

![m4a lav](https://cloud.githubusercontent.com/assets/678038/12081119/e55cdc86-b270-11e5-83e7-927709cf6e58.png)

http://forum.doom9.org/showthread.php?p=1675219#post1675219
http://forum.doom9.org/showthread.php?p=1685089#post1685089

K-Lite Codec Pack 11.8.0 (MPC-HC 1.7.10.40 + LAV Filters 0.67.0.30)

**Comment by Nevcairiel** [comment]
Unfortunately, this is a bit of a known problem with sparse video streams like this one, as DirectShow for some reason doesn't allow audio to play when no video is playing.

I have tried in the past to make it behave better, but the usual answer is to ignore those streams instead. I'll have to see what can be done.

**Comment by Nevcairiel** [comment]
This has actually been fixed in the meantime, the cover art streams are now recognized as such and don't break playback anymore.
