### ISSUE TITLE
Generic D3D11 copyback choice

### ISSUE THREAD

**Issue by clsid2** [Nevcairiel/LAVFilters#602]
I think it would be useful to be able to force copyback mode for D3D11 without having to select a specific GPU. So a generic system-independent setting value.

**Comment by Nevcairiel** [comment]
All that "default device" would do is use the first device - which you can also do.

A generic/universal "first device" choice through the API can be easily achieved by setting SetHWAccelDeviceIndex(HWAccel_D3D11, 0, 0), or when directly providing a pre-set registry, just having HWAccelDeviceD3D11 = 0 and HWAccelDeviceD3D11Desc = 0
