### ISSUE TITLE
GraphEdit crash when LAVVideo.ax is registered as Filter in Win10x64

### ISSUE THREAD

**Issue by MySelf2001** [Nevcairiel/LAVFilters#61]
When LAVVideo.ax is registered as Filter in Windows 10 x64 v1511 build 10586.36, it is not possible to open create Graph Filter because it crash on expanding DirectShow Filter tree in "Insert Filters".
When LAVVideo.ax is unregistered, GraphEdit is working correctly.

![lavvideocrash](https://cloud.githubusercontent.com/assets/5358957/12085383/c7ee4398-b2bf-11e5-8341-e389b57bb6d6.jpg)

**Comment by filler56789** [comment]
Don't use GraphEdit, use GraphStudio, problem solved.
GraphEdit is limited to 100 media-types per filter.

**Comment by Nevcairiel** [comment]
As filler56789 has said, this is a problem in GraphEdit, it doesn't support filters with more than 100 supported types, which LAV does. GraphStudio is a capable alternative without this problem.
