### ISSUE TITLE
Feature Request/Suggestion - Fast play a video without change of audio pitch

### ISSUE THREAD

**Issue by Visitor76** [Nevcairiel/LAVFilters#615]
Really appreciate LAV and all the work around it!

One feature that is missing is the availability to fast play a video without change of audio pitch.
 If its possible to add, would be great!

**Comment by Nevcairiel** [comment]
Indeed, thats a players/audio renderers job.

**Comment by Visitor76** [comment]
Thanks for the response and feedback!
Apology for lacking deeper understanding for this matter.

The player I'm using depends only on external parts, does not have internal renderer. MPC in not an option in this case because it misses other functionalities that's needed in this particular situation.

I will explore the Sanear tip, and or other options.
Thank you all

**Comment by Visitor76** [comment]
> That is not the job of LAV.
> 
> You can do that by changing the audio renderer in MPC-HC option. Sanear and MPC Audio Renderer support pitch correction.

Thank you for the feedback

**Comment by Visitor76** [comment]
Turns out you can download and install the MPC audio renderer by it self, and use with other players. 
Everything works great now. 
Thanks for pointing me in the right direction.
