### ISSUE TITLE
No choice of audio tracks

### ISSUE THREAD

**Issue by Nuqvxz** [Nevcairiel/LAVFilters#616]
LAVFilters 0.69 (Windows XP x86)
LAVFilters 0.79.2 (Windows 7 x86)

There is no choice of audio tracks in this short (1435545 bytes) video:
https://drive.google.com/file/d/1gXaEdEW_pG4vjkpZE9UQcF-xo44eMEBe/view?usp=sharing

**Comment by Nuqvxz** [comment]
https://drive.google.com/file/d/1gdvYtbKc-f0KOqc-zq3mIxUyoCKTtgsf/view?usp=sharing

Audio #1
ID                             : 2
Format                         : AC-3
Format/Info                    : Audio Coding 3
Mode extension                 : CM (complete main)
Format settings, Endianness    : Big
Codec ID                       : A_AC3
Duration                       : 5s 24ms
Bit rate mode                  : Constant
Bit rate                       : 640 Kbps
Channel(s)                     : 6 channels
Channel positions              : Front: L C R, Side: L R, LFE
Sampling rate                  : 48.0 KHz
Compression mode               : Lossy
Stream size                    : 393 KiB (28%)
Default                        : Yes
Forced                         : No

Audio #2
ID                             : 3
Format                         : AC-3
Format/Info                    : Audio Coding 3
Mode extension                 : CM (complete main)
Format settings, Endianness    : Big
Codec ID                       : A_AC3
Duration                       : 5s 24ms
Bit rate mode                  : Constant
Bit rate                       : 640 Kbps
Channel(s)                     : 6 channels
Channel positions              : Front: L C R, Side: L R, LFE
Sampling rate                  : 48.0 KHz
Compression mode               : Lossy
Stream size                    : 393 KiB (28%)
Default                        : No
Forced                         : Yes

There is still no option to select any audio track.

**Comment by Nuqvxz** [comment]
Thanks, it helped.
This is the first time I've seen someone specifically set this flag to "No".

**Comment by ViperCode7** [comment]
Hi

Was encountering the same issue. The info helped.
Would it be possible to add a check box in the splitter's options to ignore the disabled flag?
