### ISSUE TITLE
unable to get hardware acceleration with x265 encoded video on rtx3060 and AMD 5800H

### ISSUE THREAD

**Issue by the-marox** [Nevcairiel/LAVFilters#617]
Hi to all,
I have tried with many h265 videos but the result is still the same: Hardware acceleration doesn't work 
I have uploaded this little sample done with a  pixel 7a 
https://drive.google.com/file/d/1NT_z9p_Nu3KGYzygdLsA9OO5DN-e2gNs/view?usp=drive_link
![image](https://github.com/user-attachments/assets/19c1d86b-c8d7-4d1c-a14a-899c4f21cb3e)

For high most of the video-encoded like this result in a jittery playback

**Comment by the-marox** [comment]
I forget to mention the version, which is 0.79.2.20-git

**Comment by bibsp** [comment]
@the-marox Make the file public.

**Comment by the-marox** [comment]
> @the-marox Make the file public.

Done, is it working now?

**Comment by the-marox** [comment]
> No. Download doesn't work. You should try your link in incognito. No need to ask. 😎

I have just noticed is corrupted. I will upload a new one
https://drive.google.com/file/d/1R50PM1UCO72kNJusc1VRbcyK43NOlEVk/view?usp=drive_link

**Comment by the-marox** [comment]
![image](https://github.com/user-attachments/assets/551b4532-fba2-4db9-9452-470465f7cb27)
I have just noticed this using dxva checker

**Comment by the-marox** [comment]
Solved was a BIOS-related problem from Lenovo. I rollback to a previous version
