### ISSUE TITLE
More audio mixing

### ISSUE THREAD

**Issue by MurasakiZerozaki** [Nevcairiel/LAVFilters#619]
I dont know how to suggest things in Github, but it would be great if audio mixing would be better via selecting existing speakers in system. Someone could not have sub channel or center, or more, and existing options (2.0, 4.0, 5.1, 6.1, 7.1) are not always convenient.

**Comment by Nevcairiel** [comment]
LAV focuses on decoding, if you want sophisticated mixing, that would be up to the audio renderer, or a post-processing filter.
