### ISSUE TITLE
Doubled frame rate info isn't being passed to the video renderer

### ISSUE THREAD

**Issue by GCRaistlin** [Nevcairiel/LAVFilters#62]
MPC-HC settings:
Video Renderer: madVR
Audio Renderer: ReClock
LAV Video:
[x] Enable YADIF Deinterlacing (.) 50p/60p (Video)
ReClock settings:
[x] PAL SpeedDown (force to 24fps)
madVR settings:
list all display modes madVR may switch to: 1080p24, 1080p25, 1080p30, 1080p50, 1080p60
[x] treat 25p movies as 24p (requires Reclock or VideoClock)

madVR switches the monitor to 24 Hz when playing PAL video (http://mir.cr/0TO7HKQ7) and to 30 Hz when playing NTSC video (http://mir.cr/0JGNT9O8). It causes dropped frames.
If we perform YADIF deinterlacing with ffdshow madVR behaves correctly (doesn't switch when playing PAL video 'cause there's no 48 Hz mode and switches to 60 Hz when playing NTSC video).

**Comment by Nevcairiel** [comment]
Fixing this wouldn't actually help you, as YADIF is only engaged after the initial connection to the video renderer, too late for the monitor switch. LAV Video doesn't actually know if a video is interlaced early enough to signal this any earlier.

**Comment by GCRaistlin** [comment]
I drop the player's window to the secondary monitor so I believe it would. And madVR can switch the display mode even in the middle of the playing. Anyway, ffdshow passes the correct data, why LAV can't do the same?

**Comment by Nevcairiel** [comment]
Try with the latest nightly, I believe it should work in some limited cases. Note that it still relies in figuring out if a video is interlaced, which is not always information which is available early enough, and I don't believe madVR switches modes in the middle of playback.

**Comment by GCRaistlin** [comment]
No change with the latest build (54).
> I don't believe madVR switches modes in the middle of playback
You're right it doesn't. I mixed it up with playback restart.

**Comment by Nevcairiel** [comment]
I have confirmed just now that LAV Video now says 50 fps for a interlaced PAL movie to madVR when YADIF is on and in 50/60 mode.

In any case, personally I would just have display modes switch to 50/60 and not worry about double or single rate.

**Comment by GCRaistlin** [comment]
But madVR still switches the monitor to 24 Hz when YADIF is on and in 50/60 mode + ReClock's PAL SpeedDown is on.
To be precise, with madVR's "automatically activate deinterlacing when needed" disabled ffdshow+madVR+ReClock behaves the same way as LAV+madVR+ReClock does (switching to 24 Hz while video frame rate is 50 fps => dropped frames, too). With madVR's "automatically activate deinterlacing when needed" enabled madVR switches to 50 Hz regardless of ffdshow's YADIF "Double frame rate" option state. So it works incorrectly, too, but in a different way.
