### ISSUE TITLE
Incorrect stream name in AVI.

### ISSUE THREAD

**Issue by Aleksoid1978** [Nevcairiel/LAVFilters#63]
https://yadi.sk/i/I-H-4DqtmvFDZ
LAV Source show incorrect stream's name. Stream's name store in Cyrillics(CP 1251).

**Comment by Nevcairiel** [comment]
I can't really test if the cyrillic stream names are shown properly now, but at least it doesn't show unknown stream 3 anymore. ANSI encoded metadata will only ever show properly on a system which runs in the same encoding.
