### ISSUE TITLE
problem decoding some interlaced videos in dxva2n mode

### ISSUE THREAD

**Issue by jacwl** [Nevcairiel/LAVFilters#64]
LAV video decoder outputs bad frames with dotted mosaic-like blocks when decoding some interlaced h264 videos in dxva2n mode

![sample mkv_015018 828](https://cloud.githubusercontent.com/assets/15713107/12489681/69506d7a-c0ac-11e5-8d4e-e90ddac5eb86.png)

GPU in use is Intel HD Graphics 3000 (sandy bridge) with latest driver (9.17.10.4229)

Latest version of LAV video decoder that would work in dxva2n mode with those interlaced h264 videos is 0.64.0

video sample  http://www73.zippyshare.com/v/ynf4ASeU/file.html

**Comment by Nevcairiel** [comment]
You are certain 0.65.0 is already broken?

**Comment by Nevcairiel** [comment]
Please try this version:
https://files.1f0.de/lavf/nightly/LAVFilters-0.67.0-65.exe

It should hopefully be fixed.

**Comment by jacwl** [comment]
Yes indeed!
I'm able to see the correct image now using the nightly version you provided!
Thanks dude!!!
