### ISSUE TITLE
Missing icon in Applications and Features in Windows 10.

### ISSUE THREAD

**Issue by Residentcl** [Nevcairiel/LAVFilters#65]
Missing icon in Applications and Features in Windows 10.

![gegegegr](https://cloud.githubusercontent.com/assets/1659401/12513890/0d293182-c0ff-11e5-9a9e-169b64cf97d3.png)

**Comment by Nevcairiel** [comment]
Its not meant to have any specific icon.

**Comment by Residentcl** [comment]
ok. It would be good if in the future add :)
