### ISSUE TITLE
DXVAcb + HEVC10 + YV12 = Incorrect decoding result

### ISSUE THREAD

**Issue by msg7086** [Nevcairiel/LAVFilters#67]
I noticed that when setting decoding mode to DXVA copy back, selecting output format to YV12, and decoding HEVC 10bit video files, I got grayscaled magenta picture.

NV12 is working fine. AVC is fine.

Reproduced on Win10 x64, GTX 950, MPC-HC / DirectShowSource2.

**Comment by Nevcairiel** [comment]
Works fine for me, try the latest nightly build from https://files.1f0.de/lavf/nightly/?
Note that YV12 output is not recommended, as it will be crawling slow compared to NV12 or P010 native output.

**Comment by msg7086** [comment]
With 67.76 it's working perfectly. I'm using YV12 output because I need to introduce h/w decoding into avisynth, and AFAIK this is the only supported colorspace.

Thanks.
