### ISSUE TITLE
deinterlacing avc 10bit mbaff content

### ISSUE THREAD

**Issue by sdsucks** [Nevcairiel/LAVFilters#68]
LAVFilters don't seem to deinterlace this video.
I tried mpv vlc kodi mpc-be and they all deinterlace it properly.

30s sample:
https://drive.google.com/file/d/0B1mCVSSmbT2LaFNWRFJyZWNyaUk/view?usp=sharing

**Comment by Nevcairiel** [comment]
Software Deinterlacing of 10-bit content is not supported. You can however output the content interlaced and let the renderer perform the deinterlacing just fine.

**Comment by Nevcairiel** [comment]
I just tested to confirm, even when software deinterlacing is turned on, it'll gracefully fallback to untouched interlaced output, letting the renderer or any downstream processing filter deinterlace it.

**Comment by sdsucks** [comment]
thank you for clarifying this. strange thing is that only madvr deinterlaces it in my case. all the other renderers fail. some play it at 30 frames without deinterlacing, others play it at 30x2(duplicate) without deinterlacing. anyway i think it's my problem.
