### ISSUE TITLE
CUVID support in Windows 10

### ISSUE THREAD

**Issue by chorong761** [Nevcairiel/LAVFilters#69]
Hi, I am using LAV Video Decoder version 0.67.0.69-git with a Nvidia 840M GPU on Windows 10. The CUVID acceleration would show as "avcodec" when CUVID is selected and a video is playing. On my other machines running on the same LAV versions, Windows 10, and same Nvidia driver versions (Newest Stable drivers frim NVIDIA), the CUVID acceleration would work fine, and those 2 machines are using a GTX 770 and GT 430.

Any Suggestions?

**Comment by Nevcairiel** [comment]
CUVID has a bunch of known problems on Windows 10, but ultimately its up to NVIDIA to make sure those are resolved - they do not seem to be overly interested in CUVID anymore, however.

There is nothing I can personally do about such problems. CUVID is a big blackbox which either works, or doesn't.
