### ISSUE TITLE
Install via batch files does not take effect

### ISSUE THREAD

**Issue by stafio** [Nevcairiel/LAVFilters#70]
I had run into an issue where mp4's were just loading black, rather than playing the video. 

Installing LAVFilters through the exe linked here: http://forum.doom9.org/showthread.php?t=156191 and then adjusting codec settings via Win7DSFilterTweaker 5.9

Running the batch install files in an admin shell (Windows 10) the same issue with an mp4 just showing as black was present, even after setting the preferred codes in Win7DSFilterTweaker 5.9.

**Comment by Nevcairiel** [comment]
The batch files are not meant to be a replacement for the installer, they are only offered as a convenience for advanced users that know what they are doing. For a clean and full setup the installer has to be used.

**Comment by stafio** [comment]
In case anyone else comes across this, I was able to accomplish what I wanted (no user interaction on install) by doing: 
LAVFilters-0.67.exe /VERYSILENT
