### ISSUE TITLE
No sound with that mkv file

### ISSUE THREAD

**Issue by Klaus1189** [Nevcairiel/LAVFilters#73]
https://drive.google.com/file/d/0B4y5u0gBKYqbaTh0UWZzeGZQSXM/view?usp=sharing
I can't play this file -> I get so sound.
VLC media player can play it.

**Comment by Nevcairiel** [comment]
The link is broken, it appears copy-pasted in its shortened form, instead of the full link.

**Comment by Klaus1189** [comment]
fixed link

**Comment by Klaus1189** [comment]
Thank you
