### ISSUE TITLE
Can't seek/jump in dash mp4 files anymore

### ISSUE THREAD

**Issue by Klaus1189** [Nevcairiel/LAVFilters#74]
If I play a dash mp4 file downloaded from youtube I can't jump to a specific time with MPC-HC or MPC-BE anymore. If I use the built in Filters of MPC-BE it works.

**Comment by Nevcairiel** [comment]
Can you upload a sample file somewhere?

**Comment by Klaus1189** [comment]
strange is that not every file is affected, I uploaded two files, one is fine and the other causes this issue:
https://drive.google.com/folderview?id=0B4y5u0gBKYqbLThBQUgxcXVwUEU&usp=sharing

**Comment by Klaus1189** [comment]
I just noticed that there is another problem with this kind of files. At a specific time the playback gets suttery and in display stats the framerate gets lower to about 18 fps and the red line in the right corner is going up and down very wild. In this test I didn't changed the refresh rate to the match the videos framerate, so there a typical 3:2 pulldown artefacts in the graph with the red and green line visible. See here:
https://drive.google.com/file/d/0B4y5u0gBKYqbLU9mTkpQTlVORE0/view?usp=sharing

**Comment by Klaus1189** [comment]
Can you confirm that?

**Comment by Nevcairiel** [comment]
Both mp4 files seem to seek just fine.

**Comment by kasper93** [comment]
Speaking of youtube. Local dash files works fine. But they glitch when seeking during playback from url. For example grab url by using command `youtube_dl 'https://www.youtube.com/watch?v=5UE3jz_O_EM' --get-url` and open video link. It glitches every time until it gets next I frame.

**Comment by Klaus1189** [comment]
But I have several other files, which can't be jumped to a specific time with the slider in MPC-BE and MPC-HC. I use latest MPC-HC with integrated LAV Filters and latest Nightly LAV Filters from today LAVFilters-0.68.0-12.exe

On both players I can't jump to 01:00 with the slider, I always get to 00:04. I resetted MPC-HC to default settings, same thing.

**Comment by Klaus1189** [comment]
I made a video where you can see the issue:
https://www.youtube.com/watch?v=l_GfhC7IiAg

**Comment by kasper93** [comment]
@Klaus1189: Could you go to Options->Tweaks and disable "fast seek"? YouTube doesn't insert a lot I frames from what I see.

**Comment by Klaus1189** [comment]
@ kasper93: Yes, i disabled I works, but if I mux the mp4 to a MKV file I don't need to disable this option. And not all dash mp4 files I have, cause this issue.

**Comment by Klaus1189** [comment]
Hah, I have it:
LAVFilters-0.66.0-29.exe 2015-10-20 02:47  8.9M  is the last working version
LAVFilters-0.66.0-31.exe 2015-10-23 02:47  9.0M  is the first version with this behavior you can see on youtube video I made

**Comment by Klaus1189** [comment]
Seems like this issue was introduced in this commit:
https://github.com/Nevcairiel/LAVFilters/commit/c78307855c80e0d81b207bffeca1d19ac9300c1e

or in this one:
https://github.com/Nevcairiel/LAVFilters/commit/e35572ffa4547a9bed6e7cb1319ebefed0d75e53

**Comment by Nevcairiel** [comment]
Seeking in those files works perfectly fine, it just doesn't really export the seek points as key frames, hence MPC-HC forces it to seek to 0:04, not LAV. Key-frame seek is a bad kludge, not a solution, so I would rather recommend to turn it off.

**Comment by Klaus1189** [comment]
Ok, I turn it off, but what is different in versions till 0.66.0-29? Till this version I don't have to turn off key frame seeking, it works also with this.
Do you know what changed since 0.66.0-31 which is causing that?

**Comment by kasper93** [comment]
> Seeking in those files works perfectly fine, it just doesn't really export the seek points as key frames, hence MPC-HC forces it to seek to 0:04

So what has changed? LAV hasn't reported keyframes before for those files or now it is bogus? 

Either way url seeking is not working correctly, whether it is something to fix I don't know.

**Comment by Klaus1189** [comment]
Aah ok, but what is different when the file is muxed to a mkv? Then there is no issue with seeking to keyframes and the latest versions of LAV Filters.
