### ISSUE TITLE
DXVA 2 poor support to H264

### ISSUE THREAD

**Issue by Srlan** [Nevcairiel/LAVFilters#75]
H264  MKV not decoded by DXVA hardware, but by processor unity. 

1° option: DXVA2 COPY BACK. (not working)
2° option: none

Native DXVA2 always never work before. Other codecs work fine. Other LAV ancient versions work fine.

**Comment by Nevcairiel** [comment]
This reports lacks any kind of information that would even begin to start describing an issue.

**Comment by Srlan** [comment]
DXVA 2 is not working with DXVA Copy Back hardware decoder. Olders versions work fine. Video and audio desync because this issue. Slow motion are a problem too because this. Processor overhealth and noise are a problem too. Thanks anyway.
