### ISSUE TITLE
Video not work fix please , i attaced video link 4 seconds  

### ISSUE THREAD

**Issue by pop-dahaka** [Nevcairiel/LAVFilters#76]
Hi , 
This video not work , I attached 4 seconds video , fix please next version .
http://www.mediafire.com/download/v5yzszx1yxv6eai/ERTU-01_20160328-204717.7z

**Comment by Aleksoid1978** [comment]
This file contain MPEG-2 video stream that don't have I-frames.

Where did you get this file ?? You have full source, can upload it ??

**Comment by Nevcairiel** [comment]
MPEG-2 without key frames is not supported, since it lacks any kind of metadata to identify it as such and resume decoding safely.

**Comment by pop-dahaka** [comment]
I record it from sport feed channel , i can record more minutes next time this feed active again and upload and send you the link , i used old filter elecard to view it (elecard filter can decode it) .

**Comment by filler56789** [comment]
Then please keep using Elecard's decoder. Nevcairiel already said that LAV Filters are not supposed to support broken files.

**Comment by pop-dahaka** [comment]
Am trying to make lav filters better , i don't like elecard because of poor picture , how many minutes are enough to record from that channel so you can get i frame key ? 

    On Wednesday, April 6, 2016 9:07 PM, Marsia Mariner <notifications@github.com> wrote:
 

 Then please keep using Elecard's decoder. Nevcairiel already said that LAV Filters are not supposed to support broken files.—

**Comment by pop-dahaka** [comment]
Am trying to make lav filters better , i don't like elecard because of poor picture , how many minutes are enough to record from that channel so you can get i frame key ?

**Comment by pop-dahaka** [comment]
I found an other channel with the same problem and i record 1 minutes and 19 seconds (i can record any minutes you want) , test please those 79 second enough or i can record bigger file , i wish you can fix it , here you are the link 
http://www.mediafire.com/download/noup95lo5fw94gk/i_frame_Current20160408-210645.rar

**Comment by pop-dahaka** [comment]
Hi,I found an other channel with the same problem and i record 1 minutes and 19 seconds (i can record any minutes you want) , test please those 79 second enough or i can record bigger file , i wish you can fix it , here you are the link 

http://www.mediafire.com/download/noup95lo5fw94gk/i_frame_Current20160408-210645.rar
 

    On Wednesday, April 6, 2016 12:07 PM, Hendrik Leppkes <notifications@github.com> wrote:
 

 Closed #76.—

**Comment by filler56789** [comment]
@pop-dahaka — **Aleksoid1978** is not the author /maintainer of LAV Filters. **Nevcairiel** is, and he already said _this issue is closed_.

**Comment by pop-dahaka** [comment]
That means no hope to fix ,
Thanks filler .

**Comment by Nevcairiel** [comment]
Note that this may be fixed in the latest version. Not sure it works for all files.

**Comment by pop-dahaka** [comment]
Thanks for your efforts , I'll wait when you release next version .
