### ISSUE TITLE
nvidia 364 slow hevc main10

### ISSUE THREAD

**Issue by MikeGCV** [Nevcairiel/LAVFilters#77]
With the latest drivers from nvidia on my 960gtx i get very low framerate for hevc main10 300mbps (crowd video). With 361 everything works fine. (Win10 x64)

**Comment by Nevcairiel** [comment]
If a driver change causes a slowdown, I suggest you report this to NVIDIA instead.
You should also make sure you do not run out of video memory,  a 2GB GTX960 can sometimes run out if some other things consume additional memory and you try to decode 4K content.

**Comment by MikeGCV** [comment]
Nothing more is running when i'm testing. In 361 it works great. I guess i'll report to nvidia, with no great hope of resolution

**Comment by Nevcairiel** [comment]
FWIW, performance seems to not have changed for me with the latest drivers, still around 50-55 fps in dxva2 native on a crowd run 300mbit clip.
Note that the 300mbit video is broken in some ways, so its not a really good benchmarking example.

**Comment by MikeGCV** [comment]
Thank you for your reply,  i am using also the jellyfish video demo. Well that's strange, i have to test it again, which media player are you using?

thanks
