### ISSUE TITLE
video 4:2:2 not work

### ISSUE THREAD

**Issue by pop-dahaka** [Nevcairiel/LAVFilters#78]
video 4:2:2 not work , fix please .

An other link download 4 seconds 
http://www.mediafire.com/download/vk5kn555f4wxbb9/4_2_2_video_ERTU-W6_20160329-180654.rar

**Comment by Aleksoid1978** [comment]
This file contain MPEG-2 video stream that don't have I-frames.

Where did you get this file ?? You have full source, can upload it ??

**Comment by Nevcairiel** [comment]
MPEG-2 without key frames is not supported, since it lacks any kind of metadata to identify it as such and resume decoding safely.

**Comment by pop-dahaka** [comment]
I record it from sport feed channel , i can record more minutes next time this feed active again and upload and send you the link , i used old filter elecard to view it (elecard filter can decode it) .

**Comment by pop-dahaka** [comment]
Am trying to make lav filters better , i don't like elecard because of poor picture , how many minutes are enough to record from that channel so you can get i frame key ?
