### ISSUE TITLE
QuickSync on Intel HD Graphics 520 does not activate

### ISSUE THREAD

**Issue by mareksuski** [Nevcairiel/LAVFilters#79]
Hi,

I have Surface Pro 4 with Intel HD Graphics 520 and while trying to play a movie:

> Video: HEVC 3840x2160 29.97fps [V: hevc main, yuv420p, 3840x2160]
> Audio: AAC 48000Hz stereo 194kbps [A: aac lc, 48000 Hz, stereo, 194 kb/s]

with:
> MPC-HC (Nightly, 64-bit)
> ------------------------
> Build information:
>     Version:            1.7.10.130 (6d03440)
>     Compiler:           MSVC 2015 Update 1
>     Build date:         Apr  2 2016
> LAV Filters:
>     LAV Splitter:       0.68.0.0
>     LAV Video:          0.68.0.16
>     LAV Audio:          0.68.0.16
>     FFmpeg compiler:    MinGW-w64 GCC 5.3.0
> Operating system:
>     Name:               Windows NT 10.0 (build 10586)
>     Version:            10.0 (64-bit)
> Hardware:
>     CPU:                Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
>     GPU:                Intel(R) HD Graphics 520 (driver version: 20.19.15.4380)

with QuickSync hardware acceleration then processor usage is at 100%:

![image](https://cloud.githubusercontent.com/assets/18272118/14263634/ef3a539e-fabb-11e5-83ba-f55879ee347e.png)

but when switched to DXVA2 then usage is on around 7%:

![image](https://cloud.githubusercontent.com/assets/18272118/14263599/b0919d32-fabb-11e5-99c5-f8109a0136bf.png)

I have tried 3 diffrent drivers versions and 0.67 and 0.68 LAV Video Decoder versions and have same issue.

Maybe it is a issue with QuickSync in LAV Video Decoder?

Best regards,

Marek Suski

**Comment by Nevcairiel** [comment]
If QuickSync doesn't work it could have two reasons;

- You need to install a proper driver which includes the QuickSync library (Windows Update driver does not work properly)
- The QuickSync library just can't access the GPU for some reason, and nothing can be done.

For what its worth, DXVA2 Native is the better option on such a device anyway, it uses less CPU and therefor less battery.

In any case, there is nothing I can really do about that. QuickSync is a thirdparty component thats only offered through LAV as a convenience, but I don't develop it myself.
