### ISSUE TITLE
add support for WebVTT subtitles

### ISSUE THREAD

**Issue by Klaus1189** [Nevcairiel/LAVFilters#80]
MPC-BE developers added just recently support for WebVTT subtitles in r1405.

I use latest external LAVFilters-0.68.0-19.exe 2016-04-13 02:54  9.6M  but it doesn't seem to recognize the VTT subtitles. Here is a testfile:
https://drive.google.com/file/d/0B4y5u0gBKYqbSFczT1VPc2l5SXM/view?usp=sharing

**Comment by Nevcairiel** [comment]
There is no DirectShow type for WebVTT subtitles, nor a subtitle renderer that handles them. MPC-BE just pretends they are nothing but text, but any special formatting is lost, which seems to defeat the purpose of using a format like WebVTT in the first place.

**Comment by Klaus1189** [comment]
Thank you for the reply, WebVTT is the standard subtitle format on youtube now and it only uses this kind of little format part. Maybe we can add it like in MPC-BE and for later we add the full support of WebVTT

**Comment by ale5000-git** [comment]
Apparently they are embedded in MKV using S_TEXT/WEBVTT, is it possible to support it?

**Comment by ale5000-git** [comment]
Sample file: https://trac.ffmpeg.org/raw-attachment/ticket/5641/cut-vtt.mkv
More info: https://trac.ffmpeg.org/ticket/5641

**Comment by Nevcairiel** [comment]
Basic implementation in 7fa9eca9201c6b8068e548dc13c8d253498754a2
