### ISSUE TITLE
.265 video files play but don't report progress

### ISSUE THREAD

**Issue by matteo411** [Nevcairiel/LAVFilters#81]
The source/splitter filter isn't reporting progress properly for .265 files.

**Comment by Underground78** [comment]
If you're trying to play a raw H265 video, this is normal.

**Comment by Nevcairiel** [comment]
Indeed, to report progress the duration needs to be known, and raw video files like .265 files do not have a known duration. If you want this to work, mux them into a container format that provides such information, like mp4 or mkv, or many others.

**Comment by matteo411** [comment]
Thanks! that makes sense and I'll give the muxing a shot

-Matt
