### ISSUE TITLE
RGB32 colorspace vertically flipped is missing

### ISSUE THREAD

**Issue by 4b71nmdx** [Nevcairiel/LAVFilters#83]
RGB32 color space vertically flipped output option is missing, and some player and input format combinations produce upside-down video image.

**Comment by Nevcairiel** [comment]
LAV flips the image appropriately if the renderer asks for that. Its a well documented behavior pattern how a video renderer or downstream filter can ask for flipped output. I do not see how an option would help anything there, except catering for broken software which is not something I do.

**Comment by Nevcairiel** [comment]
At the very least please provide additional information which player and input format this applies to, so it can maybe be fixed without a manual option to override it.

**Comment by Nevcairiel** [comment]
Please reopen if you can provide any further information.
