### ISSUE TITLE
Feature Request: support for two subtitle pins

### ISSUE THREAD

**Issue by Krakean** [Nevcairiel/LAVFilters#85]
Hello.
My media player allows user to see two separate subtitles simultaneously (useful when learning language, for example) - http://puu.sh/orbtZ/1e0e4eb740.jpg, but currently I use modified MPC-BE codecs as internal codecs (so user don't have to install anything) to make it work. 
But, due to inconsistent updates of MPC-BE codecs, I want to switch to LAV Filters.
So, I would like to ask you: can you please add support for two subtitles pins? So I don't have to keep two copies of LAV Filters - mine and your master, and merge it, because otherwise users became dependent on how frequently I will update LAV Video and they will be not be able to use your official version.

Regards, Dmitry

**Comment by Nevcairiel** [comment]
Sorry, but I do not plan to offer multiple pins of the same type, it does generally not fit into LAVs design and would result in quite a bit of complexity when dealing with the stream chooser and whatnot.
