### ISSUE TITLE
Filters attempting to connect to Internet

### ISSUE THREAD

**Issue by Eglin** [Nevcairiel/LAVFilters#86]
Hi there,

I would like to get some filters setup to allow my OS to play MKV files, but in testing LAVFilters I found something worrying.  Every time I launch an application using the filters it attempts to connect to the Internet.  I am confident this is related to the filters, since the application never requested Internet access in the past.  The filters attempted to connect to the IP addresses 23.64.171.27, 23.4.59.27,
and 23.65.11.27 in the three times I tested it.  The addresses seem to resolve into symcd.com domains.  There were many warnings of viruses and trojans on Google searches of the IP addresses that seemed to be related to this domain.  

I cannot see anything in the settings regarding checking for version updates or anything that would explain why the filters are attempting to go to the Internet.  I can't be bothered to setup a sniffer right now, but perhaps someone here can explain to me why the software is attempting to communicate on the Internet instead of simply decoding the videos?

Thanks,
Eglin

**Comment by Nevcairiel** [comment]
LAV Filters do not connect to the internet unless you specifically open a remote URL as a media file.

**Comment by Eglin** [comment]
Then there is something else in your dependency chain that is doing it.  I tested with two different media players using a local .mkv file.  Each player was able to play AVI movies previously without requesting Internet access.  If I tried to play .mkv files, they would not play.  I installed your LAVfilter package, LAVFilters-0.68-Installer.exe, and each player began requesting access to connect to the aforementioned sites.  I uninstalled your LAVFilters package and the players reverted to their old, offline, behavior.  

The videos will play fine without being granted access, so pulling the plug on your computer isn't a valid way to disprove my claim.  However, the fact that you are unaware of why your software might be attempting to connect to the Internet increases my worry instead of relieving it.

Regards,
Eglin

**Comment by Underground78** [comment]
@Eglin: The most likely explanation is that your computer is infected and
that it has nothing to do with LAV Filters itself.

**Comment by Eglin** [comment]
How might you explain the way that multiple video players that NEVER ask for Internet access begin doing so ONLY after LAVfilters are installed and immediately cease asking after the filters are removed?

**Comment by Underground78** [comment]
Because the files are infected? It doesn't mean the problem is in LAV
Filters itself. You could have downloaded non-official binaries which were
infected or maybe the files got infected on your computer. Anyway LAV
Filters has many users, I think there would be more reports if it was
really infected.

**Comment by Eglin** [comment]
I downloaded the installer from this website (https://github.com/Nevcairiel/LAVFilters/releases/download/0.68/LAVFilters-0.68-Installer.exe).  No MD5 hash or anything was made available to verify that the version being served matches what was published, but I didn't download anything via a third-party.  

With respect to what anyone else has reported, I cannot comment.  But it should be trivially easy to verify yourself with tools built into Windows that a connection is being attempted/made.  I cannot fathom why not one person responding to this thread has made the attempt to test and verify instead of diverting.

Also, I should point out that I never claimed the files are infected.  I claim that they are needlessly attempting to make an Internet connection to a domain that has some red flags.  It could be that one of the components in the toolchain is reaching out for a certificate authority or there could be some matter of analytics built into one of the packages.  But whatever the cause, the filters are definitely trying to connect to external sites.  It makes me very uncomfortable, which is why I came here seeking explanations.

**Comment by Nevcairiel** [comment]
All I can tell you is that LAV does not do any internet connections unless specifically asked to do so, and I can also not reproduce any unexpected connections on my system after inspection of Wireshark and Process Monitor.

You have no proof that it actually is caused by LAV, correlation does not imply causation.

**Comment by Eglin** [comment]
> All I can tell you is that LAV does not do any internet connections unless specifically asked to do so

LAVSplitter.ax loads avformat-lav-57.dll which loads Secur32.dll which loads ws2_32.dll via which the connection is attempted.  I really don't want to install a complicated toolchain to figure out what's going on, but I'm not getting a lot of help here.  The software is definitely trying to connect to the Internet.

**Comment by filler56789** [comment]
I have just updated LAV Filters to version 0.68.0.29, and they behaved as they should — in other words, no attempt of connecting to the Internet while playing local files. Tested on both Windows 7 x64 and Windows XP, using MPC-HC, PotPlayer, and WMP.

**Comment by mhanor** [comment]
Use Process Monitor, from Sysinternals(Microsoft), with symbols properly configured, to look at the thread stack, when the process attempts network communication with 23.64.171.27, 23.4.59.27

**Comment by Nevcairiel** [comment]
> I really don't want to install a complicated toolchain to figure out what's going on, but I'm
> not getting a lot of help here. The software is definitely trying to connect to the Internet.

Two people here have tried to reproduce this issue at least, and not found any unexpected connections. So unless you can produce any more concrete information, there is no way we could possibly help you.

**Comment by micha137** [comment]
Does the video contain subtitles?  If yes, I suspect them to contain javascript.

**Comment by Underground78** [comment]
LAV Filters doesn't render subtitles and it certainly doesn't parse and execute JavaScript. In fact I'm not aware of any commonly used subtitles renderers that execute JavaScript.
