### ISSUE TITLE
don't delete/reset existing settings on uninstall/reinstall

### ISSUE THREAD

**Issue by mhanor** [Nevcairiel/LAVFilters#87]
Usually, I uninstall the old version, before installing the new one. The installer should not remove the settings or should ask if it should remove the existing settings when uninstalling LAV Filters, or it should ask the user if it should reset the settings when installing. I don't know what case it is, out of these two.

**Comment by Nevcairiel** [comment]
Uninstall removes everything LAV created from your system, thats what a good uninstaller does.
If you want to switch to a different version and keep the settings, just install the new version and don't uninstall before, the installer is specifically designed to handle upgrades.
