### ISSUE TITLE
lav insatlation want close windows explorer 

### ISSUE THREAD

**Issue by pop-dahaka** [Nevcairiel/LAVFilters#88]
Lav 0.68.1 want close windows explorer -
1. when push automatically close the applications windows freeze and need shutdown manually from power .
2. when push don't close the applications installation complete correct and windows need to restart .
 
Win 7 sp1 X64 ultimate 

http://s32.postimg.org/uwlz27b7p/lav_bug.jpg

**Comment by Nevcairiel** [comment]
Closing Explorer is not something that always works reliable - but if one of LAVs files is in use by explorer, its one option to try. It gives you the option to either try or to require a reboot. There is no bug here.

**Comment by pop-dahaka** [comment]
Its better to offer restart windows after installation . I vote for remove option "automatically close the applications" because of windows freeze .
Thanks for the information.
