### ISSUE TITLE
HEVC Main12 decoding in DXVA2/CUVID support request.

### ISSUE THREAD

**Issue by fuchanghao** [Nevcairiel/LAVFilters#89]
GTX 1080/1070 Introduced dedicated HEVC (H.265) video decoding (up to Main12 HEVC).

https://en.wikipedia.org/wiki/Nvidia_PureVideo

**Comment by Nevcairiel** [comment]
This is nothing I can control, NVIDIA or Microsoft need to expose this capability as part of DXVA2.
Once this is done, it will be supported.

Note that CUVID does not even support 10-bit because NVIDIA doesn't support it anymore.
