### ISSUE TITLE
Frame accurate positioning for mpeg2

### ISSUE THREAD

**Issue by DTSMediaSoft** [Nevcairiel/LAVFilters#91]
The mpeg transport stream does not include a frame index so positioning is often on the basis of bit-rate, and so, is not accurate and usually only to a GOP start. For editing mpeg streams, you need frame accurate positioning.  This has been achieved by Elecard using a secondary index file. Their demultiplexer is very efficient from the network point of view since it knows where a GOP starts and does not have to search for it over the network. This makes it usable in an editor, but not for open source use since their SDK is proprietary and expensive, I bought it ten years ago.

I have built a frame accurate program stream Deultiplexer for mpeg2 and worked out how to make the (ffdshow) decoder render the required first frame, even when it is not an I-Frame. I have given up on making my demux work with audio streams that do not contain a PTS.

I also note that the readily available wmv demultiplexers do not permit frame accurate positioning, even though I understand the file contains a frame index.

Do you have any plans to provide frame accurate positioning for the, numerous, formats your demultiplexer provides? I can give you the code for my filter. It is written in Pascal, and is a bit of a mess, but it works.

Your demux and decoders would be an ideal choice for an editor since they would avoid the need to load different splitters for different formats.

**Comment by Nevcairiel** [comment]
LAV uses FFmpeg (the avformat library specifically) for demuxing and its demuxer. I do not currently plan to incorporate any further "custom" demuxers that are not in ffmpeg, as that would add a whole lot of complexity and maintenance.

If you want to see the ffmpeg/avformat demuxers to be improved, I would recommend to try to work on their demuxers and improve those, which LAV would automatically inherit.

**Comment by DTSMediaSoft** [comment]
Hi Hendrik

I suspect the FFmpeg demux is fine, and I would not suggest any new 
dumxes, the problem is mpeg2 and the DirectShow code around the dlls. 
Sadly, in the UK, all our tv is mpeg2 as are all our DVDs and Blu-Rays

If a media player knew the precise address of the start code for a given 
frame then, provided the direct show code around the FFmpeg dlls handled 
the time stamps and discontinuity flags correctly, the first displayed 
frame would be the one requested. (all frames between the previous 
I-Frame and the requested frame would not be output from the decoder 
since they have negative time stamps in the IPPBBBP... sequence mpeg 2 way).

Mpeg 2 is the way it is because Nick Wells and Leonardo Chiariglone did 
not think it would be used for anything other than distribution. The 
fact that people record what gets transmitted and want to scan through 
it quickly to find the part of interest was way in the future when they 
did the standardisation work..


I note that with my demux and the FFmpeg audio and video decoders, the 
first displayed frame is the one requested and you can step back and 
forwards a frame at a time and all is as expected. Also, you can fast 
play through the file, using the I-Frame addresses and the player 
displays in excess of 25 new frames per second. These are the bare 
essentials for professional use and can be found in all competent editor 
programs.

The LAV demux and decoders do not step forwards until the requested 
frame gets to or  beyond an I-Frame. The same is true for stepping 
backwards. The fast play performance is also very slow since the best 
guess for the position of the  required I-Frame is just that, a guess.  
Also, the time code handling cannot be correct somewhere, otherwise the 
first displayed frame would not be only the previous I-Frame. I note the 
Microsoft demux and decoders are no better.

I could fix the combination by putting a custom filter between the demux 
and decoder which refers to a custom index file to direct the demux to 
the correct address and then fix the time stamps that come out in 
response. The problem is, the world needs a good demux, especially for 
mpeg2 and your demux is a good candidate because it would do all the 
formats provided by FFmpeg. It does not required any work from FFmpeg, 
only some additional features in your demux and decoders.

Kind Regards
Richard.
