### ISSUE TITLE
RAM at 95% after long playback

### ISSUE THREAD

**Issue by Addicted5** [Nevcairiel/LAVFilters#92]
Hi,I'm using 0.68.1.
When i use 1080p video with hardware decoding ,my RAM becomes 95% after 45min-1hr.
I got 8GB RAM & at starting of play back it's below 25%.
As time passes , it fills.
I got gtx960.

I'm gonna test 0.67 if same issue appears or not

**Comment by CHEF-KOCH** [comment]
MPC-HC or BE?
Video sample?
Which driver?
Which LAv Settings?

**Comment by Nevcairiel** [comment]
I cannot reproduce any memory issues, nor has anyone else reported any problems. Such problems can easily be a result of a broken driver, the player, or even the OS doing something bad.

**Comment by Nevcairiel** [comment]
Closed due to lack of feedback. Please re-open if you can provide any conclusive information.
