### ISSUE TITLE
Interlaced H264 DXVA decoding on Radeon RX 480

### ISSUE THREAD

**Issue by buchanan-fh** [Nevcairiel/LAVFilters#98]
Hello,

It seems that DXVA decoding of interlaced H264 content on RX 480 is broken, I get this result : ![meteo](https://cloud.githubusercontent.com/assets/11913405/16928177/92623682-4d31-11e6-9018-af819a14a5b7.png)

Here is the sample used : http://carte.fh.free.fr/meteo.ts
The results are comparable wether I use native or copy-back mode.

Progressive content is playing fine as far as I can tell.

My config:
MPC-HC 1.7.10.252 x64 (internal LAV 0.68.1.25)
AMD Radeon RX 480, 16.7.1 driver

**Comment by Nevcairiel** [comment]
New hardware, new bugs. It works fine on every other possible piece of hardware with LAV, and AMD has  a history of broken video decoders, so I would recommend you complain to them.

**Comment by buchanan-fh** [comment]
Ok, I will report this on AMD forums

**Comment by nwgat** [comment]
i just tried the Microsoft DTV-DVD Video Decoder and that seems to work, also mpv has the same problem as lavfilters

![](http://image.prntscr.com/image/59992bff973c4b4398e468d8f64cd243.png)

FYI: reporting amd driver issues can be done at http://www.amd.com/report

**Comment by nwgat** [comment]
the present is calling to say that 16.2.1 improves interlaced 1080i h264 playback
